deltachat/deltachat-desktop

package.json
Lets write some cool text here as well in case someone is interested in why don't need to nullify stuff. So we don't have access to certain functions in node because it's N A P I! See #1
=> Try using deltachat-node#no-need-to-nullify

src/renderer/chatview.js
Compare with:
```js
const C = require('deltachat-node/constants')
function test (type) {
switch (type) {
case C.DC_MSG_IMAGE || C.DC_MSG_GIF:
console.log(type + ' is an image')
break
default:
console.log(type + ' not an image')
}
}
function test2 (type) {
switch (type) {
case C.DC_MSG_IMAGE:
case C.DC_MSG_GIF:
console.log(type + ' is an image')
break
default:
console.log(type + ' not an image')
}
}
test(C.DC_MSG_IMAGE)
test(C.DC_MSG_GIF)
test2(C.DC_MSG_IMAGE)
test2(C.DC_MSG_GIF)
```
```
20 is an image
21 not an image
20 is an image
21 is an image
```
=> Fix DC_MSG_GIF case

src/main/menu.js
Fixes:
```
{ Error: Cannot find module './shell'
at Module._resolveFilename (module.js:543:15)
at Function.Module._resolveFilename (/home/lms/src/deltachat/deltachat-desktop/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
at Function.Module._load (module.js:473:25)
at Module.require (module.js:586:17)
at require (internal/module.js:11:18)
at click (/home/lms/src/deltachat/deltachat-desktop/es5/main/menu.js:154:25)
at MenuItem.click (/home/lms/src/deltachat/deltachat-desktop/node_modules/electron/dist/resources/electron.asar/browser/api/menu-item.js:55:9)
at Function.executeCommand (/home/lms/src/deltachat/deltachat-desktop/node_modules/electron/dist/resources/electron.asar/browser/api/menu.js:29:13) code: 'MODULE_NOT_FOUND' }
```
=> Fix shell.openExternal()

src/main/deltachat.js, src/renderer/components/Login.js
* Moves login button to left of cancel
* Fixes `this._render` is not a function (only set once init has completed)
* Reset email and password to empty strings rather than null
=> Tweak login page + fix this._render is not a function

src/main/deltachat.js, src/renderer/components/dialogs/DeadDrop.js
so now contact requests work and create a new chat, but for some reason the old dead drop is still there -- do we need to 'mark read' the chat? @r10s
=> fix dead drops and use contact name and addr

src/main/deltachat.js
* Listen to `DC_EVENT_MSG_DELIVERED`, `DC_EVENT_MSG_FAILED` and
`DC_EVENT_MSG_READ`
* Be lazy in `ChatMessage` and don't cache `dc.getMessage()`, instead get message
object at time of calling `toJson()`
Closes https://github.com/deltachat/deltachat-desktop/issues/78
Demo: https://cloud.weho.st/index.php/s/sMsBCEGcfCHbjdJ (link valid for 30 days from post date)
=> Update message status

src/main/index.js, src/main/windows/main.js, src/renderer/main.js
The problem was that the main window wasn't properly propagating it's close event. Moved all close handling to the `main/index.js` file and made sure once the main window is closed, the app quits after state is saved.
=> fix: app properly closes when X is hit. fixes #95

package.json, src/config.js, src/main/index.js
There's a lot of configuration that's never used and I decided to remove the strange IS_PORTABLE code as well.
Imo, we need _two_ different app folders:
* one which the real app will use, which is handled by the `application-config` module, which sets that up correctly on corresponding OS (e.g. `~/.config/DeltaChat` on linux)
* one temporary test folder that doesn't conflict with a real installation, e.g. `/tmp/DeltaChat`
=> Cleanup config and startup

_locales/en.json, src/main/deltachat.js, src/renderer/ScreenController.js, src/renderer/components/ChatView.js, src/renderer/components/CreateGroup.js, src/renderer/components/EditGroup.js, src/renderer/components/GroupBase.js
Closes https://github.com/deltachat/deltachat-desktop/issues/26
I started by copying functionality from `CreateGroup` to `EditGroup` and then refactored the common code into a `GroupBase` component.
The edit screen looks the same, but have different heading and different label on the button.
In edit mode, already existing group members cannot be de-selected, only contacts that haven't yet been added to the group can be toggled. When "Save" button is clicked, the group name is applied and the newly selected contacts are added to the group.
Also, I removed the error handling completely, disabling the button if no group name is set, or if no contacts have been selected. So the user can either add/modify name, and select contacts to enable the button or bail out with the arrow in the upper …
=> Edit group

conversations/stylesheets/_mixins.scss, conversations/stylesheets/_modules.scss, conversations/stylesheets/_variables.scss, conversations/ts/components/conversation/Message.tsx, images/padlock.svg, src/renderer/components/ChatView.js
Closes https://github.com/deltachat/deltachat-desktop/issues/144 
Darkened the default grey to get a better contrast to the shield/padlock. Couldn't find a proper padlock so used the shield for now.
Result:
=> Add padlock to messages + tweak conversation grey

_locales/en.json, conversations/ts/util/emoji.ts, package.json
Below follows _all_ emojis that can be sent from `deltachat-android` (yes, I clicked through all of them):
Emoji size also depends on length of message. If only sending a few emojis, they will be larger. But if you send with text or a lot of emojis, the smaller size will be picked.
=> Make emojis work on incoming messages

_locales/en.json, src/main/deltachat.js, src/main/ipc.js, src/main/menu.js, src/renderer/ScreenController.js, src/renderer/components/SplittedChatListAndView.js, src/renderer/components/dialogs/About.js
Closes https://github.com/deltachat/deltachat-desktop/issues/103
Will leave this hanging for someone else to tweak the dialog. I'm not skilled enough and/or don't have enough creativity to make something out of the dialog.
Currently my thoughts are:
* add some tabs
* default tab shows basic and clean About information (desktop version, license, yada yada)
* click the second tab to get more information
Also see old PR https://github.com/deltachat/deltachat-desktop/pull/197
=> Add About dialog

conversations/ts/components/conversation/Message.tsx, src/renderer/components/ChatView.js, static/main.css
Closes https://github.com/deltachat/deltachat-desktop/issues/112
@#$%^@ the `<img>` tag, lets just use `<video>` and be done with it?
Result:
=> Use <video> element for video attachments

src/renderer/components/dialogs/KeyTransfer.js, src/renderer/components/dialogs/SetupMessage.js, static/main.css
=> Fix autocrypt ui

_locales/en.json, src/renderer/components/CreateChat.js, src/renderer/components/CreateGroup.js, src/renderer/components/SplittedChatListAndView.js
This changes some language resources so we use the same naming as in android, e.g.
* `New chat` instead of `Create Chat`
* `New group` instead of `Create Group`
* `Add contact` instead of `Add Contact`
* `New group` button comes before `Add contact` button on `New chat` page/screen
Compare with:
=> Chat tweaks

static/chat.delta.desktop.appdata.xml
These days consumers of desktop applications expect appstream data.
Such consumers are GNOME software or flathub. But Debian also likes
seeing those. This change brings such a file.
Note how I defined the appid to be chat.delta.desktop. This file also contains some release information. While manually maintaining this is not too much overhead, it might still be tiresome in the future. I couldn't figure out how to have a file generated with the current build infrastructure, if you want to call it that, so I opted for hard-coding it. It has some advantages in that the end-user visible release information can arguably be made more appealing when done manually...
This addresses the appstream part mentioned in https://github.com/deltachat/deltachat-desktop/issues/100
My main motivation is to …
=> appdata: Added appstream data

src/main/deltachat.js
fixes #214  (mostly)
right now it'll mark them as seen if the user fetches them, but we don't have a reliable way right now to mark them when they're on screen -- feeling like one way to make this more reliable would be to reduce the 'messages per page size' (right now it is 20)
=> mark messages seen when fetched

static/main.css
Group name + no image, before:
Group name + no image, after:
Group name + image, before:
Group name + image, after:
=> Tweak group image and chat name margin

.github/ISSUE_TEMPLATE.md
just wanted to file an issue and came over the "version" field.
i think, the version that is expected here is the _desktop_ version, not the version of the core or the version of the platform; so we should be more precise here.
=> more concrete version label

Jenkinsfile
* renamed docker image
* only build `dist` on master branch (will speed up PRs as well, roughly ~2 mins per commit)
* add clean up step after build is done (regardless of state)
=> Tweak jenkins

conversations/ts/components/conversation/Linkify.tsx, jenkins/Jenkinsfile.linux, package.json
Actually, the whole app was broken. Took me over 4 hours to find this :grin: 
@Jikstra You have to be careful when you have branches on forks as dependencies (I have done this multiple times myself and it's really easy to mess things up). I'm not exactly sure what you did, but I'm guessing you force pushed one of your own branches, removing code from the `feature_add_option_to_allow_double_dash_domains` branch.
Somewhere around here:
This PR unbreaks the app. I'll squash this, so it will be one commit on master. Undoing this change and fixing the original problem should be easy. In this order do:
* fix the `feature_add_option_to_allow_double_dash_domains` so it's correct and push that to your fork
* _revert_ the _squashed_ commit from this PR
=> Fix broken integration test

_locales/en.json, src/main/deltachat.js, src/main/index.js, src/main/ipc.js, src/renderer/App.js, src/renderer/ScreenController.js, src/renderer/components/MessageWrapper.js, src/renderer/components/SplittedChatListAndView.js, src/renderer/components/dialogs/Settings.js, src/renderer/components/dialogs/confirmationDialog.js, src/renderer/components/dialogs/index.js, src/renderer/lib/state.js, src/renderer/main.js
This allows users to set in the settings whether or not they want messages to be marked read (or not). Default is `true`
It includes some refactoring of the settings screen -- more incoming on refactoring our dialogs to have a DialogController along with a ScreenController, probably next week.
fixes #324
=> Optionally mark messages as read

_locales/en.json, src/main/deltachat.js, src/renderer/ScreenController.js, src/renderer/components/ChatView.js, src/renderer/components/Composer.js, src/renderer/components/ContactList.js, src/renderer/components/CreateChat.js, src/renderer/components/GroupBase.js, src/renderer/components/MessageWrapper.js, src/renderer/components/SearchInput.js, src/renderer/components/SplittedChatListAndView.js, src/renderer/components/dialogs/ForwardMessage.js, src/renderer/components/dialogs/index.js
This implements forwarding messages when clicking the context menu in a message and hitting 'forward message.'
A dialog window pops up with the list of contacts. When a contact is clicked, the dialog closes and the message is forwarded to that person.
This also implements a Search input box when selecting a contact, for filtering the contact list based on a search term
* :relaxed:   refactor: Contacts are retrieved using a synchronous model so we don't have to pass contacts and re-render everything every time someone types in the contact search box
* :tada: bonus!: This search function is abstracted out into it's own `ContactList` component and reused for searching for contacts when creating a new group and creating a new chat 
* :see_no_evil:  hack!: The contact list was getting multiple …
=> Forwarding messages

src/main/deltachat.js, src/main/ipc.js, src/renderer/ScreenController.js
this handles network errors and shows them raw (as we get them from core) in the user interface. Do we need to do any translation for this? @r10s 
fixes #302
=> handle and show errors, including DC_EVENT_ERROR_NETWORK

_locales/en.json, src/main/deltachat.js, src/main/ipc.js, src/renderer/ScreenController.js, src/renderer/components/Login.js, src/renderer/components/dialogs/Settings.js, src/renderer/components/dialogs/index.js
This allows you to edit your account settings (like password, email address, and SMTP/IMAP) from the settings view.
fixes #249 
One TODO left:
@ralphtheninja @Jikstra one last thing to do: what should we do when the user hits 'update settings'? Do we need to just set the new config options? or do we login also? 
EDIT:
Work left:
=>  Advanced account settings

_locales/en.json, src/renderer/components/dialogs/SetupMessage.js
* We don't lose the entered transfer verification key if it's incorrect (currently it gets cleared after submit) 
* The autocrypt key is discarded once dialog is exited manually using the X
* Typing 4 figures into one input, automatically focuses the next one so that users don't have to press tab 
* Update and improve visual status messages 
* More accurate base English strings
* Various CSS improvements
=> autocrypt dialog improvements, fixes #282

.tx/config, README.md
Note that I have run `tx push --source` and it seems to work fine, the desktop strings were added to `strings.xml` on Transifex.
@r10s You should probably do `tx pull` in android repo to sync with desktop updates.
=> Update readme on transifex

test/unit/index.js
Makes sure each `.xml` file has a corresponding `.json` file and instead of making a single test for each file, we test that all files are valid .json (less spammy).
=> Make unit tests less spammy

_locales/de.xml, _locales/sq.xml, _locales/tr.xml, bin/convert-translations-from-xml-to-json.js, test/unit/index.js
Closes https://github.com/deltachat/deltachat-desktop/issues/544, closes https://github.com/deltachat/deltachat-desktop/issues/515
=> Fix escaped characters in translations

README.md
Feel free to push against this branch to make this readme nice and shiny :)
Fixes #504
=> Update install instructions in README to cover Arch & Mac.

src/renderer/components/ContactList.js, src/renderer/components/GroupBase.js
Closes https://github.com/deltachat/deltachat-desktop/issues/545
=> Pass showVerifiedContacts to ContactList component

src/renderer/components/SearchInput.js
for search input. This currently removes the possibility to clear the search input which is a regression, but maybe only a small one. Putting in a js version of this should be doable.
=> Restyle buttons in create chat

package.json, src/main/windows/main.js
Just making a PR for it. We don't have to merge this right now. Note that we're now setting `webPreferences: { nodeIntegration: true }` since it will default to `false` in v5.
Closes https://github.com/deltachat/deltachat-desktop/issues/473
=> Use electron v4

src/renderer/components/ChatView.js, src/renderer/components/Composer.js, src/renderer/components/SplittedChatListAndView.js
composer elements
Besides general restyling this also adresses all of the things mentioned by @Simon-Laux in the initial pr https://github.com/deltachat/deltachat-desktop/pull/608#issuecomment-456536132. Only thing which is missing is that the emojis might be too big, but i personally like the size.
=> Move emoji picker left to the send button and improve styling of all

static/chat.delta.desktop.appdata.xml
+ Changed the metadata_license identifier from CC0 > CC0-1.0 to comply with [SPDX](https://spdx.org/licenses/).
+ Added url for bugtracker, faq, donation and translate.
+ Updated with regenerated [OARS](https://hughsie.github.io/oars/generate.html)-data. Content attributes with the value of 'none' are no longer necessary to be explicitly specified.
+ General code cleanup. Release description should not look messy on Flathub etc anymore.
=> Appdata updates and cleanup

src/renderer/components/Login.js
Fixes: https://github.com/deltachat/deltachat-desktop/issues/632
=> Remove misleading/duplicate/uninformative leftIcons in login form

src/renderer/components/SplittedChatListAndView.js
Closes https://github.com/deltachat/deltachat-desktop/issues/584
Happens because the ref `this.chatView` is only passed to the `ChatView` component if there's a chat selected. From the start no chat is selected so when we click a chat the first time `this.chatView.current` is `null` (because it has never been rendered).
=> this.chatView.current is not set from the start

src/renderer/ScreenController.js
Closes https://github.com/deltachat/deltachat-desktop/issues/624
Does this a bit differently. Instead of hiding the error message at successful login, we always hide the error message before trying to login. if the login is successful, the error message is gone and if login fails again, the error is shown again.
=> Hide error message when attempting to login

css/conversations/_modules.scss
Since deltachat supports custom backgrounds, the handle for context menus (only visible on hover) should not be near the bubble but in the upper right corner. Otherwise it might not have enough contrast.
I added 10px padding-top to the text to enable a proper distance, may be there is a better solution...
=> Improvement: change handle position for context menu

src/renderer/components/Composer.js
of the number of linebreaks. This is more accurate. Fixes https://github.com/deltachat/deltachat-desktop/issues/665
=> Update the height of the composer/textarea based on scrollHeight instead

.travis.yml, README.md, static/chat.delta.desktop.appdata.xml, static/chat.delta.desktop.desktop
The appstream/appdata file is required for linux destop appliciations
and is not packaging-format specific so makes sense to include
upstream.
- Update existing appdata file.
- Add .desktop file since this is referred to by the appdata.
- Update the travis config to test this appdata and .desktop files
making sure they remain correct.  We have to add linux back to the
job matrix for this, but we only want to publish a binary release
using electron-builder on OSX.
=> Update and integrate appstream file

.travis.yml, ci_scripts/build_sasl.sh, ci_scripts/ci-build.sh, ci_scripts/ci-prelude.sh, ci_scripts/ci-test.sh, docker/Dockerfile, package-lock.json, package.json
Fixes https://github.com/deltachat/deltachat-desktop/issues/792 because -node v0.44.x is compatible with newer node versions.
Fixes https://github.com/deltachat/deltachat-desktop/issues/659 because we can bundle
Fixes https://github.com/deltachat/deltachat-desktop/issues/722 because ci is fixed
Fixes https://github.com/deltachat/deltachat-desktop/issues/708 because we bundle openssl
=> Update deltachat-node to v0.44.0 and fix ci

bin/watch.js, package.json
- We now use webpacks watch mode, this speeds up builds in watch mode quite a lot
Fixes #823
=> Implement incremental builds on watching

src/main/log-handler.js
App crashes at startup because we fail to create the log file.
=> fix: use a friendlier file name for logs on windows (: not appreciated)

src/main/deltachat/index.js, src/renderer/stores/chatList.js
Update chat list when chat changes
Resolves #831
The chat list gets updated now on every DC_EVENT_CHAT_MODIFIED event.
Maybe we should test and check for more events which might not be handled...
=> Sort chat list on update

ci_scripts/ci-prelude.sh, ci_scripts/shared-image-context/build-install-rpgp.sh, docker/Dockerfile
This also needs that we update the docker travis image https://hub.docker.com/r/deltachat/travis-dc-node-base . I don't know how to push that image, but updated the Dockerfile. @flub can you help out?
=> Update rpgp version to 0.2.1

.travis.yml, package-lock.json, package.json, src/main/ipc.js, src/renderer/ScreenController.js, src/renderer/components/Login.js, src/renderer/components/dialogs/Settings.js
Maybe leave this hanging until we have gotten `v0.104.0` out.
Closes https://github.com/deltachat/deltachat-desktop/issues/692
Closes https://github.com/deltachat/deltachat-desktop/issues/841
Closes https://github.com/deltachat/deltachat-desktop/issues/687
Closes https://github.com/deltachat/deltachat-desktop/issues/606
=> chore: update node bindings to 1.0.0-alpha.0

src/renderer/stores/chatList.js
Archived chats link should always be at the last position
resolves #859
=> Fix sort errors

src/renderer/components/MessageMarkdown.js
- add `__bold__` as alternative to `**bold**`
- match links with `<` `>` - don't take in the last `>` as part of the link
=> Minor Markdown updates

ci_scripts/pkg-build.sh, ci_scripts/shared-build-context/deltachat-desktop, ci_scripts/shared-prelude-context/build-install-rpgp.sh, ci_scripts/shared-prelude-context/install-nvm-node.sh, ci_scripts/shared-prelude-context/install-rust.sh, ci_scripts/shared-prelude-context/nvm-use.sh
Some scripts have an erroneous shebang, for example `/opt/DeltaChat/deltachat-desktop` in the Ubuntu package, so the program cannot be started.
This patch corrects the issue.
=> Fix script shebangs.

src/main/deltachat/chatlist.js, src/main/state.js, src/renderer/components/dialogs/Settings.js, test/integration/fixtures/config.js
We still need to fix the defaults in the node bindings that it is enabled by default, but otherwise it works now. The fix was easier than expected.
=> fix read reciept

src/renderer/components/NavbarWrapper.js, src/renderer/components/SplittedChatListAndView.js
Reasons:
- having it only sometimes is distracting because the name moves (currently its in this state)
- displaying it the generated avatar instead looks not too good... IMHO
- It's smaller than the one on the side (in chatList) so the duplication makes not much sense IMHO
=> remove profile picture from nav bar

src/renderer/components/helpers/AutocryptSetupMessage.js
=> Properly center the autocrypt input form

scss/_global.scss, scss/modules/_settings.scss, scss/modules/index.scss, src/main/ipc.js, src/main/state.js, src/renderer/ThemeBackend.js, src/renderer/components/ChatView.js, src/renderer/components/dialogs/Settings.js
=> Select background

src/renderer/components/Composer.js, src/renderer/components/dialogs/CreateChat.js, src/renderer/components/helpers/DeltaDialog.js
- Rename the `Create group` button to a more generic `ok` button
- Don't delete the group which got created during showing qr code on
close button again
- Make all dialogs closable with escape key but don't close them when
clicking outside
@r10s
=> Some UX improvements

README.md, package-lock.json, package.json, src/logger.js, src/main/deltachat/backup.js, src/main/deltachat/chatlist.js, src/main/deltachat/chatmethods.js, src/main/deltachat/index.js, src/main/deltachat/login.js, src/main/deltachat/settings.js, src/main/index.js, src/main/ipc.js, src/main/log-handler.js, src/main/menu.js, src/main/state.js, src/main/windows/main.js
- omit stacktrace for debug and info
- move core event logs to their own log channel (makes event output smaller and less annoying)
- change logile extention to .log.tsv
- add colors, time elapsed and generally rework main process logging a bit:
=> Improve logger a bit

_locales/_untranslated_en.json, src/main/deltachat/login.js, src/main/ipc.js, src/main/notifications.js, src/main/unread-badge.js, src/renderer/components/dialogs/Settings.js
resolves #1068
- adds 2 new controls in settings component (notifications & showContentInNotification)
what I don't like is that we need stuff like dc._dc.on(evt, handler) etc. but that should be refactored in another PR
=> Fix broken system notifications

src/main/deltachat/login.js
This is an attempt to fix #1025
=> Fix server flags configuration

src/renderer/components/chat/ChatList.js, src/renderer/components/chat/ChatListHelpers.js
Without this I always saw "empty" items when scrolling. Now you have at least to scroll fast to see empty items...
=> Preload some more chat list items as buffer

src/main/deltachat/login.js
setCoreStrings calls setStockTranslation since 05f7de61b59c3fe587932d6d886c5cc12dbdf8a7
It requires the context to be open.
Fixes #1093
=> Call setCoreStrings after opening the context

src/renderer/components/message/Message.js, src/renderer/components/message/MessageBody.js, src/renderer/components/message/MessageList.js, src/renderer/components/message/MessageWrapper.js
There is still one more bug, that we have some messageids duplicated. I'm tracking it down, but didn't find it yet.
=> Fix key warnings in message list related components

scss/_global.scss, src/renderer/ScreenController.js
=> Restyle user-feedback

docs/STYLES.md, scss/gallery/_attachment-view.scss, scss/manifest.scss, scss/message/_message-detail.scss, scss/message/_message-list.scss, scss/message/_message.scss, scss/message/_metadata.scss, src/renderer/components/Media.js, src/renderer/components/conversations/Timestamp.js, src/renderer/components/dialogs/RenderMedia.js, src/renderer/components/message/Attachment.js, src/renderer/components/message/Message.js, src/renderer/components/message/MessageMetaData.js, src/renderer/components/message/MessageWrapper.js
Beginning with renaming and duplicating css.
and reorganizing it.
best reviewed on a commit by commit basis.
=> Refactor message (scss classes edition)

scss/chat/_chat-list.scss, scss/composer/_emoji-sticker-picker.scss, scss/overwrites/_bp3-overwrites.scss, src/renderer/ThemeBackend.js, src/renderer/components/NavbarWrapper.js, src/renderer/components/dialogs/Group-Styles.js, themes/dark_amoled.json
=> Fix theming issues

src/main/deltachat/messagelist.js
For an off by one issue, we didn't display the first message in chats.
=> fix first message missing in messagelist

scss/message/_message.scss, scss/message/_metadata.scss, src/renderer/ThemeBackend.js
in light theme.
before it was grey on black, now its always white on black, except for the outgoing messages, which text color is green, which is still readable on black.
=> fix incomming image metadata unreadable

src/main/log-handler.js
`getMonth()` starts at 0, and `getDay()` returns the day of the week.
=> Save log to file containing correct day and month.

src/main/deltachat/chatlist.js
=> don't display state of incomming messages in chat list item

src/renderer/components/Media.js, src/renderer/components/dialogs/RenderMedia.js, src/renderer/components/message/Attachment.js, src/renderer/components/message/Message.js, src/renderer/components/message/MessageList.js, src/renderer/components/message/MessageMarkdown.js, src/renderer/components/message/MessageWrapper.js, src/renderer/components/message/messageFunctions.js
see commit messages for details.
In essence I moved more stuff between files in hope to make the code more readable and prepare merging of message-wrapper and message.
=> Refactor message2

src/renderer/components/message/MessageList.js, src/renderer/stores/chat.js
=> Fix MessageList not updating/scrolling down on incoming message

src/renderer/components/Menu.js, src/renderer/components/message/MessageList.js
=> Don't fetch chat twice

scss/_global.scss, src/main/ipc.js, src/renderer/components/dialogs/Settings.js
- Refactor import/export methods into callDcMethodAsync
- Fix user feedback displayed on top of dialog
Fixes https://github.com/deltachat/deltachat-desktop/issues/1226
HINT: There is still a bug in core which doesn't allow importing keys. But it's the same on android. (https://github.com/deltachat/deltachat-core-rust/issues/1104)
=> Fix importing keys

scss/chat/_chat-list-item.scss, scss/chat/_chat-list.scss, src/main/deltachat/chatlist.js, src/renderer/components/chat/ChatListItem.js, test/integration/index.js
I tested with an acoount with ~600 chats.
Since the chatlist renders a skeleton for each item upfront there is quite some overhead with 600 chat items.. 
I tested using just an empty div with fix height as skeleton and while one might say that it not looks as nice as before it really improves performance.
See 3 profiles attached (can be loaded in Chrome dev tools)
The difference is probably only noticeable with many chats but there it is evident...
The breath animation seems also expensive if you look at the profiles...
[Profiles.zip](https://github.com/deltachat/deltachat-desktop/files/3991583/Profiles.zip)
=> Use empty placeholder to avoid rendering overhead

scss/chat/_chat-list-item.scss, scss/chat/_chat-list.scss, src/main/deltachat/chatlist.js, src/renderer/components/Menu.js, src/renderer/components/chat/ChatListHelpers.js, src/renderer/components/chat/ChatListItem.js, test/integration/index.js
This improves the chatlist scrolling performance by splitting some heavy backend methods into some async callback "chunks" which blocks the event loop only for the time each chunk takes and allows other things to happen in between instead of blocking for the whole time. This is important for any ipc events getting queued up in between and unblocking the renderer process. This is still not perfect but feels snappier and smoother as before. Besides this, this also tries to fetch the deltachat-core chatList datastructure only once.
```
[BENCH] getChatListItemByIds 26: 132.433ms
[BENCH] getChatListItemByIds 56: 253.712ms
[BENCH] getChatListItemByIds 16: 83.381ms
[BENCH] getChatListItemByIds 1: 18.506ms
[BENCH] getChatListItemByIds 5: 36.413ms
[BENCH] getChatListItemByIds 8: 49.686ms
[BENCH] …
```
=> Improve chatlist scrolling performance

src/renderer/components/dialogs/Settings.js
Since useLayoutEffect is called after complete rendering the dialog is visibly reloaded
=> Avoid reload of settings dialog

scss/_global.scss, scss/message/_message-list.scss, src/renderer/components/MainScreen.js, src/renderer/components/Media.js
- Restyle selected button in gallery to don't look disabled -> change to tabs
- make the images takeup less space each
=> some gallery improvements

package-lock.json, package.json, src/main/index.js, src/main/log-handler.ts
transform log-handler file to typescript.
keep only the last 10 log files in order to save disk-space.
closes #1321
=> Delete old logs

scss/main_screen/_navbar_wrapper.scss, src/renderer/components/MainScreen.js
The search wasn't functional. This change is preliminary until someone
builds a change that fixes the search and jumps out of the archive-view
(the search is global, not restricted to the archives).
Screenshot:
Closes #1366
=> Show title, not search field when showing archived chats.

scss/message/_metadata.scss
..with no caption.
I just came across this and fixed it - it was grey on semi-transparent black now its white on semi-transparent black .
=> fix sending spinner not clearly visible on sending an image..

src/renderer/components/LoginScreen.js
=> fix welcome message is cut to "welcome to..."

package-lock.json, package.json
electron-builder >= 22.0.0 fixes the setuid problem with the sandboxing helper: https://github.com/electron-userland/electron-builder/pull/4163
This helper is required if `kernel.unprivileged_userns_clone` is not allowed (`0`), e.g. on Debian and derivates. (On other linux systems user name-spaces are used instead of the sandboxing helper.)
Fixing the sandbox-helper problem would enable us to update electron (see #895 and #948), which is apparently required to get into the MacOS app store (#1134, https://github.com/electron/electron/issues/20027).
The update is jumping to a new major version, but [the Changelog](https://github.com/electron-userland/electron-builder/releases) doesn't list any breaking changes, so I suppose this shouldn't make problems.
=> Update to electron-builder 22 (fixes SUID sandbox issues)

package-lock.json, src/main/ipc.js, src/renderer/App.tsx, src/renderer/components/message/MessageList.js, src/renderer/components/message/MessageWrapper.js
On each update a functional component will "rerender", or at least build the virtual dom stuff and compare it with what is there. To avoid this the 2nd memo parameter allows us to check if we actually need to do anything. I added this to the new MessageListInner component which checks if the messages to show changed (if we need to show new messages) and we also check this for each Message component if the message object changed it's identity and only if so we rerender. Besides this i moved the useStore call out of MessageWrapper as a useState change always triggers a rerender, causing us to rerender all Messages no matter what changed in the chat store.
=> Performance improvements for messagelist

src/renderer/components/message/Message.js
selected text. the problem was that the option was always displayed.
=> Fix that 'copy selection' is only visible on

CHANGELOG.md, _locales/_untranslated_en.json, src/main/menu.js, src/main/windows/main.js, src/shared/shared-types.d.ts, src/shared/state.ts
(It's found under `View`->`Zoom Factor`)
related to #890
keep in mind that this method is electron specific and not the same as the css zoom property.
=> Add zoom factor option in order to adjust font size.

src/renderer/experimental.ts, src/renderer/global.d.ts, src/renderer/main.tsx
(create contacts from json array)
mainly to provide **a** way to import multiple contacts at once into the desktop app. (related to https://support.delta.chat/t/using-importing-contacts-on-desktop-program/368/9)
Better to have the feature this experimental way than not having that possibility at all for the moment.
=> add primitive & experimental contact import

src/renderer/components/message/MessageListAndComposer.tsx
in order to prevent a white-screen crash.
This doesn't fix the issue fully it just turns the crash into some harmless visual glitching.
related issue: https://github.com/deltachat/deltachat-desktop/issues/1526
=> debounce composer set size call

scss/chat/_chat-list.scss, scss/dialogs/_delta-dialog.scss, scss/misc/_search-input.scss, scss/overwrites/_bp3-overwrites.scss
- remove unneccessary border on chatlist
- changer caret color of search input to the same color as the
placeholder
- make dialog height overlap navbar/composer for fixed dialogs
=> Some styling fixes:

src/main/deltachat/controller.ts, src/main/rc.ts
This should close #1555
logs always info,warn&error core-events
and logs 'ALL' events only when 'log-debug' is enabled
also --debug enables now --log-debug & --log-to-console
=> improve logging of core info events

src/renderer/ThemeBackend.ts
In my opinion it should be almost unnoticable and stay in the back. The element is already selected and flashing background colors is just to busy.
=> Make hovering over a selected chatlist item almost unnoticeable

CHANGELOG.md, UPGRADING.md, src/main/index.ts, src/main/logins.ts
- Add information about changed behavior. Also it shouldn't crash anymore if the migration failed, instead it opens an error dialog
- show error dialogs on uncaught errors, in hope to get more less technical people to report crashes
=> Login migration upgrade guides and error handling

_locales/_untranslated_en.json, scss/dialogs/_delta-dialog.scss, src/renderer/components/message/MessageListAndComposer.tsx
=> Drop-send multiple files➬ask for all files at once

src/main/deltachat/controller.ts, src/renderer/components/dialogs/ImportQrCode.tsx, src/renderer/delta-remote.ts
Resolves #1632 
Depends on deltachat/deltachat-node#452
Enables to cancel the secure join process so after canceling it's possible to try again without restart
Fix "call startsWith of undefined" error
=> Improve secure join handling

src/renderer/components/message/MessageWrapper.tsx
The warning says:
react-dom.development.js:530 Warning: Received `true` for a non-boolean attribute `custom-selectable`.
If you want to write it to the DOM, pass a string instead: custom-selectable="true" or custom-selectable={value.toString()}.
...
=> Avoid react warning

src/main/log-handler.ts
- save log-files as .log so that they aren't opened as tables by default
- padding for channels so that they are mostly aligned now
- remove `"` for timestamp, channel and level
closes #1645
=> improve logfiles

docs/STYLES.md, scss/_offline-toast.scss, scss/chat/_chat-list-item.scss, scss/dialogs/_about.scss, scss/dialogs/_autocrypt_setup.scss, scss/dialogs/_delta-dialog.scss, scss/dialogs/_settings.scss, scss/overwrites/_bp3-overwrites.scss, src/renderer/components/dialogs/DeltaDialog.tsx, themes/_themebase.scss, themes/dark.scss, themes/dark_amoled.scss, themes/darkpurple.scss, themes/light.scss
tweaks theming with an strong focus on making the dark theme usable (avoid black text on dark background for example)
also adds information about css var naming to the docs (prefer snake-case from now on, because electron will give auto completion for css-vars with snake-case which makes it more fun to play with in the dev-console)
=> Improve usability of dark theme

src/main/deltachat/controller.ts, src/main/deltachat/login.ts, src/shared/constants.ts
This reminds people to update without requiring any server contact, it assumes that our release rate is smaller than 90days.
This feature is still being discussed in the forum and the general plan is to eventually implement it in the core instead, because this is useful for all platforms.
Forum Topic: https://support.delta.chat/t/update-availible-message-after-x-day/909
=> send a suggestion to update after 90 days

CHANGELOG.md, scss/gallery/_attachment-view.scss, src/renderer/components/dialogs/FullscreenMedia.tsx, src/renderer/components/dialogs/ViewProfile.tsx
move download button in fullscreen media view to top and improve its styling a bit.
=> Move download btn to top

CHANGELOG.md, scss/_global.scss, src/main/ipc.ts, src/renderer/App.tsx, src/renderer/components/CrashScreen.tsx, src/renderer/components/Menu.tsx, src/renderer/ipc.ts, src/renderer/main.tsx, src/renderer/runtime.ts, src/renderer/stores/chat.ts
An interface that abstracts the electron functions.
This way we'll just need to implement one interface for new runtimes such as a Browser runtime.
In the long term this file will replace `src/renderer/ipc.ts`.
https://github.com/deltachat/deltachat-desktop/blob/add_runtime.ts_and_crash_screen/src/renderer/runtime.ts
Adding a crash screen in the place of the white-screen crash.
=> Add runtime.ts and crash screen

CHANGELOG.md, UPGRADING.md, src/main/deltachat/backup.ts, src/main/index.ts, src/main/ipc.ts, src/main/logins.ts, src/renderer/ScreenController.tsx, src/renderer/components/LoginScreen.tsx, src/shared/shared-types.d.ts
- You can have multiple accounts with the same email address (for example different backups you can distinguish them via the new size property on the known accounts section)
- Account folder name isn't tied to email address anymore, you can rename account folders as you like. New account folders have the format `acc[number]`. This mimics the behavior of dc iOS and dc android which could help with burner qr code reading (allows having the context before knowing the email address).
=> Change accounts folder structure again

CHANGELOG.md, src/renderer/components/chat/ChatList.tsx
When startIndex == stopIndex == 0, ids was equal to [null] and caused
message with msgId = 0 to be loaded. This commit simplifies the logic
and fixes the warning.
<del>stopIndex + 1 is replaced with stopIndex, because stopIndex is limited
by Math.min(messageResultIds.length, 10). When length is less than 10,
it caused slice to try to load more elements that were in the array,
and 11 elements maximum were loaded, which seems to be off-by-one error.</del>
=> Fix "dc_get_msg called with special msg_id=0" warnings

CHANGELOG.md, src/shared/state.ts
Technically: use system language until the user chooses their language
fixes #1712
=> Use system language on first launch if available.

package.json
The flatpak build does not require appimage or anything else.
Just the app in a directory. The change in behaviour was changed with
ff0d88bfce175ea9b182d095b6555d1e94dfb105.
This change makes the flatpak version build again.
=> package: linux add mode for just directory creation when building the app

bin/build-shared-version-info.js
Set `GIT_REF` to "None" when `git describe` returns with error,
but continue the build.
Closes #1758
-- Not sure if this full fills your style and coding guidelines, feel free to adapt or discard.
`npm test` ran fine.
=> Support builds from tar-ball.

CHANGELOG.md, src/renderer/components/helpers/useDCConfigOnce.ts, src/renderer/components/message/MessageList.tsx
Keep in mind that this text updates not when changing the setting, you need to restart dc to see the new message currently.
fixes #1638
=>  fix #1638 show explaination on no contact requests

CHANGELOG.md, docs/KEYBINDINGS.md, src/renderer/keybindings.ts
in order to provide a quick fix #1796
because `alt + left arrow` is Option + `left arrow` on mac which means move over a word like `ctrl + left arrow` on linux or windows.
=> disable keycombination for Scroll active chat

CHANGELOG.md, package-lock.json, package.json, src/renderer/components/message/LabeledLink.tsx
add a real url parser to handle the domains, this removes the 3 bugs of #1839
**Trust domain contains junk** -> now its only the hostname as it should be
**Punycode encoding should only affect the domain, not the path or the anchor** -> encoding to punycode treatment is only applied to the hostname now.
**Text shouldn't leave the dialog** -> as the remember domain text contains only the hostname it shouldn't be a problem right now (domains aren't too long most of the time, but we could also make the test breaking in the future to fix it the right way)
fix #1839
=> fix labeled links dialog issues

CHANGELOG.md, src/renderer/components/Menu.tsx, src/renderer/components/dialogs/Settings.tsx, src/renderer/stores/chat.ts, src/shared/shared-types.d.ts, src/shared/state.ts
- Disappearing messages are now enabled by default and not experimental anymore
- Fix refreshing message list when disappearing message timed out
Fixes https://github.com/deltachat/deltachat-desktop/issues/1887
=> Fix disappearing messages

CHANGELOG.md, src/renderer/components/dialogs/ForwardMessage.tsx, src/renderer/stores/chat.ts
happens. Otherwise it's possible that we corrupt the chat state.
Fixes https://github.com/deltachat/deltachat-desktop/issues/1900
=> Make sure we have a consistent chatId when DC_EVENT_MSGS_CHANGED

CHANGELOG.md, src/renderer/components/Menu.tsx
title already tells everything important.
Hides disappearing messages menu and video-chat menu in left groups and in the device chat.
=> hide non applicaple options in menu

CHANGELOG.md, build/gen-electron-builder-config.js, electron-builder.json5
fixes #1772
It turned out the icon property was missing for linux. The one for mac is probably still wrong but I'll rather look at it on a actual mac to make sure it wasn't an intentional workaround or sth. (the icon points to a non existent `resource` directory, but the file is in the build directory)
=> fix linux/debian appIcon

CHANGELOG.md, _locales/_untranslated_en.json, scss/gallery/_media-attachment.scss, src/main/deltachat/messagelist.ts, src/renderer/components/Gallery.tsx, src/renderer/components/MainScreen.tsx, src/renderer/components/attachment/Attachment.tsx, src/renderer/components/attachment/mediaAttachment.tsx, src/renderer/components/attachment/messageAttachment.tsx, src/renderer/components/message/Message.tsx, src/renderer/components/message/MessageMetaData.tsx, src/shared/shared-types.d.ts, themes/_themebase.scss
- restructure GalleryMediaAttachment code
- use real attachment type
- rename Gallery file from Media.tsx to Gallery.tsx
- display type is chosen via viewType now and if the mime type is not displayable by the browser an error is shown (fixes #1394)
adjust gallery styles:
- shorten width of files a bit so two rows can be displayed at once on half fullhd screen
- adjust play button in videos in gallery to make it clearer its a button.
=> some Attachment improvments

CHANGELOG.md, src/renderer/components/message/MessageMarkdown.tsx
to fix the merge of two links after another
and the bug that it ate the linebreak if one followed
fixes #1893
=> adjust labeled link regex

CHANGELOG.md, _locales/_untranslated_en.json, scss/contact/_contact-list.scss, scss/contact/_contact.scss, scss/login/_login.scss, src/renderer/components/LoginScreen.tsx, src/renderer/components/contact/Contact.tsx, src/renderer/components/dialogs/ConfirmationDialog.tsx, themes/_themebase.scss
- Add Keyboard navigation between accounts in account selection screen (arrow keys or tab)
- Add the account name to the account deletion-confirmation dialog (closes #1085)
- Add a hover tool-tip with account path and size when hovering over the email address of an account
(this is useful when importing a backup of an account you already have and can't distinguish which is the old account and which is the imported one)
- add hover effect to remove button (see previous gif)
=> Account selection improvements

CHANGELOG.md, src/renderer/components/message/MessageList.tsx
should work, haven't tested it yet because it needs a new core(1.47) (https://github.com/deltachat/deltachat-core-rust/pull/1936) which isn't out yet
fixes #1850
=> refresh "empty chat" info meassage on chat changes

CHANGELOG.md, scss/message/_message.scss, src/main/deltachat/messagelist.ts, src/renderer/components/helpers/MapMsgStatus.ts, src/renderer/components/message/Message.tsx, src/renderer/components/message/MessageList.tsx, src/renderer/components/message/MessageListAndComposer.tsx, src/renderer/components/message/MessageMetaData.tsx, src/renderer/components/message/MessageWrapper.tsx, src/renderer/components/message/messageFunctions.ts, src/shared/shared-types.d.ts, themes/_themebase.scss
- Code cleanup in the message component (remove unused code and some restructuring)
- Display quotes
- Show sending/error state indicator on outgoing info messages:
(state is only shown if its either pending or error)
for more info see the commit messages.
closes #1921
fixes #1867
fixes #1915
fixes #1866
=> Refactor message component and display quotes

CHANGELOG.md, src/renderer/components/dialogs/Settings.tsx
("select" and "remove" buttons beneath the profile image)
fixes #1800
=> localize some unlocalized strings in settings

CHANGELOG.md, src/main/deltachat/login.ts, src/main/logins.ts
- fixes deletion of failed-to-configure accounts
- shows a log message with all found previous orphaned/invalid accounts 
closes #1952
such an log message:
```
0.6s [i]main/find_logins: unconfigured, likely orphaned accounts, you may delete them [
'/home/username/.config/DeltaChat/accounts/ac12',
'/home/username/.config/DeltaChat/accounts/ac19',
'/home/username/.config/DeltaChat/accounts/ac20',
'/home/username/.config/DeltaChat/accounts/ac21',
'/home/username/.config/DeltaChat/accounts/ac23',
'/home/username/.config/DeltaChat/accounts/ac24',
'/home/username/.config/DeltaChat/accounts/ac30',
'/home/username/.config/DeltaChat/accounts/ac31',
'/home/username/.config/DeltaChat/accounts/ac32',
'/home/username/.config/DeltaChat/accounts/ac33',
'/home/username/.config/DeltaChat/accounts/ac34', …
```
=> Remove failed-to-configure accounts

CHANGELOG.md, scss/composer/_composer.scss, scss/gallery/_attachment-view.scss, scss/message/_message-list.scss, scss/message/_message.scss, src/main/deltachat/burnerAccounts.ts, src/main/deltachat/chatlist.ts, src/main/deltachat/messagelist.ts, src/renderer/components/attachment/messageAttachment.tsx, src/renderer/components/composer/Composer.tsx, src/renderer/components/composer/ComposerMessageInput.tsx, src/renderer/components/map/MapComponent.tsx, src/renderer/components/message/Message.tsx, src/renderer/components/message/MessageListAndComposer.tsx, src/renderer/components/message/messageFunctions.ts, src/renderer/delta-remote.ts, src/renderer/global.d.ts, src/renderer/stores/chat.ts, src/shared/shared-types.d.ts, themes/_themebase.scss
Add a draft area:
- Add possibility to add an description to an attachment
- Add quoting / reply to message
- Also removed the inline message buttons - the context menu is enough, we don't need them and they overlap sometimes with the text or the author name.
closes  #1680
=> Implement draft message with attachment & reply to message

CHANGELOG.md, src/renderer/components/message/LabeledLink.tsx, src/renderer/components/message/Message.tsx
- trust all labeled links from device chat
- Adjust order of buttons at labeled link dialog
- Fix "copy link" context menu option for labeled links
Closes #1894
Successor of #1932
=> Labeled link tweaks

CHANGELOG.md, src/main/deltachat/controller.ts, src/renderer/components/OfflineToast.tsx, src/renderer/delta-remote.ts, src/renderer/ipc.ts
- Move the networkstatus state into the frontend
- introduce ipc.onDCEvent method as alternative for
ipc.ipcBackend.on(...)
Supersedes https://github.com/deltachat/deltachat-desktop/pull/2001
Fixes https://github.com/deltachat/deltachat-desktop/issues/1842
=> Overhaul the whole reconnecting logic, making it more fault tolerant

CHANGELOG.md, src/renderer/components/message/Message.tsx, src/renderer/components/message/MessageMetaData.tsx
- show timestamp and padlock even on error
- open message info when clicking on the error status icon.
Fixes #2020
=> show timestamp and padlock even on error

CHANGELOG.md, src/renderer/components/composer/ComposerMessageInput.tsx
(dir=auto)
fix #2036
see https://support.delta.chat/t/problem-with-right-to-left-languages/1312
=> message input choose text direction (RTL or LTR) based on input

CHANGELOG.md, src/main/log-handler.ts
in essence this prints a warning instead of a huge error stack trace.
=> loghandler: warn on non-writable stream

CHANGELOG.md, docs/THEMES.md, scss/dialogs/_settings.scss, src/main/index.ts, src/main/themes.ts
- ignore css sourcemaps in theme folder (it was detecting them as themes)
- show right default background for theme in preview
- handle invalid theme metadata better
- turn cli '--theme' not found into normal init fail
and write an error message that explains it,
so normal user have a chance to understand the reason for the error:
- update guide to creating custom themes
=> theming fixes

src/renderer/components/message/Message.tsx
this was accidentally changed by the minimal theme pr,
and because there isn't a version with it we need no changelog entry this time
=> hide author name in direct messages again

CHANGELOG.md, src/main/internal-app-schemes.ts
since the electron upgrade we use custom uri schemes, this pr fixes a bug in the function handling the blob scheme which resulted in some blobs/attachments being not send to the render-process correctly - they seemed to be corrupted. (appeared on the [deltachat-logo-svg file](https://github.com/deltachat/interface/blob/master/icons/delta-v7-pathed.svg) for me)
=> fix some blobs not loading sometimes

CHANGELOG.md, src/renderer/components/composer/Composer.tsx, src/renderer/components/message/MessageMetaData.tsx
This solves 2 of the 3 issues that @jikstra reported in #2117
I'd say it closes #2117 because the "message body missing keys" bug is not easily reproduced and we plan to refactor/replace the message-markdown-parser later anyway, so as long as it is only a warning and nothing more serious (like elements missing) we can ignore it IMO.
=> Fix react warnings

CHANGELOG.md, scss/_global.scss
we decided in https://github.com/deltachat/deltachat-desktop/pull/2166 to disable font ligatures completely.
Themes could theoretically enable it again with this code if they make use of it:
```
* {
font-variant-ligatures: normal !important;
}
```
related feature request: 
https://support.delta.chat/t/disabling-font-ligatures/1490
=> disable font ligature globally

CHANGELOG.md, _locales/_untranslated_en.json, src/renderer/components/message/Message.tsx
=> Rename message context menu entry "Copy" to "Copy Text"

CHANGELOG.md, src/renderer/components/map/MapComponent.tsx, src/renderer/components/map/MapLayerFactory.ts
The own location and paths were not displayed in the map since only selectedChat.contacts were shown and the current account is not included in the contacts
=> Add current account to contacts in locations

package.json
move check-types to the end,
because it relies on the build:shared:version script
@Jikstra please also backport this to the 1.15 series, because it could help with the flatpak process
https://github.com/flathub/chat.delta.desktop/pull/52#issuecomment-803410820
Note: there is also the question of windows compatibility with the environment variable, but I don't want to pull in an extra npm package to solve it or create a script that spawns the command with the specific env var/-s in this pr.
=> fix build4production to work on its own

CHANGELOG.md, src/main/deltachat/chat.ts, src/main/deltachat/chatlist.ts, src/main/deltachat/login.ts, src/main/notifications.ts
=> make notifications more reliable and prettier

CHANGELOG.md, src/renderer/components/dialogs/ViewProfile.tsx
If the name is empty, the value of the field should be empty too,
so just opening the dialog and clicking save immediately never changes contact name.
=> fix: use display name only as a placeholder in contact profile dialog

CHANGELOG.md, src/renderer/components/message/Message.tsx
The videochat messages currently do not have a context menu. As they are basically also normal messages things like forwarding, replying and message details are also present and interesting for the user (at least for me ;).
This pull request adds the already existing context menu to the text part of the videochat message.
Secondly it adds a context menu entry for this messages that allows to copy the URL for  the videochat into the clipboard. The same strings as copying a link from a normal message is used.
=> Add context menu for videochat messages

scss/message/_message.scss, src/renderer/components/message/Message.tsx
closes #2250
(don't wonder that no names are shown, the chat shown is a mailing-list and `[Feature] mailing list support #2132` is/was not merged yet)
Change log was not changed, because there is no change to the user compared to last released version.
=> adjust styling of show html button

CHANGELOG.md, src/renderer/components/message/Message.tsx
closes #2226
Remove double-click to quote → this allows users to properly use double and triple click to select stuff again
=> remove double click to qoute

CHANGELOG.md, _locales/_untranslated_en.json, scss/message/_message.scss, src/main/deltachat/chatlist.ts, src/renderer/components/MainScreen.tsx, src/renderer/components/attachment/messageAttachment.tsx, src/renderer/components/chat/ChatListContextMenu.tsx, src/renderer/components/dialogs/MessageListProfile.tsx, src/renderer/components/message/Message.tsx, src/renderer/components/message/MessageList.tsx, src/renderer/components/message/MessageListAndComposer.tsx, src/renderer/components/message/MessageWrapper.tsx
=> [Feature] mailing list support

CHANGELOG.md, _locales/_untranslated_en.json, scss/dialogs/_audit_log.scss, scss/manifest.scss, src/main/deltachat/messagelist.ts, src/renderer/components/Menu.tsx, src/renderer/components/dialogs/ChatAuditLogDialog.tsx, src/renderer/components/dialogs/DeltaDialog.tsx, src/renderer/components/dialogs/DialogController.tsx, src/renderer/components/dialogs/Settings.tsx, src/renderer/delta-remote.ts, src/shared/shared-types.d.ts, src/shared/state.ts
Core PR: https://github.com/deltachat/deltachat-core-rust/pull/2132
Forum Feature Proposal: https://support.delta.chat/t/show-audit-log-of-group/512
=> add chat audit log

CHANGELOG.md, _locales/_untranslated_en.json, docs/CLI_FLAGS.md, src/main/index.ts, src/main/rc.ts, src/main/tray.ts, src/renderer/components/dialogs/Settings.tsx, src/shared/shared-types.d.ts
related forum topic: https://support.delta.chat/t/option-to-start-on-system-start/1663
when started minimized the tray-icon is enabled and its option is disabled for the session.
=> add `--minimized` CLI option

CHANGELOG.md, scss/message/_message.scss, src/renderer/components/message/Message.tsx
- Adjust sticker styling (quote styling).
- Fix "Forwarded by $author" in message and add support for overwritten sender name to it.
- Fix cursor type on hovering over sticker (fixes #2279)
- Reduce side margin on sticker metadata
=> sticker qoute styling and fix `Forwarded by $author` header in messages

CHANGELOG.md, package-lock.json, package.json
this release is mainly done right now to help in making the flatpak work (bin/build-shared-version-info.js manual overwrite)
=> prepare 1.20.2

scss/chat/_chat-list-item.scss, src/renderer/components/chat/ChatListItem.tsx
- Don't show fresh message counter on contact requests
- Swap contact request and archived labels position
Fixes https://github.com/deltachat/deltachat-desktop/issues/2352
=> Tune down contact requests

src/main/deltachat/backup.ts
also don't start/stop io on import, it gets started when account gets selected
and the ui does this immediatly after an succesfull import anyway
=> only stop/start affected account on backup export

CHANGELOG.md, _locales/_untranslated_en.json, src/main/deltachat/controller.ts, src/main/deltachat/login.ts, src/main/deltachat/settings.ts, src/renderer/ScreenController.tsx, src/renderer/components/screens/AccountsScreen.tsx, src/shared/shared-types.d.ts, src/shared/state.ts
- hides unread badges when syncing is off.
- also fix flashing up account list on startup
=> add switch to toggle "all account syncing"

CHANGELOG.md, src/main/deltachat/backup.ts, src/main/deltachat/controller.ts, src/main/deltachat/login.ts, src/renderer/components/screens/AccountSetupScreen.tsx, src/renderer/components/screens/AccountsScreen.tsx
(make sure to unref all contexts after use)
also make sure the account is deselected when removing the selected account
and display an error if it fails
supersedes #2371
=> fix windows account removal bug

CHANGELOG.md, src/main/deltachat/extras.ts
closes #2323
do the prebuild of this pr work for you, @YamatoRyou?
https://download.delta.chat/desktop/preview/deltachat-desktop-2378.portable.exe
=> fix copy image to clipboard compatibility on windows

CHANGELOG.md, src/main/notifications.ts
(because macOS already shows applogo)
before:
after:
(electron logo is replaced by our logo when we release)
=> don't show logo twice in notifications on macOS

CHANGELOG.md, _locales/_untranslated_en.json, src/renderer/components/message/Link.tsx, src/renderer/components/message/Message.tsx, src/renderer/components/message/MessageMarkdown.tsx
- don't show copy link, when right-clicking on tags, emails or bot commands
- also allow copying of email addresses
- fix copy of labled links
- update changelog
Only one Copy action, which can be one of the following, (in that order):
- Copy [selection] to clipboard
- Copy link to clipboard
- Copy email to clipboard
- Fallback: OR Copy message text to copy
=> context menu only show one copy

CHANGELOG.md, src/main/deltachat/chatlist.ts, src/renderer/components/chat/ChatList.tsx, src/renderer/components/map/MapComponent.tsx, src/renderer/delta-remote.ts, src/renderer/ipc.ts
when the message that changed state was not the last one it got displayed in the chat-list regardless (like when an older message got a read receipt).
though we should really move this into the core (& making it more efficient), even if @r10s should still be against that method, desktop needs it:
```js
getChatListEntryMessageIdForChatId(chatID: number): number {
// workaround until this is in core
const chatList = this.selectedAccountContext.getChatList(0,'',null)
for (let counter = 0; counter < chatList.getCount(); counter++) {
if(chatID == chatList.getChatId(counter)) {
return chatList.getMessageId(counter)
}
}
return null
}
```
=> fix wrong message in chatlistitem bug

CHANGELOG.md, docs/KEYBINDINGS.md, src/renderer/components/message/MessageList.tsx, src/renderer/keybindings.ts
- scroll up & down with pageUp/Down keys in msglist
- keep scrolling as long as the buttons are pressed
- update changelog
- also add keeping key pressed for switching chats
- update keybindings documentation
=> scroll messageList with `PageUp`/`PageDown` keys

CHANGELOG.md, src/renderer/components/map/MapComponent.tsx
this is a bug we indroduced in the 1.25.x series, so its a fix to a regression.﻿
=> fix sending POI

scss/misc/_delta-buttons.scss
**Solves #2442 (Styling for signature textarea needed)**
The text color of the "Delete Profile Image" button when disabled was not displayed correctly for some Themes, mainly for the dark theme.
**Why**
The color that was set for all themes in the disabled button when editing the profile was suitable only for light themes, since in dark themes it did not display the text.
**Additional information** 
The style bug in the "Delete Profile Image" button is corrected when it is disabled, the change is tested in the different themes.
- Photo of the button view in the different themes
=> Change the color style in the "Delete Profile Image" button when it is disabled

src/main/ipc.ts
Solves #2474 (Saving a file does not report failures)
Now when you try to download an image in a folder where you don't have write permission, an error alert is displayed to the user, indicating the problem.
**Why**
When the error of the write permission occurred, the app didn't notify the user that an error occurred.
**Additional information**
- Photo of the current error message:
=> Add error message when you try to download an image in a folder with no write permission

src/renderer/components/dialogs/Settings-Connectivity.tsx
Solves #2436 (Connectivity view uses wrong title)
Now when you enter the connectivity view, the correct title is shown.
**Why**
When you entered the connectivity view an incorrect title was displayed.
**Additional information**
Photo of the current connectivity view:
=> Fix connectivity view title

CHANGELOG.md, src/renderer/ipc.ts
Problem: renderer also logs the core events which then get sent back to the main process, so core events are currently logged twice.
also style core events in dev console:
also I removed `ipcBackend.on('error')`,
as I could not find the place where that event would be emitted.
=> don't double log core events

src/renderer/components/dialogs/Settings-DownloadOnDemand.tsx
closes #2468
mind that I still not agree with reusing the the `pref_show_emails_all` key because of its specific name, but whatever
=> change translation string for download on demand to pref_show_emails_all

scss/login/_login.scss
**Solves #2442 (Styling for signature textarea needed)**
**Style change in Textarea when editing the profile**
The color of the Textarea when editing the profile was inconsistent with the style
**Why**
There was no consistency in the "textarea" with the rest of the element in Edit profile
**Additional information** 
A transparent background is added and the color is specified: var (- bp3InputText) for the Textarea
- Photo of the "textarea" view in the dark theme and light theme
=> Texture style change

scss/_connectivity-toast.scss
Issue description:
Fixes #2454 
Offline Toast obscures message composer on small width window.
Proposed Solution:
As suggested, I modified the file `_conncetivity-toast.scss` for the divs inside the ConnectivityToast class to have a display type of block, instead of line-block.
The new behavior of the toast message can be observed here. The Archived Chats button is still clickable when the Offline Toast message appears to the user. At no moment does the toast obscure the message composer.
Suggestions are welcomed! 😁
=> Offline Toast Style Update

CHANGELOG.md, src/renderer/components/dialogs/Settings-Profile.tsx, src/renderer/delta-remote.ts
Fixes #2472  
Changed the empty string representation to 'null' when there was no profile picture. Apparently, when sending an empty string to the backend it gets interpreted as a path (which is obviously an invalid path) and throws an I/O error. 
To avoid changing many type annotations, I only added an if statement when sending the profile picture representation to the backend and added the null type on that function's parameter.
=> fix: remove profile picture

CHANGELOG.md, src/renderer/components/dialogs/Settings-Profile.tsx, src/renderer/components/dialogs/ViewGroup.tsx
**Solves #2491 (When selecting the image profile, it does not accept .jpeg .ico .apng format)**
Add image formats in the process of selecting a new image in the profile
**Why**
When trying to select an image in the profile photo, formats such as .jpeg or .ico are not accepted.
**Additional information** 
Formats are added in Setting-Profile.tsx and in ViewGroup.tsx
=> Add format image

CHANGELOG.md, src/renderer/components/dialogs/EnterAutocryptSetupMessage.tsx, src/renderer/components/dialogs/Settings-Encryption.tsx
Fixes #2277 
The solution was to remove the BlueprintJS's classes on parent `div`s (`Classes.BODY_DIALOG`). It does not affect in any way the styles of the dialogs apart from disabling horizontal scroll.
=> fix: removed horizontal scroll in autocrypt dialogs

.gitattributes
github shows the "main" language very prominently beside a respository;
for deltachat-desktop, this is meanwhile wrongly "HTML",
probably because of more help-translations
(not far ago, it was "Typescript")
this pr just let github ignore .html files from stat
so that the result should be "Typescript" again.
=> ignore .html files in programming language stats

src/renderer/components/message/MessageList.tsx, src/renderer/stores/chat.ts
This adds a guard to make sure we're not adding already existing pages to the store. The better way to prevent this, is by either filter duplicate actions/effects (maybe we can be smarter about this) or checking it way before. But this guard is good to prevent this shit from happening again.
=> Fix ghost message pages

src/renderer/components/message/MessageList.tsx, src/renderer/stores/chat.ts
Fixes `scrolls to bottom on incoming webxdc state`
https://github.com/deltachat/deltachat-desktop/issues/2545
=> [MessageList] Fix scrollToBottomIfClose on fetchedIncomingMessages

CHANGELOG.md, package-lock.json, package.json, src/shared/logger.ts
StackFrame is not exported anymore:
https://github.com/stacktracejs/error-stack-parser/pull/54#commitcomment-66531802
=> upgrade error-stack-parser to 2.0.7

CHANGELOG.md, src/main/deltachat/controller.ts, src/renderer/components/Login-Styles.tsx, src/renderer/components/LoginForm.tsx, src/renderer/delta-remote.ts
Right now, especially with poor internet connection, deltachat blocks for an annoying amount of time when entering the email address when trying to add a new account. Therefore, before this is fixed in the core we want to disable the provider check. Afterwards we want to get the provider infos only when moving the focus away from the email input field, as we don't need to check it after every key hit.
Fixes https://github.com/deltachat/deltachat-desktop/issues/2506
=> Disable get provider info as its blocking the ui sometimes

CHANGELOG.md, docs/KEYBINDINGS.md, src/renderer/components/composer/ComposerMessageInput.tsx
https://github.com/deltachat/deltachat-desktop/issues/2559#issuecomment-1052143842
=> added `Cmd ⌘ + Enter` as alias for `Ctrl + Enter` to send message when `Press Enter to Send` is deactivated

CHANGELOG.md, package-lock.json, package.json, src/main/electron-context-menu.ts
this is the oldest currently supported version of electron, electron 13 is deprecated.
the next versions of electron need a newer nodejs version﻿
=> upgrade to electron version 14

CHANGELOG.md, src/main/ipc.ts, src/renderer/experimental.ts, src/renderer/ipc.ts, src/shared/logger.ts
- fix error logging (error objects were not logged properly before) also show error message in core-coulnot-be-loaded dialog
- fix logging of catched errors
before:
```
2022-03-10T15:16:19.270Z	renderer/experiments  	DEBUG	""	{}
```
after:
```
2022-03-10T15:19:08.201Z	renderer/experiments  	DEBUG	""	{"stack":"Error: a test error - should be logged to logfile\n    at Experimental.testErrorLogging (file:///./src/renderer/experimental.ts:36:15)\n    at <anonymous>:1:5","message":"a test error - should be logged to logfile"}
```
=> fix error logging

.gitignore, CHANGELOG.md, src/main/index.ts, src/main/ipc.ts, src/main/open_url.ts, src/main/windows/main.ts, src/renderer/ScreenController.tsx, src/renderer/components/dialogs/AlertDialog.tsx, src/renderer/components/helpers/OpenQrUrl.tsx
- closes https://github.com/deltachat/deltachat-desktop/issues/2257
- show qr code content if decoding failed:
- also add a workaround for https://github.com/deltachat/deltachat-core-rust/issues/1969
until core can accept both.
=> several fixes to open uri

CHANGELOG.md, src/main/deltachat/login.ts, src/main/deltachat/webxdc.ts, src/main/index.ts, src/renderer/components/dialogs/Settings-Webxdc.tsx, src/renderer/components/dialogs/Settings.tsx, src/renderer/delta-remote.ts
- ~~[ ] clear webxdc data when message is deleted (and also close the webxdc window if its still open)~~ moved to its own issue: #2630
related: https://github.com/deltachat/deltachat-android/pull/2221
=> Webxdc keep dom storage

CHANGELOG.md, src/renderer/components/composer/ComposerMessageInput.tsx
this makes typing and long-pressing a key like backspace more smooth
=> increase debounce timeout to one second

CHANGELOG.md, package-lock.json, package.json
This turns lodash into a devDependency, removing 4.8 MiB from the package size.
=> update react-string-replace to 1.0.0

CHANGELOG.md, src/main/deltachat/login.ts
I kept the version code (label of the device message) to not annoy users with a new device message
=> remove wrong line from changelog in device msg

CHANGELOG.md, package-lock.json, package.json
fixes CVE-2022-0976: https://www.electronjs.org/releases/stable?version=14#14.2.9
=> update electron to 14.2.9

CHANGELOG.md, package-lock.json, package.json, src/renderer/components/dialogs/QrCode.tsx
why? becase we don't need it only as fallback for the core generated svg, which should not fail
also it complains about being deprecated for some time now
=> remove dependency `react-qr-svg`

src/renderer/App.tsx, src/renderer/components/ThreeDotMenu.tsx, src/renderer/components/composer/Composer.tsx, src/renderer/components/dialogs/KeybindingCheatSheet.tsx, src/renderer/components/dialogs/Settings-Advanced.tsx, src/renderer/components/dialogs/Settings-Appearance.tsx, src/renderer/components/dialogs/Settings-Autodelete.tsx, src/renderer/components/dialogs/Settings-ChatsAndMedia.tsx, src/renderer/components/dialogs/Settings-Communication.tsx, src/renderer/components/dialogs/Settings-DownloadOnDemand.tsx, src/renderer/components/dialogs/Settings-ExperimentalFeatures.tsx, src/renderer/components/dialogs/Settings-ImapFolderHandling.tsx, src/renderer/components/dialogs/Settings-Profile.tsx, src/renderer/components/dialogs/Settings.tsx, src/renderer/components/map/MapComponent.tsx, src/renderer/components/message/MessageListAndComposer.tsx, src/renderer/components/screens/MainScreen.tsx, src/renderer/contexts.ts, src/renderer/global.d.ts, src/renderer/stores/settings.ts
Move all settings (core settings, desktop settings, rc) into SettingsStore.
This improves loading times of Settings dialog (no more flashing avatar) and makes sure that all setting changes are getting announced to all components depending on them.
=> [Refactor] Use settings store in Settings.tsx

CHANGELOG.md, src/main/index.ts
when spam clicking on app icon the activate method is called
and expected the window to be ready, and threw an error otherwise (for example on startup).
To fix it I converted the "throw an error" to a "log the error" and keep working.
=> fix a startup crash on mac

CHANGELOG.md, package-lock.json, package.json, src/renderer/components/dialogs/QrCode.tsx, src/renderer/types.d.ts
fixes the peer dependency warning which is an error with newer npm versions
this pr is needed for #2687
=> use a forked version of react-qr-reader to fix the peer dependency warning

CHANGELOG.md, scss/_sidebar.scss, scss/main_screen/_main_screen.scss, scss/message/_message.scss, src/renderer/components/screens/MainScreen.tsx
before:
after:
before:
after:
before:
after:
closes #2564
=> Truncate long names and mails in sidebar, navbar, quotes and composer

src/main/deltachat/webxdc.ts
this gives more focus to the app name and looks more natural.
if we add an additional document name,
that will be prepended or will replace the Webxdc Name.
cmp. deltachat/deltachat-core-rust#3317 and https://github.com/deltachat/deltachat-core-rust/issues/3316
=> Webxdc window title: show Webxdc name first

scss/message/_message.scss
Hotfix. Want to address problems with bubble width for small devices and long user names in quotes separately.
=> Max bubble width fixed but still wrong for quotes of long user names

CHANGELOG.md, src/renderer/components/KeyboardShortcutHint.tsx, src/renderer/components/composer/ComposerMessageInput.tsx
change composer keybindings shift+enter now always adds a newline
and crtl/cmd+enter now always sends
regardless of what the enter key is set up to do
=> change composer keybindings shift+enter now always adds a newline and crtl/cmd+enter now always sends regardless of what the enter key is set up to do

scss/message/_message.scss, src/renderer/components/message/Message.tsx
For bug #2762
I made a selector for adding a top margin of 10px. I had to made the span inside the message inline-block to be able to add the margin(I think that does not create any conflict in other parts but it would be good if you can confirm it).
I also made the MessageBody component not to be rendered at all if there was no text at all. I thought an alternative to rendering the MessageBody conditional might be to use the :not(:empty) selector, but at the same time I considered that if you're not going to have any text, there wasn't even a need to run the code of MessageBody in the first place but I would also love to know your input in that.
Here is an example of the spacing between the button and the message.
And here is an example without a message.
The styles are only been applied …
=> Added vertical space between webxdc start-button and message-text

CHANGELOG.md, src/main/deltachat/webxdc.ts
closes #2803
same behaviour as https://github.com/deltachat/deltachat-ios/blob/2a091b1ab2eadc6109f362527bc099c9bdeb3d25/deltachat-ios/Controller/WebxdcViewController.swift#L82
=> use addr if displayname is not set for webxdc selfName

CHANGELOG.md, src/main/deltachat/messagelist.ts, src/renderer/components/message/Message.tsx, src/shared/shared-types.d.ts
fixes #2836
also fix changelog order
=> fix display of quoted forwarded message fix typo in log message

src/main/deltachat/chat.ts, src/main/deltachat/chatlist.ts, src/main/deltachat/contacts.ts, src/main/deltachat/login.ts, src/main/deltachat/messagelist.ts, src/renderer/ScreenController.tsx, src/renderer/components/dialogs/EncryptionInfo.tsx, src/renderer/components/message/MessageList.tsx, src/renderer/components/message/MessageWrapper.tsx, src/renderer/delta-remote.ts, src/renderer/stores/chat.ts
- more jsonrpc progress that is already mergable
- fix eslint stuff
- fix formatting
@Jikstra can you look into these warnings and into the last 2 commits:
```
./src/renderer/components/message/MessageList.tsx
106:47  warning  The ref value 
'unreadMessageInViewIntersectionObserver.current' will likely have changed by 
the time this effect cleanup function runs. If this ref points to a node 
rendered by React, copy 'unreadMessageInViewIntersectionObserver.current' to 
a variable inside the effect, and use that variable in the cleanup function  
react-hooks/exhaustive-deps
108:6   warning  React Hook useEffect has an unnecessary dependency: 
'unreadMessageInViewIntersectionObserver.current'. Either exclude it or 
remove the dependency array. Mutable values like …
```
=> more jsonrpc progress that is already mergable

src/renderer/components/conversations/Timestamp.tsx
fixes #2885
Basically move away from multiple setInterval calls to one central function calling all update functions every 60s (nothing changed there) and additionally on window focus (added). I hope this makes the whole thing more reliable in order to fix #2885
=> make timestamp update more Entity Component System like.

CHANGELOG.md, build/gen-electron-builder-config.js, electron-builder.json5, src/main/application-constants.ts, src/main/open_url.ts, src/renderer/components/helpers/OpenQrUrl.tsx, src/renderer/components/screens/WelcomeScreen.tsx, src/renderer/global.d.ts
code actually works always, like I did it for iOS in 
https://github.com/deltachat/deltachat-ios/pull/1640 or make it even 
better like I suggested in 
https://github.com/deltachat/deltachat-ios/pull/1640#discussion_r915110725
this is mainly so that we can make the code on http://webxdc.org 
clickable
cyberta found out that we already have a translation string for the already have an account case: `qraccount_ask_create_and_login_another`
=> register for `dcaccount:` and `dclogin:` scheme

src/renderer/ipc.ts
fixes #2897
I figured we don't need a changelog entry for this, or I don't know what to write there. we will move event handling to frontend sooner or later anyway so this code will be replaced. (though we might need to increase the max listener count there too)
=> solve MaxListenersExceededWarning for now

CHANGELOG.md, _locales/_untranslated_en.json, src/renderer/components/dialogs/ViewProfile.tsx
Before: `Last seen at 3min ago`
After: `Last seen 3min ago`
now show always the relative time and on hover it shows exact time:
before merging we should consider pushing translations to android so that `last_seen` can be translated
=> make contact last seen always display relative time

themes/_themebase.scss
with the "connectivity view",
we already have a green indicating sth. as "online", reuse that. the green used before is a bit too much of a muted color, this does not reflect "activity" well.
the difference is not huge, however,
this pr also synchronizes the color with android and ios and also comparable indicators
in other apps have less muted colors for showing activity.
cmp https://github.com/deltachat/deltachat-android/pull/2393 and https://github.com/deltachat/deltachat-ios/pull/1707 (there are also some screenshots)
=> use less muted color for "recently seen"

src/renderer/components/message/MessageList.tsx, src/renderer/stores/chat.ts
- type the return value in a variable, and fix a bug that became visible that way
- make naming consistent of: `newestFetchedMessageListItemIndex` and `oldestFetchedMessageListItemIndex`
=> fix chat store type checking and probably some bugs

CHANGELOG.md, _locales/_untranslated_en.json, src/renderer/system-integration/notifications.ts
when many messages are received at once (for example on startup).
Also show notifications when showNotificationContent is disabled (that was broken).
On first start notifications are grouped as soon as there is more than one, and after that they are grouped as soon as 
there are more than 3 at a time, we could still change that behaviour, both numbers are constants that can be easialy 
changed without the need to understand the code:
https://github.com/deltachat/deltachat-desktop/blob/585faf756bca476b7d429d237cbccfd5328d5631/src/renderer/system-integration/notifications.ts#L154-L156
needs a core with https://github.com/deltachat/deltachat-core-rust/pull/3643/ merged
closes #2278 for now, it is not perfect (on importing backup there are multiple `IncomingMsgBunch`-events, so 
multiple …
=> reduce notifications

CHANGELOG.md, src/renderer/components/message/MessageList.tsx, src/renderer/global.d.ts, src/renderer/stores/chat.ts, src/renderer/stores/messagelist.ts
- move message list to it's own store, that is thrown away and reacreated on selecting a chat,
so selecting a new chat auto fixes possible problems again,
also makes our code simpler
- fix go to bottom when clicking chat again
=> seperate messagelist from chat store

src/renderer/components/screens/AccountListScreen.tsx, src/renderer/experimental.ts
- cleanup account switch screen incoming message event listeners
- also add function to get context emitters to `exp`
closes #2990
=> cleanup account switch screen event listeners

CHANGELOG.md, scss/message/_message.scss, src/renderer/components/message/Message.tsx
- don't jump to parent on non webxdc messages closes #2933
- different style for webxdc info messages + show webxdc icon closes #2989
- default info style, only one icon and adjust padding
=> handle webxdc info messages differently than normal system messages

CHANGELOG.md, scss/misc/_context_menu.scss
when using touchpad it sometimes selects the text in the context menu, and then show a native context menu on top
the solution is to preventing text selection in the context menu
=> prevent double context menu on macOS

CHANGELOG.md, _locales/_untranslated_en.json, scss/message/_message.scss, src/renderer/components/message/Message.tsx
- don't show "copy text" menu entry for stickers
- add context menu option to save the sticker
- this pr needs a core with https://github.com/deltachat/deltachat-core-rust/pull/3743 merged
=> small sticker improvements and save sticker

CHANGELOG.md, src/main/deltachat/webxdc.ts
this fixes the checklist webxdc app
=> webxdc: allow `data:` in `connect-src` in CSP

CHANGELOG.md, src/main/deltachat/webxdc.ts
=> fix webxdc: allow `self` and `blob:` in `connect-src` in CSP

CHANGELOG.md, src/renderer/components/message/MessageList.tsx
- don't show unread count if you are at the bottom fixes #3033
- show jump down button earlier when scrolling up
=> improve jump down button behaviour

CHANGELOG.md, scss/message/_message-markdown.scss
for the experimental message markdown mode
=> Control overflow of so text does not escape the code block nor message bubble.

CHANGELOG.md, src/renderer/components/message/MessageList.tsx, src/renderer/stores/messagelist.ts
closes #3039
The fix consists in calling a method to load all missing messages upon rendering a “message not found in cache” message in react, would not call it clean, but it is reliable in my tests
=> fix "message not found in cache" bug

CHANGELOG.md, scss/dialogs/_forward-message.scss, src/renderer/components/dialogs/ForwardMessage.tsx, src/renderer/components/helpers/ChatMethods.ts, src/renderer/components/message/Message.tsx, src/renderer/components/message/messageFunctions.ts
* new function to open a confirmation dialog confirmDialog returns a promise so you don't have to use callback and can call other things after confirm popup is closed
* ForwardMessage dialog now has a title and a confirmation box before you forward the mesage
closes #3006
=> Add confirmDialog and confirmForwardMessage

CHANGELOG.md, src/renderer/backend-com.ts, src/renderer/components/dialogs/UnblockContacts.tsx, src/renderer/components/helpers/ChatMethods.ts
also move all use of the `window.__refetchChatlist` - hack to EffectfulBackendActions. that we can get an overview of what events need to be added to core
=> fix unblock contact did not update the chatlist

CHANGELOG.md, src/renderer/components/dialogs/Settings.tsx
unfortunatly electron builder is still too bugged to give me a way
to figgure out what kind of build we are in at runtime - I can't event plant a target specific file into the output reliably :facepalm:
I guess we'll migrate to electron forge soon...
=> temporarily remove donate link to make app store release possible again

CHANGELOG.md, _locales/_untranslated_en.json, src/renderer/components/dialogs/DeltaDialog.tsx, src/renderer/components/dialogs/DialogController.tsx, src/renderer/components/dialogs/Settings-Profile.tsx, src/renderer/components/helpers/OpenQrUrl.tsx, src/renderer/components/screens/MainScreen.tsx, src/renderer/global.d.ts
* new property on window __askForName if it is set to true first time the MainScreen opens the SettingsProfileDialog pops up for user to change their name, add photo
* SettingsProfileDialog accepts custom title, confirmLabel, cancelLabel and passes it down
fixes #3036
=> Ask for name/photo for accounts created through QR

CHANGELOG.md, src/renderer/components/LoginForm.tsx
It shows that IMAP port is going to be 993 by default, but actually the core tries multiple ports,
may get autoconfiguration XML from the server
or get the port from the provider database.
Show the string "Default" without incorrect port value instead.
=> Remove incorrect placeholder for port

CHANGELOG.md, scss/misc/_context_menu.scss
the context menu has rounded corners, before this pr the corners got pointy on hovering.
before:
after:
\#consistency
=> css: fix hover overflow on context menu corners

CHANGELOG.md, package-lock.json, package.json, src/renderer/components/conversations/emoji.ts, src/renderer/components/message/MessageBody.tsx
improve jumbomoji logic (that emoji only messages appear bigger), now works better with emoji that consist out of multiple sub-emojis like composite emojis (👪) and emojis with skin color (🧑🏾).
also removed dependency on `emoji-regex`, because it's now not needed anymore.
now works even with new emojis that are not in delta chat yet:
=> improve jumbomoji logic

CHANGELOG.md, scss/misc/_context_menu.scss, src/renderer/components/ContextMenu.tsx, src/renderer/components/chat/ChatListContextMenu.tsx
* context menu size is updated after rendering so there's no word-wrapping
* items in context menu change language when app language changes
closes [#3049]
=> ContextMenu size calculation and localization fix

bin/topEvil.sh
The new game is to remove our dependency blueprintjs, `./bin/topEvil.sh` is our trusty companion on this 
endevour: it show us where blueprint is still used.
```
🤔Result🤔
CODE:       33 | CLASSES:       35 | SCSS:      119
```
The goal is to get all 3 numbers down, idealy down to 0, bit by bit.
- change top evil goal to blueprintjs
- top evil summary
=> top evil blueprint

CHANGELOG.md, src/renderer/components/chat/ChatList.tsx, src/renderer/components/dialogs/ChatAuditLogDialog.tsx, src/renderer/components/message/Message.tsx, src/renderer/components/message/MessageList.tsx, src/renderer/components/message/MessageWrapper.tsx, src/renderer/stores/messagelist.ts
uses new MessageLoadResult type, so requires core with https://github.com/deltachat/deltachat-core-rust/pull/4038 merged
- simplify daymarkers in chataudit dialog code
- define the undefined case in the types of message caches (this make typescript catch more mistakes)
impact on desktop:
now instead of getting multiple messages that fail to load (the whole batch ~10 messages), now only the actual one faulty message fails to load, and now it also shows the error inline:
also closes #3054
also closes #3123
=> better error handling when messages fail to load from db

CHANGELOG.md, package-lock.json, package.json
adds support for `<delimited@emails>` and fixes code blocks with emojis
delimited email addresses are a part of #2872
=> update `@deltachat/message_parser_wasm` to `0.5.1`

CHANGELOG.md, src/renderer/components/conversations/Timestamp.tsx
- fix the check if TS should be fixed or updating
- also don't update them if window is not focused.
fixes #3125
=> fix relative timestamps not working

CHANGELOG.md, src/main/deltachat/webxdc.ts, src/renderer/components/dialogs/Settings-ExperimentalFeatures.tsx, src/shared/shared-types.d.ts, src/shared/state.ts
- add missing CSP header to webxdc.js
- webxdc: dedup permission rejection logging
- setting for enabling webxdc devtools
=> webxdc fixes

src/main/index.ts
=> Hardening: prohibit all DNS queries

CHANGELOG.md, src/renderer/components/attachment/menuAttachment.tsx, src/renderer/components/dialogs/Settings-ExperimentalFeatures.tsx, src/renderer/components/helpers/ChatMethods.ts
- do not save custom video chat provider if it only contains whitespaces
- sendCallInvitation: show error message instead of `[object Object]`
- don't show video chat in attachment menu when the feature is turned off
=> smaller video chat bugfixes

CHANGELOG.md, src/renderer/components/message/Message.tsx
=> always show copy link when right clicking a link in a message

CHANGELOG.md, src/main/windows/html_email.ts
by default, fixes white text on white background when the OS was in dark theme mode
=> always display html emails in black text on white background

src/renderer/components/dialogs/setup_multi_device/SendBackup.tsx
And internal variable value
I'm not sure if anything translation-related needs to be updated as well. I have not find this string in the `_locales` directory.
=> fix: multi device: translation typo transfeRring

CHANGELOG.md, src/renderer/components/conversations/emoji.ts
the issue was caused by a Variation Selector char at the end that was not accounted for.
closes #3211
|before |after|
|-------|-----|
|<img width="117" alt="Bildschirmfoto 2023-04-22 um 18 09 34" src="https://user-images.githubusercontent.com/18725968/233796165-d6f3d260-091e-41f1-9201-f30600faac07.png"> |<img width="117" alt="Bildschirmfoto 2023-04-22 um 18 34 49" src="https://user-images.githubusercontent.com/18725968/233796167-8b5f420b-c4e8-49fe-becd-8a32f0cc0f6f.png"> |
=> fix some emojis not getting larger in emoji only messages

src/main/deltachat/controller.ts
context_id was renamed into contextId,
this change is mentioned in the core changelog
=> fix: make event handling work with core 1.115.0

CHANGELOG.md, src/renderer/components/dialogs/ViewGroup.tsx
don't open view profile in the group member list when clicking on the self contact
partially addresses #3231
=> fix make self contact not clickable in group member list

CHANGELOG.md, src/main/application-constants.ts, src/main/cleanup_temp_dir.ts, src/main/deltachat/webxdc.ts, src/main/index.ts, src/main/ipc.ts, src/renderer/ScreenController.tsx, src/renderer/components/composer/Composer.tsx, src/renderer/components/dialogs/WebxdcSaveToChatDialog.tsx, src/renderer/components/dialogs/WebxdcSendToChatDialog.tsx, src/renderer/runtime.ts, static/webxdc-preload.js, static/webxdc.d.ts
also clear clipboard image/file after core copies it (needs testing) (would close #2927)
close #3241 
close #2927
=> webxdc add sendToChat api

src/main/cleanup_temp_dir.ts, src/main/index.ts
even if it seems unprobable that the temp dir ever changes during the function running,
it is better style not to mix `getDraftTempDir()` and `path` randomly and also underlines the gist better.
came over this during review of https://github.com/deltachat/deltachat-desktop/pull/3240
=> make sure, we always use the same path

CHANGELOG.md, src/renderer/components/dialogs/ViewProfile.tsx
See https://github.com/deltachat/deltachat-desktop/issues/3231#issuecomment-1557225606
~~The image might be harder to get, because is the saved messages chat avatar and not the avatar of the self contact.~~
See comments beneath r10s had a trick to get it, works, but not the prettiest or most efficient code, I know some alternative routes but they are not prettier, just a bit more efficient (runtime, not coding/maintenance) - like passing down the profile url in react properties, now that there is only one way to get to the dialog (since #3235) and that place already has the picture, but then one extra property or a cloned component just for saving 2 jsonrpc calls and 5 lines of code for this small edge case?
=> self contact now is displayed as saved messages chat in view profile

src/renderer/components/attachment/messageAttachment.tsx
Fixes #3210 
Notes:
- `dragAttachmentOut` - which eventually calls [this electron api](https://www.electronjs.org/docs/latest/api/web-contents#contentsstartdragitem) - (implicitly) expects an absolute file path. The original issue was caused by providing `fileName` to this function, which is not a proper path in general. This PR uses the `file` field of the draft object, which represents the absolute path of the relevant file. This resembles the [implementation for dragging out media attachments](https://github.com/deltachat/deltachat-desktop/blob/a713ef666e782dd81231631dadc230ddf67e1d3d/src/renderer/components/attachment/mediaAttachment.tsx#L233)
---
Preview:
=> fix crash caused by dragging file attachment from draft

CHANGELOG.md, src/main/index.ts, src/main/resume_from_sleep.ts, src/renderer/ScreenController.tsx, src/renderer/components/conversations/Timestamp.tsx, src/renderer/runtime.ts
In my experience timestamps did not update reliable when resuming from standby before. Also sometimes it did not automatically reconnect after resuming after standby.
This pr listens for resume and unlock events and then updates timestamp and calls maybe_network.
=> update timestamps and reconnect after resuming after sleep

CHANGELOG.md, src/main/windows/main.ts
(broke qr scan under linux (and maybe also under windows, was not tested))
fixes #3279
=> fix: if systemPreferences.askForMediaAccess is not available, then don't call it

CHANGELOG.md, src/main/deltachat/webxdc.ts
=> don't close webxdc on `sendToChat()`

CHANGELOG.md, src/renderer/ScreenController.tsx
the old dialog is replaced by the new one
closes #3281
=> fix: only allow one instance of `sendToChat()`

CHANGELOG.md, package-lock.json, package.json
this release is mainly needed because it fixes the qr scanning bug on linux #3279
=> prepare 1.38.1

CHANGELOG.md, src/main/deltachat/webxdc.ts
=> fix: clicking start on an already open webxdc app now opens it again even when it was minimised

CHANGELOG.md, src/main/deltachat/webxdc.ts, src/main/ipc.ts, static/webxdc-preload.js
this is an api that we added to make the UX of the "store" webxdc nicer on desktop, it allows for drag and drop sending.
It is not yet "official" or really documented as it is just for this one app.
- https://github.com/webxdc/store/pull/197
=> add: `webxdc_custom.desktopDragFileOut` api

CHANGELOG.md, src/renderer/components/dialogs/ViewGroup.tsx, src/renderer/components/dialogs/ViewProfile.tsx
This uses `ViewProfile` component to show someone's profile when they are selected from group member list. This fixes #3267 
Note: currently, when the X button is pressed in the user's profile which is shown this way, the entire dialogue is closed. Should it show the previous dialogue instead which is the group member list?
=> Fix edit button in a contact's profile not shown when selected from a group member list(fix #3267)

CHANGELOG.md, scss/_icons.scss, scss/dialogs/_view_profile.scss, src/renderer/components/dialogs/ViewProfile.tsx
=> Fix colour of clock icon in ViewProfile

CHANGELOG.md, src/renderer/components/dialogs/ImportQrCode.tsx, src/renderer/components/dialogs/QrCode.tsx, src/renderer/components/screens/WelcomeScreen.tsx
the idea of the extra "Welcome / Add Second Device" button is to guide users installing Delta Chat on a second device without even being aware of the settings option on the other device.
without the hint to the other device,
the user has no idea, how to set up a second device or what to scan.
the dialog may be improved eg. also showing
`multidevice_same_network_hint` and `multidevice_experimental_hint`, however, that does not fit to the existing dialog - therefore, this pr fixes the very basic things only.
fixes https://github.com/deltachat/deltachat-desktop/issues/3178 together with #3349
=> show at least a basic hint on "Welcome / Add Second Device"

CHANGELOG.md, package-lock.json, package.json
which fixes 2 bugs:
- Fixed problem of IPv6 links being detected as punycode
- Fixed the bug of brackets being parsed as part of the email address
=> update `@deltachat/message_parser_wasm` to `0.6.0`

CHANGELOG.md, src/renderer/components/message/Message.tsx, src/renderer/components/message/MessageList.tsx
closes #3259
depends on https://github.com/deltachat/deltachat-core-rust/pull/4567
=> add context menu entry to resend self sent messages

CHANGELOG.md, build/gen-electron-builder-config.js, electron-builder.json5
=> fix: packaging: fix corrupted .desktop file

CHANGELOG.md, src/main/deltachat/webxdc.ts, src/main/index.ts, src/main/windows/html_email.ts, src/renderer/runtime.ts
=> Offer to copy non-HTTP links to the clipboard instead of trying to open them in webxdc source code link and inside of html emails.

CHANGELOG.md, src/main/windows/html_email.ts
=> fix `target=_blank` links in html emails don't work

CHANGELOG.md, src/main/index.ts
...for the apps.
Related test: https://github.com/webxdc/webxdc-test/pull/24
I have tested it with https://github.com/webxdc/webxdc-test/pull/24 and it works.
=> feat: webxdc: make `isSecureContext === true`

CHANGELOG.md, static/help/help.css, static/webxdc_wrapper.html
With webxdc it affects the "loading" stage.
I tested both light and dark mode for both the help page and the webxdc. Both look ok.
=> style: add dark theme for help and webxdc wrapper

CHANGELOG.md, _locales/_untranslated_en.json, scss/dialogs/_group-styles.scss, src/renderer/components/dialogs/Settings-ExperimentalFeatures.tsx, src/renderer/components/dialogs/ViewGroup.tsx, src/shared/shared-types.d.ts, src/shared/state.ts
This is using experimental core API https://github.com/deltachat/deltachat-core-rust/pull/4649
For merging:
=> feat: add "related chats" to group profile

CHANGELOG.md, src/renderer/components/dialogs/ViewProfile.tsx
=> fix "Verified by" is shown weirdly for contacts that were verified directly

CHANGELOG.md, src/renderer/components/SearchInput.tsx, src/renderer/components/chat/ChatList.tsx, src/renderer/components/screens/MainScreen.tsx
fixes #3014
and more compact design:
=> fix: remove duplicated search button on "search in chat"

CHANGELOG.md, _locales/_untranslated_en.json, src/renderer/components/dialogs/Settings-Advanced.tsx, src/renderer/components/dialogs/Settings-ExperimentalFeatures.tsx, src/renderer/components/dialogs/Settings-ImapFolderHandling.tsx, src/renderer/stores/settings.ts
Depends on https://github.com/deltachat/deltachat-core-rust/pull/4803
=> feat: add developer option to disable IMAP IDLE

src/renderer/components/LoginForm.tsx, src/shared/shared-types.d.ts
- fix #3432
Looking at code this as the only boolean setConfig that was set like this. But I could have missed something, I'm >80% sure.
=> fix set config issue for socks proxy setting

CHANGELOG.md, package-lock.json, package.json
this is the last version of electron to still support windows 7
=> update electron from `v22.3.24` to version `v22.3.27`

CHANGELOG.md, build/gen-electron-builder-config.js, electron-builder.json5
=> shorten package description, because some debian had problems with our large description.

CHANGELOG.md, scss/message/_message.scss, src/renderer/components/message/MessageMarkdown.tsx
The extra linebreak class did not really do anything anyway.
(besides causing the bug)
Maybe there was an idea to compress multiple line breaks (over 3) into just 2-3 linebreaks / multiple empty lines,
but this should be done in the message-parser now if we need it.
=> fix copy text inserts extra linebreaks

CHANGELOG.md, scss/dialogs/_webxdc_send_to_chat.scss, scss/manifest.scss, src/renderer/components/dialogs/WebxdcSendToChatDialog.tsx
also removed unnecessary Card component and made a new css file for this dialog (don't just reuse all mailto styles), I think in the future it would make sense to give the "select chat from list with search" ui element it's own react component, then it makes more sense to just have one class for it because then we can be sure there really is only one variant of the element.
hide whitespaces for a clearer review experience.
=> add option to save to file system to webxdc "send to chat"-dialog

scss/dialogs/_view_profile.scss
this bug was introduced likely by #3445, which is not released yet,
so no changelog entry needed in this case.
=> fix no linebreaks in status of contacts

src/renderer/components/dialogs/Settings-ExperimentalFeatures.tsx, src/renderer/components/dialogs/ViewGroup.tsx, src/shared/shared-types.d.ts, src/shared/state.ts
we can only do this without migration because there is no release with this feature yet.
This pr is only about naming consistency.
=> lowercase `enableRelatedChats` settings key

CHANGELOG.md, _locales/_untranslated_en.json, scss/gallery/_media-attachment.scss, scss/gallery/_media.scss, scss/misc/_context_menu.scss, src/renderer/components/Avatar.tsx, src/renderer/components/Gallery.tsx, src/renderer/components/Sidebar.tsx, src/renderer/components/ThreeDotMenu.tsx, src/renderer/components/attachment/mediaAttachment.tsx, src/renderer/components/attachment/messageAttachment.tsx, src/renderer/components/dialogs/Edit-Group-Image.tsx, src/renderer/components/dialogs/FullscreenMedia.tsx, src/renderer/components/screens/MainScreen.tsx, src/renderer/keybindings.ts, src/renderer/stores/store.ts, src/shared/shared-types.d.ts, src/shared/state.ts, themes/_themebase.scss
todo:
https://react-window.vercel.app/#/api/FixedSizeGrid
- ~~lazy loading list content and reloading when it changes (like chatlist, and evens: deletion, incoming, changed (like for when webxdc title changes(loosely related to also #3412)))~~ first experiments failed, see #3446 to pick this up again
- ~~Gallery tabs integrated into navbar~~ we need to further discuss this, first experiments with it speak against it.
closes #3161
=> add global gallery / all-media view

CHANGELOG.md, src/main/index.ts, src/main/resume_from_sleep.ts
This PR fixes a race condition causing electron to directly crash returning `SIGTRAP`. Apparently we can not use electrons `powerMonitor` before the `onReady` event got fired.
Related PR: https://github.com/deltachat/deltachat-desktop/pull/3381
Closes: #3459
=> Initialise power monitor after electron signals readyness to fix SIGTRAP issue

CHANGELOG.md, src/main/windows/main.ts
This fixes an issue where `sender` is not given on the event object on `resize` or `move` events, causing an error where the bounds can not be updated.
Since this issue didn't seem to come up before, I assume this is due to my special Linux setup (no desktop, only using X11 + i3)? Might be an edge case, however, this PR changes the update method to a) make sure it retrieved the bounds b) which are now taken directly from the `window` instance.
Closes: https://github.com/deltachat/deltachat-desktop/issues/3462
=> Retrieve bounds directly from window and check if null on move or resize event

.eslintrc.js, CHANGELOG.md, package-lock.json, package.json
This PR installs the `eslint-plugin-prettier` package and enables prettier-related linting warnings through eslint.
I prefer to see prettier style violations directly in my IDE (neovim in that case) and use the automatic fixing feature as a part of it, but also happy to find another approach if there are any recommendations.
Before:
After:
=> Show prettier linter warnings through eslint

CHANGELOG.md, package-lock.json, package.json
dc core is now build with and for node 18
=> update deltachat-node and deltachat/jsonrpc-client to `v1.128.0`

src/renderer/deviceMessages.ts
also because translation for key `update_1_36_audit` was removed.
I keept the 1.38 device message that we stil have the template to modify for the 1.41 and 1.42 device messages.
=> remove outdated device messages

CHANGELOG.md, scss/dialogs/_settings.scss, src/renderer/components/dialogs/Settings-Profile.tsx
=> Fix centering of username in settings view

CHANGELOG.md, src/renderer/components/dialogs/EnterAutocryptSetupMessage.tsx, src/renderer/components/dialogs/Settings-Encryption.tsx
some autocrypt-setup strings were duplicated,
and the ones desktop was using were partly too short
or do not follow autocrypt ux as not talking about "keys".
also, this adds unneeded load for translators.
this pr switches to using the same strings as on android/ios;
once merged, the duplicated strings can be removed from transifex.
=> fix autocrypt setup message strings

src/renderer/components/helpers/ChatMethods.ts
which was a remnant from the cffi.
`BackendRemote.rpc.createChatByContactId` will return a more useful error if sth failed.
=> remove useless if statement

CHANGELOG.md, src/renderer/components/dialogs/Settings-Profile.tsx
Basically leaving the profile name empty resulted in the name `"null"` being chosen.
Also there is another bug where the name was not updated because this happens in while passing to jsonrpc and the settings cache just stores what you set, maybe it should reload the affected config key instead, but that's another issue/task.
=> fix `null` account name when leaving the field empty bug

CHANGELOG.md, src/renderer/components/dialogs/CreateChat.tsx, src/renderer/components/dialogs/ViewProfile.tsx
- for the "introduced by" line, only use verifier_id (no ContactObject.is_verified)
- show verification icon in title of view profile if verified dm chat exists.
This does the view profile part of #3468.
This pr depends on https://github.com/deltachat/deltachat-core-rust/pull/4918
=> view profile part of i3468

src/renderer/components/composer/Composer.tsx
did not work because it removed the file, but not the viewtype and core does not allow saving a draft with a file/image viewtype but without a file.
fixes #3484
no changelog entry because the thing that broke it (send compressed images) is not released yet / is in the same version as this fix.
=> fix file deletion in draft

CHANGELOG.md, src/renderer/components/contact/ContactList.tsx, src/renderer/components/dialogs/CreateChat.tsx, src/renderer/components/dialogs/ProtectionStatusDialog.tsx, src/renderer/components/dialogs/UnblockContacts.tsx, src/renderer/components/dialogs/ViewGroup.tsx, src/renderer/components/helpers/ChatMethods.ts, src/renderer/stockStrings.ts, themes/dev_rocket.scss, themes/minimal.scss
This PR simplifies the UI by removing all options to manually create a verified group chat. The idea is to automatically do so if all selected group members are known to be verified.
If an unverified member is added to an verified group a dialogue will be displayed. 
https://github.com/deltachat/deltachat-desktop/assets/1822473/5dec1da8-8f00-4cdc-a9fa-002c6c2aba1d
This entails:
Tracking issue: https://github.com/deltachat/deltachat-desktop/issues/3468
=> Automatically create verified group when all users are verified

CHANGELOG.md, package-lock.json, package.json, src/renderer/components/dialogs/CreateChat.tsx, src/renderer/components/dialogs/ViewProfile.tsx
also use the new `isProfileVerified` instead of loading the dm chat (closes #3468 (this was last todo item of it))
=> update deltachat-node and deltachat/jsonrpc-client to `v1.130.0`

CHANGELOG.md, scss/_icons.scss, scss/chat/_chat-list-item.scss, scss/contact/_contact.scss, scss/dialogs/_group-styles.scss, scss/main_screen/_main_screen.scss, scss/main_screen/_navbar_wrapper.scss, scss/misc/_avatar.scss, src/renderer/components/chat/ChatListItem.tsx, src/renderer/components/contact/Contact.tsx, src/renderer/components/dialogs/ViewGroup.tsx, src/renderer/components/dialogs/ViewProfile.tsx, src/renderer/components/screens/MainScreen.tsx
- fix truncation so verified icon is always shown on ViewGroup and on ViewProfile
- always show verified icon in chatlist items
- fix trucation on contact list items
- fix truncation in navbar
- fix centering of verified icon
- improve spaceing in chatlistitems also trucate name in chatname in message search results
- more spacing
- center avatars
- css fixes
closes #3498
removes multiline display of display/group name in view group/profile, I couldn't get it to look good, maybe some other css wizard wants to try.
=> make sure verified icon is shown everywhere

CHANGELOG.md, src/main/windows/help.ts, static/help/help.css
now, that the in-app help becomes more into view, the "scroll to top" button, looking like a foreign object, get more into focus.
this pr styles the button in a more decent way, better fitting to overall look of the app. it just sets opacity, so in dark mode, things should still be fine (in case we add dark mode to the help)
before / after:
(a shorter wording as just "Top" or "Content" may be another improvement - or only use an arrow, similar to what we're doing to scroll down in chat - but that is another effort and discussion, translation etc. - so this pr is just unconditional improvement of the current state :)
=> help gets a nicer "scroll to top"

CHANGELOG.md, src/renderer/components/dialogs/ViewGroup.tsx, src/renderer/components/dialogs/ViewProfile.tsx
the headlines in profiles should just read what the "profile" is about - so "Contact", "Group", "Broadcast List" -
not that it is a "profile" (whatever that is from the view of the user).
also the 'Edit' prefix is not correct,
esp. confusing as there is a dialog that open the thing for editing.
these are the headlines that we're using also on android/ios, and that are used in similar ways also in similar app.
left=before / right=after:
&nbsp;
(nb: it is correct that "tunis1000" does not have a green checkmark, i just used that to test breaking encryption)
=> streamline headlines in profiles

CHANGELOG.md, src/renderer/components/composer/Composer.tsx, src/renderer/components/composer/DisabledMessageInput.tsx, src/renderer/components/composer/useIsChatDisabled.ts, src/renderer/components/message/MessageListAndComposer.tsx
This PR hides the composer view including it's little message when being in the read-only "Device Message" chat as it didn't add much information for the user.
Also, I've done a mini-refactoring, moving this logic into own component and hook files.
Closes https://github.com/deltachat/deltachat-desktop/issues/3511
=> Do not show redundant read-only message when in device messages chat

CHANGELOG.md, src/renderer/components/dialogs/DisappearingMessages.tsx, src/renderer/components/dialogs/MuteChat.tsx, src/renderer/components/dialogs/Settings-Autodelete.tsx, src/shared/constants.ts
Update the global and group-scoped disappearing message options to reflect the values from the Android app.
Closes https://github.com/deltachat/deltachat-desktop/issues/3509
=> Update options for disappearing messages

CHANGELOG.md, src/renderer/components/message/Message.tsx, src/renderer/components/message/MessageList.tsx
Closes: https://github.com/deltachat/deltachat-desktop/issues/3535
=> Fix: Do not show reply option in read-only groups

CHANGELOG.md, scss/composer/_composer.scss, src/renderer/components/composer/Composer.tsx, src/renderer/components/composer/DisabledMessageInput.tsx, src/renderer/components/composer/useIsChatDisabled.ts
Follow up PR from https://github.com/deltachat/deltachat-desktop/pull/3532
**Minor fixes:**
* Fix warning for using an unknown translation by just returning an debug string (this is at least how it was in the version before)
* Remove `useRef` as it doesn't really have a use in this scenario
**Layout fix:**
CSS: Center text always, also in narrow window sizes, independent of padding
Before:
After:
=> Improve layout and fix unknown locale of `DisabledMessageInput`

CHANGELOG.md, src/renderer/components/message/Message.tsx
=> fix double message context menu

CHANGELOG.md, src/main/deltachat/webxdc.ts
Used to find this bug that is triggered when you send 2 status updates at the same time or closely together:
I think it is fixed in the next core update, so I'm doing a pr to upgrade core next: #3580
=> log error when webxdc status update send fails

CHANGELOG.md, src/main/windows/html_email.ts
to adress #3568
I can not reproduce this on mac as it only happens on arch which seems to use wrong or broken versions of electron?
Anyways this change makes logical sense so it is fine to merge.
=> try fixing the race in html view

CHANGELOG.md, src/renderer/components/dialogs/ConfirmationDialog.tsx, src/renderer/hooks/useConfirmationDialog.ts
```typescript
const openConfirmationDialog = useConfirmationDialog()
const confirmed = await openConfirmationDialog({
message: '...',
})
if (confirmed) {
// Do something
}
```
Closes: https://github.com/deltachat/deltachat-desktop/issues/3485
=> Helper method to easily use confirmation dialogues

src/renderer/components/chat/ChatList.tsx, src/renderer/components/chat/ChatListItemRow.tsx
the types are unfortuantely not checked at the point of the data of virtual lists. so the typescript compiler did not catch this.
changelog entry not needed, because the introduced bug is not released yet.
=> Regression: Add missing openDialog and type declaration for contact chat list items

CHANGELOG.md, src/main/notifications.ts
My OS does not support notifications so my console is spammed with "No handler found for notifications.clear" logs. This is clearly an edge-case but annoying for development.
This PR reduces the noise and adds a no-op handler to all notifications-related IPC events to silently "fail".
=> Silently fail when notifications are not supported by OS

CHANGELOG.md, src/renderer/components/chat/ChatListItem.tsx, src/renderer/components/message/MessageBody.tsx, src/renderer/components/message/MessageMarkdown.tsx
also simplify MessageBody component
closes #3476
preview:
| markdown disabled (default) | markdown enabled |
|------------------------------| -------------------|
|<img alt="Bildschirmfoto 2024-01-01 um 06 21 58" src="https://github.com/deltachat/deltachat-desktop/assets/18725968/7e64748b-efa9-4cca-a6e9-6560b3500a6d"> | ![image](https://github.com/deltachat/deltachat-desktop/assets/18725968/969e9f58-b2e2-4232-8112-073ff5a7fb59)|
=> message-parse summary text in chatlist item summary

CONTRIBUTING.md, README.md
follows in the footsteps of [dc-android](https://github.com/deltachat/deltachat-android/pull/2893) and [dc-ios](https://github.com/deltachat/deltachat-ios/pull/2005)
=> add info for new contributors

CHANGELOG.md, scss/dialogs/_group-styles.scss, scss/dialogs/_view_profile.scss, src/renderer/components/Avatar.tsx, src/renderer/components/ProfileInfoHeader/index.tsx, src/renderer/components/ProfileInfoHeader/styles.module.scss, src/renderer/components/dialogs/ViewGroup.tsx, src/renderer/components/dialogs/ViewProfile/index.tsx
Inline verified icon with display name and center it with text when displaying profile info in groups and contacts.
Before:
After:
Bonus-Level:
* New `ProfileInfoHeader` component which is now reused across "view profile" and "view group" dialogs
Closes #3620
=> Improve position of verified icon in profile info

CHANGELOG.md, src/renderer/components/dialogs/ViewProfile/index.tsx, src/renderer/components/screens/MainScreen.tsx
- hide email address for guaranteed e2e DM chats in the titlebar #3629
- use displayName for contact in verified_by in Contact Dialog (also hide email address) #3629
close #3629
=> hide email addresses in chat titlebar for guaranteed e2e DM chats and in verified_by in ViewProfile dialog

scss/message/_message.scss, src/renderer/components/message/Message.tsx
This PR is a minor adjustment to indicate better to the user that some of the info bubbles are clickable / interactive as they for example show further dialogs:
- Show a cursor pointer
- Add a hover style
Bonus level:
- Do _not_ register an `onClick` event on _all_ info bubbles, even when they're not interactive
- Minor design tweak: Make them a little rounder and text better horizontally centered
I haven't made a proper refactoring around styles for now as the message component logic is too interwined.
**Before**
**After**
https://github.com/deltachat/deltachat-desktop/assets/1822473/4ee30b31-690c-4d3e-872f-6ee861fe7783
=> Indicate better that some info bubbles are interactive

scss/message/_message.scss
as this is just unused css this does not need a changelog entry.
We now have hover buttons again, if we want a reply button (latest discussions with adz and r10s said no), then we better add it in the new hover button component that adz made.
=> remove unused css for reply hover button

CHANGELOG.md, scss/_connectivity-toast.scss, scss/_global.scss, scss/_sidebar.scss, scss/_variables.scss, scss/chat/_chat-list-item.scss, scss/chat/_chat-list.scss, scss/composer/_emoji-sticker-picker.scss, scss/dialogs/_group-styles.scss, scss/dialogs/_qr-code.scss, scss/dialogs/_qr-import.scss, scss/gallery/_attachment-view.scss, scss/map/_map.scss, scss/message/_message-list.scss, scss/misc/_context_menu.scss, src/renderer/components/AbsolutePositioningHelper/styles.module.scss, src/renderer/components/dialogs/FullscreenMedia.tsx, src/renderer/components/map/MapComponent.tsx
remove z-index where it was not needed, where it was needed tried to convert it to a lower or local/scoped z-index and put the remaining global ones into one file (`_variables.scss`).
- scope the FAB z-index to the chatlist to get rid of its global z-index
- remove unessesary z-index from .group-image-edit-button
- reduce dependency on z-index in qr scanner ui
- remove dependence on z-index from fullscreen media view
- rm z-index from connectivity toast
- rm unnecessary z-indexes in jump-down-button
- put all global z-index values into a scss map in _variables.scss
- fix fmt
=> z-index refactoring

CHANGELOG.md, src/renderer/components/Avatar.tsx, src/renderer/components/GroupImage.tsx, src/renderer/components/dialogs/FullscreenAvatar.tsx, src/renderer/runtime.ts
fixes #3664
This was broken because `onDownload` uses the original filename that is provided by recent cores and this change did not update the workaround/hack to fake message objects for the fullscreen media view to reuse it for avatars.
Making a dedicated component for it avoids such problems in the future in addition to fixing the issue.
=> make an own variant of fullscreen media view for avatars to fix #3664

src/renderer/stores/settings.ts
=> update UI if display name changed by a different device

CHANGELOG.md, scss/misc/_context_menu.scss, src/renderer/components/ContextMenu.tsx
Uses an transparent overlay to detect clicks to close the context menu. This allows us following the default behaviour of other applications and OS where you need to "click away" the context menu first before you can continue doing something else
Closes: https://github.com/deltachat/deltachat-desktop/issues/3643
=> Use overlay in context menu

CHANGELOG.md, src/renderer/components/AccountListSidebar/AccountItem.tsx, src/renderer/components/AccountListSidebar/styles.module.scss
These bugs were introduced by adz's refactor/merge commits on #3680, those also broke the shadow for the mute icon's shadow on the account, but I haven't addressed this in this small quick fix pr.
=> Fix broken/wrong/missing background for muted and turned off account badges in multiaccount sidebar

CHANGELOG.md, src/renderer/components/message/Message.tsx
=> Fix "Broken protection" message not opening info dialog on tap

CHANGELOG.md, src/renderer/components/AccountListSidebar/styles.module.scss
make account switcher 2px wider: https://support.delta.chat/t/a-few-ideas-to-make-dc-desktop-1-43-even-better/2931
(so traffic lights look more centered on macOS)
before:
after:
=> slightly wider account sidebar as suggested in the forum

CHANGELOG.md, scss/dialogs/_settings.scss, src/renderer/components/ImageSelector/index.tsx, src/renderer/components/ImageSelector/styles.module.scss, src/renderer/components/dialogs/EditProfileDialog/ProfileImageSelector.tsx, src/renderer/components/dialogs/EditProfileDialog/index.tsx, src/renderer/components/dialogs/EditProfileDialog/styles.module.scss, src/renderer/components/dialogs/ViewGroup.tsx
This PR refactors the new `ImageSelector` to not only be used for profile images but also group images.
=> Reuse new image selector component for group images

CHANGELOG.md, src/renderer/components/message/Message.tsx
Fix the bug where changing display name of a contact does not change it immediately in the messages
Closes #3703
=> Fix: Changing display name of a contact does not change it immediately in the messages

CHANGELOG.md, src/renderer/components/helpers/ChatMethods.ts, src/renderer/components/screens/MainScreen.tsx
I think I found a solution to tackle a race condition which caused an error described here: https://github.com/deltachat/deltachat-desktop/issues/3675 - The underlying issue is a race condition where the message list store was temporarily populated with an invalid chat id. To fix this issue we wait with displaying the critical components after the chat id got correctly set and a simple "ready" flag got flipped.
**Background**
- The message list store constructor needs the account id and chat id as arguments: https://github.com/deltachat/deltachat-desktop/blob/43e239fe8e4a9ce855204f9217a97e1dfbc7ff57/src/renderer/components/message/MessageList.tsx#L120 It gets the chat id from the chat store which gets prop-drilled down to the `MessageList` component
- This chat store is initialized in …
=> Wait until chat id got set before displaying message list

CHANGELOG.md, src/renderer/ScreenController.tsx, src/renderer/components/screens/MainScreen.tsx, src/renderer/stores/chat.ts
this is a possible fix for the bug when you delete the selected chat and then change the account and are unable to select a chat it says white or selects a random chat or other ui bugs caused by undefined behaviour.
related to https://github.com/deltachat/deltachat-desktop/pull/3726, but this pr not only removes the buggy workaround but also attempts to solve the issue, which worked nicely in my testing so far. it adds some small flickering when switching the account when the chat is loaded, but there is not much we can do about that without more refactoring. (#3725 starts with that refactoring)
closes #3726
=> move select selected chat up to select account

CHANGELOG.md, src/renderer/components/composer/DisabledMessageInput.tsx
this PR avoids getting translation for the string `messaging_disabled_device_chat` that is discarded a few lines later anyways.
(to not clutter UI, we do not show a "reasoning bar" at all for the device chat and the string is about to being removed to not add unnecessary work to the translators)
moreover, the second commit aims to cleanup the flow
=> remove deprecated string

CHANGELOG.md, src/renderer/components/dialogs/SetupMultiDevice/SendBackupDialog.tsx, src/renderer/components/dialogs/SetupMultiDevice/styles.module.scss
- **hide steps when transfering**
- **opinionated style changes - center progressbar on preparing (IMO looks better centered when switching to qr code) - while transfering make the bar take the whole width of the dialog (centered looked weird (how much width should it have); with a larger bar you can see more progress when you have a slow transfer with a big account)**
fixes #3742
After Screenshots:
- before qr code is shown: <img width="679" alt="Bildschirmfoto 2024-04-04 um 18 38 29" src="https://github.com/deltachat/deltachat-desktop/assets/18725968/5f20bd8e-f967-40ed-b4da-cb68749dfad0">
- after qr code was scanned by other device: <img width="679" alt="Bildschirmfoto 2024-04-04 um 18 38 58" src="https://github.com/deltachat/deltachat-desktop/assets/18725968/4fac628f-6217-42c7-a3ec-2445 …
=> "add second device" dialog improvements

CHANGELOG.md, src/main/menu.ts
- macOS
- `Cmd+q`
- Win/Linux
- `Ctrl+q`
=> add quick-key CtrlOrCmd+q for submenu quit

CHANGELOG.md, scss/message/_message.scss, src/renderer/components/ShortcutMenu/index.tsx, src/renderer/components/ShortcutMenu/styles.module.scss, src/renderer/components/message/Message.tsx, src/renderer/components/message/MessageList.tsx, src/renderer/components/message/MessageWrapper.tsx
Why WIP:
...instead of JS. Previously hovering over a different message would
cause the whole message list to re-render.
There are slight behavioral changes:
- Previously if you pointed the cursor to a message, then scrolled the
chat without moving the pointer, it would keep the menu on top
of the initial message, despite the cursor pointing at a different
message after the scroll.
- Now when the three-dot menu is clicked, the shortcuts menu disappears
- When you point on emojis, the menu also disappears
The new behavior more closely resembles that of Signal.
=> perf: hide/show on-hover shortcut menu with CSS

CHANGELOG.md, src/renderer/components/dialogs/ConfirmSendingFiles.tsx
when you drag and drop send multiple files on deltachat it asks you if you want to send them in one action, this confirmation dialog lacked top padding, so it looked weird
=> add missing top padding to confirm sending files dialog

src/renderer/ScreenController.tsx, src/renderer/components/RuntimeAdapter.tsx, src/renderer/components/dialogs/About.tsx, src/renderer/contexts/KeybindingsContext.tsx, src/renderer/global.d.ts, src/renderer/keybindings.ts
- **fix open about dialog and continue moving code into RuntimeAdapter**
- **fix webxdc sendToChat by moving `runtime.onWebxdcSendToChat` to `RuntimeAdapter`**
follow up to #3725. fixing 2 bugs that were introduced by that big refactoring.
This needs no changelog entry as the bugs were not released yet.
=> fix runtime-opened dialogs

CHANGELOG.md, src/renderer/backend-com.ts, src/renderer/components/chat/ChatList.tsx, src/renderer/components/chat/ChatListHelpers.tsx, src/renderer/components/dialogs/ForwardMessage/index.tsx, src/renderer/components/dialogs/MailtoDialog.tsx, src/renderer/components/dialogs/UnblockContacts.tsx, src/renderer/components/dialogs/ViewGroup.tsx, src/renderer/components/dialogs/ViewProfile/index.tsx, src/renderer/components/dialogs/WebxdcSendToChat/index.tsx, src/renderer/hooks/chat/useChatDialog.ts
depends on https://github.com/deltachat/deltachat-core-rust/pull/4476
closes #3208
=> chat list update event

CHANGELOG.md, src/main/deltachat/webxdc.ts, src/main/menu.ts, src/main/windows/help.ts, src/main/windows/html_email.ts
- **refactor menu code a bit to reuse some code**
- **add help menu to html email window and help window**
- **html-email: make select all always select the sandboxed email text**
fixes #3775
note that opening the about dialog from the menu is currently broken, I fixed that in #3777
=> further window menu fixes

CHANGELOG.md, src/main/notifications.ts
=> fix Clicking notification does not bring Delta Chat to foreground on Windows

CHANGELOG.md, src/renderer/ScreenController.tsx, src/renderer/components/RuntimeAdapter.tsx, src/renderer/components/chat/ChatList.tsx, src/renderer/components/dialogs/CreateChat.tsx, src/renderer/components/dialogs/ForwardMessage/index.tsx, src/renderer/components/dialogs/QrCode.tsx, src/renderer/components/dialogs/ViewGroup.tsx, src/renderer/components/dialogs/ViewProfile/index.tsx, src/renderer/components/dialogs/WebxdcSendToChat/index.tsx, src/renderer/components/message/MessageMarkdown.tsx, src/renderer/components/screens/MainScreen.tsx, src/renderer/components/screens/WelcomeScreen/InstantOnboardingScreen.tsx, src/renderer/contexts/ChatContext.tsx, src/renderer/contexts/DialogContext.tsx, src/renderer/hooks/chat/useChatDialog.ts, src/renderer/hooks/chat/useCreateChatByContactId.ts, src/renderer/hooks/chat/useCreateDraftMesssage.ts, src/renderer/hooks/chat/useMessage.ts, src/renderer/hooks/chat/usePrivateReply.ts, src/renderer/hooks/chat/useSelectLastChat.ts, src/renderer/hooks/dialog/useDialog.ts, src/renderer/hooks/useOpenMailtoLink.ts, src/renderer/stores/settings.ts
Closes #3776
Alternative to #3787 (which showed caching issues when switching accounts)
The only thing that is a bit annoying in terms of flickering now are the gallery tabs (when the experimental feature location streaming is enabled), though that is only minor, we could solve that by splitting the setting store up in one that caches account setting and another one that caches config.json/DesktopSettings, the latter stores the experimental option for location streaming and does not need to be reloaded everytime the account id changes.
=> Prevent re-rendering of account sidebar when switching account

CHANGELOG.md, src/main/ipc.ts, src/main/windows/main.ts
=> whitelist files chosen by file chooser

CHANGELOG.md, src/renderer/components/Settings/Advanced.tsx, src/renderer/components/Settings/ChatsAndMedia.tsx, src/renderer/components/Settings/Encryption.tsx, src/renderer/components/Settings/ExperimentalFeatures.tsx, src/renderer/components/Settings/Settings.tsx
=> reorganise some settings acording changes on android & ios

CHANGELOG.md, src/renderer/components/ReactionsBar/ReactionsBarContext.tsx, src/renderer/components/ReactionsBar/useReactionsBar.ts, src/renderer/components/message/MessageList.tsx
The bug was with scrolling. On scroll, the reactions bar closes. I'm preventing scrolling to bottom when the reactions bar is open/shown.
=> Fix the bug where new message arriving makes the reactions bar and dialogue closed

CHANGELOG.md, src/renderer/components/LoginForm.tsx
make clearer, this is not a password the user can define here, esp. later editing lacks the information completely.
we found out by complains / user testing in the past that the term 'Existing' is needed here,
cmp https://github.com/deltachat/deltachat-android/pull/1256 .
in case of chatmail creating accounts
by using new passwords for non-existing addreses,
this is a special, not recommended case anyways -
and you still cannot change passwords eg. on editing account settings.
=> emphasize 'Existing Password'

CHANGELOG.md, _locales/_untranslated_en.json, src/main/application-constants.ts, src/renderer/components/Dialog/DialogContent.tsx, src/renderer/components/ImageCropper/index.tsx, src/renderer/components/ImageCropper/styles.module.scss, src/renderer/components/dialogs/EditProfileDialog/ProfileImageSelector.tsx
fixes #1779
- a component to crop any image to a certain size by zooming and dragging the original to fit a predefined shape
- this component is used in ProfileImageSelector by altering result of ImageSelector upload
- there's a circle pattern as default and square pattern, images are cropped as square
What's left to do:
- decide on cancel behavior
- decide if there should be some way to tell cropper to use the whole image besides the zooming in manually
=> Work on ImageCropper

CHANGELOG.md, src/renderer/components/Settings/Advanced.tsx, src/renderer/components/Settings/Encryption.tsx, src/renderer/stores/settings.ts
=> hide irrelevant advanced settings for chatmail users

CHANGELOG.md, src/renderer/components/dialogs/EditAccountAndPasswordDialog.tsx
I am not sure about my solution. Perhaps a better solution would be removing `disableUpdate` state?
=> Fix the problem where Ok Button does not close EditAccountAndPassword dialogue

CHANGELOG.md, src/renderer/components/contact/ContactList.tsx, src/renderer/components/dialogs/CreateChat/index.tsx, src/renderer/components/dialogs/CreateChat/styles.module.scss
For huge contact lists (5000 contacts), rendering took ~5 seconds.
This solves this problem by only actually rendering the
part of the list that is currently scrolled to.
We already have this implemented for `ChatList.tsx`
Parially addresses https://github.com/deltachat/deltachat-desktop/issues/1830
Why partially? Because `BackendRemote.rpc.getContacts()`
still takes 3 seconds for 5000 contacts
This commit has side effects:
- a negative: the affected contact lists on non-default app themes
where the item height is not exactly 64px
are now slightly more ugly. See TODO about `itemSize={64}`
- a (positive?) side effect: `AddMemberChipsWrapper`
is now outside the scrollable region (i.e. it's always on top)
It works fine since it's `max-height: 33%`
=> perf: use 'react-window' for contact list

src/renderer/components/dialogs/EditProfileDialog/ProfileImageSelector.tsx, src/renderer/components/screens/WelcomeScreen/AlternativeSetupsDialog.tsx, src/renderer/components/screens/WelcomeScreen/InstantOnboardingScreen.tsx, src/renderer/components/screens/WelcomeScreen/OnboardingScreen.tsx, src/renderer/hooks/useInstantOnboarding.ts
profile picture is saved as soon as it is set,
displayname is set when you leave the dialog (by clicking other options, login or going back) or loose focus on the input field
=> remember profile picture and displayname by saving it to core earlier

CHANGELOG.md, src/renderer/components/ShortcutMenu/styles.module.scss
Introduced in a99910eaee
Before ("Layer Borders" in dev tools is turned on):
https://github.com/deltachat/deltachat-desktop/assets/39462442/8102a210-d33c-4f63-9840-67d375a7495e
Watch the text wobble (it's not just a compression thing).
Does not require a CHANGELOG entry because that commit is unreleased
=> fix: message text "wobbling" on hover

CHANGELOG.md, src/renderer/components/ImageCropper/index.tsx, src/renderer/components/dialogs/EditProfileDialog/ProfileImageSelector.tsx
- rename options targetWidth/Height to desiredWidth/Height
- if any of the dimensions is smaller than desiredWidth/Height we set new targetWidth/Height and work with smaller dimensions
=> ImageCropper support smaller images

CHANGELOG.md, src/renderer/components/message/Message.tsx, src/renderer/components/message/VCard.tsx, src/renderer/components/message/styles.module.scss
=> Show vcard in messages

CHANGELOG.md, src/main/notifications.ts
on Linux
Only body supports markup.
It also appears to be the same in the referenced Signal messenger code
This partially reverts https://github.com/deltachat/deltachat-desktop/commit/7a6f3dafb743cffdf8356080d40c1a6bb637ce45 (#3875)
=> fix: don't escape HTML in notification title

CHANGELOG.md, src/renderer/components/AccountListSidebar/AccountItem.tsx, src/renderer/components/MessageListView.tsx, src/renderer/components/screens/MainScreen.tsx, src/renderer/contexts/ChatContext.tsx, src/renderer/hooks/chat/useSelectLastChat.ts, src/renderer/keybindings.ts, src/renderer/system-integration/webxdc.ts
- Do not unselect chat when opening global map
- move alternativeView (global gallery) state into chat context
- do not open last chat when switching accounts in small screen mode, fixes #3908 
- open last chat when exiting small screen mode, closes #3909
best reviewed commit by commit
=> Small screen improvement

CHANGELOG.md, src/main/cleanup_temp_dir.ts, src/main/ipc.ts, src/renderer/components/composer/menuAttachment.tsx, src/renderer/components/dialogs/SelectContact/index.tsx, src/renderer/components/dialogs/SelectContact/styles.module.scss, src/renderer/runtime.ts
Works for now but needs some improvements in core for the future as mentioned in some comments
1. reduce this overhead:  call rpc.makeVcard by contact id, save the Vcard in a tmp file and attach it to the message which is converted into a vcardContact again - would be easier just to add a vcardContact directly in draft message
2. avoid duplicate code in contact list with react-window: currently several contact list dialogs are using the CreateChat dialog (broadcast, addGroupMember etc.)
=> #3830 send contact as vcard

CHANGELOG.md, src/main/index.ts
=> skip `requestSingleInstanceLock` on mac appstore builds (mas), because it made it unable to start the app on older macOS devices.

CHANGELOG.md, bin/build-shared-version-info.js
This should help in making builds reproducible.
closes #3944
=> use `SOURCE_DATE_EPOCH` environment var for build timestamp instead of `Date.now()` if set.

CHANGELOG.md, src/renderer/components/message/Message.tsx, src/renderer/components/message/MessageBody.tsx
- performance: memorize MessageBody, don't run message parser multiple times for the same message
- performance: add limits for MessageBody text generally and for quotes, core already has limits on text size, but for the cases where core has a bug it's still useful to have a failsave
=> performance: memorize MessageBody, don't run message parser multiple times for the same message

CHANGELOG.md, src/main/load-translations.ts, src/renderer/App.tsx, src/renderer/components/conversations/formatRelativeTime.ts, src/renderer/components/dialogs/CreateChat/index.tsx, src/renderer/components/dialogs/ViewGroup.tsx, src/shared/localize.ts, test/mocha/shared/localize.js
Closes #3870
Also fix some strings being displayed as keys and not actual strings, e.g. "1 minute" message age in Indonesian, which would show as "n_minutes:one" instead of "1 menit".
However, some strings are still not pluralized at all, such as `autodel_device_ask`, but let's consider that a different issue.
This is somewhat of an alternative to #3889 as a fix to the "message age" part of #3870
=> fix: i18n: wrong pluralization for many languages

CHANGELOG.md, _locales/_untranslated_en.json
It was recently updated in #3717, and became a little awkward. The title could be interpreted as "disable sync for all accounts, including the current one".
=> improvement: wording for background_sync_disabled

CHANGELOG.md, src/renderer/components/attachment/mediaAttachment.tsx, src/renderer/components/dialogs/ChatAuditLogDialog.tsx, src/renderer/components/message/Message.tsx
gist is to use an easier, less cluttering language - before, we had context menu items named 'Info', 'Message Details' or just 'i', opening then 'Message Details'.
together with https://github.com/deltachat/deltachat-android/pull/3137 , the menu entry will be named 'Info' everywhere and open a 'Message Info' dialog, this has the following benefits:
- inner consistency to other Delta Chat apps all apps have recognizable 'Info' in their context menu, opening a 'Message Info' dialog
- inner consistency to other desktopn menu entries: 'Message Details' is a little too much as the context 'Message' is already clear. (we also do not say 'Forward Message' or 'Reply to Message'; as an exception, we regard only 'Delete Message').
- also, 'Info' is shorter and fits better to the otherwise short …
=> consolidate wording for "Message Info"

CHANGELOG.md, _locales/_untranslated_en.json
there are no longer 'Accounts' :)
moreover, this shortens 'Only Synchronize Selected Profile' so that it is less often breaked into two lines,
which is not nice for a setting options
(/me wanted to add that to https://github.com/deltachat/deltachat-desktop/pull/3960 , but it was already merged :)
=> consolidate 'Profile' wording

CHANGELOG.md, src/renderer/stores/settings.ts
The toggle would show `false` after every UI reload event though the actual value is `true` ("1")
For reference, `disable_idle` was added correctly in 147d95624110a
=> fix: `webxdc_realtime` toggle incorrect value

CHANGELOG.md, src/renderer/components/chat/ChatList.tsx, src/renderer/components/contact/ContactList.tsx, src/renderer/components/dialogs/AddMember/AddMemberDialog.tsx, src/renderer/components/dialogs/AddMember/AddMemberInnerDialog.tsx, src/renderer/components/dialogs/CreateChat/index.tsx, src/renderer/components/dialogs/SelectContact/index.tsx
It's easier to review the changes commit-by-commit (also I'd prefer "rebase and merge" instead of "squash"). Also, for the last commit, GitHub is not good at showing whitespace-only changes, which it mostly is.
I did a bit of QA (but maybe not enough), and looked at the code. It doesn't look like anything should break.
TODO:
=> Lazy-load contacts

CHANGELOG.md, docs/KEYBINDINGS.md, src/renderer/components/KeyboardShortcutHint.tsx, src/renderer/keybindings.ts
`Ctrl + PageDown`, `Ctrl + PageUp`,
`Ctrl + Tab`, `Ctrl + Shift + Tab`
These are used by Telegram: https://github.com/telegramdesktop/tdesktop/wiki/Keyboard-Shortcuts
Related MR: https://github.com/deltachat/deltachat-desktop/pull/3965
I tested it a bit. Appears to work, and not break existing "PageUp" shortcut. ~~Those on Mac, please verify that these shortcuts are alright.~~ see [comment about Mac below](https://github.com/deltachat/deltachat-desktop/pull/3984#issuecomment-2196586587)
=> feat: more shortcuts to switch between chats

CHANGELOG.md, src/renderer/stores/settings.ts
=> refactor: safer types

CHANGELOG.md, src/renderer/components/chat/ChatList.tsx, src/renderer/components/dialogs/AddMember/AddMemberInnerDialog.tsx, src/renderer/components/dialogs/CreateChat/index.tsx, src/renderer/components/dialogs/SelectContact/index.tsx
See commits
Please verify that the old skeleton issues didn't come back after the removal of those `useEffect`s.
fixes #3921
fixes #3208
=> fix: more `<InfiniteLoader>` fixes

CHANGELOG.md, src/main/notifications.ts, src/renderer/backend-com.ts, src/renderer/components/AccountListSidebar/AccountItem.tsx, src/renderer/components/chat/ChatListItem.tsx
=> Ignore notification close event & clear notifications when marking accounts unread chat as noticed

CHANGELOG.md, src/renderer/components/dialogs/MailtoDialog/index.tsx, src/renderer/components/dialogs/SelectContact/index.tsx, src/renderer/components/dialogs/WebxdcSendToChat/index.tsx
in some contact/chat-select dialogs,
the call to 'enter sth' is misleading as not needed. it is just a 'search' and should be named as such.
the shorter text also unclutters UI and
fits to the approach to tune down 'email wording'.
=> clarify that the 'search field' is a 'search field'

CHANGELOG.md, src/renderer/components/Settings/ManageKeys.tsx
we're not using three dots in buttons at most other places, in general it is not that usual (more in menus).
also, adding dots this would become an translation issue.
just do not add the three dots.
=> consistent button wording

CHANGELOG.md, src/renderer/components/AccountListSidebar/AccountItem.tsx
- **fix update unread badge on when muting / unmuting a chat**
- **fix update unread badge on receiving device messages: update unread count also on `ChatlistChanged`, because `IncomingMsg` does not notify on new device messages**
closes #4013
=> fix two account sidebar unread update bugs

CHANGELOG.md, src/renderer/components/RuntimeAdapter.tsx
resolves #3983
The error came from the wrong accountId in selectChat which still had the state from the time it was set via runtime.setNotificationCallback
This change also avoids the loading of (the possibly wrong) lastChat, which is triggered by switching account, but might be superfluous if the chat from notification is not the lastChat
=> Preset lastChatId before switching accounts

CHANGELOG.md, src/main/deltachat/webxdc.ts
This doesn't appear to fix an exploitable vulnerability because `host-rules` is already set to disable network access, so "XDC-01-002 WP1" from the Cure53 audit has not been brought back ever since the initial fix.
Initially fixed in a9e5242acb
Reintroduced in fd1f8ce27b6e6
Related refactor commit 2cd310ec08f8f
Also bring back and improve the PDF comment about "XDC-01-005 WP1"
=> fix: webxdc: CSP bypass

CHANGELOG.md, scss/_global.scss, scss/composer/_composer.scss, scss/manifest.scss, scss/overwrites/_bp4-overwrites.scss, src/renderer/components/AccountListSidebar/styles.module.scss, src/renderer/components/ImageSelector/styles.module.scss, src/renderer/components/QrReader/styles.module.scss, src/renderer/components/composer/Composer.tsx, static/main.html, static/test.html
See commit messages
I tested it. Appears to be working good, but some rarely used elements might get ugly even for mouse-only navigation.
This by no means makes DC fully keyboard-accessible, but it's an improvement.
=> fix: a11y: keyboard navigation: add outline and focusability

CHANGELOG.md, src/renderer/components/dialogs/ForwardMessage/index.tsx
=> Select chat after forwarding

CHANGELOG.md, src/renderer/components/chat/ChatList.tsx, src/renderer/components/helpers/PseudoListItem.tsx
Adds a pseudo item similar to "add contact" when you type an email
The "standard" way of pasting the invite link under the gear button
on the second tab of the "scan QR" dialog is not very straigtforward.
The first reflex is to paste it in the search field,
so let's handle this.
=> feat: paste invite link to search to add contact

src/renderer/components/dialogs/AddMember/AddMemberDialog.tsx, src/renderer/hooks/useProcessQr.ts, src/renderer/hooks/useSecureJoin.ts
Only showing the mail address can be confusing, since often people don't know the Maildress only the displayname
=> Show displayname in ask start chat with

scss/_global.scss, scss/composer/_composer.scss, src/renderer/components/composer/Composer.tsx, src/renderer/components/message/VCard.tsx, src/renderer/components/message/styles.module.scss
=> WIP: Add new draft styles

CHANGELOG.md, src/renderer/stockStrings.ts
this PR removes setting the 'read receipt' stock string.
see https://github.com/deltachat/deltachat-android/issues/3179 and  https://github.com/deltachat/deltachat-core-rust/pull/5802 for reasoning.
=> 'read receipt' string is no longer needed

scss/chat/_chat-list-item.scss, scss/dialogs/_audit_log.scss, scss/dialogs/_qr-import.scss, scss/gallery/_attachment-view.scss, scss/gallery/_media-attachment.scss, scss/misc/_context_menu.scss, src/renderer/components/QrReader/styles.module.scss, src/renderer/components/message/styles.module.scss, src/renderer/components/screens/WelcomeScreen/OnboardingScreen.tsx, themes/dev_rocket.scss
since v1.77.7 the behaviour of compiling css from nested rules changed: https://sass-lang.com/documentation/breaking-changes/mixed-decls/
To avoid warnings and keep the old structure of the compiled css all properties should occur before nested rules
Follow up of #4054
=> Fix order of css rules

CHANGELOG.md, src/renderer/ScreenController.tsx, src/renderer/deviceMessages.ts
=> show device message only once as unread

CHANGELOG.md, src/main/windows/html_email.ts
- don't disply HTML mail viewer context menu if it's empty
- hide unnecessary separators
- resolves #4053
=> Fix empty context menu in HTML viewer

CHANGELOG.md, src/renderer/components/chat/ChatListItem.tsx
https://github.com/deltachat/deltachat-core-rust/issues/5782
=> Fixes Icon preview of latest WebXDC displayed when summary is reaction event

CHANGELOG.md, scss/chat/_chat-list-item.scss, src/renderer/components/chat/ChatListItem.tsx, src/renderer/components/message/MessageMarkdown.tsx
- add truncated-class to text preview in chat list
- removed excessive div from chat message preview
- resolves #4049
=> Truncate strings in chat list preview

scss/chat/_chat-list.scss
Apparently introduced by a dependency upgrade, prior to which `.chat-list` had `style="position: relative;"`.
This needs no CHANGELOG entry because no release has been made with this bug.
=> fix: "Create chat" floating button wrong position

CHANGELOG.md, src/renderer/components/dialogs/ViewProfile/index.tsx
given the right contact name length, e.g. "aaaaaaa@example.com"
Not the best solution, but appears to work for now.
Closes https://github.com/deltachat/deltachat-desktop/issues/3971
=> fix: "Contact info" contents jumping continuously

src/renderer/components/dialogs/EditAccountAndPasswordDialog.tsx
If user wants to skip configuration,
there is a "Cancel" button.
If user clicks "OK" accidenatlly, worst case
configuration fails and does not change anything.
Rerunning configuration may be useful
if autoconfig XML got new servers that work.
This will also enable "automatic reconfiguration"
for accounts that use providers not in provider database once core PR <https://github.com/deltachat/deltachat-core-rust/pull/5866> is merged.
On Android opening configuration dialog and clicking confirm button is already enough, but on Desktop it requires adding and removing a symbol in the address or similar change before clicking OK.
=> Always run configuration when user clicks "OK" in password dialog

CHANGELOG.md, src/renderer/components/ImageSelector/index.tsx, src/renderer/components/dialogs/CreateChat/index.tsx, src/shared/constants.ts
=> Allow webp in image selector

CHANGELOG.md, src/renderer/components/composer/Composer.tsx
- remove quote on Ctrl+Down when the currently quoted message is the last message
- don't quote a message on Ctrl+Down when no message is quoted instead only quote on Ctrl+Up
=> improvement: better Telegram-style Ctrl+Up/Down

CHANGELOG.md, src/renderer/components/chat/ChatListContextMenu.tsx, src/renderer/components/dialogs/CreateChat/index.tsx
- useCreateGroup returned function (CreateGroup) now accepts optional groupTemplateId same way Android/iOS version do, this is a group chat id to base new chat on
- resolves #3933
=> Add Clone Group functionality

CHANGELOG.md, src/renderer/components/ContactName/index.tsx, src/renderer/components/dialogs/ReactionsDialog/index.tsx, src/renderer/components/dialogs/ReactionsDialog/styles.module.scss, src/renderer/components/dialogs/ViewProfile/index.tsx, src/renderer/hooks/dialog/useOpenViewProfileDialog.ts
- don't show email in reactions dialog unless user has no display name
- clicking on a row in reactions dialog opens a user profile
- resolved #4066
=> ReactionsDialog: drop email, make rows clickable

CHANGELOG.md, scss/message/_message.scss
- remove margin and inline-block for text in WebXDC message as it seems unnessary since button in content has margins
- resolves #4079
=> Fix newlines in messages with WebXDC attachment

CHANGELOG.md, src/renderer/ScreenController.tsx
...imported from ArcaneChat, generated by a newer version of core.
Closes https://github.com/deltachat/deltachat-desktop/issues/4104.
I am not sure whether the rest of the discussion in #4104 was relevant to this issue, but I tested for a few minutes and didn't find a case where I can't delete the account or was unable to use the working accounts. Tried both with "Only Synchronize Selected Account" and without.
=> fix: unable to delete broken account

CHANGELOG.md, src/main/menu.ts, src/main/tray.ts, src/main/windows/main.ts
- handle ctrl+q when main window is focused to properly close the app
- File->Quit also closes the app
- #4084 tested on Windows, needs further testing
=> Ctrl+Q closes app

CHANGELOG.md, packages/frontend/src/components/dialogs/ReactionsDialog/styles.module.scss
Small CSS bugfix. Followup to #4066
Before:
After:
=> fix: spacing around avatars in reaction details dialog

CHANGELOG.md, packages/frontend/src/components/chat/ChatListItem.tsx
The `url()` wants a string, so let's give it a string. Otherwise it treats backwards slashes, which used in Windows paths, as escape characters, which results in an invalid URL.
The bug was introduced in 72bb581da4,
then there was a fix for something in 87ba793e66d.
Though it feels like there should be a proper way to convert file paths to URL...
I checked some other places where `url(` is used and didn't find a problem. Maybe it's best to unify such usage, and more thoroughly explain in JSON-RPC that those are file paths and not URLs.
=> fix: chatlist image thumbnails not showing on Win

CHANGELOG.md, packages/frontend/src/components/ContextMenu.tsx, packages/frontend/src/components/composer/Composer.tsx, packages/frontend/src/components/composer/ComposerMessageInput.tsx, packages/frontend/src/components/dialogs/AddMember/AddMemberInnerDialog.tsx, packages/frontend/src/components/dialogs/FullscreenMedia.tsx, packages/frontend/src/components/message/MessageListAndComposer.tsx, packages/frontend/src/keybindings.ts, packages/target-electron/src/deltachat/webxdc.ts, packages/target-electron/static/webxdc-preload.js
Different keyboard layouts (e.g. Russian).
`event.key` gives you the printed character and not the key code.
If the language doesn't use latin letters, you'll never get
Ctrl + N or Ctrl + K to work.
This behavior aligns with e.g. Telegram, and browsers (Ctrl + W).
There is a side-effect, however. The shortcuts cheat-sheet
shows which buttons you're currently pressing, and now it diverges
from actual behavior.
E.g. if you actually press the key with the code "Comma",
it won't show you this for the Russian language where the key
to print a comma is different.
See `KeyboardShortcutHint.tsx`.
I think this can be fixed later, especially that it's already buggy:
it won't show you that you're pressing "N" because
you'd actually need to press "Shift+N", otherwise you get "n".
=> fix: some shortcuts not working on different langs

CHANGELOG.md, packages/frontend/src/components/Reactions/styles.module.scss, packages/frontend/src/components/message/styles.module.scss
...resulting in new messages not getting scrolled into view when they arrive.
This simply removes height changes between messages with / without a reaction.
Closes https://github.com/deltachat/deltachat-desktop/issues/3753
=> fix: chat "scrolling up" upon reaction

CHANGELOG.md, packages/frontend/src/components/AccountListSidebar/AccountItem.tsx
...on initial render, and if needed when changing selection.
=> improvement: scroll selected account into view

CHANGELOG.md, packages/frontend/src/components/attachment/messageAttachment.tsx
=> Treat overriden sender name as content above attachment

CHANGELOG.md, packages/frontend/src/components/message/MessageList.tsx
...when typing a multi-line message, quoting a message, or adding an attachment, because that would cause the chat to "scroll up" due to its resize.
Closes https://github.com/deltachat/deltachat-desktop/issues/3763
I branched off of v1.46.8 FYI.
=> fix: new messages not getting scrolled into view

CHANGELOG.md, packages/frontend/src/components/message/MessageList.tsx, packages/frontend/src/stores/chat/chat_view_reducer.ts, packages/frontend/src/stores/messagelist.ts
It was very hard to work on https://github.com/deltachat/deltachat-desktop/issues/3763 and https://github.com/deltachat/deltachat-desktop/issues/3753 because of how much scrolling-related code we have, so I simplified it and added some comments before I forget.
=> refactor: add more comments about scrolling, simplify the code

CHANGELOG.md, packages/frontend/src/components/chat/ChatListItem.tsx, packages/frontend/src/components/message/MessageList.tsx, packages/frontend/src/stores/messagelist.ts
Recommended review (and merge) method: commit-by-commit.
I've tested the changes. Encoutered a few bugs with `jumpToMessage` not working, but fixed them.
=> perf: improve message list performance

CHANGELOG.md, packages/frontend/src/components/composer/Composer.tsx
- Erasing draft text and immediately focusing another element would return the focus to the composer after 500ms, when the draft gets deleted (`clearDraft` would get invoked from `saveDraft()`.
- Composer would not get re-focused when deleting / adding attachments or removing quotation if the draft text is not empty.
`.focus()` inside of `clearDraft()` was introduced in 199ea232539e77ea9b4c903451b90a56dc880554, most likely to re-focus the input after sending a message. We now have separate code for this, see `composerSendMessage`.
This change likely needs some more testing.
=> fix: inconsistent & wrong `composer.focus()`

packages/frontend/src/components/message/MessageList.tsx
The bug was introduced recently, in https://github.com/deltachat/deltachat-desktop/commit/07cd2b2c5f9d779cb71bb8c034b31b503b348806.
That commit assumed that we do not have multiple elements
with the same id in the document.
No need for a CHANGELOG entry because there has not been a release.
=> fix: not auto-scrolling to new messages

CHANGELOG.md, packages/frontend/src/components/message/MessageList.tsx
So that it's harder to bump the top / the bottom while scrolling
really fast, and lose momentum.
TODO:
=> improvement: increase "load more messages" margin

packages/frontend/src/components/chat/ChatListHelpers.tsx
Since these parameters are only used as `initialState` arguments for `useState`, it makes sense to name them as such. The API of `useChatList` is similar to that of `useState`.
=> refactor: rename vars

packages/frontend/scss/composer/_composer.scss
When quoting a message.
In the default dark theme was way too bright.
Before:
After:
=> style: lower contrast for a border in dark theme

CHANGELOG.md, packages/frontend/src/components/chat/ChatList.tsx, packages/frontend/src/components/chat/ChatListHelpers.tsx
This has the following effects:
- Upon the initial load of a component that displays a list of chats,
we start loading them instantly instead of waiting for the
debounce timeout of 200ms.
- When emptying the query string for a chat list, all chats get
displayed instantly, instead of getting re-fetched.
The following components are affected:
- The chat list on the main screen
- "Forward message to..."
- Mailto dialog
- View profile: chats in common
- webxdc sendToChat dialog
Please assess whether this is too ugly. Basically what we're doing is caching + removing the debounce. Perhaps a different approach would be more elegant. But IMO this isn't so bad, maybe not even half bad.
=> perf: cache chat list & don't delay initial load

.npmrc, docs/DEVELOPMENT.md, packages/target-electron/build/gen-electron-builder-config.js
- there is a new step before running `pnpm run pack`: `pnpm pack:patch-node-modules` (I added that to the documentation
- and there was the window path length limit that I ran into, added a note about it in docs and set a configuration variable to limit path length generated by pnpm internally to make the issue less likely.
=> fix packaging on windows (documentation and file path limit)

CHANGELOG.md, packages/frontend/src/stores/messagelist.ts
Closes https://github.com/deltachat/deltachat-desktop/issues/4186. The bug was introduced in fecdbbe3676521dea0f7aee58b9beaef0c7fff4f, https://github.com/deltachat/deltachat-desktop/pull/4145
=> fix: not scrolling to bottom on sending message

CHANGELOG.md, packages/frontend/src/components/Dialog/HeaderButton.tsx, packages/frontend/src/components/chat/ChatListContextMenu.tsx, packages/frontend/src/components/dialogs/EncryptionInfo.tsx, packages/frontend/src/components/dialogs/ViewProfile/index.tsx, packages/frontend/src/components/dialogs/ViewProfile/menu.tsx, packages/frontend/src/hooks/chat/useChatDialog.ts
- new `useViewProfileMenu` menu with two items: Block/Unblock Contact and Encryption Info
- minor refactor of `useChatDialog`, so we don't have to have a ChatListItem to block contact or get EncryptionInfo
- resolves #4043
=> Add block contact and encryption info to profile

.github/workflows/build-preview.yml, bin/github-actions/postLinksToDetails.js
When an upload to our server fails.
Currently upload keeps failing for Mac and Windows for all MRs.
But we still upload to GitHub artifacts in such a case,
so let's not miss out on it and still show the download link.
TODO:
=> chore: ci: fix preview download link missing

CHANGELOG.md, _locales/_untranslated_en.json, packages/frontend/src/components/helpers/PseudoListItem.tsx
Before:
After:
Partially addresses https://github.com/deltachat/deltachat-desktop/issues/4158. What's left I guess is adding this to the "plus button" dialog.
=> improvement: better search for invite link

CHANGELOG.md, packages/frontend/src/ScreenController.tsx, packages/frontend/src/components/AccountListSidebar/AccountItem.tsx, packages/frontend/src/stores/settings.ts
- combine all settings-gathering when changing account since some functions await for SelectAccount
- give additional 50ms to switching to Gallery since there's a conflict of setState and async media query in Gallery.tsx
- resolves #4190
- resolves #4191
=> Fix Settings/AllMedia in Account List context menu

packages/frontend/src/components/message/MessageList.tsx
The bug was introduced in 07cd2b2c5f9d779cb71bb8c034b31b503b348806.
=> fix: `jumpToMessage` not highlighting messages

CHANGELOG.md, packages/target-electron/build/gen-electron-builder-config.js
=> fix: packaging: include architecture in filename for all appimages

CHANGELOG.md, packages/frontend/src/components/composer/Composer.tsx, packages/frontend/src/components/message/MessageList.tsx
I.e. when we highlight a new message as a result of `jumpToMessage`,
remove the animation on the previously highlighted message
(or messages).
This is particularly useful for the Ctrl + Up shortcut
which is to choose the message to reply to.
Just FYI the added code usually takes 0.1-0.5ms to execute.
=> style: cancel old message highlight animations

CHANGELOG.md, _locales/_untranslated_en.json, packages/frontend/src/components/AccountListSidebar/AccountItem.tsx, packages/frontend/src/components/AccountListSidebar/AccountListSidebar.tsx, packages/frontend/src/components/AccountListSidebar/styles.module.scss, packages/frontend/src/components/Dialog/BackButton.tsx, packages/frontend/src/components/Dialog/CloseButton.tsx, packages/frontend/src/components/Dialog/HeaderButton.tsx, packages/frontend/src/components/ImageSelector/index.tsx, packages/frontend/src/components/KeyboardShortcutHint.tsx, packages/frontend/src/components/QrReader/index.tsx, packages/frontend/src/components/ReactionsBar/ReactionsBar.tsx, packages/frontend/src/components/SearchInput/index.tsx, packages/frontend/src/components/ShortcutMenu/index.tsx, packages/frontend/src/components/composer/Composer.tsx, packages/frontend/src/components/composer/ComposerMessageInput.tsx, packages/frontend/src/components/composer/menuAttachment.tsx, packages/frontend/src/keybindings.ts
I plan on working on accessibility (a11y) more, but generally this can be merged at any point.
Recommended review commit by commit.
=> improvement: improve a11y

CHANGELOG.md, packages/frontend/src/components/Navbar/styles.module.scss
The issue was introduced in 0e0d0b80d598802.
It has to do with these lines having been removed:
https://github.com/deltachat/deltachat-desktop/blob/a5c02433976909fe01a64f3049c96d0d101ae9d8/packages/frontend/scss/main_screen/_main_screen.scss#L16-L19
Before:
https://github.com/user-attachments/assets/18b1cbaa-cbff-4fc7-af96-a296bb222b28
After:
https://github.com/user-attachments/assets/e593afff-fe89-4ef1-858b-4af983a4ac82
=> fix: weird navbar widths on smaller screens

packages/frontend/src/components/composer/Composer.tsx
The bug was introduced in 23a0791dbe582105f53fd05d7e6b48bf6b2d2a58.
For left shift the `code` value is actually `ShiftLeft`.
I re-checked all other changes related that commit made,
and they appear to be alright.
The bug has not been released yet.
=> fix: emoji picker: Shift + click not working

CHANGELOG.md, packages/frontend/src/components/AccountListSidebar/AccountItem.tsx
=> show "Mark All As Read" in account menu unconditionally and move it down, right over settings menu item

packages/frontend/scss/message/_message-detail.scss
`delete-button-container` was removed in ec6f12e4bd751.
`message-content` was removed in a9313d00c892.
`message-container` was removed in 75b2c1b4830dc.
=> refactor: remove unused SCSS

packages/frontend/scss/gallery/_media.scss
Make the tabs list scrollable instead of expanding
the entire gallery view
=> fix: don't overflow gallery tabs on narrow screen

packages/frontend/src/components/Avatar/index.tsx, packages/frontend/src/components/Button/index.tsx, packages/frontend/src/components/Dialog/FooterActionButton.tsx, packages/frontend/src/components/LoginForm.tsx, packages/frontend/src/components/composer/EmojiAndStickerPicker.tsx, packages/frontend/src/components/dialogs/ConfirmationDialog.tsx, packages/frontend/src/components/dialogs/ViewProfile/index.tsx, packages/frontend/src/components/message/Message.tsx, packages/frontend/src/components/screens/AccountDeletionScreen/AccountDeletionScreen.tsx, packages/frontend/src/components/screens/WelcomeScreen/AlternativeSetupsDialog.tsx, packages/frontend/src/components/screens/WelcomeScreen/InstantOnboardingScreen.tsx, packages/frontend/src/components/screens/WelcomeScreen/OnboardingScreen.tsx, packages/frontend/src/components/screens/WelcomeScreen/UseOtherServerDialog.tsx
- make Button and some other components accept HTMLButton props
- rename Button.props.type to styling so we don't conflict with <button type="">
=> Buttons accept HTMLButton props

CHANGELOG.md, packages/frontend/src/components/chat/ChatListItem.tsx
This bug was brought back again in 65bd380986eafc8adb10814b0aea6f18167c3478.
After the recent fix in 78e188cd0e9f009e9f3805b360042972bccd8f63.
=> fix: image thumbnails not showing in chat list

CHANGELOG.md, packages/frontend/scss/login/_login.scss, packages/frontend/src/components/Login-Styles.tsx
The bug was introduced in 0e0d0b80d598802ebb972c8d6c05b593bd896f24.
Blueprint uses a range of [0, 1] and not [0, 100]:
https://blueprintjs.com/docs/#core/components/progress-bar.
=> fix: progress bar not working

CHANGELOG.md, packages/frontend/scss/chat/_chat-list-item.scss, packages/frontend/scss/contact/_contact.scss
The bug was likely introduced in 0e0d0b80d598802ebb972c8d6c05b593bd896f24,
where scrollbars got wider on Windows.
So if a contact has a long email or name, it would overflow
the chat list in "search" mode.
Before:
After:
I have tried to test this thoroughly, with the "verified" check-marks, and with the "last message at" text. Looks alright.
The new approach makes the widths less hard-coded and lets the browser handle widths.
=> style: avoid horizontal scrollbars in chat list

CHANGELOG.md, packages/frontend/src/components/AccountListSidebar/styles.module.scss
Follow-up to 46d98111b69764b278f15c3dfe300e794dd64dcc
and c71fafa6235dfc3036db5b7be434dae0fff6961d.
Before and after:
=> style: add `scroll-margin` for account list items

packages/frontend/src/components/message/Message.tsx
The correct way would be
`onClick={() => openWebxdc(message.parentId!)}`, but, as discussed in
https://github.com/deltachat/deltachat-desktop/pull/4265,
we don't want this behavior
=> refactor: remove dead code

CHANGELOG.md, packages/frontend/scss/login/_login.scss, packages/frontend/src/components/Login-Styles.tsx, packages/frontend/src/components/screens/WelcomeScreen/ImportBackupProgressDialog.tsx, packages/frontend/themes/_themebase.scss
because the browser native element is too limited.
I added the aria role and attributes, so acessibility should work in theory.
(/me wasted way too much time trying to understand how to style the native element.)
fixes #4263
preview:
| dark | light |
|--------|--------|
| ![Bildschirmfoto 2024-10-26 um 21 24 50](https://github.com/user-attachments/assets/9ed59681-b741-4bba-93f6-116f361caa2a) | ![Bildschirmfoto 2024-10-26 um 21 23 27](https://github.com/user-attachments/assets/6b146313-a94b-4452-b40c-553238d2a3b2) |
=> go back to a custom progressbar implementation

CHANGELOG.md, packages/target-electron/build/gen-electron-builder-config.js
=> add missing `libasound2` to debian package dependencies

CHANGELOG.md, packages/frontend/src/components/attachment/mediaAttachment.tsx
The bug exists since at least e2f9cdb915d59ac7d718de5eb60ecf779d8289a6.
=> fix: deleting broken video not working

packages/frontend/tsconfig.json, packages/shared/localize.ts, packages/shared/translationKeyType.d.ts, packages/shared/tsconfig.json, packages/target-browser/tsconfig.json, packages/target-electron/src/load-translations.ts
Just for autocompletion not checking, for checking we have 2 ways:
- ./bin/test_for_missing_translations.sh
- the runtime errors
we can think about using it also for checking in the future. But currently I'd to say no.
=> add autocompletion for translation keys

CHANGELOG.md, packages/frontend/src/components/RuntimeAdapter.tsx, packages/frontend/src/components/attachment/mediaAttachment.tsx, packages/frontend/src/components/chat/ChatListItemRow.tsx, packages/frontend/src/components/composer/Composer.tsx, packages/frontend/src/components/composer/EmojiAndStickerPicker.tsx, packages/frontend/src/components/dialogs/ChatAuditLogDialog.tsx, packages/frontend/src/components/dialogs/ForwardMessage/index.tsx, packages/frontend/src/components/dialogs/FullscreenMedia.tsx, packages/frontend/src/components/message/Message.tsx, packages/frontend/src/components/message/MessageList.tsx, packages/frontend/src/contexts/ChatContext.tsx, packages/frontend/src/global.d.ts, packages/frontend/src/hooks/chat/useMessage.ts, packages/frontend/src/hooks/useVideoChat.ts, packages/frontend/src/stores/chat/chat_view_reducer.ts, packages/frontend/src/stores/messagelist.ts
Add `scrollIntoViewArg` parameter to `jumpToMessage`
and specify different values for it depending on context.
More specifically, prefer scrolling the target message
to the center, e.g. when showing the first unread message.
Prior to this commit, we'd scroll the first unread message
such that it's at the bottom of the message list,
which can be considered a regression, which was introduced in
https://github.com/deltachat/deltachat-desktop/commit/5f0efe169a56113f25d6aee48fab045956c83a00.
Closes https://github.com/deltachat/deltachat-desktop/issues/4284.
I recommend reviewing commit by commit.
TODO:
=> improvement: better scroll for jumpToMessage

CHANGELOG.md, packages/frontend/src/components/ContextMenu.tsx, packages/frontend/src/components/QrReader/index.tsx, packages/frontend/src/components/Settings/Appearance.tsx, packages/frontend/src/components/ThreeDotMenu.tsx, packages/frontend/src/components/chat/ChatListContextMenu.tsx, packages/frontend/src/components/composer/menuAttachment.tsx, packages/frontend/src/components/dialogs/ChatAuditLogDialog.tsx, packages/frontend/src/components/dialogs/ViewProfile/menu.tsx, packages/frontend/src/components/message/Message.tsx, packages/frontend/src/utils/mouseEventToPosition.ts
...when activating them with keyboard (or via other means?).
Closes https://github.com/deltachat/deltachat-desktop/issues/4244.
Some of the affected places:
- Three-dot button besides a message.
- Reactions bar when activated from the message context menu.
- "More options" in the QR reader dialog.
- "Appearance" settings color picker
(it is not yet keyboard-accessible though).
=> fix: a11y: wrong positioning of context menus

CHANGELOG.md, packages/frontend/src/components/Avatar/styles.module.scss, packages/frontend/src/components/ProfileInfoHeader/styles.module.scss
Manifests itself when focusing and hovering it.
=> style: fix avatar in profile being oval-shaped

CHANGELOG.md, packages/frontend/src/components/Settings/Appearance.tsx, packages/runtime/runtime.ts, packages/shared/themes.ts, packages/target-browser/runtime-browser/runtime.ts, packages/target-browser/src/index.ts, packages/target-browser/src/themes.ts, packages/target-electron/runtime-electron/runtime.ts, packages/target-electron/src/themes.ts
- **remove unused `runtime.resolveThemeAddress`.**
- **sort event callback functions by whether we can implement them**
- **make themes work in browser edition**
I intentionally left out `--theme-watch` for now. It is semi-hard to implement here and there is not much advantage to developing a theme with the electron version.
=> add theme support in browser edition

CHANGELOG.md, packages/frontend/src/components/Radio.tsx, packages/frontend/src/components/Settings/Appearance.tsx, packages/frontend/src/components/Settings/Autodelete.tsx, packages/frontend/src/components/Settings/Communication.tsx, packages/frontend/src/components/Settings/DownloadOnDemand.tsx, packages/frontend/src/components/Settings/OutgoingMediaQuality.tsx, packages/frontend/src/components/SmallSelectDialog.tsx, packages/frontend/src/components/dialogs/MuteChat.tsx
The bug was introduced in https://github.com/deltachat/deltachat-desktop/commit/0e0d0b80d598802ebb972c8d6c05b593bd896f24,
where we switched from the Blueprint's `RadioGroup` to our
custom `RadioGroup`, which had the bug where it would not
reflect the actual value if it was changed programmatically.
This commit fixes that bug.
The bug in `Radio` existed ever since its introduction.
The reason for using `defaultChecked` instead of `checked`
probably was the fact that React would complain that
"input doesn't have `onChange` listener set,
use `defaultChecked` instead".
I have ligtly checked that "disappearing messages"
is the only affected place.
=> fix: "disappearing messages" dialog wrong value

RELEASE.md
This reverts https://github.com/deltachat/deltachat-desktop/pull/4251 ; `releases.md` does no longer exist, see https://github.com/deltachat/deltachat-pages/pull/994
=> Revert "add task to realease doc to document appstore releases centrally on pages repo

CHANGELOG.md, packages/frontend/src/components/chat/ChatListItemRow.tsx
Follow-up to d085f8a6299817bd6b39603e7c2f1379760a18bc.
`.chatId` was added just recently in core. See https://github.com/deltachat/deltachat-core-rust/pull/6120.
=> perf: faster `jumpToMessage` in search

CHANGELOG.md, _locales/_untranslated_en.json, docs/KEYBINDINGS.md, packages/frontend/src/components/KeyboardShortcutHint.tsx, packages/frontend/src/components/Settings/ExperimentalFeatures.tsx, packages/frontend/src/components/composer/Composer.tsx, packages/shared/shared-types.d.ts, packages/shared/state.ts
The feature was introduced in cd80587ed79bb1a0723dc7c36002e88818cdfcb4.
With several performance improvements to `jumpToMessage`,
the fix to https://github.com/deltachat/deltachat-core-rust/issues/6036,
and some testing, it's time to release it.
=> improvement: un-experimental Ctrl+Up to reply

CHANGELOG.md, packages/frontend/src/components/dialogs/DisappearingMessages.tsx
The button layout is now the same with Android.
=> improvement: "Learn More" to disappearing msgs

_locales/_untranslated_en.json, packages/e2e-tests/tests/basic-functionality.spec.ts, packages/frontend/src/components/QrReader/helper.ts, packages/frontend/src/components/QrReader/index.tsx, packages/frontend/src/components/dialogs/QrCode.tsx, packages/frontend/src/components/dialogs/QrCodeScanner.tsx, packages/frontend/src/components/dialogs/SetupMultiDevice/ReceiveBackupDialog.tsx
resolves #3936
move "paste from clipboard" from settings context menu to own button
Another option would be: name the paste button "Import" and show the context menu onClick with the 2 options: 'load QR Code image' or 'paste from clipboard'
But buttons that show a context menu on click are a bit unusual
=> Show paste button in qr scanner dialog

CHANGELOG.md, packages/frontend/src/components/message/MessageList.tsx
https://github.com/user-attachments/assets/90f3a24d-80f8-4876-ae6c-3931120aa647
TODO:
for it to be critical. I have seen it happen a few times.
Maybe for 1 out of 100 messages.
Ok, I have an idea. Let's merge it, and if it's not good yet, then put it behind the setting.
=> improvement: scroll to new messages smoothly

CHANGELOG.md, packages/frontend/src/components/chat/ChatList.tsx, packages/frontend/src/components/chat/ChatListItem.tsx, packages/frontend/src/contexts/RovingTabindex.tsx
https://github.com/user-attachments/assets/b43fb2c6-4c04-4080-ba15-7e644114c8d1
Implements the "roving tabindex" approach:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/Keyboard-navigable_JavaScript_widgets#technique_1_roving_tabindex.
Supersedes https://github.com/deltachat/deltachat-desktop/pull/4211.
This improves things, but the UX as a whole is not great yet:
- The tab order is such that the chat list does not
immediately follow the search field,
so you have to tab through the other navbar items
before you get to the chat list.
Same for going back from the chat list to the search bar.
This can be addressed by #4225
- The initially "active" element is just the first chat item,
and not the currently selected chat.
I can fix it, in a separate MR. I left a TODO.
- Since the …
=> improvement: arrow-key navigation for chat list

CHANGELOG.md, packages/frontend/src/components/Settings/Backup.tsx, packages/frontend/src/components/Settings/ManageKeys.tsx, packages/frontend/src/components/dialogs/AlertDialog.tsx, packages/target-browser/src/deltachat-rpc.ts, packages/target-browser/src/index.ts
- alert dialog: add option to set alternative ok button label
- make backup export work in browser, import already worked
- browser: add ability to export secret key
TODO:
=> browser edition: add backup and key export

.github/mergeable.yml
I forgot to update it while the monorepo conversion.
this should ignore changes to e2e tests, as IMO they don't need to always have a changelog entry - but we can debate that
=> fix mergeable.yml

packages/frontend/scss/gallery/_attachment-view.scss
@WofWca brought this up in private conversation. There's a limit to video width of 95vw but at the same time it's not centered. That was introduced 5 years ago, maybe to cover up for left-right navigation buttons, but they're wider than 5vw together. I tried to remove that and it seems to work fine in all scenarios.
As a further work we might want to handle video player events and hide arrows while video is playing, bringing them back on pause or video ending. I have no idea if video API is solid for this to be a straightforward implementation though.
=> Drop 95vw limitation of video in FullscreenMedia

CHANGELOG.md, packages/frontend/src/components/contact/ContactListItem.tsx, packages/frontend/src/contexts/RovingTabindex.tsx
The "contacts" section items were not included
in the roving tabindex winget: they all had individual tab stops,
which is very confusing.
Before:
https://github.com/user-attachments/assets/05f11ce0-c7a2-44c0-b698-557f9b624e1c
After (it is not clear, but I have to press Tab to get to the "Contacts" section):
https://github.com/user-attachments/assets/60cef514-5fb4-433a-8043-adc8e720fc6e
=> fix: arrow-key navigation behavior in search

CHANGELOG.md, packages/target-electron/src/application-constants.ts, packages/target-electron/src/windows/helpers.ts
...with high zoom level.
Closes https://github.com/deltachat/deltachat-desktop/issues/4063
I did not test this because for me `setMinimumSize` is not working. Though I played around with window sizes to determine the new numbers.
=> fix: window overflowing small screens

packages/frontend/src/components/contact/ContactList.tsx, packages/frontend/src/components/dialogs/AddMember/AddMemberInnerDialog.tsx
We already had similar fixes in the past.
I have looked through the code and have found no more of such calls.
Without this we get an error in the console after pressing "OK"
in the "Add Members" dialog in "Create Group":
`Warning: React has detected a change in the order of Hooks called by ContactList`.
=> fix: potential crash due to `Component({ ...props`

CHANGELOG.md, packages/frontend/scss/chat/_chat-list.scss
Before:
After:
Reported by @adbenitez
=> style: "Search in ..." divider overflow

packages/frontend/scss/main_screen/_navbar_wrapper.scss
it's more reliably to mark buttons and inout fields as no drag manually.
fixes #4370
changelog entry is not needed because bug was not released yet.
=> [fix for regression] remove button and input again from no-drag

CHANGELOG.md, packages/frontend/src/components/dialogs/AddMember/AddMemberInnerDialog.tsx, packages/frontend/src/components/dialogs/CreateChat/index.tsx, packages/frontend/src/components/dialogs/ForwardMessage/index.tsx, packages/frontend/src/components/dialogs/MailtoDialog/index.tsx, packages/frontend/src/components/dialogs/ReactionsDialog/index.tsx, packages/frontend/src/components/dialogs/SelectContact/index.tsx, packages/frontend/src/components/dialogs/UnblockContacts.tsx, packages/frontend/src/components/dialogs/ViewGroup.tsx, packages/frontend/src/components/dialogs/ViewProfile/index.tsx, packages/frontend/src/components/dialogs/WebxdcSendToChat/index.tsx
I have shallowly tested all the places where added it.
This completes arrow-key navigation for all the chat lists and contact lists, unless I missed something.
Follow up to #4224, #4291, #4361, #4362.
For easier review, hide white-space changes.  
This MR includes one small refactor commit, otherwise it's just boilerplate.
And about boilerplate: please tell me whether in general this looks like a good way to write this, or if this feels wrong and unmaintainable.
=> improvement: add arrow-key nav everywhere

packages/frontend/src/components/attachment/mediaAttachment.tsx, packages/frontend/src/components/message/Message.tsx, packages/frontend/src/components/message/messageFunctions.ts, packages/frontend/src/system-integration/webxdc.ts, packages/shared/shared-types.d.ts, packages/target-electron/src/deltachat/webxdc.ts, packages/target-electron/static/webxdc-preload.js
resolves (partly) to #4366 
Main changes: 
- openWebxdc in frontend expects a message as first argument instead a messageId
- selfAddr in webxdcInfo holds not the users address anymore
- WebxdcInfo message has a new optional property webxdc_href
- click on WebxdcInfo message directly opens the map and sets a event related location.url in iFrame (optional)
=> New webxdc api

CHANGELOG.md, packages/frontend/scss/gallery/_attachment-view.scss, packages/frontend/src/components/dialogs/FullscreenMedia.tsx
- **fix drag area problem in fullscreen media view**
- **fix: remove visible scrollbars in fullscreen media view**
closes #4368 (I know we could do even better, but this invisible drag area where the navbar would be already fixes the bug in my eyes)
The scrollbar problem: (those scrollbars are just a visual bug, they don't really do anything as far as I understood it)
The drag area:
| before| after|
|-------|-----|
|<img width="1151" alt="Bildschirmfoto 2024-12-04 um 15 51 01" src="https://github.com/user-attachments/assets/bb62e074-3317-43ee-b3a8-2ac7aca3e1bd">|<img width="1151" alt="Bildschirmfoto 2024-12-04 um 15 51 42" src="https://github.com/user-attachments/assets/a0ae7660-feee-4445-b839-165556e72c47">|
=> fullscreen media view: improve drag behaviour and remove visible scrollbars

CHANGELOG.md, packages/frontend/src/ScreenController.tsx, packages/frontend/src/components/screens/WelcomeScreen/OnboardingScreen.tsx, packages/frontend/src/components/screens/WelcomeScreen/index.tsx
resolves #4365
Pressing escape key twice will close open dialogs in Chrome no matter how onCancel is configured https://issues.chromium.org/issues/346597066
To handle that we move the onClickBackButton function one component higher to add it as onClose prop to the Dialog and handle the event the same way a BackButton Click would be handled
TODO: check other dialogs how the behave on forced close (should go into a new Issue though)
=> Handle Chrome double escape behaviour

CHANGELOG.md, packages/frontend/src/components/message/Message.tsx
=> Check text exists before accessing it

CHANGELOG.md, packages/frontend/src/components/composer/Composer.tsx, packages/frontend/src/components/message/MessageListAndComposer.tsx
=> Avoid drafts in chats where canSend is false

CHANGELOG.md, packages/frontend/src/components/dialogs/FullscreenAvatar.tsx, packages/frontend/src/components/dialogs/FullscreenMedia.tsx
Closes https://github.com/deltachat/deltachat-desktop/issues/4320
=> fix: fullscreen images getting cropped a bit

CHANGELOG.md, packages/frontend/src/components/dialogs/ViewProfile/index.tsx, packages/frontend/src/components/screens/MainScreen.tsx
- **refactor: simplify `navbar-chat-subtitle`**
- **improvement: mark bots as such in UI**
Closes https://github.com/deltachat/deltachat-desktop/issues/4332.
Thanks @r10s for the detailed instructions in https://github.com/deltachat/deltachat-desktop/issues/4332!
Tested with a bot. Works.
=> improvement: mark bots as such in UI

CHANGELOG.md, packages/frontend/src/components/AccountListSidebar/AccountListSidebar.tsx, packages/frontend/src/components/AccountListSidebar/styles.module.scss
raiden suggested this change to me in a private message.
| Before | After |
|--------|------|
| <img width="147" alt="Bildschirmfoto 2024-12-12 um 21 51 37" src="https://github.com/user-attachments/assets/b287628a-de58-47b6-b482-57f948a5defa" /> |  <img width="147" alt="Bildschirmfoto 2024-12-12 um 21 51 09" src="https://github.com/user-attachments/assets/b9eeeb9c-898e-4ec1-aed5-190875754e79" /> |
also fix the bug that size of that area changed based on profile acount and window height
=> macOS: make area under traffic lights dragable and slightly larger

CHANGELOG.md, packages/frontend/scss/message/_message.scss
The background used to be transparent,
and the text color has been changed to white in e69fd47cfaa5aec38a6401fab01cd64f6b33d351,
but then we changed background color of the quote bubbles
to be the same as the message bubble color for regular messages
in f83ce46cbf80a4c019d3be02222b164a8d58fe56, so now
there is no need to override colors.
=> fix: unreadable quote text for sticker replies

CHANGELOG.md, package.json, packages/target-browser/package.json, packages/target-electron/package.json, packages/target-tauri/package.json
This release is only to address  https://github.com/deltachat/deltachat-core-rust/issues/6338 - it has a a new core with downgraded rust version to avoid wrong malware alerts on Windows
=> Release v1.50.1

packages/frontend/scss/message/_metadata.scss, packages/frontend/src/components/message/MessageMetaData.tsx
This is no longer used after 90f4047d2a77e16ad2f31bd5b53d803a37eaf583.
=> refactor: remove dead code (`MetaData.username`)

CHANGELOG.md, packages/frontend/scss/message/_message.scss
Before:
After:
For incoming messages the color is also respective:
Closes https://github.com/deltachat/deltachat-desktop/issues/4453.
The bug (if you can call it that) was introduced in f83ce46cbf80a4c019d3be02222b164a8d58fe56.
Similar commit: 8259aad97.
CI failures are to be fixed in https://github.com/deltachat/deltachat-desktop/pull/4426.
=> style: outgoing bg color for outgoing stickers

CHANGELOG.md, packages/frontend/scss/composer/_composer.scss, packages/frontend/scss/message/_message.scss, packages/frontend/scss/message/_status-icon.scss, packages/frontend/src/components/Reactions/index.tsx, packages/frontend/src/components/Reactions/styles.module.scss, packages/frontend/src/components/message/Message.tsx, packages/frontend/src/components/message/MessageMetaData.tsx
- **improvement: turn clickable items into <button>s**
- **improvement: turn clickable items into <button>s**
- **improvement: a11y: turn quote into <button>**
- **refactor: add comment about a11y**
- **improvement: turn autocrypt msg into <button>**
- **improvement: turn delivery status into <button>**
=> improvement: a11y: turn more elements into <button>s

CHANGELOG.md, packages/frontend/scss/message/_message-attachment.scss
Because of `max-width: 80%`, which refers to 80% of the wrapper
square, and not the chat section
(the later was apparently the intention).
This has been introduced in https://github.com/deltachat/deltachat-desktop/pull/4315,
which has later been sort of reverted, but not completely, in
https://github.com/deltachat/deltachat-desktop/pull/4407.
So, let's remove the residuals, especially that stickers also have
fixed `height: 200px`, so `max-height` doesn't make sense.
=> style: stickers being smaller than needed

CHANGELOG.md, packages/frontend/scss/message/_message.scss
This is based on #4432.
Before / after 
Apparently this `margin-bottom: -7px` is a residue
from copy pasting it from `.metadata` for regular text messages.
We have `marin: 0` set for image-only messages,
so we should set `margin: 0` for sticker messages as well.
=> style: fix reactions to stickers overlapping

CHANGELOG.md, packages/frontend/src/contexts/RovingTabindex.tsx
Choose "hide whitespace" for easier review.
=> improvement: a11y: roving tabindex: End / Home

CHANGELOG.md, packages/frontend/src/components/Gallery.tsx
Closes https://github.com/deltachat/deltachat-desktop/issues/4318.
=> fix: update gallery on message deleted

CHANGELOG.md, packages/frontend/scss/message/_message-attachment.scss, packages/frontend/scss/message/_message.scss
Visual aspect, before / after: 
This, together with https://github.com/deltachat/deltachat-desktop/pull/4407,
should close https://github.com/deltachat/deltachat-desktop/issues/4404.
The bug was introduced in https://github.com/deltachat/deltachat-desktop/pull/3999.
Pior to that we used to have fixed width on quoted images as well.
This commmit practically reverts that MR, but also adds
`object-fit` and `object-position`, and is now in line with
message attachment images
=> fix: chat "scrolling up" because of imgs loading

CHANGELOG.md, packages/frontend/src/components/message/Message.tsx
To make it easy again to reach/jump-to the webxdc message. Since the notification webxdc info messages open the app directly on click.
=> add show_app_in_chat option to webxdc info message context menu

CHANGELOG.md, packages/frontend/src/backend-com.ts, packages/runtime/runtime.ts, packages/shared/logger.ts, packages/target-browser/runtime-browser/runtime.ts, packages/target-electron/runtime-electron/runtime.ts
This was likely broken by me during refactoring when changing apis and initialisation to make the browser version possible.
The problem was that the comandline flags were checked before they were loaded.
Now the jsonrpc request are logged again in devmode. (write `-jsonrpc` in the filter to not be annoyed from it)
And you can now do `exp.printCallCounterResult()` again:
=> fix: devmode: fix logging and counting jsonrpc requests

CHANGELOG.md, packages/frontend/scss/composer/_emoji-sticker-picker.scss, packages/frontend/src/components/composer/EmojiAndStickerPicker.tsx
=> improvement: arrow-key nav in sticker picker

.gitignore
to make switching from and to tauri branch more convinient
=> update gitignore for tauri

CHANGELOG.md, packages/frontend/scss/message/_message-list.scss, packages/frontend/src/components/Avatar/index.tsx, packages/frontend/src/components/Reactions/index.tsx, packages/frontend/src/components/ShortcutMenu/index.tsx, packages/frontend/src/components/attachment/mediaAttachment.tsx, packages/frontend/src/components/attachment/messageAttachment.tsx, packages/frontend/src/components/chat/ChatListItem.tsx, packages/frontend/src/components/composer/Composer.tsx, packages/frontend/src/components/message/EmptyChatMessage.tsx, packages/frontend/src/components/message/Link.tsx, packages/frontend/src/components/message/Message.tsx, packages/frontend/src/components/message/MessageBody.tsx, packages/frontend/src/components/message/MessageList.tsx, packages/frontend/src/components/message/MessageMarkdown.tsx, packages/frontend/src/components/message/MessageMetaData.tsx
https://github.com/user-attachments/assets/76391400-a379-45ac-bc6b-940b7a864853
Closes https://github.com/deltachat/deltachat-desktop/issues/2141.
Together with other previously merged MRs, closes https://github.com/deltachat/deltachat-desktop/issues/4127.
Basically what this commit comes down to:
1. Apply `useRovingTabindex` for message items
2. Set `tabindex="-1"` on all the interactive items
inside every message that is currently not the active one,
so that they do no have tab stops.
TODO:
because initially they're all active, so
tabbing to the messages list from the top selects
the first rendered one as the active one.
https://github.com/deltachat/deltachat-desktop/pull/4292
could help with this.
And remember that the messages list is dynamic (a new message can arrive), so simply …
=> improvement: a11y: arrow-key navigation for messages

CHANGELOG.md, packages/frontend/src/components/Gallery.tsx, packages/frontend/src/components/chat/ChatList.tsx, packages/frontend/src/components/dialogs/AddMember/AddMemberInnerDialog.tsx, packages/frontend/src/components/dialogs/CreateChat/index.tsx, packages/frontend/src/components/dialogs/SelectChat/index.tsx, packages/frontend/src/components/dialogs/SelectContact/index.tsx, packages/frontend/src/components/dialogs/ViewGroup.tsx, packages/frontend/src/components/dialogs/ViewProfile/index.tsx
Reviewing commit-by-commit should be a bit easier. But basically what this does is it un-inlines the renderer functions, addressing this issue: https://github.com/bvaughn/react-window/issues/420#issuecomment-585813335.
You can check this behavior by arrow-key navigating the contact list in "new chat", as long as your contact list is at least ~30 items long. When new items get loaded (with 'react-infinite-loader'), the parent component re-renders, and all items' DOM get re-created, losing focus.
I am not 100% sure whether we should squash the commits. They're all quite similar, but it might not be easy to see separate logical changes when squashed.
=> fix: a11y: arrow-key navigation stopping working after ~10 keypresses

packages/frontend/src/components/Gallery.tsx
This is based on #4441.
This does not appear to have noticeable functional effect.
=> refactor: correctly use `itemKey` in gallery

CHANGELOG.md, packages/frontend/src/components/composer/ComposerMessageInput.tsx, packages/shared/util.ts
Commit-by-commit review should be easier, though anyway there are not many changes.
Closes https://github.com/deltachat/deltachat-desktop/issues/4430.
The bug was introduced in https://github.com/deltachat/deltachat-desktop/pull/4144.
There we made `throttle` accept the `text` argument
instead of reading `this.state.text`, and `this.state.text`
would get set to `''` after the message has been sent,
but then we'd still invoke the throttled function,
with the text from the last `onChange` event.
This probably doesn't address _all_ the "draft not cleared" issues,
e.g. https://github.com/deltachat/deltachat-desktop/issues/3586
could be a different issue.
This also fixes https://github.com/deltachat/deltachat-desktop/pull/4144#discussion_r1861963395.
=> fix: draft not clearing after sending message

CHANGELOG.md, packages/frontend/src/components/message/MessageList.tsx
...when the chatId of the message is different
from the currently open chat.
Closes https://github.com/deltachat/deltachat-desktop/issues/4508.
This is probably related to the React upgrade,
which changed the behaviour of `useEffect`.
The issue was that we called `window.__internal_jump_to_message`
_before_ `MessageListStore` has been reinstantiated,
so we'd call it on an old instance.
I think there might still be cases where this bug appears,
but at least this makes it appear less often.
=> fix: `jumpToMessage` not working sometimes

CHANGELOG.md, packages/frontend/src/hooks/chat/useMessage.ts, packages/frontend/src/stores/messagelist.ts
1. "Reply Privately" to a message in a group.
2. Click on the quote. This will open the original chat.
3. Click the "jump down" button.
This will load the messages from the private chat,
but still show the original group chat in the chat header.
=> fix: showing wrong chat ("Reply Privately" quote)

CHANGELOG.md, packages/frontend/scss/message/_message.scss
Closes https://github.com/deltachat/deltachat-desktop/issues/4404,
again.
See https://github.com/deltachat/deltachat-desktop/issues/4404#issuecomment-2602438175.
=> fix: chat "scrolling up" because of imgs, again

CHANGELOG.md, packages/frontend/src/stores/messagelist.ts
Closes https://github.com/deltachat/deltachat-desktop/issues/3763 (again).
See https://github.com/deltachat/deltachat-desktop/issues/3763#issuecomment-2602630507.
Previous supposed fix: https://github.com/deltachat/deltachat-desktop/pull/4119.
Apparently the bug came back after the recent React upgrade, which was introduced in 1.51.0, so the bug is a regression.
I was unable to reproduce the bug on the Windows preview build from this MR.
=> fix: chat scrolling up on quoting sometimes

CHANGELOG.md, packages/frontend/src/components/dialogs/SelectChat/styles.module.scss
Caused by \<AutoSizer\>.
Similar commit: c746a1cc309ac3c3e088899f28141de8ce69a0c8.
=> fix: scrollbar flickering in "Send to..." dialog

CHANGELOG.md, packages/frontend/src/components/AccountListSidebar/AccountItem.tsx, packages/frontend/src/components/message/MessageList.tsx, packages/frontend/src/system-integration/badge-counter.ts
We used to only update the count when calling
`BackendRemote.rpc.markseenMsgs()` or
`BackendRemote.rpc.marknoticedChat()`.
=> fix: update unread badge on read from other device

CHANGELOG.md, packages/frontend/src/components/ContextMenu.tsx, packages/frontend/src/components/composer/ComposerMessageInput.tsx, packages/frontend/src/components/dialogs/AddMember/AddMemberInnerDialog.tsx, packages/frontend/src/components/screens/AccountSetupScreen.tsx, packages/frontend/src/keybindings.ts
Closes https://github.com/deltachat/deltachat-desktop/issues/4543.
This partially reverts 9e7830f3d7793f9985cd774ec0f66a3a1f06f429
(https://github.com/deltachat/deltachat-desktop/pull/4140)
and
23a0791dbe582105f53fd05d7e6b48bf6b2d2a58
(https://github.com/deltachat/deltachat-desktop/pull/4140).
=> fix: treat numpad "Enter" as regular "Enter"

CHANGELOG.md, packages/frontend/src/components/RuntimeAdapter.tsx, packages/frontend/src/components/attachment/mediaAttachment.tsx, packages/frontend/src/components/chat/ChatListItemRow.tsx, packages/frontend/src/components/composer/Composer.tsx, packages/frontend/src/components/composer/EmojiAndStickerPicker.tsx, packages/frontend/src/components/dialogs/ChatAuditLogDialog.tsx, packages/frontend/src/components/dialogs/ForwardMessage/index.tsx, packages/frontend/src/components/dialogs/FullscreenMedia.tsx, packages/frontend/src/components/message/Message.tsx, packages/frontend/src/components/message/MessageList.tsx, packages/frontend/src/contexts/ChatContext.tsx, packages/frontend/src/global.d.ts, packages/frontend/src/hooks/chat/useMessage.ts, packages/frontend/src/hooks/useVideoChat.ts, packages/frontend/src/stores/chat/chat_view_reducer.ts, packages/frontend/src/stores/messagelist.ts
Where appropriate. Most notably:
- When jumping to message from quote click
- When jump to webxdc app from "Show app in chat" context menu item
- After "Show in chat" from the gallery
Let's add `focus: true` only to the most basic cases for now,
and later consider expanding this, and perhaps even adding
some logic / settings as to whether to focus the message.
=> improvement: focus message when jumping to it

CHANGELOG.md, packages/frontend/src/stores/messagelist.ts
~~This could cause the message list to not update on some events, but I have not seen a concrete example.~~
The bug was introduced in 7a968b68cd0c6d586e4554f47dbf0f628555595a.
(https://github.com/deltachat/deltachat-desktop/pull/4529).
The added `messageId > C.DC_MSG_ID_LAST_SPECIAL` in the first `if`
is purely for consistency and performance.
It's the second one that matters.
Update: OK, this really does appear like this is causing the "empty chat issue". Reproduction steps are roughly as follows:
1. Create two accounts
2. On Alice, send ~20 messages to Bob.
3. Switch to Bob's account and open the chat with Alice. Do not scroll to bottom.
4. Switch to Alice account and send another message to Bob.
5. Switch to Bob's account and open the chat with Alice.
You will see the `Failed to load …
=> fix: `onEventMessagesChanged`: handle `msgId == 0`

CHANGELOG.md, packages/target-electron/src/deltachat/controller.ts, packages/target-electron/src/deltachat/stdio_server.ts, packages/target-electron/src/ipc.ts
closes #4469
needs to also be tested on windows (after installation rename deltachat-rpc-server or delete it to simulate the issue)
=> error dialog is deltachat-rpc-server is not found

CHANGELOG.md
https://github.com/deltachat/deltachat-desktop/pull/4479 did not go into 1.52.0.
=> docs: move a changelog entry

packages/frontend/src/components/Gallery.tsx, packages/frontend/src/components/chat/ChatList.tsx, packages/frontend/src/components/dialogs/SelectChat/index.tsx, packages/frontend/src/components/dialogs/ViewGroup.tsx, packages/frontend/src/components/dialogs/ViewProfile/index.tsx
Apparently it's not really necessary for vertical lists.
And we're already utilizing `disableWidth` in some other places.
So let's apply it to the rest where it's applicable,
in hopes to reduce code complexity.
After a bit of testing, this does not appear to affect behavior.
=> refactor: apply `disableWidth` to `<AutoSizer>`s

CHANGELOG.md, packages/frontend/src/components/AccountListSidebar/AccountItem.tsx
The feature was introduced in 46d98111b69764b278f15c3dfe300e794dd64dcc,
but then broken apparently in d13a36cd10bcdb3c51d4f6cb0bd77a1a85f526a3.
As a side-effect, this will also show "placeholder" acount list items
while the accounts are loading.
And it makes the account list items interactive
while they're loading, i.e. you can select one
or activate the context menu.
Another thing this fixes is roving tabindex
while the accounts are loading, but isn't really important.
=> fix: scroll selected account into view on startup

.github/workflows/e2e.yml
This is letting other workflow failures go unnoticed because you just assume that the workflows will fail.
=> chore: disable E2E test workflows

CHANGELOG.md, packages/frontend/scss/misc/_context_menu.scss, packages/frontend/src/components/ContextMenu.tsx
Closes https://github.com/deltachat/deltachat-desktop/issues/4242.
Based on https://github.com/deltachat/deltachat-desktop/pull/4577.
I tested various context menus (chat list, "three-dot menu",
messages' context menus) and found no issues with this change.
=> fix: context menu not working with keyboard

CHANGELOG.md, packages/frontend/src/components/RuntimeAdapter.tsx, packages/frontend/src/components/message/MessageList.tsx, packages/frontend/src/contexts/ChatContext.tsx, packages/frontend/src/global.d.ts, packages/frontend/src/hooks/chat/useMessage.ts, packages/frontend/src/stores/messagelist.ts
Follow-up to 6a656f968ac2bc2f67d6b9fbc1aba15d3851f053
(https://github.com/deltachat/deltachat-desktop/pull/4510).
Partially addresses https://github.com/deltachat/deltachat-desktop/issues/4508.
Why partially? Because the bug appears to still happen sometimes.
But this commit should make it more reliable, or at least be a refactor.
This should also improve performance in some cases,
thanks to the removal of `setTimeout()`.
=> fix: improve `__jump_to_message` reliability

CHANGELOG.md, packages/frontend/src/stores/messagelist.ts, packages/frontend/src/stores/store.ts
...sometimes.
And maybe sometimes showing messages from previous chat.
I have not been able to confirm whether this fixes
an actual bug.
But at least in my understanding this fixes a semantic error.
The presence of the error is obvious if you make
`store.effect.loadChat()` synchronous.
So, what could be happening is that `loadChat` finishes _before_
we subscribe to the new store instance,
and thus the state never gets updated,
at least not until the next store update, which could be e.g.
`fetchMoreMessagesTop`.
The second commit also appears to be just a refactor.
=> refactor: fix message list potentially being empty

CHANGELOG.md, packages/frontend/src/backend/chat.ts, packages/frontend/src/components/ShortcutMenu/index.tsx, packages/frontend/src/components/chat/ChatList.tsx, packages/frontend/src/components/composer/menuAttachment.tsx, packages/frontend/src/components/dialogs/ChatAuditLogDialog.tsx, packages/frontend/src/components/dialogs/ForwardMessage/index.tsx, packages/frontend/src/components/dialogs/MessageListProfile.tsx, packages/frontend/src/components/dialogs/ViewGroup.tsx, packages/frontend/src/components/message/EmptyChatMessage.tsx, packages/frontend/src/components/message/MessageList.tsx, packages/frontend/src/components/message/messageFunctions.ts, packages/frontend/src/components/screens/MainScreen.tsx, packages/frontend/src/hooks/chat/useChatDialog.ts, packages/frontend/src/hooks/chat/useCreateChatByContactId.ts, packages/frontend/src/hooks/dialog/useOpenViewGroupDialog.ts, packages/frontend/src/stores/messagelist.ts
Review commit-by-commit recommended.
=> perf: improve performance

CHANGELOG.md, packages/frontend/src/components/message/MessageList.tsx, packages/frontend/src/stores/messagelist.ts
~~This is based on https://github.com/deltachat/deltachat-desktop/pull/4561 and https://github.com/deltachat/deltachat-desktop/pull/4554. This MR is about just the last commit.~~
Before:
https://github.com/user-attachments/assets/19f2c7c4-e3ee-4cf8-ae58-9b83936deebf
After:
https://github.com/user-attachments/assets/41d2210d-727d-44cf-8ed7-40fddf443673
That is, when you jump to a message in a different chat
(e.g. by clicking on a notification, or from message search,
or from a "private reply" quote),
we would momentarily show the new chat scrolled to bottom
prior to jumping to the desired message.
Why this is bad:
- We mark the visible messages as read.
In this case that would be the last messages in the chat.
But they weren't actually read, the user did not intend
to scroll to them.
- …
=> fix: jumpToMessage flashing the bottom of new chat

CHANGELOG.md, packages/frontend/src/stores/messagelist.ts
It sometimes momentarily shows "loading message" before
displaying the message properly, and sometimes,
if you send a lot of messages rapidly, doesn't load the messages
at all until you re-open the chat
or reload the message list otherwise.
Before:
https://github.com/user-attachments/assets/438bd0b9-65d2-4652-b648-0ad1d607ac81
After:
https://github.com/user-attachments/assets/0a242f20-11b8-4ec6-8543-2c077d16180f
This has probably been surfaced by the last core upgrade,
i.e. the thing that also introduced
https://github.com/deltachat/deltachat-core-rust/issues/6468.
=> fix: freshly sent "Saved Messages" not displaying

CHANGELOG.md, packages/frontend/src/stores/messagelist.ts
- **refactor: remove outdated comment**
- **refactor: simplify jumpToMessage**
- **refactor: simplify jumpToMessage again**
- **perf: improve jumpToMessage speed**
=> perf: improve `jumpToMessage` speed

CHANGELOG.md, docs/KEYBINDINGS.md, packages/frontend/src/components/KeyboardShortcutHint.tsx, packages/frontend/src/components/SearchInput/index.tsx, packages/frontend/src/components/ThreeDotMenu.tsx, packages/frontend/src/components/chat/ChatList.tsx, packages/frontend/src/components/composer/ComposerMessageInput.tsx, packages/frontend/src/components/screens/MainScreen.tsx, packages/frontend/src/keybindings.ts
- **improvement: Ctrl + F to focus search**
- **improvement: Enter or ArrowDown to focus 1st item**
- **improvement: don't clear search on focus**
- **improvement: Ctrl+M to focus composer, not Ctrl+N**
- **feat: Ctrl + N to open "Create Chat"**
- **feat: add Ctrl + Shift + F to search in chat**
=> improvement: better shortcuts

.github/workflows/e2e.yml, docs/E2E-TESTING.md, packages/e2e-tests/package.json, packages/e2e-tests/playwright.config.ts, packages/e2e-tests/tests/basic-functionality.spec.ts, packages/frontend/src/components/AppPicker/index.tsx, pnpm-lock.yaml
Since current chrome has no builtin headless mode anymore we have to update playwright
The tests on Windows & MacOS are very flaky, so removed to have not too many false positives. in the CI pipeline
Our copy process also often fails, so needs some future improvements...
I tried to speed up the App picker loading, by not waiting for the icon load promises.
=> test: upgrade playwright to 1.50

CHANGELOG.md, packages/target-electron/src/menu.ts
- do not advertise "Github" in our menu, also, contributions can be translations, donations, whatnot. just link to our own "contribute" page
- change homepage title to "Delta Chat Homepage", the old "Learn more about ..." opened questions :)
- group "online" actions together; the old separator was a but random
with this PR, things are in sync again with android/iOS, see https://github.com/deltachat/deltachat-android/pull/3556 and https://github.com/deltachat/deltachat-ios/pull/2545
=> streamline help menu

CHANGELOG.md, packages/frontend/src/components/contact/ContactListItem.tsx, packages/frontend/src/components/helpers/PseudoListItem.tsx, packages/frontend/src/contexts/RovingTabindex.tsx
Reproduction steps:
1. Create a group with one more contact.
2. Open the "View Group" dialog.
3. Click "Add Members"
4. Arrow-key navigate to the member that is already
part of the group.
You'll notice that you pressed the arrow key,
but the focus didn't change.
5. Press Tab.
Now you will not be able to focus the widget with Shift + Tab,
because the "active element"
(the only element that doesn't have tabindex="-1") is not focusable.
=> fix: arrow-key nav widgets being unfocusble

packages/frontend/scss/misc/_keyboard_hint_box.scss, packages/frontend/src/components/KeyboardShortcutHint.tsx, packages/frontend/src/components/dialogs/KeybindingCheatSheet.tsx
- add alternative shortcut to open shortcut hints
Before:
After:
=> refactor: improve styles in shortcut hint

CHANGELOG.md, packages/frontend/src/components/Settings/Notifications.tsx, packages/frontend/src/components/Switch/index.tsx, packages/frontend/src/components/Switch/styles.module.scss, packages/frontend/src/system-integration/notifications.ts, packages/shared/constants.ts, packages/shared/shared-types.d.ts, packages/shared/state.ts, packages/target-tauri/runtime-tauri/runtime.ts
=> Notify on mention

CHANGELOG.md, packages/target-electron/package.json, pnpm-lock.yaml
FYI breaking changes. Nothing much appears to apply to us, except perhaps macOS. Please re-check:
- https://www.electronjs.org/blog/electron-33-0#breaking-changes
- https://www.electronjs.org/blog/electron-34-0#breaking-changes
Closes https://github.com/deltachat/deltachat-desktop/issues/3416.
Appears to work after some basic testing.
=> chore: upgrade Electron from 32 to 34

.vscode/launch.json
To be reviewed by someone who uses VScode.
Electron has to be started with pnpm debug:electron
=> fix: enable attach to node process

CHANGELOG.md, Cargo.lock, packages/target-tauri/src-tauri/Cargo.toml
(update all dependencies because I was too lazy to surgically resolve the conflicts that the dc core upgrade caused + delta tauri is still unreleased so it is not a problem)
=> tauri: update core to 1.155.3 and update delta tauri dependencies

CHANGELOG.md, packages/frontend/src/components/Settings/Advanced.tsx
=> make log additionally available at "Settings / Advanced / View Log"

CHANGELOG.md, packages/e2e-tests/tests/basic-functionality.spec.ts, packages/frontend/scss/_global.scss, packages/frontend/scss/dialogs/_audit_log.scss, packages/frontend/scss/manifest.scss, packages/frontend/scss/message/_message-list.scss, packages/frontend/scss/misc/_react-window-list-reset.scss, packages/frontend/src/components/Gallery.tsx, packages/frontend/src/components/chat/ChatList.tsx, packages/frontend/src/components/chat/ChatListItemRow.tsx, packages/frontend/src/components/contact/ContactList.tsx, packages/frontend/src/components/contact/ContactListItem.tsx, packages/frontend/src/components/dialogs/AddMember/AddMemberInnerDialog.tsx, packages/frontend/src/components/dialogs/ChatAuditLogDialog.tsx, packages/frontend/src/components/dialogs/CreateChat/index.tsx, packages/frontend/src/components/dialogs/SelectContact/index.tsx, packages/frontend/src/components/helpers/PseudoListItem.tsx, packages/frontend/src/components/message/MessageList.tsx
~~I suggest to merge this after 1.52 in order to not break stuff, therefore draft.~~ 1.52 is released
=> fix: a11y: improve semantics

packages/target-electron/bin/printCheckWarning.js, packages/target-electron/src/index.ts
Looks like the event never passed an argument:
https://github.com/electron/electron/blob/624b6b97626d9baef48f60b67d84031b0a614870/docs/api/app.md?plain=1#L32-L39.
So this change does not affect behavior and only has to do with types.
This became an error after the recent Electron 32 -> 34 upgrade.
The first commit ("don't ignore Electron `check:types` err") makes sure that such errors don't get ignored.
=> refactor: fix Electron type error

packages/frontend/src/components/message/MessageList.tsx, packages/frontend/src/contexts/ChatContext.tsx, packages/frontend/src/stores/messagelist.ts
1. Open a chat with no messages.
2. Click on the currently open chat in the chat list.
The messages list will display an error
"cannot read toString of undefined" on MessageList.ts line 374.
The bug was surfaced by 28aa40a515a5d4ac3ff4d792007da57b401c0d93.
The bug existed before, but we wouldn't show error:
`jumpToMessage` would simply throw on `await getMessage()` instead.
#skip-changelog because the bug has not been released.
=> fix: don't show error on empty chat double click

CHANGELOG.md, packages/frontend/src/components/dialogs/ViewGroup.tsx
Since the core now has a new group consistency algorithm, the list of past members who left the group in the last 90 days is sent around in the (encrypted) header. Displaying it makes users aware that this happens and past members are known even to the new members. Besides "security" aspect, the feature is just occasionally useful to check "have I removed the bot from the group already, or just cannot find it in the huge member list?".
For use together with https://github.com/deltachat/deltachat-core-rust/pull/6442
=> feat: display past chat members

packages/target-tauri/src-tauri/Cargo.toml
Apparently it started failing after https://github.com/deltachat/deltachat-desktop/pull/4533.
=> fix: tauri: build failing (base64 dependency)

packages/target-electron/src/deltachat/webxdc.ts
The code was written in a way to reduce spamming when a permission was denied. But allowed permissions still had the same spammy behavior because Electron wants to call the permission handler a gazillion times.
This PR fixes so no spamming occurs, regardless if the permission is denied or allowed.
=> Remove spam for allowed and denied permissions

CHANGELOG.md, packages/frontend/src/contexts/ChatContext.tsx
This is a follow-up to
https://github.com/deltachat/deltachat-desktop/issues/4501
(166ee8acf0c479728210f6d3d37367d3032b41e5).
The issue now is that `cancelPendingSetChat.current = undefined`
unsets the cancel function for a different `selectChat()` call.
This happens when you selectChat more than 2 times
in a quick succession. And can go like this:
1. set cancelPendingSetChat for chat 1
2. set cancelPendingSetChat for chat 2
3. chat loaded 1
4. unset cancelPendingSetChat, from chat 1
5. set cancelPendingSetChat for chat 3
6. chat loaded 3
7. unset cancelPendingSetChat, from chat 3
8. chat loaded 2
9. unset cancelPendingSetChat, from chat 2
As you can see, when we called `selectChat(2)`,
it set cancelPendingSetChat (entry 2), but chat 1 loaded first,
and it unset cancelPendingSetChat …
=> fix: chat list & chat view desync, again

CHANGELOG.md, packages/frontend/src/components/message/MessageList.tsx, packages/frontend/src/global.d.ts
The bug was likely introduced in
https://github.com/deltachat/deltachat-desktop/pull/4554
(da4b9167513c76c5bc89e1302aedaf4cde020e40).
FYI the bug has only been released with 1.53.0.
=> fix: "Show in Chat" in gallery not working

packages/runtime/runtime.ts, packages/target-electron/src/ipc.ts
=> Sanitize filename

CHANGELOG.md, packages/frontend/src/components/AppPicker/index.tsx
=> fix source code links in app picker

CHANGELOG.md, packages/frontend/src/stores/messagelist.ts
FYI this moves the jumpToMessage function without changing it.
This should fix the bug where we'd try to load too many messages,
namely (almost) all messages of the chat.
The problem is that `loadChat` might return early,
to delegate its job to `effect.jumpToMessage`,
but there could already be other effects
(such as `fetchMoreMessagesTop`) already queued up,
so the `effect.jumpToMessage` would get added
to the back of the queue, resulting in other operations getting
executed prior to the `jumpToMessage`.
Those other operations do not work well with an uninitialized
store state, namely when
`oldestFetchedMessageListItemIndex` is `-1`.
In particular, `fetchMoreMessagesTop` would call `loadMessages`
with `newestFetchedMessageListItemIndex === -2` and
`oldestFetchedMessageListItemIndex === …
=> fix: message list freezes on selectChat

bin/lib/gather-version-info.js
According to the docs: "By default (without --all or --tags) git describe only shows annotated tags"
But we want to search for any tag, not only annotated tags
=> fix: show correct git version in build info

packages/e2e-tests/playwright.config.ts
Namely,
`expect(page.locator('.verified-icon-info-msg')).toBeVisible()`.
Looks like we should just wait for a bit longer.
=> test: fix E2E test timing out on group creation

packages/frontend/src/components/AppPicker/index.tsx
If we are offline we should show it and not pretend we are loading...
=> Offline or loading

.github/workflows/e2e.yml
So that we can debug flaky tests, because they _are_ pretty flaky
as of now.
=> test: always upload E2E test artifacts

packages/frontend/src/stores/messagelist.ts
=> fix: MessageListStore logger name is Store

CHANGELOG.md, packages/frontend/src/components/AccountListSidebar/AccountItem.tsx, packages/frontend/src/components/chat/ChatListItem.tsx, packages/frontend/src/components/message/MessageList.tsx
In:
- Chat list items.
- Account list items.
- "Jump down" button badge.
=> improvement: a11y: `aria-label` for unread count

CHANGELOG.md, packages/frontend/src/components/Avatar/index.tsx, packages/frontend/src/components/chat/ChatListItem.tsx, packages/frontend/src/components/contact/Contact.tsx, packages/frontend/src/components/dialogs/AddMember/AddMemberDialog.tsx, packages/frontend/src/components/dialogs/MessageDetail/ReadReceipts.tsx, packages/frontend/src/components/dialogs/ReactionsDialog/index.tsx, packages/frontend/src/components/screens/MainScreen.tsx
We can ignore them because contact / chat name is displayed
alongside the avatar, so avatars in this case are redundant.
This commit does not affect some clickable avatars,
e.g. in message list items in groups.
I am not sure how to approach those yet.
=> fix: a11y: `aria-hidden="true"` for some avatars

packages/shared/logger.ts
Just adding some more examples. This is a very nice feature!
Before change:
After change:
I'll update the `docs/LOGGING.md` file later in a separate PR.
=> logger: Add some more examples and mention Verbose in drop down

CHANGELOG.md, packages/frontend/src/stores/messagelist.ts
- **refactor: simplify jumpToMessage**
- **refactor: jumpToMessage more type safety, comments**
- **refactor: move var declaration in `jumpToMessage`**
- **fix: message list being empty on chat double click**
The important commit is the last one. Reviewing commit-by-commit should be easier for full understanding.
To reproduce, simply double click on a chat in the chat list
really fast.
Or:
```javascript
item = document.querySelector(
'.chat-list-item:not(.archive-link-item):not(.selected)'
);
chatListItem.click();
// Let React re-render, then click again.
setTimeout(() => chatListItem.click());
```
https://github.com/user-attachments/assets/23ce7b0b-f05d-49a8-a29e-8504ac077e91
The problem is, in `selectChat` we have code that is supposed to
jump to the last message when the currently …
=> fix: message list being empty on chat double click

packages/frontend/src/stores/messagelist.ts
- **refactor: simplify jumpToMessage**
- **refactor: simplify jumpToMessage 2**
- **refactor: simplify jumpToMessage 3**
This does not affect jumpToMessage behavior. TypeScript ensures that the vars are initialized eventually.
=> refactor: simplify jumpToMessage

CHANGELOG.md, packages/frontend/src/components/Gallery.tsx, packages/frontend/src/components/NoChatSelected.tsx, packages/frontend/src/components/message/MessageListAndComposer.tsx, packages/frontend/src/components/screens/MainScreen/MainScreen.tsx
if you listen to the screen-reader, it's not clear
what the buttons do, and how to change the active view.
This should fix it.
=> fix: a11y: 'tablist' role for gallery / chat view

packages/target-electron/src/deltachat/webxdc.ts
A slightly different approach.
* Pass a default size (note, a `Size` that only has `width` and `height`) instead of a boolean
* Compute the default size for webxdc and map at startup, based on the primary display, instead of putting it into `getLastBounds()`
* `getLastBounds()` returns a bounds if there were any, if this wasn't the case, use the `defaultSize` which already is adjusted to to the size of the primary display
Tweak to https://github.com/deltachat/deltachat-desktop/pull/4683
#skip-changelog PR to a PR
=> Pass in default size instead of booleans

CHANGELOG.md, packages/frontend/src/components/chat/ChatList.tsx, packages/frontend/src/components/chat/ChatListItem.tsx, packages/frontend/src/components/chat/ChatListItemRow.tsx
Also hide the "Archived" and "Contact Request" status.
This info is redundant when searching in a particular single chat.
=> improvement: hide chat name for single chat search

CHANGELOG.md, packages/frontend/src/components/Settings/Settings.tsx
=> Handle esc key in settings

CHANGELOG.md, packages/frontend/scss/message/_message.scss, packages/frontend/scss/message/_metadata.scss, packages/frontend/src/components/message/Message.tsx, packages/frontend/src/components/message/MessageMetaData.tsx
Closes https://github.com/deltachat/deltachat-desktop/issues/4694.
Depends on (hence draft):
~~skip-changelog~~ because:
=> feat: show "edited" in message status line

packages/e2e-tests/tests/basic-functionality.spec.ts, packages/frontend/scss/composer/_composer.scss, packages/frontend/src/components/composer/Composer.tsx, packages/frontend/themes/dev_minimal.scss, packages/frontend/themes/dev_rocket.scss
Apply the `onClick` handler to the button itself
and not its container.
This should make it easier to apply `disabled` state to the button.
This also makes the `outline` style reflect the button circular shape,
which looks better.
=> refactor: adjust send button HTML

packages/e2e-tests/tests/basic-functionality.spec.ts
More `await`s, fewer `textContent()`s.
=> test: reduce E2E tests flakiness

packages/frontend/scss/_global.scss, packages/frontend/src/components/dialogs/AlertDialog.tsx, packages/frontend/src/components/dialogs/ConfirmationDialog.tsx
Should be carefully checked for unexpected side effects.
AlertDialogs sometimes show an error besides a translated message, which might look bad if it's a long error message with many line breaks.
I also removed the alternate message type ReactNode from AlertDialog since it was not used (according to type checks)
=> fix: keep white-space in dialogs

CHANGELOG.md, packages/frontend/src/hooks/useProcessQr.ts
=> Show dialog if backup is too new

packages/frontend/src/components/message/Message.tsx
> this PR is the outcome of some one to one discussions
even though "Save" saves to saved messages
and "Save As" saves a file to some other place,
user may not think much about that,
and it is more confusing if they are not listed together as usual.
background: there are other ideas around,
eg. to reword "Saved Messages" to "Bookmarks"
(which would have the disadvantage to change a known UI element, and it would not fit that nicely to adding things manually, and it would not reflect the presistence).
another idea is to use "Export" instead,
however that was used before  https://github.com/deltachat/deltachat-desktop/pull/2546/ and probably cahnged for $reasons
(also cmp. https://github.com/deltachat/deltachat-desktop/pull/2160 ) so, all in all, the simple moving of the option seems to be …
=> move "Save" and "Save as" together

CHANGELOG.md, packages/frontend/src/components/composer/EmojiAndStickerPicker.tsx, packages/runtime/runtime.ts, packages/shared/shared-types.d.ts, packages/target-browser/runtime-browser/runtime.ts, packages/target-electron/runtime-electron/runtime.ts, packages/target-tauri/runtime-tauri/runtime.ts, packages/target-tauri/src-tauri/src/lib.rs, packages/target-tauri/src-tauri/src/runtime_info.rs, packages/target-tauri/src-tauri/src/stickers.rs
Before this pr the stickers where shown in the picker, but failed to load, this pr adds the `dcsticker://` scheme to fix that.
=> tauri: add support for sticker picker

CHANGELOG.md, _locales/_untranslated_en.json, packages/target-electron/src/deltachat/webxdc.ts
Closes https://github.com/deltachat/deltachat-desktop/issues/4726.
Here is an example of an app that uses `beforeunload`:
https://github.com/user-attachments/assets/02d6ac25-4f1e-4438-8995-1a42d6e643e8
=> fix: unclosable webxdc apps (`beforeunload`)

packages/target-tauri/src-tauri/src/help_window.rs
Because we can and for consistency (this applies the content protection also on start of the window before it was only applied when switching the setting).
=> tauri: content protection for help window

packages/frontend/src/components/screens/MainScreen/MainScreen.tsx, packages/frontend/src/components/screens/MainScreen/styles.module.scss
This is a regression introduced in
66c96d7df19f591a8c8610842952cb9f7b9ed540
(https://github.com/deltachat/deltachat-desktop/pull/4672).
#skip-changelog because insignificant
=> style: fix "Archived Chats" title ugliness

packages/target-tauri/src-tauri/src/lib.rs, packages/target-tauri/src-tauri/src/util/csp.rs, packages/target-tauri/src-tauri/src/util/mod.rs, packages/target-tauri/src-tauri/tauri.conf.json5
=> tauri: secure CSP to only contain `.localhost` urls on windows and android where they are intercepted

packages/target-electron/src/deltachat/webxdc.ts
Move out the lookup code by `event.sender` into a separate function for better readability.
#skip-changelog Refactor
=> Refactor webxdc lookup

packages/target-tauri/src-tauri/src/html_window/mod.rs, packages/target-tauri/src-tauri/src/util/csp.rs
lint says it is unused, it is mostly unused outside of windows and android, but it is used there.
=> allow unused in add_custom_schemes_to_csp_for_window_and_android

CHANGELOG.md, packages/target-tauri/src-tauri/src/help_window.rs, packages/target-tauri/src-tauri/src/html_window/mod.rs
https://github.com/deltachat/deltachat-desktop/issues/4745.
This implements the recommendadtion stated in `WebBuilder::new()` docs:
> On Windows, this function deadlocks when used
> in a synchronous command, see
> [the Webview2 issue](https://github.com/tauri-apps/wry/issues/583).
> You should use async commands when creating windows.
The windows don't hang the app anymore, but they are empty on Windows.
Opening the HTML message viewer also opens
"http://email.localhost/index.html" in the default system browser, which doesn't seem intentional.
Tokio complained about `block_on`, so I replaced it with `await`.
=> tauri: fix: HTML viewer and help hanging on Win

CHANGELOG.md, packages/target-tauri/src-tauri/src/help_window.rs, packages/target-tauri/src-tauri/src/html_window/mod.rs
This MR is based on #4759.
https://github.com/deltachat/deltachat-desktop/issues/4745.
I tested it with a fresh open of the help window, and when it's already open.
#skip-changelog because previously opening the help window would just freeze the app (which is addressed in #4759)
=> tauri: fix: empty "Help" window

packages/target-tauri/src-tauri/src/html_window/mod.rs
Partically addresses
https://github.com/deltachat/deltachat-desktop/issues/4745.
Note that in order to make the HTML message viewer work, https://github.com/deltachat/deltachat-desktop/pull/4759 is needed.
Windows uses different URL pattern for custom protocols, see `register_asynchronous_uri_scheme_protocol()`.
#skip-changelog because https://github.com/deltachat/deltachat-desktop/pull/4759 will add an entry.
=> tauri: fix: Windows: empty HTML message viewer

CHANGELOG.md, packages/target-electron/src/deltachat/webxdc.ts
The bug was introduced in e7221753d0b03064db5e3b2abacf10cf3fa22acb
(https://github.com/deltachat/deltachat-desktop/pull/4728).
[The Editor app](https://codeberg.org/webxdc/editor),
when getting closed, would always cause the "Close app?"
dialog to get shown to the user, but it's not intentional,
because the app would close regardless of what the user picks.
See the code comments for more info.
This also adds a comment about main process blocking.
I tested it with the Editor app, and with the previously unclosable Emacs app. Appears to work fine.
=> fix: unwanted "Close app?" dialog in Editor app

packages/frontend/scss/dialogs/_qr-code.scss
This is a follow-up to d4938ceffa036119b9ead78ac2cde7de9320d3be
(https://github.com/deltachat/deltachat-desktop/pull/4642).
Before / after
=> style: fix "Copy Link" color in QR dialog

CHANGELOG.md, packages/target-tauri/src-tauri/src/blobs.rs
FYI we also have the stickers, email, and the webxdc icon custom protocols, but we do not utilize
the `Content-Type` header explicitly there.
Test image from https://github.com/webrtc-for-the-curious/webrtc-for-the-curious/blob/master/content/docs/images/05-frame-types.svg
=> tauri: fix: broken SVG preview in composer

packages/target-tauri/src-tauri/src/help_window.rs
The bug is a result of a merge conflict between
a7d3ac05a14760b7461ce848e94c91eb4e107554 and
5bc35db79894506eba80cefde1359a14e56b9498.
Tokio doesn't like `block_on` inside async.
#skip-changelog because the menu and the hang fix are not released yet.
=> tauri: fix: help window not having menu

CHANGELOG.md, packages/target-tauri/src-tauri/src/temp_file.rs
Core returns the base64 string without padding (`=` at the end), but `write_temp_file_from_base64` enforced padding. This commit makes it not enforce padding.
I tested with a few apps that previously didn't work (e.g. Time Tracker), and with ones that did work (Pac-1D). All work good now.
=> tauri: fix: app picker not working (base64)

packages/frontend/src/components/AppPicker/styles.module.scss, packages/frontend/src/components/SearchInput/styles.module.scss
The original navbar buttons are not affected by this, I tested.
=> style: fix app picker clear search button hidden

CONTRIBUTING.md, Cargo.lock, README.md, bin/link_core/link_local.sh, bin/link_core/link_version.js, docs/UPDATE_CORE.md, packages/target-tauri/src-tauri/Cargo.toml, static/help/cs/help.html, static/help/de/help.html, static/help/en/help.html, static/help/es/help.html, static/help/fr/help.html, static/help/id/help.html, static/help/it/help.html, static/help/nl/help.html, static/help/pl/help.html, static/help/pt/help.html, static/help/ru/help.html, static/help/sk/help.html, static/help/sq/help.html, static/help/uk/help.html, static/help/zh_CN/help.html
https://github.com/deltachat-core-rust is now at https://github.com/chatmail/core
I left references to issues & PRs in comments to point to the old repository URL since we have the redirects in place.
=> chore: update old core repository to new one

packages/e2e-tests/tests/basic-functionality.spec.ts
I suspect that sometimes it tries to click a skeleton
(not yet loaded) item.
=> test: reduce E2E test flakiness

CHANGELOG.md, packages/target-tauri/src-tauri/src/html_window/error.rs, packages/target-tauri/src-tauri/src/html_window/mod.rs, packages/target-tauri/src-tauri/src/lib.rs, packages/target-tauri/src-tauri/src/menus/float_on_top.rs, packages/target-tauri/src-tauri/src/menus/html_window_menu.rs, packages/target-tauri/src-tauri/src/menus/main_menu.rs, packages/target-tauri/src-tauri/src/menus/mod.rs, packages/target-tauri/src-tauri/src/settings.rs, packages/target-tauri/src-tauri/src/state/menu_manager.rs
- **ignore more logs for iroh**
- **conditionaly compile `get_menu_for_window` method that it does not produce an unused warning and always set the menu on mac when creating a window**
- **html window menu**
=> tauri: menu for html email window

CHANGELOG.md, packages/e2e-tests/tests/basic-functionality.spec.ts, packages/frontend/src/components/Settings/Profile.tsx
I was running into a number of intermittent issues running the e2e tests.
- Often the `create profiles` was simply running too long for the default 30s timeout, so increased it to 120s (on my laptop I'm often seeing ~28-44s)
- That said, I also slowed it down a bit afterward because there is a race condition in the testing where the "onboarding" dialog does not necessarily precede the "add account" button. The code was written as if only one of the two will resolve, but that isn't true (anymore?). The "add account" is always present, so it would randomly win the race. I've updated it to wait for up to 1 second for the "onboarding", and then fall back on the "add account".
- Sometimes "after" hooks would error out because `settings` was null, so added a check there
=> chore: tweaks to fix intermittent errors seen in running e2e tests

packages/frontend/src/components/dialogs/SetupMultiDevice/ReceiveBackupDialog.tsx, packages/frontend/src/components/dialogs/SetupMultiDevice/SendBackupDialog.tsx
add-second-device is arguably no longer experimental, we're pointing to that options officially and often.
#skip-changelog as rewordings usually do not make it to the changelog (not sure if that fits on desktop, someone, please adapt to real policies :)
counterpart of https://github.com/deltachat/deltachat-android/pull/3685 and https://github.com/deltachat/deltachat-ios/pull/2646
=> no second device experiments

CHANGELOG.md, packages/frontend/src/components/CopyContentAlertDialog.tsx, packages/frontend/src/components/QrReader/helper.ts, packages/frontend/src/components/QrReader/index.tsx, packages/frontend/src/components/dialogs/QrCode.tsx, packages/frontend/src/components/dialogs/SetupMultiDevice/ReceiveBackupDialog.tsx
Resolves #4639
- show the spinner while processing imported qr code images or clipboard
- enable to cancel the processing if it takes too long
- call QrCode.handlePasteFromClipboard from parent component
- use second worker for clipBoard processing to avoid race conditions
=> Use worker for processing qr images

packages/target-tauri/src-tauri/capabilities/html-email-viewer-header.toml, packages/target-tauri/src-tauri/capabilities/main-window.toml, packages/target-tauri/src-tauri/tauri.conf.json5
https://v2.tauri.app/security/capabilities/ says:
> It is good practice to use individual files
> and only reference them by identifier in the tauri.conf.json
> but it is also possible to define them directly
> in the capabilities field.
This adds support for edit-time schema validation and permissions autocompletion.
Why TOML and not JSON? Because it supports comments.
I have verified that the capabilities are still properly applied.
=> tauri: refactor: move capabilities to files

CHANGELOG.md, packages/target-tauri/runtime-tauri/runtime.ts, packages/target-tauri/src-tauri/src/state/deltachat.rs
Tauri itself can serialize and deserialzie IPC messages.
From https://v2.tauri.app/concept/inter-process-communication/ :
> Because this mechanism uses a JSON-RPC like protocol
> under the hood to serialize requests and responses,
> all arguments and return data must be serializable to JSON.
I did not measure the performance difference, however.
=> tauri: perf: don't re-serialize JSON-RPC events

CHANGELOG.md, packages/frontend/src/components/message/messageFunctions.ts, packages/runtime/runtime.ts, packages/target-browser/runtime-browser/runtime.ts, packages/target-electron/runtime-electron/runtime.ts, packages/target-electron/src/ipc.ts, packages/target-electron/src/windows/html_email.ts, packages/target-tauri/runtime-tauri/runtime.ts, packages/target-tauri/src-tauri/src/html_window/mod.rs
In Tauri, window IDs are important for permission control,
and, prior to this commit, `open_html_window` used the `window_id`
parameter for making the label of the respective HTML message viewer window.
This commit limits the amount of control that the caller gets
over the window label, by replacing `window_id` string
with just two numbers.
So, e.g. now it's not possible to inject things like "main" there.
I have tested this change on both Electron and Tauri.
=> refactor: HTML msg viewer: replace `windowId` arg

packages/target-tauri/src-tauri/src/i18n/commands.rs
...from `locale_dir`. Otherwise it seems like "directory".
=> tauri: refactor: rename `locale_direction`

packages/frontend/src/components/Dialog/styles.module.scss
#skip-changelog because it's a very minor change
Follow-up to https://github.com/deltachat/deltachat-desktop/pull/4806.
Before / After:
=> style: fix dialogs not having margin, small screen

packages/frontend/src/components/dialogs/QrCode.tsx
the dialog for copying invite link does not say anything about a "QR code", and the old text saying "Copied QR url to clipboard" opens additional questions - what is a "QR url"?
this is esp. bad as the toast disappears while thinking about it :)
so, better just use the default text "Copied to clipboard" - the toast is anyway more a visual feedback that sth. has happend, not so much sth. to read.
came over that as translators have issues with the existing "QR url" text.
cmp https://github.com/deltachat/deltachat-android/pull/3697
=> improve toast after copying link to clipboard

packages/target-tauri/src-tauri/src/menus/main_menu.rs
=> tauri: fix: translation: "0.6x" missing in zoom size

packages/frontend/scss/composer/_composer.scss, packages/frontend/src/components/composer/Composer.tsx, packages/frontend/src/components/composer/ComposerMessageInput.tsx
This change provides a solution for #4763  with only minimal code changes by just hiding the send button if there is nothing to send.
~~Only downside so far: it does not work when a message is edited, but we have a warning there if the send button is clicked without a message text~~
~~Maybe it would be possible to adapt the editMessageInput to provide a function to detect if the textarea of an edited message is empty?~~
=> Hide send button if nothing to send

CHANGELOG.md, packages/frontend/src/components/message/Message.tsx
This makes the label a verb rather than a noun, consistently with the [Android version][1].
[1]: https://github.com/deltachat/deltachat-android/blob/2f432bfd3b31865487ca0bf36f0289af5e6c6b6c/src/main/res/menu/conversation_context.xml#L42
=> Change Reply in message menu to notify_reply_button

packages/frontend/scss/chat/_chat-list-item.scss, packages/frontend/scss/dialogs/_audit_log.scss, packages/frontend/scss/message/_metadata.scss
changes date, time and edited flag being shown in the given case, without additional transformations.
this unifies desktop to what is done on android and iOS, and also gives a smarter LESS YELLING look.
=> do not SHOUT OUT time, unify with other platform

packages/target-tauri/src-tauri/src/webxdc/webxdc_scheme.rs
It's not clear why it's there, maybe a residual
from testing iframes.
Iframes work without this source still, so let's remove it.
#skip-changelog because Tauri webxdc has not been released yet.
=> tauri: hardening: remove unnecessary `webxdc:` src

packages/target-tauri/src-tauri/src/menus/webxdc_menu.rs, packages/target-tauri/src-tauri/src/state/webxdc_instances.rs, packages/target-tauri/src-tauri/src/webxdc/commands.rs, packages/target-tauri/src-tauri/src/webxdc/webxdc_scheme.rs
- **tauri: refactor: `WebxdcInstancesState`: accept `Window`**
This gives better type safety, now it's harder to pass
an "arbitrary" `&str` to the methods of `WebxdcInstancesState`.
- **tauri: refactor: simplify webxdc commands**
A little less boilerplate
#skip-changelog because it's just a refactor
=> tauri: refactor: simplify webxdc commands

CHANGELOG.md, packages/target-tauri/src-tauri/src/webxdc/commands_main_window.rs
This is about https://delta.chat/en/2023-05-22-webxdc-security.
Using the "Test Webxdc" and "Cure 53 Test App - DNS checker" apps
I was unable to get any packets to get sent with this patch.
Not to the proxy URL, not to the STUN server, not to the DNS server,
even when I disabled CSP for the webxdc.
Edit:
Also this appears to prevent the PDF CSP bypass exploit
(XDC-01-005 WP1: Full CSP bypass via desktop app PDF embed).
The iframe gets created, and does bypass CSP,
but it can't actually load, even by IP.
Yes, with this approach, the `RTCPeerConnection` objects
can still be created.
Related:
- https://github.com/deltachat/deltachat-desktop/pull/3179
- https://github.com/deltachat/deltachat-desktop/pull/4351
- https://github.com/deltachat/deltachat-android/pull/2539
- …
=> tauri: hardening: disable WebRTC & DNS prefetch on Win

CHANGELOG.md, packages/frontend/scss/message/_message.scss, packages/frontend/scss/misc/_avatar.scss, packages/frontend/src/components/Avatar/index.tsx, packages/frontend/src/components/LargeProfileImage/index.tsx, packages/frontend/src/components/LargeProfileImage/styles.module.scss, packages/frontend/src/components/message/Message.tsx, packages/frontend/themes/_themebase.scss
- **gradient for color avatars**
- **add gradient to largeProfileImageArea and add type for it so ts doesn't complain**
- **add gradient to avatars in message view (author avatars)**
Basically makes the colors a bit less flat or harsh. Gives a slight impression of 3D.
Telegram also does this, though they have a much stronger gradient.
| Before | After |
|----|----|
| <img width="438" alt="Bildschirmfoto 2025-03-29 um 20 44 11" src="https://github.com/user-attachments/assets/550b3a53-9c47-4435-a557-4d505c2d3302" />|<img width="438" alt="Bildschirmfoto 2025-03-29 um 20 44 39" src="https://github.com/user-attachments/assets/bcabaee1-f7d4-4eaa-bca0-b768053c3184" /> | 
Why did I do this? This is inspired by feedback from older people that complained about harsh colors. (they also asked for a …
=> slight gradients for avatars for a more modern look

CHANGELOG.md, packages/frontend/src/components/Settings/Settings.tsx, packages/frontend/src/contexts/DialogContext.tsx, packages/frontend/src/hooks/dialog/useDialog.ts
resolves #4865
Closing the "latest" dialog by calling closeDialog(latestDialogID) could be a generic solution to "always" close the last opened dialog. Just a consideration in case we have longer stacks of dialogs some day
=> Expose open dialog IDs from DialogContext

CHANGELOG.md, packages/frontend/src/components/Dialog/Dialog.tsx
=> fix double escape bypasses dialog attribute `canEscapeKeyClose={false}`

CHANGELOG.md, packages/frontend/src/stores/accountNotifications.ts
=> migrate account mute state to new is_muted config option

bin/webxdc-check-permissions-policy-count.js, packages/target-tauri/package.json, packages/target-tauri/src-tauri/src/webxdc/webxdc_scheme.rs
#skip-changelog because Tauri webxdc has not been released yet.
I verified that putting `navigator.getUserMedia({ video: true }, console.log, console.error)` in the console no longer causes a permission prompt on Windows.
OK, it runs in CI, but still I guess I need to rewrite it.
=> tauri: hardening: webxdc: disable all web permissions

packages/frontend/src/components/Reactions/index.tsx, packages/frontend/src/components/message/Message.tsx
follow up:
- allow more visible reactions on non image messages: since text messages can be very small the detected width would only allow 1 visible emoji although the width would grow with more emojis. That is fixed now
- avoid a +1 pill wich takes the same space as one emoji
https://github.com/user-attachments/assets/b0b14490-31d0-402a-9f70-4db959615bf6
=> Improve reactions display

CHANGELOG.md, packages/frontend/src/components/KeyboardShortcutHint.tsx, packages/frontend/src/keybindings.ts
`Ctrl + N` exists already, but `Cmd + N` was missing.
=> `Cmd + N` shortcut to open new chat on macOS

packages/target-tauri/src-tauri/src/html_window/mod.rs, packages/target-tauri/src-tauri/src/state/app.rs, packages/target-tauri/src-tauri/src/state/html_email_instances.rs, packages/target-tauri/src-tauri/src/state/main_window_channels.rs, packages/target-tauri/src-tauri/src/state/translations.rs, packages/target-tauri/src-tauri/src/state/webxdc_instances.rs
Tauri's `State` manages `Arc`s itself,
we don't have to make them explicitly.
See https://tauri.app/develop/state-management/#do-you-need-arc.
#skip-changelog because it's just a refactor
For good measure, I made a build. It works fine.
=> tauri: refactor: remove unnecessary `Arc`s

packages/target-tauri/src-tauri/src/lib.rs, packages/target-tauri/src-tauri/src/state/deltachat.rs
This is not expected to have a hige impact
because JSON-RPC messages are not super frequent,
but why not go for it if we can.
#skip-changelog because it's minor.
I have checked that it works.
=> tauri: perf: move "get RPC channel" out of loop

CHANGELOG.md, Cargo.lock, packages/target-tauri/runtime-tauri/runtime.ts, packages/target-tauri/src-tauri/Cargo.toml, packages/target-tauri/src-tauri/src/cli.rs, packages/target-tauri/src-tauri/src/i18n/load.rs, packages/target-tauri/src-tauri/src/i18n/mod.rs, packages/target-tauri/src-tauri/src/lib.rs, packages/target-tauri/src-tauri/src/menus/mod.rs, packages/target-tauri/src-tauri/src/run_config.rs, packages/target-tauri/src-tauri/src/state/main_window_channels.rs, packages/target-tauri/src-tauri/src/util/fs_watcher.rs, packages/target-tauri/src-tauri/src/util/mod.rs
- **tauri: add `--translation-watch` also load from the right folder during development**
- **rename option to --watch-translations**
enabled by default in development. So that you can edit translations and they are automatically reloaded like in the electron edition.
I renamed the option, because I thought the old name was confusing:
---
> [!TIP]
>
>  Idea: Together with the env var `DELTACHAT_LOCALE_DIR` you could make a visual editor for translations that could be used by translators without a dev setup, possibly even with direct integration into transifex (or weblate or whatever we eill be using then).
=> tauri: add `--watch-translations` cli flag

CHANGELOG.md, packages/frontend/src/stores/accountNotifications.ts
I did not add extra migrations, because the change wasn't released yet.
=> fix typo in CONFIG_MUTED

CHANGELOG.md, packages/frontend/src/components/RuntimeAdapter.tsx, packages/runtime/runtime.ts, packages/target-browser/runtime-browser/runtime.ts, packages/target-electron/runtime-electron/runtime.ts, packages/target-tauri/runtime-tauri/runtime.ts, packages/target-tauri/src-tauri/Cargo.toml, packages/target-tauri/src-tauri/build.rs, packages/target-tauri/src-tauri/capabilities/main-window.toml, packages/target-tauri/src-tauri/src/cli.rs, packages/target-tauri/src-tauri/src/html_window/mod.rs, packages/target-tauri/src-tauri/src/lib.rs, packages/target-tauri/src-tauri/src/menus/main_menu.rs, packages/target-tauri/src-tauri/src/menus/mod.rs, packages/target-tauri/src-tauri/src/menus/tray_menu.rs, packages/target-tauri/src-tauri/src/menus/webxdc_menu.rs, packages/target-tauri/src-tauri/src/run_config.rs, packages/target-tauri/src-tauri/src/settings.rs, packages/target-tauri/src-tauri/src/state/main_window_channels.rs, packages/target-tauri/src-tauri/src/state/menu_manager.rs, packages/target-tauri/src-tauri/src/state/mod.rs, packages/target-tauri/src-tauri/src/state/tray_manager.rs, packages/target-tauri/src-tauri/src/tray.rs, packages/target-tauri/src-tauri/src/webxdc/commands_main_window.rs
- macOS keep in dock when closing
- translate `close_window` on webxdc window menu
- main window menu: app menu for macOS and add close window option to main window menu
- show/hide tray icon based on setting and update menu when language changes
- remove hide action from tray icon menu.
- tray icon: add option to mute notifications (bonus feature)
- implement tray icon badge
- add `--minimized` cli flag
=> Tauri: Tray Icon and `--minimized` flag

CHANGELOG.md, packages/target-tauri/runtime-tauri/runtime.ts, packages/target-tauri/src-tauri/src/lib.rs, packages/target-tauri/src-tauri/src/resume_from_sleep.rs, packages/target-tauri/src-tauri/src/state/main_window_channels.rs
choose elapsed time method over native apis, because native apis are too much work for now, and not clear whether it would be worth the extra complexity. (a tiny amount of less cpu usage for a ton of more complexity to maintain)
=> tauri: resume from sleep

packages/target-tauri/src-tauri/Cargo.toml, packages/target-tauri/src-tauri/src/lib.rs, packages/target-tauri/src-tauri/src/network_isolation_dummy_proxy.rs, packages/target-tauri/src-tauri/src/webxdc/commands_main_window.rs, packages/target-tauri/src-tauri/src/webxdc/error.rs
Making a browser use a proxy is arguably the most powerful way
(out of all feasible ways) to disable internet access
for webxdc apps.
Let's use it!
I have verified that on Windows (Chromium) the proxy still
doesn't receive any packets (because of `host-rules`).
I also tried disabling `host-rules`, in which case the packets
to the dummy proxy do get sent, but I was unable to produce
any kind of other network activity, not DNS prefetch, not WebRTC,
even if I removed the webxdc CSP.
This also fixes the wrong argument name on Windows,
`--proxy-url` -> `--proxy-server`.
#skip-changelog because Tauri webxdc has not been released yet.
TODO
Things to test:
=> tauri: hardening: invalid proxy for network isolation

packages/target-tauri/runtime-tauri/runtime.ts, packages/target-tauri/src-tauri/src/lib.rs, packages/target-tauri/src-tauri/src/settings.rs, packages/target-tauri/src-tauri/src/state/deltachat.rs
maybe we should think about whether we move this to the frontend on all 3 platforms
#skip-changelog tauri is not released yet and this is a small bugfix, but feel free to disagree and add a changelog entry
=> tauri: fix: start io for all accounts

CHANGELOG.md, packages/target-tauri/src-tauri/src/blobs.rs, packages/target-tauri/src-tauri/src/html_window/email_scheme.rs, packages/target-tauri/src-tauri/src/stickers.rs, packages/target-tauri/src-tauri/src/webxdc/icon_scheme.rs, packages/target-tauri/src-tauri/src/webxdc/webxdc_scheme.rs
There is not a known explot that this fixes, but let's do it to be extra safe.
=> tauri: hardening: check webview label in custom protos

CHANGELOG.md, packages/target-tauri/src-tauri/tauri.conf.json5
Apparently this is only visible in non-dev mode.
=> tauri: fix: sticker picker previews not working

CHANGELOG.md, packages/target-tauri/src-tauri/tauri.conf.json5
I have verified that this works, at least on Windows.
=> tauri: fix: emoji picker styles not working (CSP)

_locales/_untranslated_en.json, packages/frontend/src/components/dialogs/CreateChat/index.tsx
broadcasts are now encrypted as other chats,
in case of chatmail, always.
this change was needed as usage was broken otherwise, see https://github.com/chatmail/core/pull/6781 for more details
=> remove now superfluous broadcast-not-encrypted hint

CHANGELOG.md, packages/target-tauri/src-tauri/src/lib.rs
If the window is closed and not just minimized,
launching a second instance would do nothing.
=> tauri: fix: `main_window.show()` on second instance

CHANGELOG.md, packages/target-tauri/src-tauri/src/html_window/mod.rs, packages/target-tauri/src-tauri/src/util/mod.rs, packages/target-tauri/src-tauri/src/util/url_origin.rs, packages/target-tauri/src-tauri/src/webxdc/commands_main_window.rs
The `on_navigation` didn't fully check the URL origin
on Windows and Android, so a webxdc app could navigate
to `https://webxdc.localhost`, which could potentially
produce network traffic on `localhost:443`.
Fortunately, thanks to the presence of `host-rules`
and `proxy_url`, this wouldn't happen
even if navigation were to take place,
but let's still properly deny it.
This also refactors the HTML email viewer `on_navigation` check.
=> tauri: fix: deny navigation to https://webxdc.localhost

CHANGELOG.md, packages/target-tauri/src-tauri/src/help_window.rs, packages/target-tauri/src-tauri/src/menus/main_menu.rs
Prior to this, opening the help window from the menu
would always open the English version.
I tested that it works.
=> tauri: fix: use current locale in help window

packages/e2e-tests/playwright-helper.ts, packages/frontend/src/components/Settings/Advanced.tsx, packages/frontend/src/components/Settings/Profile.tsx, packages/frontend/src/components/Settings/Settings.tsx, packages/frontend/src/components/Settings/SettingsButton.tsx, packages/frontend/src/components/Settings/SettingsIconButton.tsx
showing the address here prominently results in bad UX as ppl try to pass the address around,
which will not result in e2ee and will often not work.
see https://github.com/deltachat/deltachat-ios/pull/2664 for more resoning and discussion, eg. why remove it unconditionally
cmp https://github.com/deltachat/deltachat-android/pull/3730
=> remove address from primary settings UI

CHANGELOG.md, packages/frontend/src/hooks/useProcessQr.ts
`error instanceof Error` is not true
for errors returned by the backend,
so we would basically ignore all errors.
I tested it, now the error dialog gets shown when you pass an invalid text there.
=> fix: error dialog not showing on `setConfigFromQr`

packages/frontend/src/components/LoginForm.tsx, packages/frontend/src/components/dialogs/ConfigureProgressDialog.tsx, packages/frontend/src/components/dialogs/EditAccountAndPasswordDialog.tsx, packages/frontend/src/components/screens/AccountSetupScreen.tsx, packages/frontend/src/hooks/useInstantOnboarding.ts, packages/frontend/src/hooks/useProcessQr.ts
This PR contains only a reorganization of code and moves the ConfigureProgressDialog from LoginForm to a separate file
It is based on PR #4945 but separated to make the review of the other PR easier
=> Transport api followup

packages/frontend/src/components/ImageCropper/index.tsx, packages/frontend/src/components/ImageSelector/index.tsx, packages/frontend/src/components/dialogs/CreateChat/index.tsx, packages/frontend/src/components/dialogs/EditProfileDialog/ProfileImageSelector.tsx, packages/frontend/src/components/dialogs/ViewGroup.tsx, packages/frontend/src/utils/copyToBlobDir.ts, packages/target-tauri/src-tauri/src/blobs.rs, packages/target-tauri/src-tauri/src/lib.rs
This PR adds image support by copying the selected profile picture to the blobfolder and using the dcblob asset scheme to display the images. `crossOrigin=anonymous` is needed because otherwise the canvas would get tainted.
=> Fix setting profile picture

CHANGELOG.md, Cargo.lock, _locales/_untranslated_en.json, packages/frontend/src/components/Settings/Advanced.tsx, packages/frontend/src/components/Settings/DesktopSettingsSwitch.tsx, packages/runtime/runtime.ts, packages/shared/shared-types.d.ts, packages/shared/state.ts, packages/target-browser/runtime-browser/runtime.ts, packages/target-electron/runtime-electron/runtime.ts, packages/target-tauri/Development.md, packages/target-tauri/runtime-tauri/runtime.ts, packages/target-tauri/src-tauri/Cargo.toml, packages/target-tauri/src-tauri/build.rs, packages/target-tauri/src-tauri/capabilities/main-window.toml, packages/target-tauri/src-tauri/src/autostart.rs, packages/target-tauri/src-tauri/src/cli.rs, packages/target-tauri/src-tauri/src/lib.rs, packages/target-tauri/src-tauri/src/settings.rs
- **fix: wait for setting to be applied before calling callback**
- **tauri: add autostart**
related to https://github.com/deltachat/deltachat-desktop/issues/2518, now spearheading on tauri, because tauri already has a plugin.
The option is hidden for now on electron and browser, because a disabled autostart option would only create confusion as long as tauri is not the default.
Also the option on tauri is for now only shown in release builds.
- ~~Linux flatpak~~ postponed
=> Autostart on Tauri

docs/UPDATE_CORE.md, packages/frontend/src/components/LoginForm.tsx, packages/frontend/src/components/Settings/DefaultCredentials.ts, packages/frontend/src/components/dialogs/ConfigureProgressDialog.tsx, packages/frontend/src/components/dialogs/EditAccountAndPasswordDialog.tsx, packages/frontend/src/components/screens/AccountSetupScreen.tsx, packages/frontend/src/components/screens/WelcomeScreen/AdditionalActionInfo.tsx, packages/frontend/src/components/screens/WelcomeScreen/InstantOnboardingScreen.tsx, packages/frontend/src/components/screens/WelcomeScreen/OnboardingScreen.tsx, packages/frontend/src/components/screens/WelcomeScreen/index.tsx, packages/frontend/src/hooks/useInstantOnboarding.ts, packages/frontend/src/hooks/useProcessQr.ts, packages/frontend/src/hooks/useSecureJoin.ts
This PR cleans up some outdated comments and namings and moves the account creation call to ConfigureProgressDialog to avoid inconsistencies (like passing default Credentials in createInstantAccount after account creation). Also prepares to pass the proxy configuration before account creation 
- move configurationQR to ConfigureProgressDialog
- move defaultCredentials to ConfigureProgressDialog
- move addTransportFromQr to ConfigureProgressDialog
- add inline documentation
- show new AEAP message on addr change #4989
=> Refactoring configure & instant onboarding

CHANGELOG.md, packages/frontend/src/components/composer/menuAttachment.tsx
the existing order was grown and appears a bit random, and also not consistent with android/ios,
where "image and related stuff" are the items most in view, and at least loosely separated (new line on android, separator on iOS)
as also on desktop, sending an image is the thing done most often, this PR reorders the menu to image/file/app/videochat/contact (from bottom to top, as focus is down, one reads from bottom, also shorter ways)
this is pretty much the same as iOS,
and still more similar to android
(which, by having horizontal layout, has different focus points)
desktop before / after:
ios:
=> reorder attach menu

CHANGELOG.md, packages/frontend/src/components/dialogs/EditAccountAndPasswordDialog.tsx, packages/frontend/src/components/dialogs/SetupMultiDevice/ReceiveBackupProgressDialog.tsx, packages/frontend/src/components/helpers/unknownErrorToString.ts, packages/frontend/src/components/screens/CrashScreen.tsx, packages/frontend/src/components/screens/RecoverableCrashScreen.tsx, packages/frontend/src/components/screens/WelcomeScreen/ImportBackupProgressDialog.tsx, packages/frontend/src/components/screens/WelcomeScreen/index.tsx, packages/frontend/src/hooks/useProcessQr.ts
The error thrown by `await BackendRemote.rpc...()` is not
`instanceof Error`, so we handled it incorrectly often times.
FYI there are a lot more `catch`es in our code base,
and I didn't re-check all of them.
This only fixes those that used `instanceof Error`.
Follow-up to https://github.com/deltachat/deltachat-desktop/pull/4981.
Related: https://github.com/deltachat/deltachat-desktop/issues/3883.
=> fix: error message not being shown on RPC calls

CHANGELOG.md, Cargo.lock, packages/frontend/src/components/message/MessageListAndComposer.tsx, packages/shared/shared-types.d.ts, packages/target-tauri/runtime-tauri/runtime.ts, packages/target-tauri/src-tauri/Cargo.toml, packages/target-tauri/src-tauri/build.rs, packages/target-tauri/src-tauri/capabilities/main-window.toml, packages/target-tauri/src-tauri/src/chat_background_image.rs, packages/target-tauri/src-tauri/src/lib.rs, packages/target-tauri/src-tauri/src/runtime_info.rs, packages/target-tauri/src-tauri/tauri.conf.json5
The new Tauri `saveBackgroundImage` is pretty much a Rust re-implemetation of the Node version of the function, except it doesn't remove the entire directory (which is arguably a bit over-engineered, but I just didn't want to `rm` more than needed).
This introduces a custom protocol scheme to get the image.
=> tauri: feat: custom chat background image

packages/target-tauri/runtime-tauri/runtime.ts
On macOS this caused a warning.
=> tauri: refactor: fix warning on `setOverlayIcon()`

CHANGELOG.md, _locales/_untranslated_en.json, packages/frontend/src/components/AppPicker/index.tsx, packages/frontend/src/components/chat/ChatList.tsx, packages/frontend/src/components/message/Link.tsx, packages/frontend/src/components/message/MessageMetaData.tsx, packages/frontend/src/hooks/useProcessQr.ts, packages/frontend/src/types-app.d.ts, packages/shared/localize.ts
This is a follow-up to https://github.com/deltachat/deltachat-desktop/commit/1c989ce0866b590e7e83b095c567ae652b4a64f1
(https://github.com/deltachat/deltachat-desktop/pull/4287).
Now it's not only about auto-completion, but also enforcing
that the key is present.
We have `./bin/test_for_missing_translations.sh`,
but we don't run it on every build, so sometimes we end up
specifying a wrong key.
One still can pass an arbitrary string to `tx` as such
`tx(myStr as any)`.
=> fix: some untranslated strings, add tx type safety

CHANGELOG.md, packages/frontend/src/components/KeyboardShortcutHint.tsx, packages/frontend/src/keybindings.ts
Follow-up to 19523b07bcc6d21d212332a4b2daa55a861bb77b
(https://github.com/deltachat/deltachat-desktop/pull/4901).
=> improvement: `Cmd + F` to focus search on macOS

CHANGELOG.md, packages/target-tauri/src-tauri/src/webxdc/commands_main_window.rs
depends on https://github.com/tauri-apps/tauri/pull/13076
Try it on:
=> tauri: webxdc hardening: disable webrtc by overwriting the JS API

CHANGELOG.md, packages/frontend/scss/_global.scss, packages/frontend/static/main.html, packages/target-browser/static/test.html, packages/target-tauri/src-tauri/tauri.conf.json5, packages/target-tauri/static/tauri_main.html
- Fullscreen media's `TransformComponent`
- color picker hiding styles
This commit concludes fixing all the CSP issues of the main window,
at least the ones that appear on initial page load.
=> tauri: fix: some styles not loading (CSP)

packages/frontend/src/components/screens/WelcomeScreen/OnboardingScreen.tsx, packages/frontend/src/components/screens/WelcomeScreen/index.tsx
resolve #4700
- "Esc" to close the dialog, if user has configured accounts
- replace the "back" button with a "close" button
=> Close instead back button

CHANGELOG.md, packages/frontend/scss/message/_message.scss, packages/frontend/scss/message/_metadata.scss, packages/frontend/src/components/message/MessageMetaData.tsx
This will only announce the "edited" status,
and not the new text of the message.
This also includes a refactor, see individual commits for clarity.
I have checked that the layout didn't change, at least in basic cases.
=> improvement: a11y: announce msg "edited" change

CHANGELOG.md, packages/frontend/src/components/dialogs/QrCode.tsx
Partially addresses https://github.com/deltachat/deltachat-desktop/issues/4743.
=> fix: a11y: alt text for QR invite image

CHANGELOG.md, packages/frontend/src/components/chat/ChatList.tsx
Previously, all the search results, i.e. contacts, chats, messages,
were a part of the same "roving tabindex" widget.
This is perhaps not intuitive, because they're in different sections.
Let's fix that, and make each section separately tabbable to.
For easier review, turn off "show whitespace".
I have checked that it works.
=> improvement: a11y: search: separate tabindex divs

CHANGELOG.md, packages/frontend/src/components/message/MessageMetaData.tsx
This should somewhat address this point in https://github.com/deltachat/deltachat-desktop/issues/4743
> Screenreader does not announce that it is successfully sent
=> improvement: a11y: `aria-live` for message status

packages/frontend/src/components/Button/style.module.scss, packages/frontend/themes/_themebase.scss
before: disabled secondary and primary button
after
=> Add missing disabled styles

packages/frontend/src/components/composer/Composer.tsx, packages/frontend/src/components/message/MessageListAndComposer.tsx
- **refactor: add comment about `draftRef`**
- **refactor: rename `_setDraftButKeepTextareaValue`**
- **refactor: rename `clearDraft` var and add docs**
This does not affect behavior. This is only about renaming and comments.
=> refactor: rename and comment vars in useDraft

CHANGELOG.md, packages/frontend/src/components/AccountListSidebar/AccountItem.tsx, packages/frontend/src/components/AccountListSidebar/AccountListSidebar.tsx
This should make it more clear that those are not just some
"buttons". UX-wise these are very close to "tabs",
so let's mark them as such.
This also adds `aria-selected`.
This, however, doesn't add the corresponding `role='tabpanel'`
element (see the comment).
=> fix: a11y: `role='tablist'` for accounts list

packages/frontend/scss/message/_message-attachment.scss, packages/frontend/scss/message/_message.scss, packages/frontend/src/components/attachment/messageAttachment.tsx
- no min-width for stickers (to avoid height crop)
- no border radius for stickers
- no max-width for images in portrait mode
=> Avoid stickers to be cropped in height

packages/target-tauri/src-tauri/src/help_window.rs, packages/target-tauri/src-tauri/src/html_window/mod.rs, packages/target-tauri/src-tauri/src/webxdc/commands_main_window.rs
This is mostly for consistency, because in some places
we already do use `Arc` for window, and in some places
we clone the window itself.
=> tauri: refactor: avoid `window.clone()`, use `Arc`

packages/target-tauri/src-tauri/src/lib.rs, packages/target-tauri/src-tauri/src/main.rs
This is to make sure that all the `drop()` that need to be called
do get called.
I don't know whether this has a practical effect,
but let's do it to be sure.
#skip-changelog because it's not clear whether there is a user-visible change.
=> tauri: fix: don't use `process::exit`, return instead

CHANGELOG.md
This actually has not been merged before 1.57.0.
https://github.com/deltachat/deltachat-desktop/pull/4959.
=> chore: fix wrong changelog entry

CHANGELOG.md, packages/target-electron/src/deltachat/webxdc.ts
Closes https://github.com/deltachat/deltachat-desktop/issues/4993,
and likely https://github.com/deltachat/deltachat-desktop/issues/4401.
The issue is that we register the `webxdc:` scheme protocol handler
once per account, when you open the first webxdc, and when we do,
we incorrectly use the captured `webxdcInfo` var inside the handler,
resulting in us using `selfAddr` of the first opened webxdc app
for all the subsequently opened apps.
The fix is to get `selfAddr` from the respective webxdcInfo object
for each app instance.
This commit also does the same for other `webxdcInfo` properties,
such as `sendUpdateInterval`.
`selfAddr` used to be the email address, so this used to be fine,
but then `selfAddr` started to be different between messages …
=> fix: webxdc: same `selfAddr` on different webxdcs

packages/target-electron/src/deltachat/webxdc.ts
Instead of defining it inside of `openWebxdc`.
This is so that it doesn't capture the variables inside of
`openWebxdc`, so that it's harder to introduce bugs like
https://github.com/deltachat/deltachat-desktop/issues/4993.
And also move `ses` declaration to inner scope, because it's only used in that scope.
FYI this does not modify its body, besides the `rpc` access. You can see it in git, showing code moves.
I have tested this, and it works.
TODO:
=> refactor: move webxdc proto handler to top level

packages/target-tauri/crates/user-notify/src/platform_impl/windows.rs
I have tested that notifications work now, even from the Actions Center.
=> tauri: fix: notification click on Windows

packages/frontend/scss/message/_message.scss
Height for images should never be "auto" since the message height might be wrong calculated. So the fix to avoid width cropped images is to reduce the height for small screens to 300px instead 450px. The cropping then only happens on screen width <= 380px which is fine I would say
=> Always use a fix height

packages/target-tauri/src-tauri/src/deeplink.rs
This is Windows-specific. We'd print it on every notification click,
even if we actually do handle the link successfully.
=> tauri: refactor: fix erroneous "unknown deeplink" log

packages/target-tauri/crates/user-notify/src/platform_impl/windows.rs
Notification action URL format has been changed in
0d5df734e0f47336f422c86a8bb6b246e5b416ea,
so parsing stopped working.
Additionally, this removes the dependency on the URL
having the `dcnotification:` scheme.
=> tauri: fix: notification action parsing

packages/target-tauri/src-tauri/src/deeplink.rs
We would only focus it if we were unable to handle the link instead.
#skip-changelog because it's minor
=> tauri: fix: deep-links not focusing main window

CHANGELOG.md, packages/frontend/src/components/NoChatSelected.tsx, packages/frontend/src/components/message/MessageListAndComposer.tsx
It's redundant most of the time.
https://github.com/deltachat/deltachat-desktop/issues/5074.
Partially reverts
00c7e6939675156e842f45ca9948dfa9b4cce507
(https://github.com/deltachat/deltachat-desktop/pull/4675).
=> improvement: a11y: don't announce "Chat" tab label

packages/target-electron/.gitignore, packages/target-electron/build/packageignore_list
New builds were 35mb bigger than 1.56.0 since the migration-tests were not excluded
=> Add migration-tests to packageignore_list

CHANGELOG.md, packages/frontend/src/components/composer/Composer.tsx
resolves #5092
This is an example. The draft will be kept. https://github.com/chatmail/core/issues/6847 si silved now and part of the pgp-contacts PR
=> Show AlertDialog on error

CHANGELOG.md, packages/frontend/src/components/dialogs/ViewGroup.tsx
Closes https://github.com/deltachat/deltachat-desktop/issues/5111.
Related issues and MRs that have to do with updating members list:
- https://github.com/deltachat/deltachat-desktop/pull/4894.
- https://github.com/deltachat/deltachat-desktop/issues/4646.
- https://github.com/deltachat/deltachat-desktop/pull/4531.
- https://github.com/deltachat/deltachat-desktop/pull/4353.
I have tested this for a bit. Adding, removing, blocking, unblocking members from the current and another device. I have not encountered any issues.
Although I don't claim that this is fool-proof. This could potentially surface another bug.
My biggest concern is that this commit makes it no longer re-fetch the entire list of contacts, so it might be that we're sometimes not updating when we should.
=> fix: crash in "View Group" dialog on adding member

packages/frontend/src/stores/messagelist.ts
resolves #5118
Just to show the user what happened instead "no reaction" at all
=> Show error if jumpToMessage failed

bin/build-shared-convert-translations.mjs, bin/copy.js
It seems the default import of chokidar (which is only used in watch mode) causes trouble in the build process sometimes.
`
file:///build/deltachat-desktop/src/deltachat-desktop/node_modules/.pnpm/[chokidar@3.6.0](mailto:chokidar@3.6.0)/node_modules/chokidar/esm/index.js:6
import { readdirp } from 'readdirp';
^^^^^^^^
SyntaxError: Named export 'readdirp' not found. The requested module 'readdirp' is a CommonJS module, which may not support all module.exports as named exports.
`
Since the build process doesn't need the watch parameter we can avoid the
=> Import chokidar only when needed

CHANGELOG.md, packages/target-tauri/src-tauri/src/deeplink.rs, packages/target-tauri/src-tauri/src/lib.rs
This only affects Windows.
`dcnotification:` is only needed when the app is not already running.
This is also an additional security measure.
Related: https://github.com/deltachat/deltachat-desktop/pull/5134.
I have tested this, and notifications still work, both when the app is initially closed and when it is running.
=> tauri: fix: ignore dcnotification: when not needed

packages/frontend/src/components/composer/ComposerMessageInput.tsx, packages/frontend/src/components/message/MessageListAndComposer.tsx
Related to https://github.com/deltachat/deltachat-desktop/issues/4590.
=> refactor: add comments about `composer.focus()`

packages/target-electron/src/deltachat/webxdc.ts
#skip-changelog because it probably doesn't affect behavior currently.
=> fix: webxdc: leave realtime when closing app

flake.nix
Add electron to flake, this is needed because the npm electron package can not be run natively on nixos.
To make this work, electron bin has to be deleted `rm ./packages/target-electron/node_modules/.bin/electron`
=> Add electron to flake

CHANGELOG.md, packages/frontend/src/contexts/ChatContext.tsx, packages/frontend/src/global.d.ts, packages/frontend/src/system-integration/notifications.ts
Instead of only showing notifications for messages
of other accounts, when the window is focused.
This is mainly for accessibility, but is also in line with
other messengers.
Together with https://github.com/deltachat/deltachat-desktop/pull/5143,
this concludes fixing accessibility issues related to
screen reader users not being notified of new messages.
There has been a bit of a discussion regarding when to show and when not to show notifications in https://github.com/deltachat/deltachat-desktop/pull/3680.
=> improvement: notify on msg in all non-curr chats

CHANGELOG.md, Cargo.lock, RELEASE.md, packages/frontend/src/components/composer/Composer.tsx, packages/frontend/src/components/message/MessageListAndComposer.tsx, packages/runtime/package.json, packages/runtime/runtime.ts, packages/target-browser/runtime-browser/runtime.ts, packages/target-electron/runtime-electron/runtime.ts, packages/target-electron/static/preload.js, packages/target-tauri/runtime-tauri/runtime.ts, packages/target-tauri/src-tauri/Cargo.toml, packages/target-tauri/src-tauri/build.rs, packages/target-tauri/src-tauri/capabilities/main-window.toml, packages/target-tauri/src-tauri/src/drag_and_drop.rs, packages/target-tauri/src-tauri/src/lib.rs, packages/target-tauri/src-tauri/src/state/notification.rs, pnpm-lock.yaml, pnpm-workspace.yaml
add drag in and drag out to tauri edition.
- accept drop one file in
- accept drop multiple files in
- drag out single file
original pr by @Septias: https://github.com/deltachat/deltachat-desktop/pull/4951
tested on macos, linux and windows.
on flatpak only dragging out seems to work on kde. dragging files in don't work.
I failed to understand how to utilize the file transfer portal - It should give us a file with a special mime type, but I can't figure out how to enable/trigger this behavior, in my test it still transferred the absolute path to the file, to which the flatpak app has no access to.
=> Tauri Drag and Drop 2

packages/target-tauri/runtime-tauri/runtime.ts
The bug was introduced in cc130b47ab7d9241eb980033909c36bcb63ff83a
(https://github.com/deltachat/deltachat-desktop/pull/5143).
It does not affect Electron.
The workaround is to go to Settings -> Notifications
and set "In-Chat Sounds" to any other value.
#skip-changelog because this has not been released yet.
=> tauri: fix: messagelist crashing due to `<audio>`

packages/frontend/scss/dialogs/_group-styles.scss, packages/frontend/src/components/dialogs/ViewProfile/styles.module.scss
In group profile: Avoid white margins in pinned chats and on hover. 
Before:
After:
TBD: we have different margins in chat lists (10px) and contact lists (20px). So in a group profile we have to adapt either the one or the other.
Should we change that to have the same margin for both? Chat list needs as much space as possible so we probably should go for 10px for both.
=> Adapt margins in profiles

packages/frontend/src/components/screens/MainScreen/MainScreen.tsx
Avoid "default" electron context menu for images on App Icons:
(reported by @hpk42 )
=> No image context menu on app icons

CHANGELOG.md, packages/frontend/scss/_global.scss
=> tauri: prevent moving around of the whole app with the touchpad gestures on windows

CHANGELOG.md, packages/frontend/src/components/message/Message.tsx
Well, to be precise, it did work sometimes,
but only when you click outside `.msg-container`
but inside `.message`.
For some reason we had two even listeners
from the very start
(bc0112ed6f07f91c829e6a00ee1a950a33abae6b,
https://github.com/deltachat/deltachat-desktop/pull/690).
But the issue with this is that `buildContextMenu`
gets invoked twice, and on the second run
`window.getSelection()` always returns an empty selection.
Looking at d48c8490b459c120f87ffb94d29f0f0501453a6d
(https://github.com/deltachat/deltachat-desktop/pull/2015),
it appears that this worked properly at least at some point,
but it's not clear when it broke.
Possibly with a React or Electron upgrade.
This commit should also make the context menu appear faster,
due to not having to do the work twice.
=> fix: "Copy Selected Text" on message not working

CHANGELOG.md, packages/frontend/src/components/Gallery.tsx, packages/frontend/src/components/NoChatSelected.tsx, packages/frontend/src/components/message/MessageListAndComposer.tsx, packages/frontend/src/components/screens/MainScreen/MainScreen.tsx
The issue has been introduced in
3bc21041bfbafea2da9c297adcdffa28528e8480
(https://github.com/deltachat/deltachat-desktop/pull/5149).
That MR was unfinished in this aspect.
This MR finished it, and closes
https://github.com/deltachat/deltachat-desktop/issues/5074.
This reverts 00c7e6939675156e842f45ca9948dfa9b4cce507
(https://github.com/deltachat/deltachat-desktop/pull/4675).
Also see 4073e2a400fc98b22a18d3b760a8f441e4fe42f8
(https://github.com/deltachat/deltachat-desktop/pull/5076).
=> fix: a11y: fix incorrect gallery "tab" role

CHANGELOG.md, packages/frontend/src/system-integration/notifications.ts
To be precise, when the chat ID of the currently selected chat
mathches the chat ID of the chat on another account
in which a message gets received.
The bug has been introduced in
928d73a70ec991266e8b0ff274ce8194c9b18b03
(https://github.com/deltachat/deltachat-desktop/pull/5146).
I have verified that this fixes the bug.
=> fix: notifications not working sometimes

CHANGELOG.md, packages/frontend/src/components/message/MessageListAndComposer.tsx
Closes https://github.com/deltachat/deltachat-desktop/issues/5167.
Closes https://github.com/deltachat/deltachat-desktop/issues/5193.
This is a follow-up to
- https://github.com/deltachat/deltachat-desktop/pull/4951.
- https://github.com/deltachat/deltachat-desktop/pull/5109.
- https://github.com/deltachat/deltachat-desktop/pull/5094.
This also fixed drag and drop to inside Delta Chat on Tauri, both in and out.
I have verified that this fixes dropping multiple files,
and a single file from outside.
But the code is still very problematic.
=> fix: dropping files on Windows

CHANGELOG.md, packages/frontend/src/components/attachment/mediaAttachment.tsx, packages/frontend/src/components/dialogs/FullscreenAvatar.tsx, packages/frontend/src/components/dialogs/FullscreenMedia.tsx, packages/frontend/src/components/dialogs/WebxdcSendToChat/index.tsx, packages/frontend/src/components/message/Message.tsx
in fact, it is 'Export Attachment' on android since forever, and it was changed on desktop to 'Save As' for forgotten or today minor reasons at https://github.com/deltachat/deltachat-desktop/pull/2546
now, that we have 'Save' used for 'Saving Messages' on all platforms, it makes sense to go back to 'Export Attachment' - we've seen that coming, that 'Save' and 'Save As' is a too close wording for different things, but now we get real user feedback and it is time to iterate :)
that way, we use the same term again for the same functionality.
ftr, 'Download Attachment' was bad as well, see
https://github.com/deltachat/deltachat-desktop/pull/2160
ftr, could be shortened to just "Export", but that is another consideration
=> reword 'Save As' to 'Export Attachment'

packages/e2e-tests/playwright.config.ts
"Invite new user to group" keeps failing.
Related:
- https://github.com/deltachat/deltachat-desktop/pull/5236.
- https://github.com/deltachat/deltachat-desktop/pull/4791.
=> test: bump test timeout from 30s to 5m

CHANGELOG.md, packages/frontend/src/components/attachment/Attachment.tsx, packages/frontend/src/components/attachment/mediaAttachment.tsx, packages/frontend/src/components/attachment/messageAttachment.tsx, packages/frontend/src/components/composer/Composer.tsx, packages/frontend/src/components/message/Message.tsx, packages/frontend/src/components/message/messageFunctions.ts, packages/frontend/src/components/screens/MainScreen/MainScreen.tsx, packages/frontend/src/system-integration/notifications.ts, packages/frontend/src/system-integration/webxdc.ts, packages/target-electron/src/deltachat/webxdc.ts
Resolves #5218 
I already tested various stuff, only thing I'm not really sure about is if broken media handling in Gallery is still the same as before, as I didn't had the various use cases
=> Fetch webxdc info seperately with `rpc.getWebxdcInfo`, because new core will no longer provide it in the MessageObject

CHANGELOG.md, Cargo.lock, packages/target-tauri/src-tauri/Cargo.toml, pnpm-lock.yaml, pnpm-workspace.yaml
I had to add 
```
[patch.crates-io]
parking_lot = "=0.12.4"
```
to Cargo.toml to avoid:
```
error: failed to select a version for `parking_lot`.
... required by package `hickory-resolver v0.25.2`
... which satisfies dependency `hickory-resolver = "^0.25.2"` (locked to 0.25.2) of package `deltachat v1.160.0 (https://github.com/chatmail/core?tag=v1.160.0#a40337f4)`
... which satisfies git dependency `deltachat` of package `deltachat-tauri v1.59.2 (/home/ndh/projekte/deltachat/deltachat-desktop/packages/target-tauri/src-tauri)`
versions that meet the requirements `^0.12` (locked to 0.12.3) are: 0.12.3
```
Not sure if there is a better way to fix that.
I also added a missing entry for the electron upgrade
=> Upgrade to core 1.160.0

packages/frontend/src/components/screens/MainScreen/MainScreen.tsx
Preserve the order core provides
=> Order app icons by last update

packages/frontend/src/components/dialogs/ProxyConfiguration/index.tsx
Follow-up to https://github.com/deltachat/deltachat-desktop/pull/5052.
=> fix: minor fixes for `ProxyConfiguration`

CHANGELOG.md, packages/frontend/scss/message/_message.scss
This also reduces the margin between info messages
to (somewhat) match Android.
Note that there are many kinds of `info-message`s, including daymarkers, webxdc info messages, "no chat selected" message. This affects all of them.
Reproduction steps:
1. Create a group.
2. Open the group chat.
Do not unfocus the window for the rest of the steps.
3. From another device, trigger an info message in this group,
for example, by setting "disappearing messages".
4. Make sure to scroll to the bottom of the messsage list.
You will notice that the "unread" counters for this chat remain at 1.
This had to do with the `.info-message` margin pushing
the `.message-observer-bottom` to the very bottom
of the message list, such that when you scroll to the bottom,
it doesn't register as `isIntersecting` in …
=> fix: not marking last info message as read

.github/workflows/build-preview.yml, CHANGELOG.md, bin/github-actions/postLinksToDetails.js, docs/DEVELOPMENT.md
To reduce the size of Downloads on https://download.delta.chat, till we have a better solution
Now a line 
#public-preview
is needed in the PR description to trigger the upload of a preview on download.delta.chat
=> New condition for preview builds

CHANGELOG.md, packages/frontend/src/components/message/MessageList.tsx, packages/frontend/src/components/message/MessageWrapper.tsx
Do some refactoring, and reduce the amount of unnecessary RPC calls.
Prior to this, when the window gets focused,
we'd try to mark _all_ visible messages as seen,
even if they're already seen or outgoing.
This would cause an unnecessary `debouncedUpdateBadgeCounter`,
which is quite expensive.
See individual commits for better understanding.
=> perf: clean up unread message observing, improve perf

CHANGELOG.md, packages/frontend/src/components/AccountListSidebar/AccountItem.tsx, packages/frontend/src/components/AccountListSidebar/AccountListSidebar.tsx, packages/frontend/src/components/AccountListSidebar/styles.module.scss, packages/frontend/src/components/chat/ChatList.tsx, packages/frontend/src/components/contact/ContactList.tsx, packages/frontend/src/components/dialogs/CreateChat/index.tsx, packages/frontend/src/components/dialogs/SelectChat/index.tsx, packages/frontend/src/components/dialogs/ViewGroup.tsx, packages/frontend/src/components/dialogs/ViewProfile/index.tsx, packages/frontend/src/components/message/MessageList.tsx
So that screen readers announce "messages list" or "chats list"
instead of just "list" when you focus an item inside of it.
For easier review, turn on "hide whitespace".
TODO:
=> improvement: add `aria-label(ledby)` for lists

CHANGELOG.md, packages/frontend/package.json, packages/frontend/src/components/contact/ContactList.tsx, packages/frontend/src/components/dialogs/AddMember/AddMemberDialog.tsx, packages/frontend/src/components/dialogs/CreateChat/index.tsx, pnpm-lock.yaml
Note that this affects many places:
- Chat list search.
- "New Chat" dialog search.
- "Attach Contact" dialog search.
***
- replace `debounce` with `asyncThrottle`,
which allows for much lower delay thanks to the fact
that it awaits the previous call.
- fix potential race conditions, utilize `useFetch`.
This partially addresses
https://github.com/deltachat/deltachat-desktop/issues/4501.
Also note that this adds a new NPM dependency.
The esbuild upgrade has been automatically performed by PNPM.
I have tested the change.
TODO:
=> perf: reduce debouncing in `useContactIds`

packages/frontend/src/hooks/useFetch.ts
Because we don't always handle them in the UI code and we need to be
aware of them when they happen regardless.
=> Log catched useFetch errors

packages/frontend/src/components/message/MessageMarkdown.tsx
(affects mainly browser and tauri edition, not so much electron, because there we block all navigation in the main window)
fixes regression introduced by #5286
for more info see
https://github.com/deltachat/deltachat-desktop/pull/5286/files/d3262d2a74d4a7d14759b89f43ea6100521f4825#r2207270975
=> prevent navigation when clicking on email addresses

packages/e2e-tests/tests/qrcode-tests.spec.ts
This is a problem for adding future tests which run after it,
because they'll refuse to proceed if there are existing profiles,
which was the case in
https://github.com/deltachat/deltachat-desktop/pull/5311.
I have verified that this fixes the issue.
=> test: fix qrcode test not deleting all profiles

package.json, packages/frontend/package.json, packages/target-browser/package.json, pnpm-lock.yaml, pnpm-workspace.yaml
This fixes all `pnpm audit` warnings as of today.
- **chore: remove unused `split2` dependency**
- **chore: update form-data**
- **chore: upgrade esbuild in packages/target-browser**
- **chore: upgrade esbuild in all packages**
- **chore: upgrade eslint stuff**
- **chore: upgrade @eslint/plugin-kit**
- **chore: upgrade `typescript-plugin-css-modules`**
- **chore: upgrade `@babel/runtime`**
- **chore: upgrade `brace-expansion`**
- **chore: target-browser: upgrade `express-session`**
#skip-changelog because this shouldn't affect users.
Feel free to squash if you think that's too many commits.
=> chore: upgrade dependencies, fix `pnpm audit`

packages/frontend/scss/chat/_chat-list-item.scss, packages/frontend/scss/composer/_composer.scss, packages/frontend/scss/message/_message.scss, packages/frontend/src/components/screens/MainScreen/styles.module.scss
When navigating with the keyboard in light mode it seems sometimes the focus is "lost" since the contrast of the outline is too small. This PR improves that for:
- selected chat item
- create chat button
- Info messages
Before:
https://github.com/user-attachments/assets/04054f97-8465-48dc-b12f-2188ad3305c3
After:
https://github.com/user-attachments/assets/d9eefe8a-83ad-44fa-b8d0-180a3151d59f
=> Improve outline visibility (a bit)

packages/frontend/scss/message/_message.scss
Such that days are more visually separated.
Closes https://github.com/deltachat/deltachat-desktop/issues/5338.
Related: https://github.com/deltachat/deltachat-desktop/pull/5244.
#skip-changelog because this is minor.
Before / After:
=> improvement: add more margin for daymarker msgs

CHANGELOG.md, packages/frontend/src/components/helpers/PseudoListItem.tsx
This is the first step to resolve _"remove "Add Contact Manually"_ in #5294
"Add contact manually" should never be shown when on a Chatmail account since it is not possible to add a contact just by email.
It does only partial resolve #5336 though, since on non chatmail accounts it is still possible to add contacts manually to Groups. That willl be addressed in another PR
=> Hide add contact manually if on chatmail

CHANGELOG.md, packages/frontend/src/components/ThreeDotMenu.tsx, packages/frontend/src/components/message/Message.tsx
- **fix: hide "Edit Message" for unencrypted chats**
- **fix: hide "Disappearing Messages" for unencrypted**
https://github.com/deltachat/deltachat-desktop/issues/5365.
What's left is avatars.
=> fix: hide "Disappearing Messages" and "Edit" for unencrypted chats

CHANGELOG.md, packages/frontend/src/components/Avatar/index.tsx, packages/frontend/src/components/ImageSelector/index.tsx, packages/frontend/src/components/LargeProfileImage/index.tsx, packages/frontend/src/components/ProfileInfoHeader/index.tsx, packages/frontend/src/components/Settings/Profile.tsx, packages/frontend/src/components/dialogs/MailingListProfile.tsx, packages/frontend/src/components/dialogs/ViewGroup.tsx, packages/frontend/src/components/dialogs/ViewProfile/index.tsx
A side effect is that one can't enlarge the "Device Messages"
chat avatar. Which is probably good.
Closes https://github.com/deltachat/deltachat-desktop/issues/5365,
together with
https://github.com/deltachat/deltachat-desktop/pull/5371.
=> fix: hide fullscreen avatar view for unencrypted

packages/frontend/src/components/dialogs/ViewProfile/index.tsx
See https://github.com/deltachat/deltachat-android/issues/3855.
TODO:
Note that for Device Messages it's already hidden,
thanks to https://github.com/deltachat/deltachat-desktop/pull/5373.
#skip-changelog because this is insignificant.
=> fix: hide "fullscreen avatar" for Saved Messages

CHANGELOG.md, _locales/_untranslated_en.json, packages/frontend/src/components/AccountListSidebar/AccountItem.tsx, packages/frontend/src/components/ContextMenu.tsx, packages/frontend/src/components/ThreeDotMenu.tsx, packages/frontend/src/components/chat/ChatListContextMenu.tsx, packages/frontend/src/components/composer/menuAttachment.tsx, packages/frontend/src/components/message/Message.tsx, packages/frontend/src/hooks/useContextMenu.ts
https://www.w3.org/WAI/ARIA/apg/patterns/menubar/ :
> An element with role menu either has:
> - aria-labelledby set to a value that refers to the menuitem
>   or button that controls its display.
> - A label provided by aria-label.
=> improvement: a11y: add `aria-label` for some menus

packages/target-electron/runtime-electron/runtime.ts
resolves #5403 
We have to reload the main window (not restart the app!) to make sure all caches are reset. Otherwise we would always have to care explicit that caches are reset on language change.
Since we "remember" last open chat and draft etc. there is no impact for the user except a short reload of the window.
FYI Signal has to restart the whole app on each language change
@r10s  TBD: do we need to show a confirm dialog before reloading?
=> Reload main window on language change

CHANGELOG.md, packages/frontend/scss/chat/_chat-list-item.scss, packages/frontend/src/components/ShortcutMenu/styles.module.scss, packages/frontend/themes/_themebase.scss, packages/frontend/themes/dark.scss, packages/frontend/themes/dark_amoled.scss, packages/frontend/themes/darkpurple.scss, packages/frontend/themes/dev_minimal.scss, packages/frontend/themes/dev_rocket.scss, packages/frontend/themes/light.scss
This PR renames floatingActionButtonBg to newChatButtonBg since the color is only used for that button
It also introduces a new css variable "showInChatButtonBg"  since the color was assigned from variable iconBackground which doesn't make sense.
resolves #5183
=> New chat button color

packages/frontend/src/components/chat/ChatListItem.tsx, packages/frontend/src/components/chat/ChatListItemRow.tsx, packages/frontend/src/components/screens/MainScreen/MainScreen.tsx
We do not re-render `ChatListItem`
even when `onContextMenu` prop changes,
due to the fact that we don't check if this prop changed
in our `areEqual` function.
This commit makes it harder to introduce a bug
when introducing new props for `ChatListItem`,
and potentially fixes some existing bugs.
I have verified that the component still doesn't re-render unnecessarily,
e.g. when switching to another chat.
TODO:
=> refactor: fix potential ChatListItem `memo()` bugs

packages/e2e-tests/playwright-helper.ts, packages/e2e-tests/tests/basic-tests.spec.ts, packages/e2e-tests/tests/group-tests.spec.ts, packages/e2e-tests/tests/qrcode-tests.spec.ts, packages/e2e-tests/tests/unencrypted-group-tests.spec.ts
This was first introduced in
https://github.com/deltachat/deltachat-desktop/pull/5311,
just for that test.
But let's expand it to all tests.
This reduces total run time of all tests from ~2.6 minutes
to ~1.9 minutes.
TODO:
=> test: perf: don't reload page before every test

packages/e2e-tests/tests/chat-list-multiselect.spec.ts
Follow-up to
https://github.com/deltachat/deltachat-desktop/pull/5297.
This doesn't cover all the intricate behaviors,
but it does cover the basic ones.
It's a separate MR because the base one is already quite big, and is approved, so I don't want to make noise in it. But it doesn't matter if this one's merged before or after that one.
=> test: add tests for chat list multiselect

CHANGELOG.md, packages/frontend/src/components/composer/Composer.tsx, packages/frontend/src/components/message/MessageListAndComposer.tsx
The primary point of this change is to remove
`textarea.focus()`, which makes screen readers re-announce
the composer, which is disorienting and pointless.
https://github.com/deltachat/deltachat-desktop/issues/4590#issuecomment-2821985528.
This change has side-effects:
- Now if the user starts typing right after sending a message,
we will not ignore it, as we would if the composer was disabled,
which is good.
- However, as a consequence, now it's possible to type
while a message is being sent,
which might have unexpected consequences itself,
i.e. race conditions, i.e. bugs.
This also ~~adds an~~ improves the alert dialog that pops up if sending fails.
"hide whitespace" should make this easier to review.
I have tested this for a bit, and it appears to work OK. I have …
=> fix: a11y: dont disable composer while sending

CHANGELOG.md, packages/frontend/src/components/chat/ChatListItem.tsx, packages/frontend/src/components/chat/ChatListItemRow.tsx, packages/frontend/src/components/contact/ContactListItem.tsx
Due to the usage of a virtualized list,
screen readers would announce an incorrect number of chats
in the chat list, and the positions of individual chats in the list.
Explicitly setting `aria-posinset` and `aria-setsize` should work.
This only handles the chat list and not all the virtualized lists
that we have.
Related:
- https://github.com/bvaughn/react-window/issues/808.
- https://github.com/deltachat/deltachat-desktop/pull/4660.
- https://github.com/deltachat/deltachat-desktop/pull/5025.
TODO:
=> fix: a11y: correct `aria-posinset` for chat list

packages/e2e-tests/tests/chat-list-multiselect.spec.ts
The `unencrypted-group-tests.spec.ts` was not properly rebased
in one of the recent MRs.
Sorry about that!
=> test: fix E2E tests

CHANGELOG.md, packages/frontend/src/components/message/MessageListAndComposer.tsx
On Linux and macOS.
Such that you'd be unable to focus anything else
by using the Tab key.
Closes https://github.com/deltachat/deltachat-desktop/issues/5097.
https://github.com/deltachat/deltachat-desktop/issues/4590.
This also affects Electron on all platforms and Tauri for Windows:
now we will not re-focus the composer
after you un-select some text in a message.
This can be considered a downside,
but I was not able to come up with a simple soltuion
that I am sure is also good accessibility-wise.
On WebKit, the `selectionchange` event fires pretty much every time
something is clicked or when focus changes.
Namely, it fires when the focus exits the composer,
which is what caused the bug.
Although this is gonna be a bit annoying for mouse users
that they now have to …
=> fix: a11y: focus being locked on message input

Cargo.lock, Cargo.toml
Supersedes https://github.com/deltachat/deltachat-desktop/pull/5429.
I have checked that this still works, and also checked that the new versions that include the needed fixes are used.
=> chore: tauri: update dependencies

CHANGELOG.md, packages/e2e-tests/tests/unencrypted-group-tests.spec.ts, packages/frontend/scss/message/_message.scss, packages/frontend/scss/message/_metadata.scss, packages/frontend/src/components/message/MessageMetaData.tsx
The issue was that apparently NVDA first announces the label
(`aria-label`) of the changed element, and then announces
the change itself, which, in this case, is a change to
`aria-label`. This results in it simply announcing the label twice.
Let's mitigate this by removing `aria-label`.
And along the way, let's split the button
into a `role='status'` element and a "Message Info" button.
I have verified that the look of the app is the same, with WebXDC messages, info messages, and videos.
TODO:
It's easier to test it after the rebase, therefore it's draft.
=> fix: a11y: delivery status being announced twice

CHANGELOG.md, packages/frontend/src/components/AppPicker/index.tsx, packages/frontend/src/components/composer/Composer.tsx
Don't show the list of apps only if we failed to fetch it,
and not whenever we're offline.
This also fixes an annoying bug where the app picker
would show "offline" if you opened it
during "updating" network status,
which notably also happens when you just focused the window
(due to a `rpc.maybeNetwork()` call).
And this has been causing E2E test failures recently.
`getHttpResponse` is able to cache data since not so long ago,
so let's utilize that.
Note that the fact that we have cached the list of apps
doesn't mean that all the apps themselved are cached,
so users might still encounter an error.
However, if the list of apps and the app file is cached,
this allows you, even when offline,
to send an app to the chat and open it.
This change also makes sense even if `getHttpResponse`
didn't …
=> fix: allow offline usage of app picker

packages/target-electron/build/afterPackHook.mjs
If SKIP_FUSES = true we skip the flip fuses script.
This helps building nixOS packages. See comments in #5423 
=> Add SKIP_FUSES env var

packages/frontend/src/components/Settings/Notifications.tsx
Add `disabledValue` to "Mentions" toggle, so that when
"Current Profile -> Mute Notifications" is on,
"Mentions" gets automatically toggled off.
It will retain its actual value in settings store,
this only affects appearance.
#skip-changelog because this is insignificant.
=> improvement: adjust notif settings appearance

packages/target-electron/src/windows/video-call.ts, packages/target-electron/static/calls-webapp-preload.js
#skip-changelog because we'll add it later.
This changes the calls-webapp URL to add `accountId`,
`chatId` and `messageId` to it, in order to determine
which avatar we need to get. Similarly to our WebXDC implementation.
Note that if a user doesn't have an avatar,
the avatar won't be displayed at all.
https://github.com/deltachat/calls-webapp/pull/29 would improve this a little.
=> feat: video calls: show other's avatar

packages/target-electron/src/windows/video-call.ts, packages/target-electron/static/calls-webapp-preload.js, pnpm-lock.yaml
- It looks nicer.
- Allows you to toggle video and mute mic before you accept the call.
See https://github.com/deltachat/calls-webapp/pull/37.
Security-wise, not that it's critical, but note that now
we pass the offer to the app immediately, so hypothetically
the app could auto-accept the call without waiting
for user interaction, if it wanted to.
Let's not remove the old prompt code for now.
The updated calls-webapp has been built from ~~<https://github.com/deltachat/calls-webapp/commit/63fd46ee132029635e838b81e6f61d84019688d1>~~ https://github.com/deltachat/calls-webapp/commit/0fa0c9dd616183070ed9b58e4ada6b1c0382349e (latest main).
#skip-changelog because this is an experimental feature.
=> improvement: calls: use in-app "Answer?" prompt

images/icons/phone.svg, packages/frontend/scss/message/_message.scss, packages/frontend/src/components/message/Message.tsx, packages/frontend/themes/_themebase.scss, packages/frontend/themes/dark.scss, packages/frontend/themes/dark_amoled.scss, packages/frontend/themes/darkpurple.scss
Changes:
1. adds phone icons to messages
2. changes outgoing meta data color in dark mode
3. disable edit & forward for call messages
Reasons:
1. Similar to https://github.com/deltachat/deltachat-android/pull/3920 although the UI might still change
2. we had the same color (green) for dark & light mode, but the green has very low contrast to a dark background, the change is more similar to the color in Android
3. call messages should not be forwardable & editable - could be confusing since call messages are more some kind of log
TBD: I used a "filled" phone icon since it seemed to me more visible. Maybe we replace the icon in the navbar also?
Dark mode:
#skip-changelog as this is part of an experimental WIP feature
=> Improve display of call messages

CHANGELOG.md, packages/frontend/src/components/Dialog/styles.module.scss, packages/frontend/src/components/Settings/Settings.tsx, packages/frontend/src/components/Settings/SettingsSeparator.tsx, packages/frontend/src/components/Settings/styles.module.scss, packages/frontend/src/components/dialogs/About.tsx, packages/frontend/src/components/dialogs/MediaView/styles.module.scss, packages/frontend/src/components/screens/WelcomeScreen/AlternativeSetupsDialog.tsx, packages/frontend/src/components/screens/WelcomeScreen/OnboardingScreen.tsx, packages/frontend/src/components/screens/WelcomeScreen/UseOtherServerDialog.tsx
- **remove dialog margin**
- **re-add dialog margin to settings. It is a seperate element, because that way it is inside of the scroll area, not taking away from it, only visible when you scrolled to the end.**
- **reintroduce bottom space for gallery, again by adding the margin to the scroll content and not the container**
- **add spacing to remaining dialogs. using br line break beacuse it works just fine and is easy to do and understand. again, idea here is to add it to the content and not outside of it for the case that the dialog is scrollable.**
Before this pr scroll-able content vanishes at an invisible line:
After this pr the content is visible until the edge of the dialog:
=> Improvements to Dialog Bottom Margin

packages/target-electron/runtime-electron/runtime.ts, packages/target-electron/src/windows/video-call.ts
This should make the front-end console print an error
if `startOutgoingVideoCall` throws an error.
This does not affect functionality.
=> refactor: `startOutgoingVideoCall`: return Promise

packages/frontend/src/components/dialogs/ProxyConfiguration/index.tsx
This has been mentioned in
https://github.com/deltachat/deltachat-desktop/issues/5507.
#skip-changelog because this is insignificant.
=> improvement: proxy dialog title: Settings -> Proxy

packages/e2e-tests/_env
It was referencing a nonexisten var.
See ce82703ab4d43770cdcfa10f3fb3f87551a8e3f2
(https://github.com/deltachat/deltachat-desktop/pull/5342).
Also add a comment about running tests
without a non-Chatmail server.
=> test: fix example `_env` file

packages/e2e-tests/playwright.config.ts
They keep failing for a lot of recent MRs.
=> test: disable flaky non-Chatmail tests again

CHANGELOG.md, packages/frontend/src/stockStrings.ts
Add type safety and add back some missing strings.
The first commit adds type safety, the second commit adds missing strings.
This partially reverts f0d264b857c3b3176a100a877553ce6d1725107f,
which removed `DC_STR_AEAP_EXPLANATION_AND_LINK`,
which apparently should not have been removed. See
https://github.com/deltachat/deltachat-desktop/pull/5503#discussion_r2401112411.
=> fix: untranslated stock strings, add type safety

packages/target-electron/src/windows/video-call.ts
We can now get the `chatId` directly, instead of asynchronously
determening it from `messageId`.
This allows us to simplify the host name
and remove the `getChatInfo` helper function.
Note that now all calls in the same chat have the same origin.
Which is OK.
This also renames a type `T` which was conflicting. This became evident to me just after these changes.
TODO:
=> refactor: simplify `video-calls.ts` (chatId)
