deltachat/deltachat-desktop

- CHANGELOG.md
i forgot changelog update, so this is just a follow up to #2435
> Push translations nov 2021

- CHANGELOG.md
- package-lock.json
- package.json
- src/main/deltachat/chat.ts
- src/main/deltachat/login.ts
- src/renderer/components/Menu.tsx
- src/renderer/components/dialogs/CreateChat.tsx
- src/renderer/components/dialogs/QrCode.tsx
- src/renderer/components/dialogs/ViewGroup.tsx
- src/renderer/delta-remote.ts
> display qrcode svg from core

- CHANGELOG.md
- _locales/_untranslated_en.json
- package-lock.json
- package.json
- scss/message/_message.scss
- src/main/deltachat/messagelist.ts
- src/renderer/components/dialogs/DeltaDialog.tsx
- src/renderer/components/dialogs/Settings-DownloadOnDemand.tsx
- src/renderer/components/dialogs/Settings.tsx
- src/renderer/components/message/Message.tsx
- src/renderer/components/message/messageFunctions.ts
- src/renderer/delta-remote.ts
- src/shared/constants.ts
> download on demand / auto-download

- CHANGELOG.md
- scss/message/_message.scss
- src/renderer/components/dialogs/ConfirmationDialog.tsx
- src/renderer/components/message/Message.tsx
> Fixed blob width by replacing button with div

- src/renderer/components/message/MessageList.tsx
- src/renderer/stores/chat.ts
the reducer event and current state object
> Better guard against changing the state if the chatId changed in between

- src/main/deltachat/messagelist.ts
- src/renderer/components/composer/Composer.tsx
- src/renderer/components/helpers/ChatMethods.ts
- src/renderer/delta-remote.ts
> fix draft bugs with new core

- CHANGELOG.md
- src/renderer/components/dialogs/CreateChat.tsx
Continuation of: https://github.com/deltachat/deltachat-desktop/pull/2509
Fixes #2256
Closes #2509
> Add new contact by email to group

- src/renderer/components/message/MessageList.tsx
- src/renderer/stores/chat.ts
> Move locking logic for fetch more to the store

- CHANGELOG.md
- src/main/deltachat/login.ts
- themes/dev_rocket.scss
Overwrote hover color for rocket theme.
> Fixed font color for highlighted settings options

- src/renderer/components/composer/Composer.tsx
This feels a bit better then first sending the message, then the message pops up, then the draft disappears
> First remove the draft, then send the message

- src/main/deltachat/messagelist.ts
- src/renderer/components/dialogs/DisappearingMessages.tsx
- src/renderer/components/message/MessageList.tsx
- src/renderer/delta-remote.ts
- src/renderer/ipc.ts
- src/renderer/stores/chat.ts
> Fix refresh messagelist

- scss/contact/_contact-list.scss
- themes/_themebase.scss
> fix style of group add member contact chip

- CHANGELOG.md
- src/main/deltachat/settings.ts
- src/main/ipc.ts
- src/renderer/components/dialogs/Settings-Appearance.tsx
- src/renderer/components/message/MessageListAndComposer.tsx
- src/renderer/runtime.ts
First take on making the background image url portable. Not sure if this is the right way. Happy about reviews and suggestions!
closes #2169
> Make background image url portable

- CHANGELOG.md
- src/renderer/components/message/MessageListAndComposer.tsx
- src/renderer/components/message/MessageMarkdown.tsx
- src/renderer/components/screens/MainScreen.tsx
- src/renderer/components/screens/RecoverableCrashScreen.tsx
- log msg-parser errors and display plain text as fallback instead of crashing closes #2605
- fix formatting
- add an extra error boundary for MessageList
> more error boundaries

- CHANGELOG.md
- src/renderer/stores/chat.ts
> Fix special messages not getting fetched on incoming messages

- CHANGELOG.md
- scss/message/_message.scss
- src/renderer/components/message/Message.tsx
Fixes https://github.com/deltachat/deltachat-desktop/issues/2610
> Fix div is not allowed to be descendant of p

- CHANGELOG.md
- src/renderer/components/message/MessageList.tsx
- src/renderer/stores/chat.ts
1. if we are both close to top and bottom because theres only little messages
2. also setMessageIds if we cannot append messages (hole detected)
> Fix loading more messages

- CHANGELOG.md
- src/renderer/components/chat/ChatList.tsx
> fix chatlist jumps to top after archiving #2463

- .github/mergeable.yml
- scss/manifest.scss
> try fix mergable check to work also on scss folder

- CHANGELOG.md
- src/main/unread-badge.ts
& enable unread badge counter on windows
fixes #2452
> fix tray icon unread indicator on windows

- scss/dialogs/_view_profile.scss
Added a 1/4 rem margin top to address in profile view to separate it from contact name
> fix no margin between name and address #2665

- CHANGELOG.md
- src/renderer/components/chat/ChatList.tsx
> fix random search result position

- CHANGELOG.md
- src/main/deltachat/webxdc.ts
- static/webxdc-preload.js
- static/webxdc.d.ts
closes #2584
needs the a new core release
> update webxdc api

- src/main/index.ts
- src/main/ipc.ts
basically call stopIO and wait half a second until shutting down the logger.﻿
> attempt to solve shutdown crash (see #2285)

- CHANGELOG.md
- src/renderer/components/attachment/mediaAttachment.tsx
- src/renderer/components/dialogs/FullscreenMedia.tsx
- src/renderer/components/helpers/ChatMethods.ts
- src/renderer/components/message/MessageMarkdown.tsx
- src/renderer/components/screens/MainScreen.tsx
- src/renderer/global.d.ts
- src/renderer/stores/chat.ts
- move view to chatstore & jump to msg in gallery fix #2592 closes #2619 closes #2618 closes #2698
- add show in chat to fullscreenmedia view
> feat jump to message from gallery

- .github/workflows/test.yml
- scss/main_screen/_navbar_wrapper.scss
- scss/message/_message.scss
- src/renderer/components/ThreeDotMenu.tsx
- src/renderer/components/attachment/menuAttachment.tsx
- src/renderer/components/screens/MainScreen.tsx
- test/testcafe/helpers.js
- test/testcafe/messagelist_tests.ts
- test/testcafe/test.js
e2e tests are working on ubuntu now at least
> Fix e2e tests settings

- CHANGELOG.md
- scss/message/_message.scss
- src/main/deltachat/messagelist.ts
- src/renderer/components/message/Message.tsx
- src/shared/shared-types.d.ts
> add images to quotes

- CHANGELOG.md
- scss/message/_message.scss
> Changed metadata's text color to white for media messages

- src/renderer/components/dialogs/Settings-ExperimentalFeatures.tsx
Very basic right now without logos or anything. But maybe nice to add now and polish later?
> Added systemli and Autistici as videochat providers

- CHANGELOG.md
- _locales/_untranslated_en.json
- package-lock.json
- scss/gallery/_media-attachment.scss
- scss/message/_message.scss
- src/main/deltachat/chat.ts
- src/renderer/components/Gallery.tsx
- src/renderer/components/attachment/mediaAttachment.tsx
- src/renderer/components/message/Message.tsx
- themes/_themebase.scss
- add Webxdc tab to gallery closes #2696 (missing .xdc files in Documents tab)
- fix unexpected click behavior in gallery/document view closes #2626
- fix prev/next media had seperate list for images and gifs
- fixed height for webxdc icons in messages
- better empty gallery tab messages
- fix eslint complaining
- fix formatting
> webxdc in gallery and some gallery fixes

- CHANGELOG.md
- src/main/deltachat/controller.ts
Fixes https://github.com/deltachat/deltachat-desktop/issues/2644
> Bring back getProviderInfo

- CHANGELOG.md
- src/main/deltachat/login.ts
closes https://github.com/deltachat/deltachat-desktop/issues/2735
> fix stock translations set too late (after I/0 is started)

- CHANGELOG.md
- src/main/deltachat/webxdc.ts
- src/renderer/components/attachment/mediaAttachment.tsx
- src/renderer/components/message/Message.tsx
- src/shared/util.ts
> support webxdc document names

- CHANGELOG.md
- src/renderer/components/Sidebar.tsx
> Added archived chats link

- src/renderer/components/dialogs/ViewProfile.tsx
For enhancement #2573 (closes #2573)
I'm having a problem with the timestamps. I'm getting dates from 1970. 
This is how it looks at the moment
Any suggestions?
> Added last seen to profile view

- CHANGELOG.md
- src/renderer/components/chat/ChatList.tsx
> Hide new contact button if a contact already exists

- scss/misc/_keyboard_hint_box.scss
- src/renderer/components/KeyboardShortcutHint.tsx
- src/renderer/components/dialogs/KeybindingCheatSheet.tsx
> and improve keybings help dialog layout remove the headings and fix layout

- CHANGELOG.md
- src/main/menu.ts
- src/renderer/ScreenController.tsx
> add open keybindings to to menu

- CHANGELOG.md
- _locales/_untranslated_en.json
- src/main/deltachat/webxdc.ts
- static/webxdc-preload.js
closes #2755
not yet on mac, though
> custom titlebar menu for webxdc

- CHANGELOG.md
- images/icons/plus.svg
- scss/chat/_chat-list-item.scss
- src/renderer/components/chat/ChatList.tsx
- themes/_themebase.scss
- themes/dark.scss
- themes/dark_amoled.scss
- themes/darkpurple.scss
- themes/dev_rocket.scss
- themes/light.scss
- themes/minimal.scss
> Add floating action button to start a new chat

- CHANGELOG.md
- src/renderer/components/Gallery.tsx
> rename the gallery tab "documents" to "files"

- bin/find_delta_remote.js
```
- ./components/dialogs/MessageDetail.tsx [2]
- ./components/dialogs/FullscreenMedia.tsx [1]
- ./components/dialogs/ChatAuditLogDialog.tsx [2]
- ./components/map/MapComponent.tsx [1]
- ./components/helpers/ChatMethods.ts [1]
- ./stores/chat.ts [10]
- ./components/dialogs/CreateChat.tsx [1]
- ./components/chat/ChatList.tsx [1]
- ./components/contact/ContactList.tsx [1]
- ./components/helpers/OpenQrUrl.tsx [2]
- ./components/helpers/ChatMethods.ts [1]
- ./components/map/MapComponent.tsx [1]
- ./stores/settings.ts [2]
- ./components/dialogs/ViewProfile.tsx [1]
- ./components/Sidebar.tsx [1]
- ./components/helpers/ChatMethods.ts [1]
- ./components/helpers/OpenQrUrl.tsx [1]
- ./components/message/messageFunctions.ts [1]
- ./components/message/MessageMarkdown.tsx [2]
- …
```
> Add script to count backend method usage

- CHANGELOG.md
- src/renderer/runtime.ts
> open mailto links in messages always in deltachat

- CHANGELOG.md
- src/renderer/components/Sidebar.tsx
- fix escape key let sidebar flimmer shortly upon startup
- fix double open settings crash fixes #2824
> fix small sidebar bugs

- CHANGELOG.md
- scss/_sidebar.scss
- src/renderer/components/Sidebar.tsx
> add connectivity status in sidebar/hamburger menu fixes #2819

- CHANGELOG.md
- _locales/_untranslated_en.json
- src/renderer/components/dialogs/CreateChat.tsx
> add warning that broadcast lists are not encrypted

- src/renderer/ScreenController.tsx
- src/renderer/backend.ts
- src/renderer/components/LoginForm.tsx
- src/renderer/components/Sidebar.tsx
- src/renderer/components/chat/ChatList.tsx
- src/renderer/components/chat/ChatListContextMenu.tsx
- src/renderer/components/chat/ChatListHelpers.tsx
- src/renderer/components/chat/ChatListItem.tsx
- src/renderer/components/contact/ContactList.tsx
- src/renderer/components/dialogs/About.tsx
- src/renderer/components/dialogs/EncryptionInfo.tsx
- src/renderer/components/dialogs/EnterAutocryptSetupMessage.tsx
- src/renderer/components/dialogs/QrCode.tsx
- src/renderer/components/dialogs/Settings-Account.tsx
- src/renderer/components/dialogs/Settings-Encryption.tsx
- src/renderer/components/helpers/ChatMethods.ts
- src/renderer/components/helpers/OpenQrUrl.tsx
- src/renderer/components/screens/AccountListScreen.tsx
- src/renderer/components/screens/WelcomeScreen.tsx
- src/renderer/experimental.ts
- src/renderer/stores/chat.ts
- src/renderer/stores/settings.ts
- Rename BackendRemote to DeltaChat
- Add Backend export as shortcut for DeltaChat.rpc
- Rename backend-com.ts to backend.ts
- Move selectedAccountId to backend.ts
- Use selectedAccountId() and get rid of manual null/undefined checks where possible
> [jsonrpc] Clean up backend-com.ts

- bin/find-delta-remote.js
- bin/jsonrpc-portage-status.js
Example output on use-json-rpc branch:
```
$ node ./bin/find-delta-remote.js 
- ./components/dialogs/MessageDetail.tsx [2]
- ./components/dialogs/FullscreenMedia.tsx [1]
- ./components/dialogs/ChatAuditLogDialog.tsx [2]
- ./components/helpers/ChatMethods.ts [1]
- ./components/map/MapComponent.tsx [1]
- ./stores/chat.ts [10]
- ./components/dialogs/CreateChat.tsx [1]
- ./components/chat/ChatList.tsx [1]
- ./components/contact/ContactList.tsx [1]
- ./components/helpers/OpenQrUrl.tsx [2]
- ./components/map/MapComponent.tsx [1]
- ./components/helpers/ChatMethods.ts [1]
- ./stores/settings.ts [2]
- ./components/dialogs/ViewProfile.tsx [1]
- ./components/Sidebar.tsx [1]
- ./components/helpers/ChatMethods.ts [1]
- ./components/helpers/OpenQrUrl.tsx [1]
- ./components/message/MessageMarkdown.tsx …
```
> Add ported section with percentage to find-delta-remote script

- CHANGELOG.md
- package-lock.json
- package.json
> update deltachat-node and prepare 1.32.1

- CHANGELOG.md
- src/main/deltachat/webxdc.ts
closes #2630
should work, did not test though
> clear webxdc browser data on webxdc instance deletion

- src/renderer/components/Avatar.tsx
- src/renderer/components/dialogs/Edit-Group-Image.tsx
- src/renderer/components/dialogs/FullscreenMedia.tsx
> fix fullscreen avatar view

- CHANGELOG.md
- src/renderer/components/dialogs/QrCode.tsx
> fix low resolution of copy qrcode image

- CHANGELOG.md
- scss/message/_message.scss
> fix quote linebreaks

- CHANGELOG.md
- _locales/_untranslated_en.json
- src/renderer/components/ThreeDotMenu.tsx
- src/renderer/components/helpers/ChatMethods.ts
> add button to clear chat history (delete all messages of a chat)

- docs/UPDATE_CORE.md
- package-lock.json
- package.json
- src/renderer/backend-com.ts
- src/renderer/components/Avatar.tsx
- src/renderer/components/dialogs/Edit-Group-Image.tsx
- src/renderer/components/helpers/OpenQrUrl.tsx
- prepare update to core 1.96
- add --access=public to npm publish command
- update core to 1.96.0
> update core to 1.96

- src/main/deltachat/chat.ts
- src/renderer/components/dialogs/FullscreenMedia.tsx
- src/renderer/delta-remote.ts
needs core with https://github.com/deltachat/deltachat-core-rust/pull/3610
> use jsonrpc for next media

- src/renderer/components/message/MessageList.tsx
- src/renderer/components/message/MessageWrapper.tsx
> fix mark messages as read on window focus

- CHANGELOG.md
- _locales/_untranslated_en.json
- scss/chat/_chat-list.scss
- src/renderer/components/ThreeDotMenu.tsx
- src/renderer/components/chat/ChatList.tsx
- src/renderer/components/message/MessageMarkdown.tsx
- src/renderer/components/screens/MainScreen.tsx
- src/renderer/global.d.ts
> add feature "search in chat"

- src/renderer/components/message/MessageList.tsx
Fixes https://github.com/deltachat/deltachat-desktop/issues/2928
> Fix MessageListInner using old onScroll callback

- scss/message/_message-list.scss
- themes/_themebase.scss
var(--jumpDownButtonIconColor)
> Add var(--jumpDownButtonBackgroundColor) and

- scss/message/_message-list.scss
Fixes https://github.com/deltachat/deltachat-desktop/issues/2936
> Fix jump down button over composer

- src/renderer/components/dialogs/Settings-Profile.tsx
- src/renderer/components/message/MessageList.tsx
- src/renderer/stores/chat.ts
Fixes https://github.com/deltachat/deltachat-desktop/issues/2932
> Fix scrollTo being stuck

- CHANGELOG.md
- scss/message/_message.scss
- src/renderer/components/message/Message.tsx
needs a core with https://github.com/deltachat/deltachat-core-rust/pull/3651 merged
> show webxdc icon in quote

- CHANGELOG.md
- src/renderer/components/dialogs/ChatAuditLogDialog.tsx
> fix chat audit log

- CHANGELOG.md
- src/renderer/backend-com.ts
- src/renderer/components/composer/Composer.tsx
> fix contact requests button to run block function and show right label (Group: delete, DM: block)

- src/renderer/components/message/MessageList.tsx
- src/renderer/stores/chat.ts
- src/renderer/stores/messagelist.ts
reduces code complexity
fixes #2974
should also fix #2973, though I'm not sure how to test/reproduce that one
> remove the message pages abstraction

- CHANGELOG.md
- src/renderer/components/helpers/ChatMethods.ts
- src/renderer/components/map/MapComponent.tsx
- src/renderer/components/message/MessageList.tsx
- src/renderer/components/message/MessageListAndComposer.tsx
- src/renderer/global.d.ts
- src/renderer/stores/chat.ts
- src/renderer/stores/messagelist.ts
- remove delete message from chatStore
- remove sendMessage from chatStore
- fix last commit
- jump down to the message that was just sent
those two functions don't need to be in the chatstore
> remove send and delete from chatstore

- src/renderer/system-integration/notifications.ts
looks like the mute check being async turned into a race condition.
> fix notification delay

- CHANGELOG.md
- package-lock.json
- package.json
- src/renderer/deviceMessages.ts
- preparations for 1.33.3 - bump version - add version heading to changelog
- add device message for 1.33.1
> prepare for 1.33.1

- CHANGELOG.md
- src/renderer/stores/chat.ts
> fix jump to message from gallery

- CHANGELOG.md
- src/renderer/deviceMessages.ts
> fix device message

- CHANGELOG.md
- scss/_icons.scss
- scss/contact/_contact.scss
- scss/main_screen/_main_screen.scss
- scss/misc/_avatar.scss
- src/renderer/components/Avatar.tsx
- src/renderer/components/VerifiedIcon.tsx
- src/renderer/components/contact/Contact.tsx
- src/renderer/components/dialogs/CreateChat.tsx
- src/renderer/components/dialogs/Edit-Group-Image.tsx
- src/renderer/components/dialogs/MessageListProfile.tsx
- src/renderer/components/dialogs/ViewGroup.tsx
- src/renderer/components/dialogs/ViewProfile.tsx
- src/renderer/components/screens/MainScreen.tsx
> move all verified icons to the end of the name

- CHANGELOG.md
- src/renderer/stores/chat.ts
- fix update on changing ephemeral timer
- update if dm contact changed
- update changelog
fixes #3046
> fix chat title in navbar did not update correctly when it should change (disappearing messages & recently seen indicator)

- src/renderer/components/chat/ChatListItem.tsx
related to https://github.com/deltachat/deltachat-desktop/issues/2961
> log chatlistitem error and show whole error in tooltip on hover

- CHANGELOG.md
- scss/login/_login.scss
- src/main/application-constants.ts
* also hide logo on welcome screen on scale 1.2x
closes #3040
> Change default height of a welcome screen

- CHANGELOG.md
- package-lock.json
- package.json
- src/main/ipc.ts
- src/renderer/runtime.ts
- static/main.html
- static/preload.js
to make this work, we also moved some electron api invocations from preload script to main process
> upgrade electron to version `22`

- CHANGELOG.md
- src/main/deltachat/webxdc.ts
- static/webxdc-preload.js
- static/webxdc_wrapper.html
regression: mailto links don't work anymore, also we can't catch them properly anyway until https://github.com/electron/electron/pull/34418 is implemented
See also:
https://github.com/deltachat/deltachat-ios/pull/1797
https://github.com/deltachat/deltachat-android/pull/2458
> add progressbar to webxdc loading

- CHANGELOG.md
- src/renderer/components/message/Message.tsx
> add reply privately in mailinglists to context menu

- CHANGELOG.md
- package-lock.json
- package.json
- src/renderer/components/dialogs/ChatAuditLogDialog.tsx
- src/renderer/components/helpers/ChatMethods.ts
- src/renderer/stores/messagelist.ts
everything that depends on the new upcomming core release 108.
get_chat_msgs api had a breaking change, this pr updates desktop to that change so it works again 
now with this branch
> WIP: use this branch to try core master

- src/renderer/components/ConnectivityToast.tsx
- src/renderer/components/chat/ChatList.tsx
- src/renderer/components/chat/ChatListContextMenu.tsx
- src/renderer/components/chat/ChatListItemRow.tsx
- src/renderer/components/dialogs/DeltaDialog.tsx
- src/renderer/components/helpers/ChatMethods.ts
- resolve some `todo` types
- represent "undefined" state in TS type of virtual list caches
> improve typescript typing

- CHANGELOG.md
- images/icons/devices.svg
- scss/dialogs/multidevice/send_backup.scss
- scss/manifest.scss
- scss/misc/_delta-buttons.scss
- src/renderer/components/dialogs/DeltaDialog.tsx
- src/renderer/components/dialogs/Settings-Backup.tsx
- src/renderer/components/dialogs/Settings.tsx
- src/renderer/components/dialogs/setup_multi_device/ReceiveBackup.tsx
- src/renderer/components/dialogs/setup_multi_device/SendBackup.tsx
- src/renderer/components/helpers/OpenQrUrl.tsx
- src/renderer/components/screens/WelcomeScreen.tsx
- src/renderer/stockStrings.ts
- themes/_themebase.scss
depends on new core with these prs merged:
- https://github.com/deltachat/deltachat-core-rust/pull/4007
- https://github.com/deltachat/deltachat-core-rust/pull/4198
> networked multidevice setup

- CHANGELOG.md
- src/renderer/backend-com.ts
- src/renderer/components/screens/MainScreen.tsx
- src/renderer/stores/settings.ts
> fix #3154 also fix the bug of last chat of old account still visible in new account.

- CHANGELOG.md
- src/main/deltachat/controller.ts
- src/main/deltachat/splitout.ts
- src/main/deltachat/webxdc.ts
- src/renderer/backend-com.ts
- static/webxdc-preload.js
one further step in the direction of allowing us to switch to stdio jsonrpc server binary instead of the 
node-bindings.
depends on ﻿https://github.com/deltachat/deltachat-core-rust/pull/4070
> backend use jsonrpc for webxdc

- bin/build-shared-convert-translations.mjs
> fix escape in `fr` language

- CHANGELOG.md
- scss/message/_message.scss
- src/renderer/components/message/Message.tsx
closes #3146 (I posted screenshots in the issue)
> add message metadata to video chat invitiation (encryption and send status and date-time)

- CHANGELOG.md
- src/renderer/components/dialogs/setup_multi_device/SendBackup.tsx
> improve confirm abort dialog for setup second device

- src/main/deltachat/webxdc.ts
Follow-up to a9e5242a
Why "refactor"? Because it only adds CSP to the 404 response, but it doesn't currently affect it because requesting a non-existent file results in a network error, not a valid 404 response
Also now CSP for `webxdc.js` depends on `internet_access` as well.
> refactor: apply CSP to all webxdc responses

- CHANGELOG.md
- src/main/windows/html_email.ts
> fix "Always Load Remote Images" should be hidden for contact requests

- CHANGELOG.md
- src/main/ipc.ts
- src/main/windows/html_email.ts
- src/renderer/components/message/messageFunctions.ts
- src/renderer/runtime.ts
- static/electron_html_email_view/electron_html_email_view.css
- static/electron_html_email_view/electron_html_email_view.html
- static/electron_html_email_view/electron_html_email_view.js
> add received timestamp to html email view

- src/main/index.ts
> refactor: add a comment about `--host-resolver-rules`

- CHANGELOG.md
- src/main/windows/main.ts
- src/renderer/components/dialogs/QrCode.tsx
fix race on image loading and a permission issue
> bugfix copy qrcode to clipboard

- CHANGELOG.md
- scss/message/_message.scss
> webxdc message: icon make cursor a pointer

- src/main/ipc.ts
- src/main/windows/html_email.ts
- src/renderer/components/message/messageFunctions.ts
- src/renderer/runtime.ts
depends on https://github.com/deltachat/deltachat-core-rust/commit/37503dd3e838bfcdcfd784dce705b169700e0066
> use core for load remote content in html emails

- src/main/deltachat/controller.ts
- src/renderer/backend-com.ts
Depends on https://github.com/deltachat/deltachat-core-rust/pull/4347
Related Android PR is at https://github.com/deltachat/deltachat-android/pull/2479
also depends on this fix in core: https://github.com/deltachat/deltachat-core-rust/pull/4373
> adjust desktop for event polling, needs core v1.114.0

- CHANGELOG.md
- src/main/deltachat/controller.ts
- src/renderer/backend-com.ts
- src/renderer/components/chat/ChatList.tsx
- src/renderer/components/chat/ChatListHelpers.tsx
- src/renderer/components/chat/ChatListItemRow.tsx
- src/renderer/components/dialogs/ForwardMessage.tsx
- src/renderer/components/dialogs/MailtoDialog.tsx
- src/renderer/components/dialogs/ViewProfile.tsx
depends on new core with https://github.com/deltachat/deltachat-core-rust/pull/3931
> remove message id from chatlist item

- CHANGELOG.md
- scss/chat/_chat-list-item.scss
- src/renderer/components/Avatar.tsx
- src/renderer/components/chat/ChatList.tsx
- src/renderer/components/chat/ChatListItem.tsx
- themes/_themebase.scss
and also fix show verification state of chat in chatlist
depends on core pr: https://github.com/deltachat/deltachat-core-rust/pull/4374
> prettier message search results

- scss/chat/_chat-list-item.scss
- src/renderer/components/chat/ChatListItem.tsx
Also added xdc icon preview
needs core with pr merged
https://github.com/deltachat/deltachat-core-rust/pull/4311
> introducing chatlist item thumbnail image

- README.md
- docs/TROUBLESHOOTING.md
- add doc links to readme
- remove broken badges
- move openssl troubleshooting into the docs file for troubleshooting
- Fix heading level
- Add info about windows
- Hide manual AUR instructions in details
> improve readme

- docs/DEVELOPMENT.md
Notes:
- mostly includes relatively surface-level changes, such as:
- grammar improvements
- syntax improvements
- proper capitalization/spelling of project names
- incorrect/outdated links
- attempted to avoid the following kinds of changes:
- anything that would change heading links. this is to preserve urls that may have been shared in the past. if this is not of great concern, can add a couple of more edits to this PR
- potential things to add to these docs that aren't yet implemented:
- an early section about installing the proper development environment (e.g. node, npm, etc)
> add various fixes to development readme

- CHANGELOG.md
- static/webxdc-preload.js
- static/webxdc.d.ts
> webxdc: add `importFiles` api

- CHANGELOG.md
- package-lock.json
- package.json
- src/renderer/deviceMessages.ts
update deltachat-node and deltachat/jsonrpc-client to `v1.116.0`
closes #3246
> prepare 1.37.0 and update core

- CHANGELOG.md
- src/renderer/components/dialogs/WebxdcSendToChatDialog.tsx
> WebxdcSaveToChatDialog: filename in title

- CHANGELOG.md
- src/renderer/ScreenController.tsx
- src/renderer/components/composer/ComposerMessageInput.tsx
- src/renderer/components/dialogs/DialogController.tsx
- src/renderer/components/message/MessageListAndComposer.tsx
- src/renderer/global.d.ts
> Make input text in CreateChat dialogue always focused

- CHANGELOG.md
- src/renderer/components/dialogs/FullscreenMedia.tsx
> Esc always closes Fullscreen media screen. fix #2919

- CHANGELOG.md
- src/main/log-handler.ts
- src/shared/logger.ts
> Fix problem of crash when the app can't write to stdout

- CHANGELOG.md
- src/main/windows/main.ts
> solve problem of exceptions on quit. fix #2201

- CHANGELOG.md
- static/help/it/help.html
- static/help/nl/help.html
- static/help/pl/help.html
- static/help/sq/help.html
- static/help/uk/help.html
- static/help/zh_CN/help.html
that was missing at https://github.com/deltachat/deltachat-desktop/pull/3338
> update offline help

- CHANGELOG.md
- src/main/ipc.ts
- src/renderer/components/message/messageFunctions.ts
- src/renderer/runtime.ts
> use filename property for saving files

- CHANGELOG.md
- package-lock.json
- package.json
- src/renderer/deviceMessages.ts
- prepare 1.39.0
- add device message
> prepare 1.39.0

- CHANGELOG.md
- _locales/_untranslated_en.json
- src/renderer/components/dialogs/setup_multi_device/ReceiveBackup.tsx
> Add translation for receive_backup during multi device setup

- CHANGELOG.md
- package-lock.json
- package.json
- src/renderer/deviceMessages.ts
- ensure device message ordering
- prepare 1.40.0
> prepare 1.40

- CHANGELOG.md
- src/renderer/components/chat/ChatList.tsx
- src/renderer/components/contact/ContactList.tsx
- src/renderer/components/dialogs/CreateChat.tsx
> fix contact creation in new chat dialog not working with leading or trailing spaces.

- CHANGELOG.md
- src/renderer/components/dialogs/Settings-ExperimentalFeatures.tsx
because they added a sign-in requirement
closes #3366
> remove jitsi as a default Video Chat instance

- CHANGELOG.md
- scss/chat/_chat-list-item.scss
- src/renderer/ScreenController.tsx
- src/renderer/components/ContextMenu.tsx
- src/renderer/components/chat/ChatList.tsx
- src/renderer/components/chat/ChatListContextMenu.tsx
- src/renderer/components/chat/ChatListItem.tsx
- src/renderer/components/chat/ChatListItemRow.tsx
- src/renderer/contexts.ts
fixes #3238 
Edit: took about an hour :)
> make a chat list item look hovered when its context menu is open

- CHANGELOG.md
- src/renderer/components/contact/ContactList.tsx
- src/renderer/components/contact/ContactListItem.tsx
- src/renderer/components/dialogs/CreateChat.tsx
> option to delete contacts in list when creating a new chat

- CHANGELOG.md
- package-lock.json
- package.json
- update deltachat-node and deltachat/jsonrpc-client to `v1.121.0`
- prepare 1.40.2
> prepare 1.40.2

- CHANGELOG.md
- src/renderer/components/dialogs/Settings-ManageKeys.tsx
> fix: import key from file instead of folder

- CHANGELOG.md
- src/main/deltachat/webxdc.ts
- src/renderer/runtime.ts
- src/renderer/system-integration/webxdc.ts
> fix webxdc title not updated in document title changes

- CHANGELOG.md
- src/main/deltachat/webxdc.ts
- src/main/windows/help.ts
- src/main/windows/html_email.ts
> open help, webxdc and html email windows with always on top flag, if main window has that flag.

- CHANGELOG.md
- package-lock.json
- package.json
- src/main/deltachat/controller.ts
- src/renderer/App.tsx
- src/renderer/ScreenController.tsx
- src/renderer/backend-com.ts
- src/renderer/components/Gallery.tsx
- src/renderer/components/chat/ChatList.tsx
- src/renderer/components/chat/ChatListContextMenu.tsx
- src/renderer/components/chat/ChatListItem.tsx
- src/renderer/components/chat/ChatListItemRow.tsx
- src/renderer/components/dialogs/ChatAuditLogDialog.tsx
- src/renderer/components/dialogs/EncryptionInfo.tsx
- src/renderer/components/dialogs/MuteChat.tsx
- src/renderer/components/helpers/ChatMethods.ts
- src/renderer/components/helpers/OpenQrUrl.tsx
- src/renderer/components/message/MessageList.tsx
- src/renderer/components/screens/AccountListScreen.tsx
- src/renderer/components/screens/WelcomeScreen.tsx
- src/renderer/stockStrings.ts
- src/renderer/stores/locations.ts
- src/renderer/stores/messagelist.ts
- adapt to addition of 'writable' property
- adapt to ne enum variant key: `kind`
closes #3341
> update to core 127

- CHANGELOG.md
- package-lock.json
- package.json
- src/renderer/components/composer/Composer.tsx
- src/renderer/components/composer/menuAttachment.tsx
- src/renderer/components/dialogs/MailtoDialog.tsx
- src/renderer/components/dialogs/ProtectionStatusDialog.tsx
- src/renderer/components/dialogs/Settings-ChatsAndMedia.tsx
- src/renderer/components/dialogs/Settings-OutgoingMediaQuality.tsx
- src/renderer/components/dialogs/WebxdcSendToChatDialog.tsx
- src/renderer/components/helpers/ChatMethods.ts
- src/renderer/components/map/MapComponent.tsx
- src/renderer/components/message/MessageListAndComposer.tsx
- src/renderer/components/message/MessageMarkdown.tsx
- src/renderer/components/message/messageFunctions.ts
- src/renderer/experimental.ts
- src/renderer/stores/settings.ts
- src/shared/constants.ts
- src/shared/shared-types.d.ts
rename attach media button to "image", allow only images and compress them on sending.
fixes https://github.com/deltachat/deltachat-desktop/issues/2838
fixes https://github.com/deltachat/deltachat-desktop/issues/2869
depends on https://github.com/deltachat/deltachat-core-rust/pull/4888
also use the new send message core function.
> send compressed images

- src/renderer/components/dialogs/ViewProfile.tsx
> show verifier name and address

- CHANGELOG.md
- scss/dialogs/_group-styles.scss
- src/renderer/components/dialogs/CreateChat.tsx
- src/renderer/components/dialogs/MessageListProfile.tsx
> fix #3440 (ask for broadcast name)

- CHANGELOG.md
- src/main/index.ts
> handle mailto: and openpgp4fpr: links in webxdc

- CHANGELOG.md
- src/renderer/components/chat/ChatListContextMenu.tsx
- src/renderer/components/dialogs/Settings-Backup.tsx
- src/renderer/components/dialogs/ViewProfile.tsx
- src/renderer/components/helpers/ChatMethods.ts
- src/renderer/components/message/Message.tsx
- src/renderer/components/screens/AccountListScreen.tsx
this pr rewords some strings and slightly shifts menu items.
see commit messages for details.
> reword some strings

- CHANGELOG.md
- src/renderer/components/dialogs/Settings-DownloadOnDemand.tsx
> remove 40KiB download on demand option

- .eslintrc.js
- package-lock.json
- package.json
- src/main/deltachat/controller.ts
https://eslint.org/blog/2022/07/interesting-bugs-caught-by-no-constant-binary-expression/
> Upgrade eslint and enable 'no-constant-binary-expression' lint

- CHANGELOG.md
- scss/dialogs/_view_profile.scss
> fix status text overflow in ViewProfile

- CHANGELOG.md
- src/main/ipc.ts
- src/main/windows/help.ts
- src/renderer/components/dialogs/ProtectionStatusDialog.tsx
- src/renderer/runtime.ts
> use local help for guaranteed end-to-end encryption more info

- src/main/ipc.ts
- src/renderer/deviceMessages.ts
- src/shared/shared-types.d.ts
informing them that they got the testrelease early.
> add device message for windows store release

- CHANGELOG.md
- src/renderer/components/Gallery.tsx
> fix: files search not case-insensitive

- CHANGELOG.md
- src/renderer/components/conversations/emoji.ts
> fix: bug in emoji detection for jumbomoji

- src/main/notifications.ts
> add more debug logging when clearing notifications

- CHANGELOG.md
- src/renderer/components/message/Message.tsx
Closes https://github.com/deltachat/deltachat-desktop/issues/3540
> Use `dc_chat_can_send` to show or hide reply functionality

- CHANGELOG.md
- src/renderer/components/LoginForm.tsx
- src/renderer/components/screens/MainScreen.tsx
Closes https://github.com/deltachat/deltachat-desktop/issues/3499
> Select device message chat automatically to welcome first users

- src/renderer/stores/messagelist.ts
- src/renderer/stores/store.ts
that we don't need because we don't debug it right now
closes #3542
> comment out verbose logging of store

- CHANGELOG.md
- src/renderer/components/composer/Composer.tsx
> focus after loading draft fixes 2 issues

- CHANGELOG.md
- src/main/notifications.ts
> fix uncaught exception

- CHANGELOG.md
- src/renderer/components/Gallery.tsx
- src/renderer/components/screens/MainScreen.tsx
closes #3523
https://github.com/deltachat/deltachat-desktop/assets/18725968/e16b2616-95fe-4c74-8cbd-fe4646b68e51
> Disable three-dot-menu when not applicable (map, other gallery tabs)

- CHANGELOG.md
- images/icons/navigate_next.svg
- scss/misc/_context_menu.scss
- src/renderer/components/ContextMenu.tsx
- src/renderer/components/ThreeDotMenu.tsx
- src/renderer/components/chat/ChatListContextMenu.tsx
Tries to address #3116 
- ContextMenu now handles sublevels
- ContextMenuItem has subitems
- New icon for ContextMenuItem with subitems
closes #3116
> Introduce sub-levels & make "mute chat" options configurable in context menu

- CHANGELOG.md
- src/renderer/components/dialogs/CreateChat.tsx
> add button to new chat to open existing qr scan dialog

- CHANGELOG.md
- scss/chat/_chat-list-item.scss
- src/renderer/components/chat/ChatListItem.tsx
as suggested in https://support.delta.chat/t/three-small-changes-to-make-delta-chat-better/2886/2
> move pin icon in chatlist after date

- src/renderer/stockStrings.ts
the strings need to be pulled successfully in #3652 before this can be merged
counterpart of https://github.com/deltachat/deltachat-android/pull/2938 and https://github.com/deltachat/deltachat-ios/pull/2064; the image will probably also be updated in core at some point
> update welcome message

- CHANGELOG.md
- src/renderer/components/dialogs/QrCode.tsx
- src/renderer/utils/invite.ts
Closes: https://github.com/deltachat/deltachat-desktop/issues/3647
> Copy invite link to clipboard instead of only QR code data

- CHANGELOG.md
- package-lock.json
- package.json
Master CI is failing because I merged #3639 before doing this (https://github.com/deltachat/deltachat-desktop/pull/3639#issuecomment-1926416468). Thus merging this pr will fix CI on master.
> Update `deltachat-node` and `deltachat/jsonrpc-client` to `v1.134.0`

- docs/THEMES.md
because there were questions raised on the forum: https://support.delta.chat/t/how-do-i-create-a-custom-theme/2909/2
> a bit more info on custom theme creation

- scss/main_screen/_navbar_wrapper.scss
- src/main/windows/main.ts
- src/renderer/components/SearchInput/SearchInputButton.tsx
- src/renderer/components/screens/AccountListSidebar/AccountListSidebar.tsx
- src/renderer/components/screens/AccountListSidebar/styles.module.scss
- src/renderer/components/screens/MainScreen.tsx
other apps like discord do this, looks quite nice
But of course might bring new bugs with it.
> Account Sidebar: No window titlebar on MacOS

- CHANGELOG.md
- src/main/ipc.ts
- src/renderer/components/dialogs/About.tsx
- src/shared/shared-types.d.ts
- add more versions to about dialog and update order of existing information.
> improve about dialog

- CHANGELOG.md
- src/renderer/components/screens/MainScreen.tsx
> Show search bar when searching chat in archived mode

- CHANGELOG.md
- package-lock.json
- package.json
Preparations for the upcoming DeltaChat Desktop test release `v1.43` ✨
> Prepare test release `v1.43`

- CHANGELOG.md
- src/main/windows/html_email.ts
> fix broken html email window (CSP got broken with the recent electron update)

- CHANGELOG.md
- scss/main_screen/_main_screen.scss
Closes https://github.com/deltachat/deltachat-desktop/issues/3688
> Make chat title & subtitle unselectable to prevent unusual behaviour

- CHANGELOG.md
- src/renderer/components/Settings/ManageKeys.tsx
> change export keys open directory confirm button label to "select"

- src/renderer/components/screens/AccountDeletionScreen/styles.module.scss
looks like this is the best fire image we have at the time.
> remove todo comment

- CHANGELOG.md
- _locales/_untranslated_en.json
- src/renderer/components/Settings/ExperimentalFeatures.tsx
> Change wording of "sync all" setting and make it appear disabled by default like the other experimental settings

- CHANGELOG.md
- src/renderer/components/LoginForm.tsx
- src/renderer/components/helpers/OpenQrUrl.tsx
> Fix bug where cancellation of configure led to an undefined state where it looked like the account was configured successfully, but it was not.

- CHANGELOG.md
- package-lock.json
- package.json
- Update `deltachat-node` and `deltachat/jsonrpc-client` to `v1.136.3`
- prepare 1.44.1
> prepare 1.44.1

- CHANGELOG.md
- src/renderer/components/ContactName/styles.module.scss
- src/renderer/components/dialogs/ChatAuditLogDialog.tsx
- src/renderer/components/dialogs/ReactionsDialog/styles.module.scss
- fix chat audit dialog was going out of viewport on smaller screens
- fix long names breaking layout of reactions dialog
> some small dialog fixes

- CHANGELOG.md
- src/renderer/components/ContextMenu.tsx
- src/renderer/global.d.ts
> perf: remove `passive: false` `wheel` listener

- CHANGELOG.md
- src/renderer/components/composer/Composer.tsx
> attempt to fix double sending

- CHANGELOG.md
- src/main/deltachat/webxdc.ts
- src/shared/shared-types.d.ts
> Save bounds on webxdc close

- CHANGELOG.md
- src/main/deltachat/webxdc.ts
- src/shared/shared-types.d.ts
follow up for #3755
documentation pr should also be merged after this is merged: https://github.com/deltachat/interface/pull/65
> use ui core config for persisting webxdc window bounds

- CHANGELOG.md
- scss/message/_message-list.scss
- src/renderer/components/message/MessageList.tsx
> perf: fix low FPS on chat scroll on some machines (again)

- CHANGELOG.md
- src/renderer/backend-com.ts
> Remove deleted chat id from ui settings

- CHANGELOG.md
- src/main/deltachat/webxdc.ts
- src/main/windows/help.ts
- src/main/windows/html_email.ts
> add keyboard shortcut to close child windows and add a custom menu to the child windows

- .gitignore
> ignore direnv files

- CHANGELOG.md
- src/renderer/components/ReactionsBar/ReactionsBar.tsx
- src/renderer/components/ReactionsBar/ReactionsBarContext.tsx
Closes: https://github.com/deltachat/deltachat-desktop/issues/3761
> Close reactions bar on emoji selection

- CHANGELOG.md
- src/renderer/components/composer/ComposerMessageInput.tsx
the problem was that composer input was stealing focus each time.
> Fix the problem of focus in create chat

- src/renderer/components/RuntimeAdapter.tsx
no changelog entry because it was introduced in this unreased version.
fixes #3820
> fix open about dialog via menu

- CHANGELOG.md
- src/renderer/components/LoginForm.tsx
- src/renderer/components/screens/AccountSetupScreen.tsx
- src/renderer/contexts/DialogContext.tsx
> Fix the bug in LoginForm making multiple open dialogs

- RELEASE.md
Thanks for accompanying me through these steps :)
> updating release docs after my first test release

- CHANGELOG.md
- src/renderer/components/screens/MainScreen.tsx
https://github.com/deltachat/deltachat-desktop/issues/3858#issuecomment-2131190083
> fix that map tab is highlighted when you are in the media/gallery tab

- CHANGELOG.md
- src/renderer/components/screens/WelcomeScreen/UserAgreement.tsx
closes #3860
also add pr number to translation pr in changelog
> adapt title of "Privacy Policy" link

- README.md
fixes the rem part of #3854
followup to #3885
> remove more building / dc node reference from readme

- CHANGELOG.md
- package-lock.json
- package.json
> prepare v1.45.2

- CHANGELOG.md
- src/main/deltachat/stdio_server.ts
> Show error to user if core process exits unexpectedly

- CHANGELOG.md
- src/renderer/components/ImageSelector/index.tsx
- src/renderer/components/dialogs/EditProfileDialog/ProfileImageSelector.tsx
- src/renderer/components/dialogs/EditProfileDialog/index.tsx
- src/renderer/components/dialogs/ViewGroup.tsx
- src/renderer/components/screens/WelcomeScreen/InstantOnboardingScreen.tsx
- fixes #3903
- adds cropper to group avatars, which is part of #3893
> fixes removing group avatars and adds cropper to group avatars

- CHANGELOG.md
- src/renderer/components/dialogs/ViewGroup.tsx
> Fix missing translation for broadcastlist name

- CHANGELOG.md
- build/afterPackHook.cjs
> fix: packaging: respect `NO_ASAR` env var in `afterPackHook`

- CHANGELOG.md
- src/renderer/components/dialogs/CreateChat/index.tsx
> fix image cropper is not started when creating a group

- CHANGELOG.md
- package-lock.json
- package.json
- src/renderer/deviceMessages.ts
- **Update `@deltachat/stdio-rpc-server` and `deltachat/jsonrpc-client` to `1.140.2`**
- **prepare 1.45.5**
> prepare 1.45.5

- CHANGELOG.md
- src/renderer/components/composer/Composer.tsx
- src/renderer/components/message/VCard.tsx
> add pretty preview to vcard draft

- CHANGELOG.md
- package-lock.json
- package.json
- src/renderer/deviceMessages.ts
- **fix old device message, add new device message**
- **change phrasing**
- **prepare 1.46.1**
> simon/prepare 1.46.1

- CHANGELOG.md
- src/renderer/components/screens/MainScreen.tsx
> comply with react hook rules

- CHANGELOG.md
After an accidental push to main
> docs: fix changelog referencing nonexistent MR

- CHANGELOG.md
- src/renderer/components/screens/MainScreen.tsx
> really hide 3dot menu when it is hidden

- CHANGELOG.md
- scss/message/_message.scss
> keep aspect ratio in quoted images

- CHANGELOG.md
- src/main/deltachat/webxdc.ts
- src/main/menu.ts
- src/main/windows/help.ts
- src/main/windows/html_email.ts
- src/main/windows/main.ts
This PR fixes #3988 
It also implements [the suggestion](https://github.com/deltachat/deltachat-desktop/issues/3988#issuecomment-2198590315) in the same thread.
> Fix the bug where File > Quit on the WebXDC window closes DC

- src/main/deltachat/stdio_server.ts
- src/renderer/components/KeyboardShortcutHint.tsx
`camelCase` is the standard in TS and in Desktop. Will merge upon the first approval
> Found some snake_case var names and converted them to camelCase counterparts

- CHANGELOG.md
- src/renderer/components/contact/ContactList.tsx
- src/renderer/components/dialogs/AddMember/AddMemberInnerDialog.tsx
- src/renderer/components/dialogs/CreateChat/index.tsx
- src/renderer/components/dialogs/WebxdcSendToChat/index.tsx
> perf: parallelize some async operations

- CHANGELOG.md
- package-lock.json
- package.json
> update core to 1.141.2

- CHANGELOG.md
The issue originally discovered here
https://github.com/deltachat/deltachat-desktop/pull/3994#discussion_r1661142333
> docs: fix some CHANGELOG links not working

- CHANGELOG.md
- _locales/_untranslated_en.json
- src/renderer/components/attachment/mediaAttachment.tsx
- src/renderer/components/dialogs/MessageDetail/MessageDetail.tsx
- src/renderer/components/dialogs/MessageDetail/ReadReceipts.tsx
- src/renderer/components/dialogs/MessageDetail/styles.module.scss
- src/renderer/components/message/messageFunctions.ts
- themes/_themebase.scss
ReadReceiptBox inspired by WhatsApp iOS
> Added UI for read receipts in message info dialog

- CHANGELOG.md
- scss/chat/_chat-list-item.scss
- src/renderer/components/chat/ChatListItem.tsx
- **Fixing distorted summaryPreviewImage**
> fix chatlist item preview icon distortion

- CHANGELOG.md
- src/main/windows/html_email.ts
> Fix empty space before HTML view content

- CHANGELOG.md
- src/renderer/hooks/useProcessQr.ts
This PR adds support for the new backup codes generated by the mobile app.
fixes #4073
> fix: Handle DCBACKUP2 QR codes (#4073)

- src/renderer/components/dialogs/AddMember/styles.module.scss
> Fix addMember bg

- CHANGELOG.md
- packages/target-electron/package.json
- packages/target-electron/src/deltachat/webxdc.ts
- pnpm-lock.yaml
> Update electron from `30.3.1` to `32.0.2`

- .github/workflows/build-preview.yml
Fixes https://github.com/deltachat/deltachat-desktop/issues/4135
Please verify that the new name is fine.
I have downloaded the artifact and it works.
> chore: fix Windows CI preview build

- CHANGELOG.md
- packages/frontend/src/components/Settings/ExperimentalFeatures.tsx
- packages/frontend/src/components/composer/Composer.tsx
- packages/frontend/src/keybindings.ts
Follow-up to cd80587ed7.
Telegram has this shortcut.
> feat: "Esc" to cancel reply (quote)

- CHANGELOG.md
- packages/frontend/src/components/chat/ChatList.tsx
- packages/frontend/src/components/helpers/PseudoListItem.tsx
Recommended review commit-by-commit
Follow-up to https://github.com/deltachat/deltachat-desktop/pull/4041
> Improve invite link chatlist item

- packages/shared/util.ts
To clarify this is not just about contacts, but also groups.
> refactor: add a docstring for `isInviteLink`

- CHANGELOG.md
- packages/frontend/src/components/dialogs/EncryptionInfo.tsx
Closes https://github.com/deltachat/deltachat-desktop/issues/4160
Tested ✅.
> fix: "Encryption Info" dialog newline wrapping

- CHANGELOG.md
- packages/frontend/src/components/AccountListSidebar/AccountListSidebar.tsx
> exit search when clicking on profile, when the selected profile is already the selected account

- CHANGELOG.md
- packages/frontend/src/components/QrReader/index.tsx
> trim whitepaces when reading from clipboard in qr code reader

- packages/frontend/src/stores/chat/chat_scheduler.ts
- packages/frontend/src/stores/messagelist.ts
As per https://github.com/deltachat/deltachat-desktop/pull/4145#discussion_r1780667160
> refactor: comment about scroll lock return false

- packages/frontend/src/components/chat/ChatList.tsx
- packages/frontend/src/components/chat/ChatListHelpers.tsx
- packages/frontend/src/components/dialogs/ForwardMessage/index.tsx
- packages/frontend/src/components/dialogs/MailtoDialog/index.tsx
- packages/frontend/src/components/dialogs/WebxdcSendToChat/index.tsx
Remove the unnecessary state from it, and don't return it.
> refactor: simplify useChatList

- docs/UPDATE_CORE.md
> docs: `pnpm fix:format` for UPDATE_CORE.md

- CHANGELOG.md
- packages/frontend/src/hooks/useOpenLinkSafely.ts
> fix: make open external link scheme case insensive

- packages/frontend/src/components/Callout/styles.module.scss
- packages/frontend/src/components/Dialog/styles.module.scss
Didn't write to CHANGELOG.md since it's a fix to an issue introduced by Blueprint removal.
- resolves #4215
> Fix callout overflow

- docs/THEMES.md
Commit a5c02433976909fe01a64f3049c96d0d101ae9d8 moved the location of `_themebase.scss`. This PR adjusts sources to changes.
> Update theme reference

- CHANGELOG.md
- packages/frontend/src/components/dialogs/ViewGroup.tsx
This is similar to https://github.com/deltachat/deltachat-desktop/pull/4253.
Likely introduced in 0e0d0b80d598802ebb972c8d6c05b593bd896f24.
> fix: horizontal scrollbar in "View Group"

- CHANGELOG.md
- packages/frontend/src/components/dialogs/EditAccountAndPasswordDialog.tsx
> change title of EditAccountAndPasswordDialog to make it clearer that it is about email account

- CHANGELOG.md
- packages/frontend/src/components/dialogs/MessageListProfile.tsx
The code is in line with other `modifyGroup` occurence in
`ViewGroup.tsx`.
For reference, here are some related commits:
- e2f9cdb915d59ac7d718de5eb60ecf779d8289a6
- 076fcc8db59e19d04db878e613beb71800fe05cb
> fix: removing mailing list avatar not working

- CHANGELOG.md
- packages/frontend/src/components/dialogs/EditAccountAndPasswordDialog.tsx
Follow-up to https://github.com/deltachat/deltachat-desktop/pull/4271
Closes https://github.com/deltachat/deltachat-desktop/issues/4182
> improvement: change button label

- CHANGELOG.md
- packages/frontend/src/components/Settings/Autodelete.tsx
and rename option "never" to "automatic" for chatmail.
closes #4113
> Limit options for "Delete Messages from Server" for chatmail accounts

- CHANGELOG.md
- pnpm-lock.yaml
- pnpm-workspace.yaml
> Update core v1.148.6

- CHANGELOG.md
- packages/frontend/scss/message/_message.scss
> Change sticker reply background to make name more readable

- CHANGELOG.md
- packages/frontend/src/components/Settings/Appearance.tsx
- packages/frontend/src/components/message/MessageListAndComposer.tsx
- packages/target-browser/runtime-browser/runtime.ts
- packages/target-browser/src/backendApi.ts
- packages/target-browser/src/index.ts
- **make removeTempFile request answer**
- **browser edition: make selecting chat background image work**
> Browser Edition: add support for chat background images

- CHANGELOG.md
- packages/frontend/src/components/Settings/Communication.tsx
- packages/frontend/src/components/Settings/ExperimentalFeatures.tsx
Closes https://github.com/deltachat/deltachat-desktop/issues/4293
> improvement: rearrange "realtime webxdc" setting

- packages/frontend/src/components/AccountListSidebar/AccountItem.tsx
- packages/frontend/src/components/AccountListSidebar/AccountListSidebar.tsx
- packages/frontend/src/components/chat/ChatListItem.tsx
- packages/frontend/src/contexts/RovingTabindex.tsx
It's harder to forget to set it this way.
> refactor: `useRovingTabindex`: expose `className`

- CHANGELOG.md
- packages/frontend/src/components/dialogs/CreateChat/index.tsx
- packages/frontend/src/components/helpers/PseudoListItem.tsx
This is based on https://github.com/deltachat/deltachat-desktop/pull/4361
Hide whitespace changes for easier review.
> improvement: arrow-key navigation in "New Chat"

- CHANGELOG.md
- packages/frontend/src/components/LoginForm.tsx
- packages/frontend/src/components/dialogs/QrCode.tsx
- packages/frontend/src/utils/invite.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
resolves https://github.com/deltachat/deltachat-desktop/issues/4338 and https://github.com/deltachat/deltachat-desktop/issues/4363
> Core update v1.151.1

- packages/frontend/scss/gallery/_media.scss
> Readd Date styles in gallery

- CHANGELOG.md
- packages/frontend/src/components/Gallery.tsx
- packages/frontend/src/contexts/RovingTabindex.tsx
This is based on https://github.com/deltachat/deltachat-desktop/pull/4369: only look at the last 2 commits.
> improvement: arrow-key nav for gallery tabs

- CHANGELOG.md
- packages/frontend/scss/message/_message-attachment.scss
- packages/frontend/src/components/attachment/messageAttachment.tsx
- add a portrait class to images with ratio <= 3:4 and allow at least 300px image hight for those images
basically reverts https://github.com/deltachat/deltachat-desktop/pull/4315/files
> Revert dynamic image height

- CHANGELOG.md
- pnpm-lock.yaml
- pnpm-workspace.yaml
See https://github.com/deltachat/deltachat-core-rust/issues/6338
and https://github.com/deltachat/deltachat-core-rust/pull/6346
> Upgrade core to 1.152.1

- packages/frontend/scss/message/_message-attachment.scss
https://sass-lang.com/d/mixed-decls
> refactor: fix SCSS nested rule warning

- packages/frontend/src/components/dialogs/AddMember/styles.module.scss
> style: remove horizontal scrollbar in members

- CHANGELOG.md
- packages/frontend/src/components/dialogs/EditProfileDialog/index.tsx
> Always validate non empty displayname

- CHANGELOG.md
- packages/frontend/package.json
- pnpm-lock.yaml
See https://github.com/deltachat/message-parser/releases/tag/0.12.0
> update `@deltachat/message_parser_wasm` from `0.11.0` to `0.12.0`

- packages/e2e-tests/tests/basic-functionality.spec.ts
- packages/frontend/src/components/attachment/Attachment.tsx
- packages/frontend/src/components/attachment/messageAttachment.tsx
- packages/frontend/src/components/composer/Composer.tsx
> Webxdc draft preview

- .tx/config
- _locales/en.xml
- _locales/zh_CN.xml
- package.json
also fixes transifex cli command
tx -s -f didn't work for me, getting an "project not found" error 
the -t parameter (for --translations) fixed it
see https://github.com/transifex/cli/issues/91
> More translations

- CHANGELOG.md
- packages/frontend/src/components/AppPicker/index.tsx
- packages/frontend/src/components/AppPicker/styles.module.scss
- allow to search by author
- add link to search by author in overlay
- add delete button to reset search query
> Order searched apps by relevance

- .github/mergeable.yml
- CONTRIBUTING.md
- docs/DEVELOPMENT.md
Try additional comment
#skip-changelog test
> Enable to skip changelog check for PRs

- packages/frontend/scss/login/_login.scss
resolves #4520 
Also changed the bottom-border to 1px width
Before:
After:
#skip-changelog since it's just a small UI change
> fix: improve input styles - less contrast to placeholders

- CHANGELOG.md
- packages/frontend/src/components/screens/MainScreen.tsx
Without waiting for `T.FullChat` to load.
This should be good for shortcuts.
> perf: chat list: immediately reflect chatId change

- CHANGELOG.md
- packages/target-browser/src/deltachat-rpc.ts
- packages/target-electron/src/deltachat/controller.ts
> fix log format for logging core events

- _locales/_untranslated_en.json
Introduced in c40d605058e247cc1b0068c16ea13dfdc272d7df.
\#skip-changelog
> fix: build failing due to invalid JSON

- packages/frontend/src/components/MessageListView.tsx
- packages/frontend/src/components/screens/MainScreen.tsx
- packages/frontend/src/contexts/ChatContext.tsx
- packages/frontend/src/hooks/chat/useChatDialog.ts
So that the user of `useChat()` is more careful.
> refactor: rename `useChat().chatWithLinger`

- packages/shared/shared-types.d.ts
> refactor: fix format

- packages/frontend/src/stores/messagelist.ts
> refactor: improve jumpToMessage type safety

- packages/target-electron/runtime-electron/runtime.ts
- Show time it took to complete request.
- When logging the response, log the corresponding request
together with it.
The main point of this is that responses do not arrive immediately
and in order.
- Reduce nesting of logged objects.
Before:
After:
> refactor: improve JSONRPC logging

- packages/frontend/src/components/chat/ChatListItem.tsx
- packages/frontend/src/components/helpers/MapMsgStatus.ts
- packages/frontend/src/types-app.d.ts
- **refactor: rename var**
- **refactor: adjust `mapCoreMsgStatus2String` returns**
> refactor: very small refactor

- packages/e2e-tests/playwright-helper.ts
- packages/e2e-tests/tests/basic-functionality.spec.ts
- packages/frontend/src/components/screens/WelcomeScreen/InstantOnboardingScreen.tsx
- packages/frontend/src/components/screens/WelcomeScreen/OnboardingScreen.tsx
- packages/frontend/src/components/screens/WelcomeScreen/UseOtherServerDialog.tsx
> use ci-chatmail server in e2e tests

- packages/target-tauri/runtime-tauri/runtime.ts
> tauri move locale field to shared settings

- CHANGELOG.md
- pnpm-lock.yaml
- pnpm-workspace.yaml
Should be added to the test release
> Update core to 1.155.4

- packages/shared/state.ts
> Set isMentionEnabled default to true

- packages/frontend/src/deviceMessages.ts
> Add new device message

- packages/frontend/src/components/AppPicker/index.tsx
- packages/frontend/src/components/composer/AppPickerWrapper.tsx
- packages/frontend/src/components/composer/Composer.tsx
An attempt at fixing the caching issues in the app picker.
> Fix app picker caching

- CONTRIBUTING.md
#skip-changelog Developer docs only.
> docs: tweaks to the contribution guidelines

- packages/frontend/scss/_global.scss
- packages/frontend/src/ScreenController.tsx
- packages/frontend/src/components/dialogs/QrCode.tsx
- close user feedback after 3 seconds
> Close on invite link copy

- CHANGELOG.md
- packages/frontend/src/components/Settings/Encryption.tsx
- packages/runtime/runtime.ts
> add "learn more"-button to manage-key section that links to local help

- packages/e2e-tests/tests/basic-functionality.spec.ts
> test: skip closing qr-code dialog

- CHANGELOG.md
- packages/target-electron/src/windows/html_email.ts
according to this blogpost https://www.electronjs.org/blog/migrate-to-webcontentsview
> html email view: migrate from deprecated `BrowserView` to `WebContentsView`

- CHANGELOG.md
- Cargo.lock
- packages/frontend/src/components/composer/Composer.tsx
- packages/frontend/src/components/composer/menuAttachment.tsx
- packages/frontend/src/components/dialogs/WebxdcSendToChat/index.tsx
- packages/frontend/src/components/message/MessageListAndComposer.tsx
- packages/frontend/src/components/message/MessageMarkdown.tsx
- packages/frontend/src/deviceMessages.ts
- packages/frontend/src/hooks/chat/useCreateDraftMesssage.ts
- packages/frontend/src/hooks/chat/useMessage.ts
- packages/frontend/src/hooks/chat/usePrivateReply.ts
- packages/target-tauri/src-tauri/Cargo.toml
- pnpm-lock.yaml
- pnpm-workspace.yaml
Needed some adaptions for filenames (see commit 2 & 3)
> Update core 1.156.0

- packages/frontend/src/stores/messagelist.ts
> refactor: comment about missing edit request msgs

- packages/frontend/src/components/Dialog/styles.module.scss
- packages/frontend/src/components/QrReader/styles.module.scss
- packages/frontend/src/components/dialogs/QrCode.tsx
Increase line height, remove bottom padding
Before:
After:
> Improve dialog style1

- Cargo.lock
- Cargo.toml
- packages/target-tauri/src-tauri/src/help_window.rs
> update tauri dependency to tauri git and fix a clippy lint

- packages/target-tauri/src-tauri/src/html_window/mod.rs
- packages/target-tauri/src-tauri/tauri.conf.json5
- **fix csp for windows**
- **fix compile issue on windows and linux**
closes #4742
> tauri: fix build and csp on windows

- CHANGELOG.md
- packages/target-electron/src/deltachat/webxdc.ts
Fixes https://github.com/deltachat/deltachat-desktop/issues/4752
> Fix menu bar hiding when pressing Escape

- CHANGELOG.md
- packages/frontend/scss/dialogs/_qr-code.scss
- packages/frontend/scss/message/_message-detail.scss
- packages/frontend/src/components/AppPicker/index.tsx
- packages/frontend/src/components/Button/style.module.scss
- packages/frontend/src/components/Dialog/CloseFooterAction.tsx
- packages/frontend/src/components/Dialog/OkCancelFooterAction.tsx
- packages/frontend/src/components/Dialog/styles.module.scss
- packages/frontend/src/components/QrReader/styles.module.scss
- packages/frontend/src/components/SmallSelectDialog.tsx
- packages/frontend/src/components/dialogs/AlertDialog.tsx
- packages/frontend/src/components/dialogs/ConfirmationDialog.tsx
- packages/frontend/src/components/dialogs/CreateChat/index.tsx
- packages/frontend/src/components/dialogs/EditProfileDialog/index.tsx
- packages/frontend/src/components/dialogs/QrCode.tsx
- packages/frontend/src/components/dialogs/SetupMultiDevice/ReceiveBackupDialog.tsx
- packages/frontend/src/components/dialogs/SetupMultiDevice/SendBackupDialog.tsx
- packages/frontend/src/components/message/messageFunctions.ts
- packages/frontend/src/components/screens/AccountDeletionScreen/AccountDeletionScreen.tsx
- packages/frontend/themes/_themebase.scss
- packages/frontend/themes/dark.scss
- packages/frontend/themes/dark_amoled.scss
- packages/frontend/themes/darkpurple.scss
- packages/frontend/themes/dev_minimal.scss
- packages/frontend/themes/dev_rocket.scss
- packages/frontend/themes/light.scss
- no transform: uppercase
- buttons visible as buttons
- min-width
- more primary / secondary hierarchies
Some screens: (the focus depends on the action before the screenshot and is dynamic of course)
new vs. old
secondary - danger
secondary - primary
tbd: cancel or close ??
min width
Dark mode
> refactor: dialog footer button styles

- CHANGELOG.md
- packages/e2e-tests/tests/basic-functionality.spec.ts
- packages/frontend/scss/composer/_composer.scss
- packages/frontend/scss/composer/_emoji-sticker-picker.scss
- packages/frontend/src/components/Dialog/CloseButton.tsx
- packages/frontend/src/components/composer/Composer.tsx
- packages/frontend/src/components/composer/ComposerMessageInput.tsx
- packages/frontend/src/components/composer/EmojiAndStickerPicker.tsx
- packages/frontend/src/components/composer/styles.module.scss
- packages/frontend/src/components/message/Message.tsx
- packages/frontend/src/components/message/MessageList.tsx
- packages/frontend/src/components/message/MessageListAndComposer.tsx
- packages/frontend/src/components/message/messageFunctions.ts
- packages/frontend/src/global.d.ts
Closes https://github.com/deltachat/deltachat-desktop/issues/4695.
For a high-level understanding of the changes,
see the added "philosophy" comment in Composer.tsx.
There is one "main" commit, and a few smaller improvement commits. But maybe reviewing commit-by-commit is not gonna be much easier this time.
Hide white-space in the diff viewer for easier review.
Why draft:
> feat: add a way to edit messages

- packages/frontend/src/components/dialogs/MessageDetail/MessageDetail.tsx
> show isEdited info in message detail

- packages/e2e-tests/playwright-helper.ts
> test: reduce E2E test flakiness, again

- CHANGELOG.md
- packages/frontend/src/components/QrReader/index.tsx
- packages/frontend/src/components/QrReader/styles.module.scss
~~This (hopefully) closes (update: wrong issue) https://github.com/deltachat/deltachat-desktop/issues/4639.~~
See individual commits for details.
I tested with dev tools with x6 CPU slowdown. It works fine.
I also tried to play around with constraints, but adding e.g. `width` causes an error for me.
We probably should switch to a library that would do all the stuff in a worker, but these are small changes that I got so far.
> perf: improve QR scanner performance

- CHANGELOG.md
- Cargo.lock
- packages/target-tauri/runtime-tauri/runtime.ts
- packages/target-tauri/src-tauri/Cargo.toml
- packages/target-tauri/src-tauri/capabilities/default.json
- packages/target-tauri/src-tauri/src/lib.rs
- packages/target-tauri/src-tauri/src/runtime_capabilities.rs
- packages/target-tauri/src-tauri/src/state/deltachat.rs
- packages/target-tauri/src-tauri/src/temp_file.rs
- packages/target-tauri/src-tauri/tauri.conf.json5
- **tauri: fix open logfile from settings, fix opening stickerfolder, fix opening weblinks**
- **tauri: implement `runtime.copyFileToInternalTmpDir` and allow opening files in temp dir**
> tauri fix openening files and urls

- CHANGELOG.md
- packages/frontend/src/components/Settings/Advanced.tsx
- packages/frontend/src/components/Settings/Encryption.tsx
> Remove e2e encryption preferences from settings

- packages/target-tauri/src-tauri/src/html_window/email_scheme.rs
- packages/target-tauri/src-tauri/src/html_window/mod.rs
#skip-changelog as this was introduced in #4765
> tauri: fix html email window not working under linux/macos

- packages/frontend/src/components/Dialog/styles.module.scss
> Add bottom margin to dialogs without footer

- CHANGELOG.md
- packages/e2e-tests/tests/basic-functionality.spec.ts
- packages/frontend/scss/dialogs/_qr-code.scss
- packages/frontend/src/components/dialogs/QrCode.tsx
- packages/frontend/src/components/dialogs/QrCodeCopyConfirmationDialog.tsx
- packages/frontend/src/components/dialogs/ViewGroup.tsx
> fix: Show additional dialog with hints about invite link #4667

- CHANGELOG.md
- packages/frontend/src/components/message/Message.tsx
This feature should be released soon (maybe pre release tomorrow)
> Publish edit message feature

- CHANGELOG.md
- packages/frontend/src/components/dialogs/QrCode.tsx
> add withdraw qr code context menu option

- packages/e2e-tests/playwright-helper.ts
- packages/frontend/src/components/AccountListSidebar/AccountItem.tsx
Make check for first onboarding more resilient
> refactor: check onboarding in e2e tests

- packages/frontend/src/components/ThreeDotMenu.tsx
- packages/frontend/src/components/chat/ChatListContextMenu.tsx
- packages/frontend/src/components/dialogs/MuteChat.tsx
the option somehow sneaked in although the title of https://github.com/deltachat/deltachat-desktop/pull/4801 says "instead" :)
> 'mute for 2 hours' is deprecated, see recent discussions

- packages/frontend/src/components/QrReader/index.tsx
> refactor: simplify QR worker code

- packages/frontend/src/components/dialogs/QrCode.tsx
> chore: fix false eslint error

- packages/frontend/src/components/dialogs/QrCode.tsx
> Remove unused variable

- CHANGELOG.md
- Cargo.lock
- package.json
- packages/target-browser/package.json
- packages/target-electron/package.json
- packages/target-tauri/package.json
- packages/target-tauri/src-tauri/Cargo.toml
Test release for upcoming final release 1.56.0
> Prepare release 1.55.0

- packages/target-tauri/src-tauri/src/help_window.rs
> tauri: refactor: fix fmt

- packages/target-tauri/src-tauri/src/i18n/commands.rs
- packages/target-tauri/src-tauri/src/menus/main_menu.rs
- packages/target-tauri/src-tauri/src/settings.rs
> tauri: refactor: `cargo clippy --fix`

- .eslintignore
> chore: exclude playwright reports in eslint

- CHANGELOG.md
- packages/target-tauri/src-tauri/src/help_window.rs
- packages/target-tauri/src-tauri/src/i18n/commands.rs
- packages/target-tauri/src-tauri/src/i18n/errors.rs
- packages/target-tauri/src-tauri/src/temp_file.rs
- packages/target-tauri/src-tauri/src/util/mod.rs
- packages/target-tauri/src-tauri/src/util/sanitization.rs
See individual commits for descriptions.
> tauri: hardening: more validation for commands

- packages/target-tauri/src-tauri/src/html_window/mod.rs
#skip-changelog because just a refactor.
> tauri: refactor: reduce `if let` nesting

- .log.convention.ignore
- packages/e2e-tests/playwright-helper.ts
- packages/e2e-tests/playwright.config.ts
- packages/e2e-tests/tests/basic-functionality.spec.ts
- packages/frontend/src/components/AccountListSidebar/AccountItem.tsx
> E2e test for delete message

- packages/e2e-tests/playwright-helper.ts
- packages/e2e-tests/tests/basic-functionality.spec.ts
- **test: reduce E2E test flakiness, again**
- **test: reduce E2E "send message" test flakiness**
See commit messages for more details.
> test: reduce E2E test flakiness

- packages/e2e-tests/playwright-helper.ts
- packages/e2e-tests/tests/basic-functionality.spec.ts
> test: reduce E2E test flakiness (once more)

- packages/target-tauri/src-tauri/src/lib.rs
This is based on https://github.com/deltachat/deltachat-desktop/pull/4839.
#skip-changelog because it's not important for most users.
I have tested this on Windows, it works OK there. However, the second Ctrl + C apparently kills the process without us having to manually handle this (which is good (IMO)).
> tauri: fix: handle Ctrl+C gracefully

- packages/frontend/src/deviceMessages.ts
> Remove misunderstandable mentions of private keys

- packages/frontend/scss/message/_metadata.scss
> Add style for saved message icon

- packages/target-tauri/src-tauri/src/webxdc/webxdc_scheme.rs
- packages/target-tauri/webxdc-js-implementation/webxdc.ts
So that it's more clear that those are templates.
> tauri: refactor: webxdc: rename __TEMPLATE strs

- packages/target-tauri/src-tauri/src/webxdc/webxdc_scheme.rs
The good old
"XDC-01-005 WP1: Full CSP bypass via desktop app PDF embed"
from https://delta.chat/en/2023-05-22-webxdc-security.
This disables MIME sniffing, so I had to also add one explicitly
for webxdc.js.
I have verified that it works on Windows: the PDF file
now goes to "Downloads".
This also simplifies setting the CSP header.
#skip-changelog because Tauri webxdc has not been released yet.
Related:
- e874c8bdb98321c12d2d972106b0143e7f63577c
(https://github.com/deltachat/deltachat-desktop/pull/3181).
- https://github.com/deltachat/deltachat-desktop/pull/3157.
- https://github.com/deltachat/deltachat-desktop/pull/3174.
- https://github.com/deltachat/deltachat-desktop/pull/4011.
> tauri: fix: webxdc CSP bypass via PDF on Windows

- CHANGELOG.md
- packages/frontend/package.json
- pnpm-lock.yaml
> Update message parser

- CHANGELOG.md
- packages/frontend/src/components/contact/Contact.tsx
- packages/frontend/src/components/dialogs/CreateChat/index.tsx
- **remove addr from contact list items unless they are not verified.**
- **create chat: add context menu option to view profile**
closes #4878
> remove addr from create chat and add view profile to context menu

- CHANGELOG.md
- packages/frontend/src/components/dialogs/ViewGroup.tsx
- packages/frontend/src/hooks/useProcessQr.ts
- packages/frontend/src/hooks/useSecureJoin.ts
> change usage of `nameAndAddr` to `displayName`

- CHANGELOG.md
- packages/frontend/src/components/message/MessageMarkdown.tsx
Related to #4559
#skip-changelog since it's an advanced feature anyway
> Do not render Markdown links if not enabled

- packages/e2e-tests/tests/basic-functionality.spec.ts
> Use user.name instead of user.address

- CHANGELOG.md
- packages/frontend/src/components/chat/ChatList.tsx
> scroll to top when search query changes

- CHANGELOG.md
- packages/shared/localize.ts
- packages/shared/tests/localize.js
> i18n: fix wrong order of substitutions for some strings

- CHANGELOG.md
- packages/frontend/src/components/Gallery.tsx
> remove unexpected horizontal scroll in gallery

- CHANGELOG.md
- packages/frontend/src/components/composer/menuAttachment.tsx
- packages/frontend/src/components/message/MessageListAndComposer.tsx
> fix order when sending multiple files at once

- packages/target-tauri/src-tauri/src/lib.rs
- packages/target-tauri/src-tauri/src/webxdc/webxdc_scheme.rs
> fix clippy lint

- packages/frontend/src/components/Button/style.module.scss
- packages/frontend/themes/_themebase.scss
https://github.com/user-attachments/assets/31bd1309-2d7d-4040-bccd-e6d04a9960cb
> Add hover colors to buttons

- packages/target-tauri/src-tauri/build.rs
> Add necessary second parameter to git describe

- CHANGELOG.md
- Cargo.lock
- packages/target-tauri/runtime-tauri/runtime.ts
- packages/target-tauri/src-tauri/Cargo.toml
- packages/target-tauri/src-tauri/build.rs
- packages/target-tauri/src-tauri/capabilities/main-window.toml
- packages/target-tauri/src-tauri/src/cli.rs
- packages/target-tauri/src-tauri/src/lib.rs
- packages/target-tauri/src-tauri/src/run_config.rs
> tauri: add cli interface `--help`, `--version`, and developer options (like `--dev-mode`)

- packages/target-tauri/src-tauri/src/html_window/mod.rs
- packages/target-tauri/src-tauri/src/state/menu_manager.rs
- packages/target-tauri/src-tauri/src/webxdc/commands_main_window.rs
> tauri: refactor: fix all clippy warnings

- packages/target-tauri/src-tauri/src/menus/webxdc_menu.rs
> tauri: refactor: fix var name ({html,webxdc}_window)

- packages/target-tauri/runtime-tauri/runtime.ts
- packages/target-tauri/src-tauri/src/lib.rs
- packages/target-tauri/src-tauri/src/settings.rs
- packages/target-tauri/src-tauri/src/state/deltachat.rs
and remove outdated comments
#skip-changelog not user visible
> move `notifications` to `frontendAndTauri`

- packages/frontend/src/stockStrings.ts
the translations were removed at
https://github.com/chatmail/core/pull/6777
> remove now unused stock translations

- packages/target-tauri/src-tauri/src/html_window/commands.rs
- packages/target-tauri/src-tauri/src/html_window/mod.rs
- packages/target-tauri/src-tauri/src/lib.rs
- packages/target-tauri/src-tauri/src/menus/tray_menu.rs
- packages/target-tauri/src-tauri/src/settings.rs
- packages/target-tauri/src-tauri/src/state/deltachat.rs
- packages/target-tauri/src-tauri/src/tray.rs
- packages/target-tauri/src-tauri/src/webxdc/commands_main_window.rs
This arguably simplifies its usage.
> tauri: refactor: rewrite get_setting_bool_or with trait

- packages/target-tauri/src-tauri/src/util/url_origin.rs
> tauri: test: fix `UrlOriginExtension` example, add test

- packages/target-tauri/src-tauri/src/webxdc/commands_main_window.rs
I do not see what's the difference in behavior,
but this should be more correct semantically.
> tauri: refactor: webxdc: `WebviewUrl::CustomProtocol`

- packages/frontend/src/components/LoginForm.tsx
> refactor: improve type safety in `LoginForm`

- CHANGELOG.md
- packages/target-electron/runtime-electron/runtime.ts
> Fix sticker folder on windows

- packages/frontend/src/components/AudioRecorder/AudioRecorder.tsx
> Dont show audio error dialog after stopping immediately

- packages/target-tauri/src-tauri/src/lib.rs
> tauri: refactor: add comment about webxdc window bounds

- packages/frontend/src/components/dialogs/ViewProfile/styles.module.scss
> Min height for Bio field

- CHANGELOG.md
- packages/frontend/src/components/Settings/Profile.tsx
- packages/frontend/src/components/Settings/styles.module.scss
> show signature/bio in settings

- packages/frontend/src/components/Settings/Profile.tsx
This failing e2e test should not have been ignored:
https://github.com/deltachat/deltachat-desktop/actions/runs/14422080442/job/40445918481
> Fix replace on null error

- CHANGELOG.md
- packages/frontend/src/components/LoginForm.tsx
- packages/frontend/src/components/composer/Composer.tsx
- packages/frontend/src/components/composer/menuAttachment.tsx
- packages/frontend/src/components/dialogs/EditAccountAndPasswordDialog.tsx
- packages/frontend/src/components/message/MessageListAndComposer.tsx
- packages/frontend/src/components/screens/AccountSetupScreen.tsx
- packages/frontend/src/hooks/useInstantOnboarding.ts
- packages/frontend/src/hooks/useProcessQr.ts
- packages/frontend/src/hooks/useSecureJoin.ts
- packages/frontend/src/types-app.d.ts
resolves #4849
Use new Credentials: EnteredLoginParams & ProxySettings instead self defined Credentials
> Switch from configure to transport API

- packages/target-tauri/src-tauri/src/help_window.rs
- packages/target-tauri/src-tauri/src/i18n/commands.rs
- packages/target-tauri/src-tauri/src/util/sanitization.rs
This should make it easier to use in future code.
TODO:
> tauri: refactor: rewrite a helper fn with trait

- .gitignore
- flake.lock
- flake.nix
> Feat: Add nix flake

- packages/frontend/src/components/screens/WelcomeScreen/InstantOnboardingScreen.tsx
> Fix wrong tx key

- CHANGELOG.md
- packages/frontend/src/ScreenController.tsx
- packages/frontend/src/components/Settings/ExperimentalFeatures.tsx
- packages/frontend/src/stores/settings.ts
> remove experimental option to disable IMAP IDLE

- Cargo.lock
- Cargo.toml
- packages/target-tauri/package.json
- packages/target-tauri/src-tauri/capabilities/main-window.toml
- packages/target-tauri/src-tauri/capabilities/webxdc.toml
- pnpm-lock.yaml
they meanwhile have merged all our contributions.
Also update other rust dependencies.
note that this commit doesn't work yet - it looks like channels don't really work by default:
> go back to released tauri version

- packages/target-tauri/src-tauri/src/lib.rs
- packages/target-tauri/src-tauri/src/settings.rs
- packages/target-tauri/src-tauri/src/themes/cli.rs
- packages/target-tauri/src-tauri/src/themes/themes.rs
And also update CLI error message.
> tauri: refactor: fix some clippy warnings

- packages/target-tauri/src-tauri/src/state/menu_manager.rs
> tauri: refactor: fix error fmt interpolation

- packages/target-tauri/src-tauri/src/runtime_info.rs
I forgot to push changes before merging 🤦 
> follow up to #5006 (fix chat background in tauri on macOS and linux)

- CHANGELOG.md
- packages/target-tauri/src-tauri/src/help_window.rs
- packages/target-tauri/src-tauri/src/html_window/mod.rs
- packages/target-tauri/src-tauri/src/lib.rs
- packages/target-tauri/src-tauri/src/webxdc/commands_main_window.rs
- packages/target-tauri/src-tauri/tauri.conf.json5
depends on https://github.com/tauri-apps/tauri/pull/13090
> deny/disable link preview on long-press on macOS

- CHANGELOG.md
- packages/frontend/src/components/dialogs/EditProfileDialog/index.tsx
- packages/frontend/src/components/dialogs/EditProfileDialog/styles.module.scss
- packages/frontend/themes/_themebase.scss
- packages/frontend/themes/dark.scss
- packages/frontend/themes/light.scss
> Add Profile explain hint

- packages/frontend/src/components/Settings/Profile.tsx
> Show default label if no name

- packages/frontend/src/components/dialogs/ConfigureProgressDialog.tsx
tx arguments are now type checked
> Fix type check error

- CHANGELOG.md
- packages/frontend/src/components/AudioRecorder/AudioRecorder.tsx
- packages/frontend/src/components/AudioRecorder/styles.module.scss
- packages/runtime/runtime.ts
- packages/target-browser/runtime-browser/runtime.ts
- packages/target-electron/build/entitlements.mac.plist
- packages/target-electron/build/gen-electron-builder-config.js
- packages/target-electron/runtime-electron/runtime.ts
- packages/target-electron/src/ipc.ts
- packages/target-electron/src/windows/main.ts
- packages/target-tauri/runtime-tauri/runtime.ts
New runtime methods to ask for media access
resolves #4988
> Ask for microphone permission on Mac

- CHANGELOG.md
- Cargo.lock
- package.json
- packages/frontend/src/deviceMessages.ts
- packages/target-browser/package.json
- packages/target-electron/package.json
- packages/target-tauri/package.json
- packages/target-tauri/src-tauri/Cargo.toml
Reset version to 1.57.0 and add a device message for the test release
The forum topic still has to be created once 1.57.0 is released
> Prepare release 1.57.0 and add test release device message

- CHANGELOG.md
- packages/frontend/src/components/AudioRecorder/AudioRecorder.tsx
resolves #4977
As discussed before, 32 bitrate seems to be a reasonable value
Filesize is now ~240 kB per minute
> Reduce bitRate to 32kb/s

- .github/mergeable.yml
You can test this on https://github.com/deltachat/deltachat-desktop/pull/5064: try changing the title of the MR.
> chore: meta: don't require CHANGELOG on refactor

- packages/frontend/scss/login/_login.scss
- packages/frontend/src/components/Login-Styles.tsx
- **refactor: simplify `DeltaInput` styles**
- **refactor: simplify `DeltaInput`: less JS more CSS**
I have confirmed that this still works.
> refactor: simplify `DeltaInput`: less JS more CSS

- packages/target-tauri/src-tauri/src/notifications.rs
> tauri: refactor: remove `mut`

- CHANGELOG.md
- packages/frontend/src/components/chat/ChatListHelpers.tsx
related to #5100 
Update results when messages are deleted and when new messages arrive
> Update search results on change

- packages/frontend/scss/message/_status-icon.scss
> Only show pointer on clickable status button

- CHANGELOG.md
- Cargo.lock
- packages/frontend/src/components/AudioRecorder/AudioRecorder.tsx
- packages/frontend/src/components/QrReader/index.tsx
- packages/target-tauri/crates/system_permissions/Cargo.toml
- packages/target-tauri/crates/system_permissions/src/apple.rs
- packages/target-tauri/crates/system_permissions/src/lib.rs
- packages/target-tauri/runtime-tauri/runtime.ts
- packages/target-tauri/src-tauri/Cargo.toml
- packages/target-tauri/src-tauri/build.rs
- packages/target-tauri/src-tauri/capabilities/main-window.toml
- packages/target-tauri/src-tauri/src/lib.rs
- packages/target-tauri/src-tauri/src/media_permissions.rs
- packages/target-tauri/src-tauri/src/state/notification.rs
- packages/target-tauri/src-tauri/tauri.conf.json5
- **tauri: ask for media permissions on macOS**
- **Update CHANGELOG.md**
> tauri: ask for media permissions on macOS

- packages/target-electron/static/webxdc-preload.js
#skip-changelog because it's insignificant
> fix: better webxdc realtime channel send error msg

- packages/frontend/scss/message/_message.scss
- packages/frontend/src/components/Button/style.module.scss
Best to be reviewed commit by commit
> Small css cleanups

- .prettierignore
Avoid superfluous warnings in prettier check
> Ignore dynamic created data in prettier

- packages/frontend/scss/login/_login.scss
- packages/frontend/src/components/Button/index.tsx
- packages/frontend/src/components/Button/style.module.scss
- packages/frontend/src/components/CopyContentAlertDialog.tsx
- packages/frontend/src/components/Dialog/DialogHeader.tsx
- packages/frontend/src/components/Dialog/OkCancelFooterAction.tsx
- packages/frontend/src/components/Login-Styles.tsx
- packages/frontend/src/components/SmallSelectDialog.tsx
- packages/frontend/src/components/composer/EmojiAndStickerPicker.tsx
- packages/frontend/src/components/dialogs/AlertDialog.tsx
- packages/frontend/src/components/dialogs/ConfirmDeleteMessage.tsx
- packages/frontend/src/components/dialogs/ConfirmationDialog.tsx
- packages/frontend/src/components/dialogs/CreateChat/index.tsx
- packages/frontend/src/components/dialogs/EditProfileDialog/index.tsx
- packages/frontend/src/components/dialogs/EncryptionInfo.tsx
- packages/frontend/src/components/dialogs/ProxyConfiguration/ProxyItemRow.tsx
- packages/frontend/src/components/dialogs/ProxyConfiguration/index.tsx
- packages/frontend/src/components/dialogs/QrCode.tsx
- packages/frontend/src/components/dialogs/QrCodeCopyConfirmationDialog.tsx
- packages/frontend/src/components/dialogs/SetupMultiDevice/SendBackupDialog.tsx
- packages/frontend/src/components/dialogs/ViewProfile/index.tsx
- packages/frontend/src/components/screens/AccountDeletionScreen/AccountDeletionScreen.tsx
- packages/frontend/src/components/screens/MainScreen/MainScreen.tsx
- packages/frontend/src/components/screens/MainScreen/styles.module.scss
- packages/frontend/src/components/screens/WelcomeScreen/AlternativeSetupsDialog.tsx
- packages/frontend/src/components/screens/WelcomeScreen/InstantOnboardingScreen.tsx
- packages/frontend/src/components/screens/WelcomeScreen/OnboardingScreen.tsx
- packages/frontend/src/components/screens/WelcomeScreen/UseOtherServerDialog.tsx
resolves #5045
Just 2 usages of the Button component needed an extra style, since they were not "real" buttons:
- navbar buttons on main
- password preview button on login
> Make secondary button style default

- CHANGELOG.md
- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
Typescript 5.8.x has many improvements compared to 5.5.4 wich was released in July 2024
https://github.com/microsoft/TypeScript/releases/tag/v5.5.4
> Typescript upgrade

- packages/e2e-tests/tests/group-tests.spec.ts
- packages/frontend/src/components/chat/ChatListContextMenu.tsx
- packages/frontend/src/components/chat/ChatListItem.tsx
- packages/frontend/src/components/dialogs/ViewGroup.tsx
- add new user with invite link
- remove user
- readd user
- rename group from context menu
> Add e2e group tests

- packages/frontend/src/components/Gallery.tsx
- packages/frontend/src/components/screens/MainScreen/MainScreen.tsx
Show app icon in navbar and open media view with app tab as default tab
related to #5141
#skip-changelog (will be added in step 2 or 3)
> Refactor gallery step1

- CHANGELOG.md
- packages/frontend/scss/composer/_composer.scss
> Set max height in drafts

- CHANGELOG.md
- packages/frontend/src/components/dialogs/ViewProfile/index.tsx
> Load all chats initially in contact profile

- packages/frontend/src/components/AccountListSidebar/AccountItem.tsx
- packages/frontend/src/components/screens/AccountDeletionScreen/AccountDeletionScreen.tsx
- packages/target-browser/src/index.ts
I have not tested this, but it should work.
> refactor: fix log error: `undefined.getStackTrace`

- packages/shared/state.ts
resolves #890 
Default value for zoomFactor needs to be undefined
> Set undefined zoomFactor as default

- CHANGELOG.md
- packages/frontend/scss/_variables.scss
- packages/frontend/scss/message/_message-attachment.scss
- packages/frontend/scss/message/_message.scss
- packages/frontend/src/components/AppPicker/styles.module.scss
resolves #5162
- use breakpoint variable
> Fix horizontal scroll

- packages/target-electron/package.json
- packages/target-tauri/package.json
- pnpm-lock.yaml
fails to build for me with
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'esbuild' imported from /build/source/packages/target-electron/bin/build.js
```
> chore: upgrade Electron from 34 to 37

- CHANGELOG.md
- Cargo.lock
- packages/target-tauri/src-tauri/Cargo.toml
- packages/target-tauri/src-tauri/src/lib.rs
- packages/target-tauri/src-tauri/src/webxdc/commands_main_window.rs
> tauri: fix: remember webxdc window position & size

- CHANGELOG.md
- packages/frontend/src/components/message/MessageList.tsx
Closes https://github.com/deltachat/deltachat-desktop/issues/3072.
I have verified that this works.
> fix: set "unread" count to 0 when jump to bottom

- CHANGELOG.md
- packages/frontend/themes/_themebase.scss
This was especially need the in the dark theme.
| Before | After |
|------------|--------|
| ![image](https://github.com/user-attachments/assets/c7aeb8b6-6e12-40fe-9ea6-31c4bd30a609)| ![image](https://github.com/user-attachments/assets/ac6f4a24-863f-4547-a9ec-7fa911c4a244)|
> Slightly increase contrast for unread badge on pinned muted chats. 

- packages/frontend/scss/message/_message.scss
- packages/frontend/src/components/attachment/messageAttachment.tsx
- packages/frontend/src/components/message/Message.tsx
- packages/frontend/src/components/screens/MainScreen/MainScreen.tsx
> Avoid line breaks in webxdc-info

- CHANGELOG.md
- packages/frontend/src/components/chat/ChatListHelpers.tsx
This also fixes potential async race conditions
(see https://github.com/deltachat/deltachat-desktop/issues/4501),
long with simplifying the code.
TODO:
> perf: use asyncThrottle in useChatList

- packages/frontend/src/components/AccountListSidebar/styles.module.scss
#skip-changelog because this bug has not been released.
> fix: style: distance between account list items

- packages/frontend/src/components/chat/ChatList.tsx
> perf: improve ChatList performance, refactor a little

- packages/frontend/src/components/chat/ChatList.tsx
> refactor: improve type safety of `ChatListPart`, other minor stuff

- packages/target-tauri/package.json
- pnpm-lock.yaml
See https://github.com/tauri-apps/tauri/issues/13862.
This also upgrades esbuild.
> chore: fix Tauri Ubuntu build: upgrade Tauri CLI

- packages/frontend/src/deviceMessages.ts
> Add new deviceMessage for 2.x release

- .github/workflows/delete-preview.yml
> Run delete action only conditionally

- .github/workflows/build-windows-appx.yml
> Build win appx only on tags

- packages/e2e-tests/tests/group-tests.spec.ts
- packages/e2e-tests/tests/unencrypted-group-tests.spec.ts
- packages/frontend/src/components/GroupImage.tsx
- packages/frontend/src/components/dialogs/CreateChat/index.tsx
- packages/frontend/src/global.d.ts
> test: add some E2E tests for unencrypted groups

- CHANGELOG.md
- packages/frontend/src/components/AccountListSidebar/AccountItem.tsx
- packages/frontend/src/components/attachment/mediaAttachment.tsx
- packages/frontend/src/components/chat/ChatListItem.tsx
- packages/frontend/src/components/contact/ContactListItem.tsx
- packages/frontend/src/components/dialogs/ChatAuditLogDialog.tsx
- packages/frontend/src/components/dialogs/FullscreenAvatar.tsx
- packages/frontend/src/components/dialogs/FullscreenMedia.tsx
- packages/frontend/src/components/dialogs/QrCode.tsx
- packages/frontend/src/components/message/Link.tsx
- packages/frontend/src/components/message/Message.tsx
https://github.com/deltachat/deltachat-desktop/issues/4743.
> improvement: a11y: aria-haspopup=menu contextMenu

- CHANGELOG.md
- packages/frontend/src/components/AppPicker/index.tsx
- packages/frontend/src/components/AppPicker/styles.module.scss
> Truncate app title and description

- packages/frontend/src/components/Settings/styles.module.scss
> Fix a small text align issue

- CHANGELOG.md
- packages/frontend/src/components/message/MessageMetaData.tsx
> No email icon for not downloaded messages

- packages/frontend/src/components/message/Message.tsx
- packages/frontend/src/components/message/MessageMetaData.tsx
resolves #5407 
#skip-changelog (just a followup)
> Check downloadState in Metadata

- README.md
Just small formatting improvements.
> Small improvements for README

- packages/frontend/src/components/ProfileInfoHeader/styles.module.scss
> Fix profile name position

- packages/frontend/themes/_themebase.scss
- packages/frontend/themes/dark_amoled.scss
- packages/frontend/themes/darkpurple.scss
- packages/frontend/themes/dev_minimal.scss
- packages/frontend/themes/dev_rocket.scss
- packages/frontend/themes/light.scss
> Remove unused variables in themebase

- packages/frontend/themes/dark.scss
> Remove outlineColor

- packages/shared/logger.ts
> Skip colors in log if --no-color param is set

- CHANGELOG.md
- packages/frontend/src/components/contact/Contact.tsx
> Show no addresse for keyContacts

- CHANGELOG.md
- packages/frontend/src/components/dialogs/DisappearingMessages.tsx
- packages/frontend/src/stockStrings.ts
> Add one year option for disappearing messages

- packages/e2e-tests/tests/chat-list-multiselect.spec.ts
> test: add another chat multiselect test

- eslint.config.js
> Configure eslint to ignore test results

- .github/workflows/e2e.yml
- packages/e2e-tests/_env
- packages/e2e-tests/playwright-helper.ts
- packages/e2e-tests/tests/plain-email-tests.spec.ts
- packages/frontend/src/components/dialogs/CreateChat/index.tsx
read mail server urls from secrets
> Test: Create non chatmail account

- .github/workflows/e2e.yml
- docs/E2E-TESTING.md
- packages/e2e-tests/playwright-helper.ts
- packages/e2e-tests/playwright.config.ts
- packages/e2e-tests/tests/basic-tests.spec.ts
- packages/e2e-tests/tests/chat-list-multiselect.spec.ts
- packages/e2e-tests/tests/group-tests.spec.ts
- packages/e2e-tests/tests/plain-email-tests.spec.ts
- packages/e2e-tests/tests/qrcode-tests.spec.ts
- packages/e2e-tests/tests/unencrypted-group-tests.spec.ts
so we can run all tests that are suitable one time with chatmail accounts and one time with non chatmail accounts
> Add new test config option chatmail

- packages/frontend/src/components/chat/ChatList.tsx
- packages/frontend/src/components/chat/ChatListItem.tsx
- packages/frontend/src/components/chat/ChatListItemRow.tsx
Wording is hard: we have a ChatList that can also be a list of search results which means a list of messages or contacts. So a ChatListItem can be a ChatListChatItem or a ChatListMessageItem etc...
Just a first draft here, besides commenting a rewording: ChatListItemNormal => DefaultChatListItem
> Add comments to ChatList and related components

- packages/target-electron/src/deltachat/controller.ts
Currently this commit does not affect behavior of the app,
so it can be considered a refactor, #skip-changelog.
This is a preparation for the upcoming calls MR,
which relies on listening to events in the main process.
Related:
- e16f88b47ba6323577e2e91bcef1d16856ca82f4
(https://github.com/deltachat/deltachat-desktop/pull/5470).
> fix: emit core events on main proc JSON-RPC client

- packages/target-browser/src/deltachat-rpc.ts
Apply the patches from
- e16f88b47ba6323577e2e91bcef1d16856ca82f4
(https://github.com/deltachat/deltachat-desktop/pull/5470).
- https://github.com/deltachat/deltachat-desktop/pull/5470.
TODO:
> refactor: update copy-pasted browser JSON-RPC code

- .github/workflows/basic-tests.yml
- .github/workflows/build-preview.yml
- .github/workflows/build-windows-appx.yml
- .github/workflows/e2e.yml
- .github/workflows/test.yml
- README.md
- bin/check-nodejs-version.js
- flake.lock
- flake.nix
- package.json
- **update nix flake dependencies and pin electon version to the same version we use.**
- **increase min nodejs version to 22 becaue that is what electron 37 uses.**
- **add "pnpm install" to nix flake on startup**
> update nix flake and node version requirement

- packages/frontend/src/components/screens/MainScreen/MainScreen.tsx
#skip-changelog because we'll add it later
> fix: hide "Start call" button when unavailable

- packages/target-electron/src/windows/video-call.ts
Also set their avatar as the window icon.
#skip-changelog because we'll add it later.
> feat: show caller's name on incoming call

- packages/target-electron/src/windows/video-call.ts
#skip-changelog because this is an experimental feature
> fix: calls window: a way to go fullscreen, zoom

- CHANGELOG.md
- packages/frontend/scss/misc/_keyboard_hint_box.scss
This is achieved by small improvements to Curvature Consistency and
tweaking spacing between elements.
|Before|After|
|---------|-------|
| <img width="1020" height="1452" alt="Screenshot_20250930_013056" src="https://github.com/user-attachments/assets/17f72342-23fb-43e5-8fdb-cf10804d0a14" /> | <img width="1019" height="1332" alt="Screenshot_20250930_014816" src="https://github.com/user-attachments/assets/55f08e4c-81fe-491a-9780-4f8e8ac4f36b" /> |
> small tweaks to improve the keybindings preview and cheatsheet.

- packages/frontend/src/components/Settings/ExperimentalFeatures.tsx
> Reactivate new call settings switch

- pnpm-lock.yaml
Includes
- https://github.com/deltachat/calls-webapp/pull/55
- https://github.com/deltachat/calls-webapp/pull/56
> chore: upgrade calls-webapp

- packages/target-tauri/src-tauri/src/webxdc/webxdc_scheme.rs
> tauri: fix: add new item to PERMISSIONS_POLICY
