- package.json
- src/main/deltachat.js
Closes https://github.com/deltachat/deltachat-desktop/issues/61
> Close dc context if it's open

- _locales/en.json
- src/main/deltachat.js
- src/renderer/ScreenController.js
- src/renderer/components/ChatList.js
- src/renderer/components/Login.js
half-done: needs to re-enable the login button when login fails.. @ralphtheninja
> disable login button

- src/main/deltachat.js
- src/main/ipc.js
- src/renderer/components/ChatView.js
- src/renderer/components/dialogs/KeyTransfer.js
- src/renderer/components/dialogs/SetupMessage.js
> Add loading screens for key transfer screens.

- src/renderer/components/ChatView.js
a very minimal implementation.
> add chat name, subtitle, and profile image

- README.md
- package.json
- reload.js
Closes https://github.com/deltachat/deltachat-desktop/issues/86
> Fix `npm run watch`

- src/main/deltachat.js
- src/renderer/components/ChatList.js
- src/renderer/components/ChatView.js
- static/main.css
Closes https://github.com/deltachat/deltachat-desktop/issues/99
This removes code caching messages and chats and renders everything on the fly (which we did before anyway).
> Refactor state

- package.json
- src/main/index.js
- src/main/logins.js
- src/renderer/App.js
- src/renderer/ScreenController.js
- src/renderer/components/ChatList.js
- src/renderer/components/Login.js
- static/main.css
Just need some CSS love on this thing (like most things with the app right now..)
fixes #75
> feature: scan user data directory for existing logins and auto-configure

- _locales/en.json
- package.json
- src/localize.js
Closes https://github.com/deltachat/deltachat-desktop/issues/111 (pushed to transifex)
> Some locale fixes

- _locales/en.json
- src/main/menu.js
Closes https://github.com/deltachat/deltachat-desktop/issues/140
> Translate language abbreviations

- _locales/en.json
- src/main/ipc.js
- src/main/menu.js
- src/main/windows/main.js
Various fixes and cleanup of menu code
* Closes #156 
* Closes #128
> Menu fixes

- conversations/stylesheets/_modules.scss
- src/renderer/ScreenController.js
- src/renderer/components/ChatList.js
- src/renderer/components/ChatView.js
- src/renderer/components/CreateChat.js
- src/renderer/components/GroupBase.js
- src/renderer/components/Login.js
- src/renderer/components/SplittedChatListAndView.js
- static/main.css
Fixes https://github.com/deltachat/deltachat-desktop/issues/36
Some things i want to mention:
- for the `#root` element there was an padding-top: 50px which caused trouble. I switched to using calc + 100vh to have the complete window height instead of doing some weird css stuff. Please consider switching to vh for your components too. It's possible that this "breaks" other things.
- Adding css to conversations isn't really possible because we define the bigger components outside of conversations. That means we have no sass support & can't really do nice css preprocessing. 
- There's weird css code in conversations. For example the chatlist is a weirdly hacked flexbox (which isn't the right thing for this, a normal ul would be enough for this as we don't need wrapping or anything like …
> Consolidate ChatList and ChatView

- src/renderer/components/ChatView.js
Fixes https://github.com/deltachat/deltachat-desktop/issues/183
> We didn't select the correct element for the scroll down

- _locales/en.json
> Add translations for sendFailed and retrySend

- src/renderer/components/ChatView.js
Closes https://github.com/deltachat/deltachat-desktop/issues/180
Result:
> Set conversationType correctly (always set to direct)

- conversations/ts/components/conversation/Message.tsx
- static/main.css
right) in groups
Fixes https://github.com/deltachat/deltachat-desktop/issues/200
> Move avatar out of Message and display it next to the message (left or

- package.json
Closes https://github.com/deltachat/deltachat-desktop/issues/50 and closes https://github.com/deltachat/deltachat-desktop/issues/196
> Switch to electron v3

- src/main/deltachat.js
- src/renderer/components/ChatList.js
- src/renderer/components/ChatView.js
- src/renderer/components/SplittedChatListAndView.js
Tackles #212
To make this work properly, we should als implement markNoticedChat(chatId) and maybe even markSeenMessages(). For this i need to make some IPC stuff with which i'm unsure in the moment. Maybe @ralphtheninja  can help me with this?
EDIT: Implemented ipc dispatch to mark chat as noticed, only marking messages as read is missing.
EDIT1:
Bugs:
- if we are in a chat and get new messages, we need to switch the selected chat to get rid of the fresh message counter. Maybe we can check for a onFocus event or something and also call markNoticedChatIfNeeded()
EDIT2: Telegram is cleaning the fresh message counter for the selected chat on window focus
> [WIP] Implement fresh message counter in ChatList

- src/main/deltachat.js
- src/renderer/components/ChatList.js
- src/renderer/components/SplittedChatListAndView.js
- static/main.css
Closes https://github.com/deltachat/deltachat-desktop/issues/146
> View archived chats

- src/main/deltachat.js
- src/renderer/components/ChatList.js
- src/renderer/components/SplittedChatListAndView.js
archive chat functionality to backend
> Reimplement move_selected_chat_id_to_deltachat_controller and move

- src/config.js
- src/main/deltachat.js
- src/main/ipc.js
- src/main/windows/main.js
- src/renderer/components/SplittedChatListAndView.js
- src/renderer/lib/state.js
- src/renderer/main.js
- static/main.html
Closes https://github.com/deltachat/deltachat-desktop/issues/210
> Put logged in user in window title

- _locales/en.json
- src/main/deltachat.js
- src/renderer/components/ChatList.js
- src/renderer/components/SplittedChatListAndView.js
- static/main.css
> don't select recent chat by default, fixes #228

- _locales/en.json
- src/main/deltachat.js
- src/main/ipc.js
> Translate core strings

- _locales/en.json
- src/main/deltachat.js
- src/renderer/ScreenController.js
- src/renderer/components/SplittedChatListAndView.js
- src/renderer/components/UnblockContacts.js
- src/renderer/components/dialogs/index.js
* See currently blocked contacts
* Block a contact
* Refactor dialogs, add shared 'confirmation' dialog code
* Dialog for confirming blocking a contact
* Dialog for confirming unblocking a contact
> Block a contact/Unblock contacts

- _locales/en.json
- src/renderer/components/SplittedChatListAndView.js
- src/renderer/components/UnblockContacts.js
- src/renderer/components/dialogs/index.js
Tweaking this before finishing confirm on delete chat.
> Translate confirmation dialog buttons + callback with boolean

- _locales/en.json
- src/renderer/components/SplittedChatListAndView.js
Closes https://github.com/deltachat/deltachat-desktop/issues/199
> Add confirmation dialog when deleting a chat

- .travis.yml
_Addresses_ https://github.com/deltachat/deltachat-desktop/issues/110 (we need to make a new release so e.g. @gerroon can test this)
> Install libssl-dev on Travis

- src/main/deltachat.js
- src/renderer/components/dialogs/DeadDrop.js
It was never calling `create_chat_by_msg_id` https://c.delta.chat/classdc__context__t.html#aa150be55af0f0a7b7f9ed9bb530f78c5
> fix: contact requests properly resolve when request is from a group chat

- _locales/en.json
- src/renderer/components/Login.js
Fixes https://github.com/deltachat/deltachat-desktop/issues/207
> Hide password by default and add button to show it

- _locales/en.json
- src/main/deltachat.js
- src/main/index.js
- src/renderer/components/ChatView.js
- src/renderer/components/SplittedChatListAndView.js
- static/main.css
> add search box for chatlist

- src/renderer/components/dialogs/About.js
Closes https://github.com/deltachat/deltachat-desktop/issues/245
> Wrap <a href>

- src/config.js
- src/renderer/components/dialogs/About.js
> Main window and about dialog should show same version

- package.json
- src/config.js
- src/main/index.js
Closes https://github.com/deltachat/deltachat-desktop/issues/283
> Ensure CONFIG_PATH always exists at start up

- _locales/en.json
- src/renderer/components/ChatView.js
- static/main.css
Closes https://github.com/deltachat/deltachat-desktop/issues/202
Picked the same orange color as android.
> Tweak autocrypt setup message

- package.json
- src/main/deltachat.js
- src/renderer/components/Login.js
Closes https://github.com/deltachat/deltachat-desktop/issues/271
> Snake case keys during configure

- src/renderer/components/CreateContact.js
- src/renderer/components/GroupBase.js
Found this gem while going through `git log` :)
> the back button should go back to CreateChat screen on both CreateGroup and AddContact

- conversations/ts/components/ConversationListItem.tsx
- src/renderer/components/ChatList.js
Closes https://github.com/deltachat/deltachat-desktop/issues/175
WDYT?
> Add group image to chat list

- README.md
Closes https://github.com/deltachat/deltachat-desktop/issues/279 and closes https://github.com/deltachat/deltachat-desktop/issues/278
> Improve install instructions in troubleshooting section

- src/main/deltachat.js
- src/renderer/components/ChatView.js
fixes #6 loading messages on demand using a page model. 
this is similar to how Signal handles it -- the user scrolls to the top, and then it loads new messages.
> load messages on demand using a paging model

- src/renderer/components/EditGroup.js
I like the idea of this messenger!
fixes #292
> Back button for Edit group should go back to split view

- src/main/deltachat.js
- src/renderer/components/ChatView.js
- src/renderer/components/Composer.js
- src/renderer/components/RenderMedia.js
- static/main.css
> add image attachments

- src/main/deltachat.js
- src/renderer/components/GroupBase.js
Closes https://github.com/deltachat/deltachat-desktop/issues/312
> Only try setting image if different + allow null

- src/main/ipc.js
- src/renderer/ScreenController.js
- src/renderer/components/Message.js
> allow user to save a file attachment to disk

- package.json
- src/main/deltachat.js
**Note** This will pull in the single folder core.
> Upgrade node bindings

- _locales/en.json
- conversations/stylesheets/_modules.scss
- conversations/ts/components/ContactListItem.tsx
- src/renderer/components/Contact.js
- static/main.css
Closes https://github.com/deltachat/deltachat-desktop/issues/294
> Verified contact should use same icon as for verified group

- package.json
- src/renderer/components/Menu.js
- src/renderer/components/SplittedChatListAndView.js
:file_cabinet: :factory: :recycle: :relaxed: cleaning house
still didn't find a broom emoji though, what's with that?
> refactor menu

- src/main/index.js
- static/main.html
depends on moving to webpack merging #329
> set content security policy to script:self -- fixes #198

- static/main.html
fixes https://github.com/deltachat/deltachat-desktop/issues/343
> add img-src: 'self' to Content-Security-Policy fixes https://github.com/deltachat/deltachat-desktop/issues/343

- package.json
- src/renderer/components/ChatList.js
- src/renderer/components/ChatView.js
- src/renderer/components/Composer.js
- src/renderer/components/Login.js
- src/renderer/components/SplittedChatListAndView.js
- src/renderer/components/UnblockContacts.js
- src/renderer/components/dialogs/SetupMessage.js
- src/renderer/components/helpers/Centered.js
- static/main.css
We're now using styled components for half of the css rules in main.css. Fixes https://github.com/deltachat/deltachat-desktop/issues/298
> Start using styled-components

- static/main.html
Just noticed we need this for media/video as well.
> Update media-src CSP as well

- conversations/ts/components/conversation/Linkify.tsx
- package.json
Fixes https://github.com/deltachat/deltachat-desktop/issues/325
Thanks @ralphtheninja  :)
> Use linkify fork wich allows domains to contain multiple dashses

- src/renderer/components/Login.js
> Update single folder banner wording

- CHANGELOG.md
- README.md
- UPGRADING.md
* updates `CHANGELOG.md`
* adds `UPGRADING.md`
> Prepare v2.0.0

- src/main/deltachat.js
- src/renderer/components/ChatList.js
- src/renderer/components/SplittedChatListAndView.js
- src/renderer/components/dialogs/DeadDrop.js
Fixes https://github.com/deltachat/deltachat-desktop/issues/332
> Refactor state render & fix deaddrop accept

- package.json
Reduce install time from like 45 to 25 seconds.
> Try preminor release of node bindings

- src/main/deltachat.js
this fixes the bug where contact names and infos were not showing in group chats
> turn contact into json before passing to frontend. fixes #360

- src/main/deltachat.js
- src/renderer/components/Message.js
- static/main.css
addresses this comment by @r10s https://github.com/deltachat/deltachat-desktop/issues/273#issuecomment-441241757
> display info text differently than regular messages

- src/renderer/components/CreateChat.js
- src/renderer/components/CreateContact.js
- src/renderer/components/GroupBase.js
- src/renderer/components/Login.js
- src/renderer/components/NavbarWrapper.js
- src/renderer/components/SplittedChatListAndView.js
Closes https://github.com/deltachat/deltachat-desktop/issues/383
> Move out NavbarWrapper and reuse it

- src/main/deltachat.js
are hard) and fix unnecessary rerenders if ChatView is scrolled to top.
Fixes https://github.com/deltachat/deltachat-desktop/issues/378
> Fix accidentially skipped message (for loops from last to first index

- src/renderer/components/MessageWrapper.js
fixes #417, bug was introduced here: https://github.com/deltachat/deltachat-desktop/pull/392/files#diff-e4dfa3b74591a80875d1bbb32d549eadR79
> ensure setup message is rendered

- _locales/en.json
- src/main/menu.js
Closes https://github.com/deltachat/deltachat-desktop/issues/424
> Add File menu and Quit menu alternative

- webpack.config.js
> use webpack-node-externals to speed up the build

- package.json
> electron 3 time

- _locales/en.json
- src/renderer/components/Menu.js
Closes https://github.com/deltachat/deltachat-desktop/issues/395
> Ask user before leaving group (+ quote names)

- package.json
- src/renderer/components/MessageWrapper.js
Closes https://github.com/deltachat/deltachat-desktop/issues/404
> Lookup mime type using filename

- _locales/en.json
- src/main/deltachat.js
- src/renderer/components/ChatList.js
- src/renderer/components/ChatView.js
- src/renderer/components/Menu.js
- src/renderer/components/MessageWrapper.js
- src/renderer/components/SplittedChatListAndView.js
- src/renderer/components/dialogs/DeadDrop.js
> list contact requests, fixes #248

- src/renderer/components/Menu.js
> add menue divider to fix #433

- _locales/en.json
- src/main/deltachat.js
- src/renderer/ScreenController.js
- src/renderer/components/ChatView.js
- src/renderer/components/ContactList.js
- src/renderer/components/GroupBase.js
- src/renderer/components/Menu.js
- src/renderer/components/SplittedChatListAndView.js
- src/renderer/components/UnblockContacts.js
- src/renderer/components/dialogs/About.js
- src/renderer/components/dialogs/ContactDetail.js
- src/renderer/components/dialogs/DeadDrop.js
- src/renderer/components/dialogs/EncrInfo.js
- src/renderer/components/dialogs/ForwardMessage.js
- src/renderer/components/dialogs/ImexProgress.js
- src/renderer/components/dialogs/KeyTransfer.js
- src/renderer/components/dialogs/MessageDetail.js
- src/renderer/components/dialogs/QrCode.js
- src/renderer/components/dialogs/RenderMedia.js
- src/renderer/components/dialogs/Settings.js
- src/renderer/components/dialogs/SetupMessage.js
- src/renderer/components/dialogs/index.js
> add encryption info for chats

- _locales/en.json
- src/main/deltachat.js
- src/renderer/components/SplittedChatListAndView.js
fixes #449 
@Simon-Laux  can you review and see if this works for you?
> fix contact requests

- src/main/deltachat.js
> select chat after contact request has been granted

- src/renderer/ScreenController.js
depends upon https://github.com/deltachat/deltachat-node/pull/210
> remove single folder compat message.

- _locales/en.json
- src/main/deltachat.js
- src/main/ipc.js
- src/renderer/ScreenController.js
> forget account button with confirmation. fixes #221

- src/renderer/components/Media.js
> Fix height on the media page

- src/main/deltachat.js
- src/main/ipc.js
> Handle self not in group error

- src/renderer/components/ChatList.js
#482 
@Jikstra approved it IRL
> add a divider between chatlist and chatview

- src/main/logins.js
Fixes https://github.com/deltachat/deltachat-desktop/issues/496
> Fix unneccessay db file creation

- README.md
Trying it out on Arch Linux I noticed that the install step is missing, before building.
I also fixed a minor formatting problem.
> improve build / run instructions

- src/localize.js
Closes https://github.com/deltachat/deltachat-desktop/issues/502
> Use locale fallback, e.g. en-US falls back to en if it does not exist

- src/renderer/components/SplittedChatListAndView.js
Closes https://github.com/deltachat/deltachat-desktop/issues/507
> Only add <img> element if profileImage is set

- src/renderer/components/Menu.js
Closes https://github.com/deltachat/deltachat-desktop/issues/511
> Add back menu item for unblock contacts

- src/renderer/components/dialogs/SetupMessage.js
Closes https://github.com/deltachat/deltachat-desktop/issues/493
> Use provided onClose() method (this.onClose() does not exist)

- src/renderer/components/ChatView.js
- src/renderer/components/Composer.js
- src/renderer/components/SplittedChatListAndView.js
> Re focus chat input field

- package.json
- src/main/deltachat.js
- src/renderer/components/dialogs/Settings.js
> Implement settings for watching movebox, sentbox, inbox & enabling move. Fixes #526

- _locales/en.xml
- conversations/stylesheets/_modules.scss
- src/renderer/components/ContactList.js
- src/renderer/components/GroupBase.js
+ More visual difference for members and contacts
+ Group members are now at the top
> Temporary partial solution to the group info/edit screen mess

- _locales/en.xml
- src/renderer/components/Media.js
- src/renderer/components/conversations/MessageDetail.js
Closes https://github.com/deltachat/deltachat-desktop/issues/528
> Missing translations

- src/renderer/lib/state.js
Many small commits, but simplifies quite a bit. Squash at merge.
> Refactor and simplify state load

- README.md
- package.json
Closes https://github.com/deltachat/deltachat-desktop/issues/549
Squash at merge.
> Readme tweaks

- src/renderer/ScreenController.js
> Hide Known-Accounts section when it's empty

- bin/watch.js
Closes https://github.com/deltachat/deltachat-desktop/issues/551
> Update outdated watch script

- src/renderer/components/CreateChat.js
> Restyle create chat buttons

- package.json
- src/logger.js
- src/main/index.js
- src/rc.js
Ticks off third checkbox in https://github.com/deltachat/deltachat-desktop/issues/550
> Tweak logger

- src/main/deltachat.js
- src/main/index.js
- src/main/ipc.js
- src/main/state.js
Closes https://github.com/deltachat/deltachat-desktop/issues/258
> Login automatically if last credentials were saved in state

- package.json
- src/application-config.js
- src/application-constants.js
- src/main/developerTools/logHandler.js
- src/main/index.js
- src/main/state.js
- test/integration/setup.js
Closes https://github.com/deltachat/deltachat-desktop/issues/597, closes https://github.com/deltachat/deltachat-desktop/issues/596
> Wrap application-config module for proper appConfig during production and testing

- bin/extract_local_language_names.js
- package.json
- src/main/menu.js
- test/unit/index.js
> change language dropdown to use the local names

- .gitignore
- README.md
- _locales/_experimental_en.json
- src/localize.js
- src/logger.js
- src/renderer/components/Login.js
- test/unit/index.js
This implements a new language string which needs to get reviewed and implemented into the transifix stuff. 
Fixes #503
> Implement login instruction

- src/renderer/components/conversations/Linkify.js
> fix emailadress parsing bug in message

- _locales/en.xml
- src/renderer/components/CreateChat.js
this still misses:
I don't have the transiflex client installed and don't know shit about this, @ralphtheninja can you help me out with pulling in the translations?
Will fix https://github.com/deltachat/deltachat-desktop/issues/523
> Move create verified group button to the right and add some margin

- src/renderer/components/ChatList.js
- src/renderer/components/style-variables.js
Before:
After:
After with light color:
Opinions? @r10s @hpk42 @Simon-Laux @ralphtheninja
> Selected chat now uses the delta (light) color

- src/renderer/ScreenController.js
> Add line break between advanced and login button

- src/main/menu.js
> sort languages alphabeticaly

- .github/ISSUE_TEMPLATE.md
See https://github.com/deltachat/deltachat-core/pull/546
> Update github issue template

- src/main/deltachat.js
- src/main/ipc.js
- src/renderer/components/ChatView.js
- src/renderer/components/ContactList.js
- src/renderer/components/CreateChat.js
- src/renderer/components/CreateContact.js
- src/renderer/components/CreateGroup.js
- src/renderer/components/EditGroup.js
- src/renderer/components/GroupBase.js
- src/renderer/components/Login.js
- src/renderer/components/Media.js
- src/renderer/components/Menu.js
- src/renderer/components/MessageWrapper.js
- src/renderer/components/SplittedChatListAndView.js
- src/renderer/components/UnblockContacts.js
- src/renderer/components/dialogs/DeadDrop.js
- src/renderer/components/dialogs/EncrInfo.js
- src/renderer/components/dialogs/ForwardMessage.js
- src/renderer/components/dialogs/Settings.js
Closes https://github.com/deltachat/deltachat-desktop/issues/591
> Cleanup ipc

- src/main/index.js
- src/main/windows/main.js
Closes https://github.com/deltachat/deltachat-desktop/issues/495
* Tries to get a lock and quits if it fails
* The process with the lock focuses the main window
> Prevent running multiple instances

- src/renderer/components/ChatList.js
- src/renderer/components/SplittedChatListAndView.js
- src/renderer/components/UnblockContacts.js
- src/renderer/components/dialogs/About.js
- src/renderer/components/dialogs/SetupMessage.js
- src/renderer/components/helpers/Centered.js
- src/renderer/components/helpers/Unselectable.js
- static/main.css
Closes https://github.com/deltachat/deltachat-desktop/issues/393
> Remove style specific components

- src/main/deltachat.js
- src/renderer/components/ChatView.js
- src/renderer/components/MessageWrapper.js
- src/renderer/components/dialogs/SetupMessage.js
Closes https://github.com/deltachat/deltachat-desktop/issues/467
Also removes the up/down arrows:
> Autocrypt leading digits

- src/renderer/components/ChatList.js
- src/renderer/components/ChatView.js
- src/renderer/components/Composer.js
- src/renderer/components/SplittedChatListAndView.js
- static/main.css
Still missing:
Fixes https://github.com/deltachat/deltachat-desktop/issues/543
> Resize the composer based on the newlines in the text

- css/conversations/_modules.scss
- src/renderer/components/ChatListItem.js
> Fix emoji groupname problems

- src/main/deltachat.js
- src/main/ipc.js
- src/renderer/components/dialogs/About.js
> dc info in About screen

- src/renderer/components/Composer.js
I agree, empty messages should not be sent. We still should discuss, if we trim spaces from messages...
> Do not send empty messages (i.e. only spaces)

- css/conversations/_mixins.scss
- css/conversations/_modules.scss
So we just use these until we come up with a better solution...?
> Use vertical ellipsis for context handle

- src/renderer/components/Composer.js
Fixes https://github.com/deltachat/deltachat-desktop/issues/656
> Focus the composer on the current selection/cursor

- src/renderer/components/Composer.js
Fixes https://github.com/deltachat/deltachat-desktop/issues/675
> Fix layout breaking when pasting long multiline messages into composer

- src/main/index.js
- src/main/ipc.js
> Log file catch when deltachat-node dependency is missing

- src/renderer/components/conversations/Message.js
> Open context menu on right click

- src/main/deltachat.js
- src/main/ipc.js
- src/main/unread-badge.js
on Linux only with the unity desktop environment.
closes #682
> add native badge count for osx and linux

- src/renderer/components/ChatView.js
What works currently: 
What should be in the pull request: 
related to #415 
EDIT: add that link: https://electronjs.org/docs/api/file-object
> Drop File to send

- static/main.css
At least on my screens the is a very bad contrast with the dark green background
New color has same value as $color-core-green variable
> Change background color for success feedback

- _locales/_experimental_en.json
- css/conversations/_global.scss
- src/main/deltachat.js
- src/main/ipc.js
- src/renderer/components/Login.js
- src/renderer/components/dialogs/EncrInfo.js
- src/renderer/components/dialogs/Settings.js
- src/renderer/components/dialogs/SetupMessage.js
As long as wrong credentials result in a crash this PR should not be merged
> Settings login

- src/logger.js
- src/main/deltachat.js
- src/main/ipc.js
- src/main/state.js
- src/main/windows/main.js
- src/renderer/App.js
- src/renderer/components/ChatView.js
- src/renderer/components/Composer.js
- src/renderer/components/ComposerMessageInput.js
- src/renderer/components/SplittedChatListAndView.js
- src/renderer/components/dialogs/Settings.js
- src/renderer/contexts/SettingsContext.js
closes #542 
What's missing/not 100% working:
> Multiline keybinding setting

- src/renderer/components/Composer.js
Fixes https://github.com/deltachat/deltachat-desktop/issues/700
> Fix multline performance

- src/renderer/components/Media.js
Fixes https://github.com/deltachat/deltachat-desktop/issues/688
> Fix media buttons hidden below navbar

- static/main.html
for good measures, we shouldn't need it anyway.
> remove unpkg from whitelist

- src/renderer/components/Media.js
- src/renderer/components/MessageWrapper.js
> Make sure images don't overflow

- _locales/_experimental_en.json
- src/main/deltachat.js
- src/main/ipc.js
- src/renderer/ScreenController.js
- src/renderer/components/dialogs/Settings.js
> Keys export import

- README.md
Also add a few lines to the release checklist.
> Update instructions now dc-node has changed

- src/renderer/main.js
> prevent select all

- src/renderer/components/map/MapComponent.js
> Do not cache window.translate at file scope

- src/renderer/components/Composer.js
> change emoji picker behavior

- src/main/deltachat/login.js
Fixes https://github.com/deltachat/deltachat-desktop/issues/798
> Fix delete account

- ci_scripts/ubuntu-19_04-netpgp/Dockerfile
- ci_scripts/ubuntu-19_04-netpgp/build.sh
- ci_scripts/ubuntu-19_04-netpgp/electron-builder-ubuntu.json
- ci_scripts/ubuntu-19_04-netpgp/rebuild-core.js
Only needed for debugging rpgp issues. Still want to have it in the repo.
> Add build instructions for ubuntu 19.04 netpgp

- src/renderer/components/Media.js
> open files in media view directly

- src/main/log-handler.js
Reverts deltachat/deltachat-desktop#828
> Revert "fix: use a friendlier file name for logs on windows (: not appreciated)"

- src/main/deltachat/chatlist.js
- src/main/deltachat/chatmethods.js
- src/main/deltachat/index.js
- src/main/deltachat/login.js
- src/main/deltachat/messagelist.js
- src/main/ipc.js
- src/renderer/components/ChatList.js
- src/renderer/components/ChatListContextMenu.js
- src/renderer/components/ChatView.js
- src/renderer/components/ComposerMessageInput.js
- src/renderer/components/Menu.js
- src/renderer/components/MessageWrapper.js
- src/renderer/components/SplittedChatListAndView.js
- src/renderer/components/UnblockContacts.js
- src/renderer/components/conversations/MessageDetail.js
- src/renderer/components/dialogs/DeadDrop.js
- src/renderer/components/dialogs/ForwardMessage.js
- src/renderer/components/map/MapComponent.js
- src/renderer/stores/blockedContacts.js
- src/renderer/stores/chat.js
- src/renderer/stores/chatList.js
- src/renderer/stores/locations.js
@nicodh did some really awesome work and this contains a lot of improvements. We should merge this as is and later on @nicodh can continue on sorting.
Closes https://github.com/deltachat/deltachat-desktop/issues/788
Closes https://github.com/deltachat/deltachat-desktop/issues/757
> Chatlist refactoring

- _locales/_experimental_en.json
- src/main/state.js
- src/renderer/components/SplittedChatListAndView.js
- src/renderer/components/dialogs/Settings.js
enable/disable on demand location streaming
> Implement advanced features section in settings and add setting to

- src/renderer/components/ChatList.js
- src/renderer/components/ChatListItem.js
- src/renderer/components/Contact.js
- src/renderer/components/conversations/ContactListItem.js
- src/renderer/components/conversations/ContactName.js
- src/renderer/components/conversations/Message.js
- src/renderer/components/conversations/MessageDetail.js
I prefer email instead of address or addr since we might have a real address as contact property in future...
> Rename contact.phoneNumber to contact.email

- bin/test_for_missing_translations.sh
> re-add test for mising translations script

- src/renderer/components/dialogs/KeyTransfer.js
> Reset state when closing key transfer dialog

- src/main/deltachat/chatlist.js
Simplify _getGeneralFreshMessageCounter
> Update badge if messages are marked as read

- src/main/deltachat/chatmethods.js
- src/renderer/components/CreateContact.js
> Validate mail address before chat is created

- static/chat.delta.desktop.desktop
(inspired by telegrams desktop file)
> update some tags in desktop file

- src/renderer/components/SplittedChatListAndView.js
> Make search case insensitive

- src/renderer/ScreenController.js
- src/renderer/components/ChatList.js
- src/renderer/components/ChatListContextMenu.js
- src/renderer/components/ChatView.js
- src/renderer/components/CreateChat.js
- src/renderer/components/CreateContact.js
- src/renderer/components/EditGroup.js
- src/renderer/components/GroupBase.js
- src/renderer/components/Media.js
- src/renderer/components/SplittedChatListAndView.js
- src/renderer/components/UnblockContacts.js
- src/renderer/contexts/ScreenContext.js
resolves #727 for the time being. We should come up with an even better solution in the future.
Only merge after enough testing and/or review.
> [needs testing] move the screenfunctions to a context

- src/main/deltachat/index.js
> Log payload for core events

- bin/watch.js
- scss/_global.scss
- scss/modules/_bp3-dialogs.scss
- scss/modules/index.scss
> Restyle dialogs

- src/renderer/components/EditGroup.js
- src/renderer/components/GroupBase.js
> Use heading property from state

- src/main/deltachat/index.js
Just to make sure it's not possible to call "any" method on deltachat via EVENT_DC_FUNCTION_CALL event from frontend context
> Filter accessible functions

- src/renderer/components/CreateGroup.js
> Fix createGroup changeScreen

- _locales/_experimental_en.json
- src/renderer/components/conversations/Message.js
> copy selected message text to clipboard

- src/main/deltachat/index.js
- src/main/deltachat/settings.js
- src/main/ipc.js
- src/renderer/App.js
- src/renderer/ScreenController.js
- src/renderer/components/Login.js
- src/renderer/components/SplittedChatListAndView.js
- src/renderer/components/dialogs/Settings.js
- src/renderer/components/dialogs/index.js
- src/renderer/components/map/MapComponent.js
- test/integration/domHelper.js
- test/integration/fixtures/config.js
- test/integration/index.js
- test/integration/setup.js
> Refactor desktop settings

- scss/modules/_message.scss
- src/renderer/components/Attachment.js
- src/renderer/components/ChatView.js
- src/renderer/components/conversations/Message.js
..When clicking on the file icon (the same one you drag to drag out the file.
> Open file on click

- src/renderer/components/dialogs/Settings.js
implementing the logic on our own
> Use openDialog for SendAutocryptSetupMessage dialog instead of

- scss/modules/_bp3-overwrites.scss
- src/renderer/ThemeBackend.js
- src/renderer/components/dialogs/EnterAutocryptSetupMessage.js
- src/renderer/components/dialogs/SendAutocryptSetupMessage.js
Seems like the fps on the gif is too low, so in reality the animation is smoother :)
> Restyle spinner to more fit the styling used on android

- _locales/_experimental_en.json
- src/renderer/components/conversations/Message.js
- src/renderer/components/conversations/MessageMetaData.js
We should cleanup this file. Not sure if all label are needed.
At least the one I added should go into the _locales files...
> Add missing labels to experimental.json

- _locales/_experimental_en.json
- src/renderer/components/ChatListItem.js
- src/renderer/components/Composer.js
- src/renderer/components/CreateChat.js
- src/renderer/components/GroupBase.js
- src/renderer/components/Login-Styles.js
- src/renderer/components/LoginScreen.js
- src/renderer/components/SplittedChatListAndView.js
- src/renderer/components/UnblockContacts.js
- src/renderer/components/conversations/Message.js
- src/renderer/components/conversations/MessageMetaData.js
- src/renderer/components/dialogs/RenderMedia.js
#870
@OzancanKaratas please test if that works the way you want.
Also the text is in `_locales/_experimental_en.json` if you want to change it to sound better.
> Label Icon Buttons for accessibility

- src/renderer/components/dialogs/CreateChat-Styles.js
- src/renderer/components/helpers/Contact.js
@Simon-Laux I used the same hardcoded fallback color #505050 for pseudo group/contact that was used in AvatarBubble. Not sure if we need to adapt that for theming...
> Rework create chat avoid react errors

- src/main/deltachat/index.js
- src/main/deltachat/locations.js
- src/main/ipc.js
- src/renderer/components/ChatView.js
- src/renderer/components/GroupBase.js
- src/renderer/components/Menu.js
- src/renderer/components/SplittedChatListAndView.js
- src/renderer/components/UnblockContacts.js
- src/renderer/components/dialogs/CreateChat.js
- src/renderer/components/dialogs/DeadDrop.js
- src/renderer/components/dialogs/ForwardMessage.js
- src/renderer/components/map/MapComponent.js
- src/renderer/ipc.js
- src/renderer/stores/chat.js
- src/renderer/stores/chatList.js
- src/renderer/stores/locations.js
This PR is mainly about renaming but also a bit refactoring (last commit)
I consider 'viewMode' more intuitive than 'show'
I also would like to get rid of the name "ScreenController" and the "screen" variables. To me "screen" is more a hardware term (although I'm not native speaker...)
"ScreenController" => "FrontendController" ?
"changeScreen" => "changeView"
etc.
But let's start with this PR first...
> Renaming proposals

- src/renderer/components/dialogs/CreateChat.js
- src/renderer/components/dialogs/EditGroup.js
- Fix padding in EditGroup dialog
- Fix creating a group resulting in empty dialog
> Fix some edit group bugs

- scss/modules/_bp3-overwrites.scss
- src/renderer/ThemeBackend.js
- src/renderer/components/dialogs/CreateChat.js
- src/renderer/components/dialogs/EditGroup.js
- src/renderer/components/dialogs/Settings.js
- src/renderer/components/helpers/DeltaDialog.js
- implement optional border bottom for DeltaDialogHeader
- implement DeltaDialogBody supporting noFooter
- Adjust colors
> Refactor DeltaDialog Footer, Header & Body to make them more generic

- scss/modules/_bp3-overwrites.scss
- src/main/deltachat/chatlist.js
- src/main/deltachat/index.js
- src/renderer/ThemeBackend.js
- src/renderer/components/ChatListContextMenu.js
- src/renderer/components/Menu.js
- src/renderer/components/dialogs/CreateChat.js
- src/renderer/components/dialogs/EditGroup.js
- src/renderer/components/dialogs/Settings.js
- src/renderer/components/dialogs/confirmationDialog.js
- src/renderer/components/helpers/ChatMethods.js
- src/renderer/components/helpers/Contact.js
- src/renderer/components/helpers/ContactList.js
- src/renderer/components/helpers/DeltaDialog.js
- src/renderer/components/helpers/SmallDialog.js
- Tweak confirmation dialog to
- use a better and more fitting danger color
- the 'bad' option can now be chosen with the yesIsDanger prop, and
the danger option is always on the left side and in the red danger
color
- Make overlay opacity more prominent
- Add hover to DeltaButtons 
- Fix encryption info 
- To add/remove a Contact you dont need to click directly on the checkbox 
- Give more room to the dialog header & properly align buttons
- Add dialoger header border line to AddGroup Main dialog
- Dont show initals
- Add border to Footer and show it in CreateGroup Dialog
- Give create chat/group dialog a fixed height
- Always show border on DialogHeader/Footer
- Fix open edit group from chatlist context menu 
- Debounce updateContacts
Fixes …
> Some UI/UX tweaks & bug fixes

- README.md
See https://github.com/deltachat/deltachat-desktop/issues/987
> update license text in README.md

- _locales/_experimental_en.json
Hello @Jikstra, I corrected some typos. @Simon-Laux is working, so I think you should merge this commit into select_background branch.
Thanks.
> Fix typos in _experimental_en.json

- _locales/_languages.json
- _locales/ar.xml
- _locales/az.xml
- _locales/ca.xml
- _locales/cs.xml
- _locales/da.xml
- _locales/de.xml
- _locales/es.xml
- _locales/eu.xml
- _locales/fr.xml
- _locales/hu.xml
- _locales/it.xml
- _locales/ja_JP.xml
- _locales/lt.xml
- _locales/nl_NL.xml
- _locales/pl.xml
- _locales/pt.xml
- _locales/pt_BR.xml
- _locales/ru.xml
- _locales/sq.xml
- _locales/sv.xml
- _locales/tr.xml
- _locales/uk.xml
- _locales/zh_CN.xml
- _locales/zh_TW.xml
- src/main/menu.js
> update translations & lang list + hide empty langs

- src/main/deltachat/login.js
> Fix constants in serverFlags conversion

- package-lock.json
- package.json
- src/main/devtools.js
- src/main/index.js
> add react devtools

- test/integration/index.js
There are still other tests which fail, not sure when i will find time to fix them.
> Fix hardcoded translation string in integration tests

- scss/_global.scss
fixes #1046
and make it look different, its still nowhere near pretty but now its a bit better imho
> Bring back userinfo

- src/main/deltachat/index.js
- src/main/ipc.js
- src/main/markseenFix.js
closes #1043 for now.
ping @hpk42
> mark seen quick fix

- src/renderer/components/dialogs/QrInviteCode.js
- test/integration/domHelper.js
Now we don't need to update the tests if number or order of main menu items changes. (But if we need other icon classes) :-/
> Fix integration tests

- scss/composer/_emoji-sticker-picker.scss
- src/renderer/components/composer/EmojiAndStickerPicker.js
- src/renderer/components/dialogs/QrInviteCode.js
Fixes https://github.com/deltachat/deltachat-desktop/issues/1058
> Dont show emoji or sticker headbar when we have no stickers to show

- src/renderer/components/MainScreen.js
- src/renderer/components/helpers/ChatMethods.js
> Unselect chat

- src/renderer/components/composer/Composer.js
> fix draft bug

- .vscode/launch.json
Copied from https://electronjs.org/docs/tutorial/debugging-main-process-vscode
> Add .vscode/launch.json

- src/main/deltachat/login.js
To be merged after https://github.com/deltachat/deltachat-node/pull/389
> Use setStockTranslation instead of setStringTable

- scss/_global.scss
- scss/login/_login.scss
- scss/manifest.scss
- src/main/deltachat/controller.js
- src/main/deltachat/login.js
- src/main/deltachat/settings.js
- src/main/deltachat/stickers.js
- src/main/ipc.js
- src/renderer/components/Login-Styles.js
- src/renderer/components/Login.js
- src/renderer/components/dialogs/Settings.js
This is an attempt to fix the update advanced settings implementation
> Advanced settings update

- README.md
- _locales/_untranslated_en.json
- _locales/az.xml
- _locales/ca.xml
- _locales/da.xml
- _locales/de.xml
- _locales/en.xml
- _locales/es.xml
- _locales/eu.xml
- _locales/fr.xml
- _locales/hu.xml
- _locales/it.xml
- _locales/lt.xml
- _locales/nl_NL.xml
- _locales/pl.xml
- _locales/pt.xml
- _locales/pt_BR.xml
- _locales/ru.xml
- _locales/sq.xml
- _locales/tr.xml
- _locales/uk.xml
- _locales/zh_CN.xml
- _locales/zh_TW.xml
- package.json
- src/renderer/components/Login.js
Followup to https://github.com/deltachat/deltachat-desktop/pull/1076
> Fix certificate ui translations and standard

- src/renderer/components/message/Message.js
> Hide retry send menu as long as it is not implemented

- src/main/deltachat/messagelist.js
> Do not call messageToJson for DC_MSG_ID_DAYMARKER

- src/main/deltachat/context.js
- src/main/deltachat/controller.js
- src/renderer/App.js
- src/renderer/ipc.js
- src/renderer/main.js
- This moves almost all logic from main.js to App.js
- refactors the logic in a react style
- es6 and imports everywhere
Fixes https://github.com/deltachat/deltachat-desktop/issues/1097 & closes https://github.com/deltachat/deltachat-desktop/issues/1095
> Implement maybeNetwork & refactor app into functional component and more react style

- _locales/_untranslated_en.json
- src/renderer/components/Menu.js
> rename "logout" to "switch account"

- package-lock.json
- package.json
> update electron builder

- .github/workflows/build-preview.yml
the download links should go to the checks, the comments from the bot are too noisy.
> pushing download link to details

- scss/message/_message.scss
- src/renderer/components/message/MessageBody.js
- src/renderer/components/message/MessageMarkdown.js
> fix message rendering new line behaviour

- static/chat.delta.desktop.appdata.xml
These changes are necessary to make the validator happy.
It'd be nice if the release would be filled out, though.
cf. https://github.com/hughsie/appstream-glib/issues/333 and https://github.com/flathub/chat.delta.desktop/pull/23
> Make appdata file compliant with the validator

- src/renderer/ScreenController.js
- src/renderer/components/MainScreen.js
- src/renderer/components/message/MessageList.js
- src/renderer/components/message/MessageListAndComposer.js
One step closer to throwing out the chat store
> Refactor MainScreen and split MessageList component into two components

- src/renderer/components/dialogs/Settings.js
> Fix selecting a file to import a secret key.

- bin/prepare-build-portable.js
- package.json
- src/application-config.js
related to https://support.delta.chat/t/please-make-deltachat-for-windows-a-truly-portable-standalone-program/675/8
> add command to make portable builds

- src/main/deltachat/messagelist.js
- src/renderer/components/map/MapComponent.js
- src/renderer/stores/locations.js
> Use callDcMethod for map click callback

- _locales/_untranslated_en.json
- src/renderer/components/message/Message.js
> add "Copy link" into context menu

- _locales/_untranslated_en.json
- scss/dialogs/_settings.scss
- src/main/deltachat/controller.js
- src/renderer/components/dialogs/Settings.js
- static/main.html
also fix the instant closing bug of the color picker.
The styling could be improved before releasing this in the wild. The plan is to use symbols instead of the text and style the buttons similar to the other buttons.
> Set profile image

- src/renderer/components/chat/ChatList.js
- src/renderer/components/dialogs/CreateChat.js
> Switch to new created group

- src/renderer/App.js
- src/renderer/components/MainScreen.js
- src/renderer/components/SearchInput.js
- src/renderer/components/chat/ChatList.js
- src/renderer/components/composer/ComposerMessageInput.js
- src/renderer/keybindings.js
> Implement keybindings

- src/renderer/components/MainScreen.js
> Fix archive chat

- src/renderer/ThemeBackend.js
> make messageStatusIcon in chatlistitem green

- _locales/_untranslated_en.json
- src/renderer/components/message/MessageListAndComposer.js
> add file drag in confirmation dialog 

- scss/message/_message.scss
- src/renderer/components/message/Message.js
> add forwarded message indicator

- src/renderer/components/composer/ComposerMessageInput.js
> Resize textarea and composer on chatId change

- scss/message/_message.scss
- src/renderer/components/message/Message.js
> fix image margin for forwarded label

- src/renderer/components/chat/ChatList.js
- src/renderer/components/dialogs/CreateChat.js
- src/renderer/stores/chat.js
Fixes https://github.com/deltachat/deltachat-desktop/issues/1201
Fixes https://github.com/deltachat/deltachat-desktop/issues/1204
> Fix dispatching select chat action

- _locales/_untranslated_en.json
- package.json
- src/main/deltachat/chatlist.js
- src/main/deltachat/login.js
- src/renderer/components/message/MessageListAndComposer.js
Fixes https://github.com/deltachat/deltachat-desktop/issues/1175
Fixes https://github.com/deltachat/deltachat-desktop/issues/1129
Missing:
> Create device chat and saved message chat on first login

- scss/message/_message.scss
Fixes https://github.com/deltachat/deltachat-desktop/issues/1188
> Set max width for message author

- _locales/_untranslated_en.json
tackles https://github.com/deltachat/deltachat-desktop/issues/1225
just a suggestion. feel free to change the text or to close this or :)
> reword the hints when the user cannot write to a chat

- src/main/deltachat/login.js
see https://github.com/deltachat/deltachat-desktop/pull/1237#pullrequestreview-331789423 for some reasons
> remove markdown from device-message

- src/renderer/stores/chat.js
> Fix CHAT_MODIFIED state update

- src/main/deltachat/chatlist.js
- src/renderer/components/Menu.js
- src/renderer/components/chat/ChatListContextMenu.js
refactor menu and chatListItem contextmenu for ease of development
hide some options that don't make any sense on selftalk and deviceTalk,
in mainMenu and chatListItem contextmenu
> fix Menu Items (closes #1232)

- src/renderer/components/map/MapComponent.js
- src/renderer/components/map/MapLayerFactory.js
- src/renderer/stores/locations.js
> Send poi message via chat store

- src/renderer/components/composer/ComposerMessageInput.js
> Avoid update draft loop

- src/renderer/components/message/MessageBody.js
- src/renderer/components/message/MessageMarkdown.js
> disable markdown for now

- scss/message/_message.scss
> fix avatar hidden in chatview

- _locales/_untranslated_en.json
- src/renderer/components/LoginScreen.js
- src/renderer/components/dialogs/ConfirmationDialog.js
- src/renderer/components/dialogs/UnblockContacts.js
- src/renderer/components/helpers/ChatMethods.js
- src/renderer/components/message/MessageListAndComposer.js
- src/renderer/components/message/MessageWrapper.js
> Improve confirm dialog

- package-lock.json
- package.json
- src/application-constants.js
- src/main/deltachat/backup.js
- src/main/deltachat/login.js
- src/main/deltachat/util.js
- src/main/index.js
- src/main/ipc.js
- src/main/logins.js
- src/main/state.js
- src/renderer/components/LoginScreen.js
This is made to be backwards compatible (it creates symlinks, not 100% whether this part works on windows so lets better test it)
fixes #1209
> Account folders

- scss/dialogs/_about.scss
- src/main/deltachat/chat.js
- src/main/deltachat/chatlist.js
- src/main/deltachat/controller.js
- src/main/deltachat/messagelist.js
- src/main/ipc.js
- src/main/markseenFix.js
- src/main/notifications.js
- src/main/unread-badge.js
- src/renderer/components/Media.js
- src/renderer/components/dialogs/About.js
- src/renderer/components/dialogs/MessageDetail.js
- src/renderer/ipc.js
- src/renderer/stores/chat.js
See commit messages for more info, best reviewed commit by commit.
Also styling the about dialog a bit:
> Pimp about delta chat dialog, small steps towards moving away from direct ipc

- scss/message/_message.scss
- src/renderer/components/MainScreen.js
- src/renderer/components/Menu.js
- src/renderer/components/chat/ChatListContextMenu.js
- src/renderer/components/helpers/ChatMethods.js
Fixes https://github.com/deltachat/deltachat-desktop/issues/1282
> Fix view profile

- scss/map/_map.scss
- scss/overwrites/_bp3-overwrites.scss
- src/renderer/components/Media.js
- src/renderer/components/dialogs/DeltaDialog.js
- src/renderer/components/dialogs/FullscreenMedia.js
- src/renderer/components/dialogs/MapDialog.js
- src/renderer/components/dialogs/index.js
- src/renderer/components/helpers/ChatMethods.js
- src/renderer/components/map/MapComponent.js
- fix viewprofile once again
- improve dialogs on small screens
> Fix styling problems of Map dialog

- scss/message/_message.scss
- src/main/deltachat/contacts.js
- src/renderer/components/dialogs/DeadDrop.js
- src/renderer/components/message/Message.js
- src/renderer/components/message/MessageWrapper.js
- Fixes clicking on a contact request not opening the profile view anymore. If you click on the text it opens the contact request thingy, everything else is the same.
- Fixes actually accepting the contact request when clicking on yes 
- Fixes marking the contact as noticed when clicking on Not now (Fixes https://github.com/deltachat/deltachat-desktop/issues/1273)
> Fix various message body clicking (includes contact requests & autocrypt setup)

- scss/message/_message.scss
- src/renderer/components/message/Message.js
of adding another wrapping div element which broke some css rules.
> Implement clickable text as a modifier class for the .text div instead

- _locales/ar.xml
- _locales/az.xml
- _locales/ca.xml
- _locales/da.xml
- _locales/de.xml
- _locales/en.xml
- _locales/es.xml
- _locales/eu.xml
- _locales/fr.xml
- _locales/hu.xml
- _locales/it.xml
- _locales/ja_JP.xml
- _locales/lt.xml
- _locales/nl_NL.xml
- _locales/pl.xml
- _locales/pt.xml
- _locales/pt_BR.xml
- _locales/ru.xml
- _locales/sq.xml
- _locales/sv.xml
- _locales/tr.xml
- _locales/uk.xml
- _locales/zh_CN.xml
- _locales/zh_TW.xml
> update translations (pull from transifex)

- src/main/deltachat/chatlist.js
> Fix missing Avatars in groups with unread messages

- scss/_global.scss
- scss/chat/_chat-list.scss
- scss/gallery/_media.scss
- scss/manifest.scss
- src/renderer/ThemeBackend.js
- src/renderer/components/Media.js
related to #889
fixes a some theming bugs
> Theming adventures ep2

- scss/message/_message.scss
- src/renderer/components/message/Message.js
This fixes attachments not being clickable
> Reintroduce msg-body div and fix message overflow

- src/main/ipc.js
- src/main/logins.js
add the list of found accounts to the error
debug log found accounts on account search
successor of #1300
> Don't crash/panic on account not found

- _locales/_untranslated_en.json
- package-lock.json
- package.json
- src/renderer/components/Menu.js
- src/renderer/components/dialogs/HelpPage.js
- src/renderer/components/dialogs/index.js
- src/renderer/stores/chat.js
- static/help/de/help.html
- static/help/en/help.html
- test/integration/help-page.js
Uses the faq-page of the website as content. The HTML has been changed
to only contain the div#content without the h1, and the path of
delta-what.png has been fixed to "./"
- ~~[ ] preprocess the HTML when building the app, not when serving the page.~~ (later)
> Include FAQ page as in-app help

- test/integration/index.js
7b115c609b removed text that these tests tried to find.
> Fix some integration tests after removing welcome text.

- src/renderer/components/dialogs/Settings.js
Fixes https://github.com/deltachat/deltachat-desktop/issues/1187
> Implement bcc self setting

- scss/help/_help.scss
- scss/manifest.scss
- src/main/menu.js
- src/renderer/ScreenController.js
- src/renderer/components/dialogs/HelpPage.js
- add androids help page styling to inApp FAQ
- add FAQ to help menu
> In app faq refinements

- scss/main_screen/_main_screen.scss
- src/renderer/components/MainScreen.js
> add verified checkmark into chat title in navbar

- _locales/_untranslated_en.json
- src/main/deltachat/chatlist.js
> remove translation hack

- src/renderer/components/contact/Contact.js
> Fix "Profile Image not visible in contact view"

- _locales/_languages.json
> remove duplicated netherlands language

- _locales/_untranslated_en.json
- src/main/deltachat/contacts.js
- src/renderer/components/dialogs/ViewProfile.js
> add button for opening DM to profile view

- scss/chat/_chat-list-item.scss
- src/renderer/components/chat/ChatListItem.js
before:
after:
bonus:
change `has-unread` to modifier class
> Chatlistitem scss work

- src/renderer/components/message/MessageListAndComposer.js
and also fix the logger import in this file
> fix forbidden drop path regex, fixes #1380

- scss/chat/_chat-list-item.scss
> more visibility for sending status in selected chatlistitem

- scss/message/_message.scss
> fix author clickable area - fixes #1391

- package-lock.json
- package.json
https://www.npmjs.com/advisories/961
> Update node-sass to fix a vulnerability.

- scss/gallery/_media-attachment.scss
- src/renderer/components/attachment/mediaAttachment.tsx
- src/renderer/components/conversations/Timestamp.tsx
- src/renderer/components/conversations/formatRelativeTime.ts
Improves the document and audio tab a bit.
<details>
<summary>Before</summary>
</details>
<details>
<summary>Before</summary>
</details>
> Gallery improvements step 3

- src/main/deltachat/login.js
This fix will maybe reach only people who don't update now but after releasing the next version, but nevertheless it will reach some people.
> Fix typo in device message.

- scss/contact/_contact.scss
- src/main/deltachat/contacts.js
- src/renderer/components/contact/ContactListItem.js
- src/renderer/components/dialogs/ViewProfile.js
- src/renderer/components/helpers/PseudoListItem.js
Only show the New Chat pseudo item if there's no dm chat with this contact yet. If there's a dm chat, show it as the first item in the chat list
Without having a dm chat:
With a dm chat:
@r10s this could be interesting for android too
> Overhaul open new chat ui

- src/renderer/ThemeBackend.js
- src/renderer/components/message/MessageWrapper.js
in order to be able to select error messages:
> make info message selectable

- package-lock.json
- package.json
- src/renderer/components/dialogs/HelpPage.js
Maybe this saves some space, but it also prevents leakage of rc credential files when making local test builds
> update electron builder file exclusions

- src/renderer/components/message/MessageList.js
- src/renderer/components/message/MessageWrapper.js
Fixes https://github.com/deltachat/deltachat-desktop/issues/1426
> Fix rerendering MessageList if a message changed

- scss/overwrites/_bp3-overwrites.scss
- src/renderer/ThemeBackend.js
- themes/light.json
> Use primary color for tabs and Ok button

- package-lock.json
- package.json
- scss/login/_login.scss
- src/main/deltachat/controller.js
- src/renderer/App.tsx
- src/renderer/ScreenController.tsx
- src/renderer/components/Login-Styles.js
- src/renderer/components/Login-Styles.tsx
- src/renderer/components/Login.js
- src/renderer/components/Login.tsx
- src/renderer/components/LoginScreen.js
- src/renderer/components/Media.tsx
- src/renderer/components/attachment/mediaAttachment.tsx
- src/renderer/components/attachment/messageAttachment.tsx
- src/renderer/components/conversations/formatRelativeTime.ts
- src/renderer/global.d.ts
- src/shared/localize.ts
closes #1408 
Adds provider db and converts 2 files to typescript.
[video.zip](https://github.com/deltachat/deltachat-desktop/files/4146289/video.zip)
github doesn't let me upload the mp4 as video, so zipped it.
> Provider db

- scss/composer/_emoji-sticker-picker.scss
- src/renderer/ThemeBackend.js
> Make emoji selector great again

- scss/gallery/_media.scss
- scss/message/_message-list.scss
- scss/overwrites/_bp3-overwrites.scss
- src/renderer/components/Media.tsx
- src/renderer/components/message/MessageList.js
> Show empty chat and gallery texts

- src/shared/constants.ts
Fixes https://github.com/deltachat/deltachat-desktop/issues/1439
> Remove preview and version from window app title

- scss/overwrites/_bp3-overwrites.scss
- scss/overwrites/_react-context-menu-overwrites.scss
- src/renderer/components/Menu.js
- src/renderer/components/chat/ChatListContextMenu.js
- src/renderer/components/chat/ChatListHelpers.js
- src/renderer/stores/chat.js
> Reorder menu, remove some items and restyle it a bit

- src/renderer/stores/chat.js
fixes https://github.com/deltachat/deltachat-desktop/issues/1306
> Add event handling for read message to chat store

- src/renderer/components/dialogs/CreateChat.js
- src/renderer/components/dialogs/EditGroup.js
> Remove checkbox in quick member add on new group, apply same ux on edit group

- scss/dialogs/_delta-dialog.scss
- src/renderer/stores/chat.js
Fixes https://github.com/deltachat/deltachat-desktop/issues/1461
> Fix qr images getting scrollable

- scss/chat/_chat-list-item.scss
- scss/contact/_contact.scss
- scss/message/_message.scss
prevent avatars from being selected
(text selection) -> user-select: none;
Also remove 2 unused scss classes
> prevent avatars from being selected

- src/renderer/components/message/MessageList.js
Fixes https://github.com/deltachat/deltachat-desktop/issues/1492
> Focus composer textarea when chat id changes

- scss/contact/_contact.scss
- src/renderer/components/message/Message.js
(see the commit messages)
fix #1498
> Fix 2 small avatar bugs

- scss/_global.scss
- scss/_variables.scss
- scss/chat/_chat-list.scss
- scss/gallery/_media.scss
- scss/main_screen/_main_screen.scss
- scss/message/_message-list.scss
also reduce the gallery margin/padding a bit.
and refactor a minor thing (turn the navbar size into an sass var)
> fix css gallery bug

- bin/build/build-js.js
- bin/build/builder.js
This addresses to things:
- set react into devmode
- build script should fail on error! (if any error the exit status should be an error so that run dev doesn't start on error, but on watch nothing much happens on errors)
> Fix build script

- src/renderer/components/message/Message.js
> Show Copy Link only if the message contains a link

- _locales/_untranslated_en.json
- src/renderer/components/message/Message.js
> copy whole message text to clipboard

- src/renderer/components/contact/Contact.tsx
- src/renderer/components/message/Message.js
on failed messages -> related to #1361
the failed messages are still displayed strangely so this does not fix the linked issue.
> fix a react bug where the screen went blank

- docs/KEYBINDINGS.md
- src/main/menu.ts
- src/renderer/ScreenController.tsx
- src/renderer/global.d.ts
- src/renderer/keybindings.ts
closes #1451
closes #634
see commit messages and `docs/KEYBINDINGS.md` for more info
please test on mac before merging.
> add some Mac keybindings

- scss/contact/_contact.scss
> Fix fake-contact-item label

- scss/dialogs/_view_profile.scss
- scss/manifest.scss
- src/main/deltachat/contacts.ts
- src/renderer/components/dialogs/ViewProfile.tsx
closes #1502 
Bonus: add Big view of profile image (closes #1356)
> Add option to change contact name

- images/pin.svg
- package-lock.json
- package.json
- scss/chat/_chat-list-item.scss
- src/main/deltachat/chat.ts
- src/main/deltachat/chatlist.ts
- src/renderer/ThemeBackend.ts
- src/renderer/components/Menu.js
- src/renderer/components/chat/ChatListContextMenu.tsx
- src/renderer/components/chat/ChatListItem.tsx
- src/renderer/components/dialogs/ForwardMessage.js
- src/renderer/components/helpers/ChatMethods.ts
- src/shared/shared-types.d.ts
- themes/dark.json
- themes/dark_amoled.json
- themes/darkpurple.json
- themes/light.json
This pr needs a `deltachat-node` version where https://github.com/deltachat/deltachat-node/pull/434 is merged.
closes #1456
closes #1365 
closes #1511
> add archive Label & Pinned chats & forward dialog new sorting

- scss/_variables.scss
- scss/chat/_chat-list-item.scss
- scss/chat/_chat-list.scss
- src/renderer/ThemeBackend.ts
- src/renderer/components/chat/ChatListItem.tsx
- src/renderer/keybindings.ts
- test/testcafe/test.js
and adjust background colors of the states:
> Cleanup chatlist styles

- bin/topEvil.sh
> add top-evil script

- src/renderer/keybindings.ts
Fixes https://github.com/deltachat/deltachat-desktop/issues/1565
> Fix selecting chat with ALT+Up/Down key

- scss/overwrites/_bp3-overwrites.scss
- scss/overwrites/_react-context-menu-overwrites.scss
> Remove padding around context menu items and change background color on hover to the same as from chat list items

- src/main/menu.ts
- src/main/windows/help.ts
- src/main/windows/main.ts
Fixes https://github.com/deltachat/deltachat-desktop/issues/1583
Fixes https://github.com/deltachat/deltachat-desktop/issues/1606
> Fix titlebar on mac. Yup just dont hide it.

- src/renderer/components/dialogs/ViewProfile.tsx
Fixes https://github.com/deltachat/deltachat-desktop/issues/1609
> Fix changing contact name

- src/renderer/components/dialogs/ImportQrCode.tsx
> Mirror video

- scss/gallery/_media-attachment.scss
- scss/message/_message-attachment.scss
> pointer cursor on hovering over document icon

- src/renderer/components/Login.tsx
- src/renderer/components/LoginScreen.tsx
- src/renderer/components/MainScreen.tsx
- src/renderer/components/Menu.tsx
- src/renderer/components/attachment/messageAttachment.tsx
- src/renderer/components/chat/ChatListContextMenu.tsx
- src/renderer/components/contact/ContactList.tsx
- src/renderer/components/contact/ContactListItem.tsx
- src/renderer/components/helpers/ChatMethods.ts
- src/renderer/components/message/Message.tsx
- src/renderer/components/message/MessageBody.tsx
- src/renderer/components/message/MessageList.tsx
- src/renderer/components/message/MessageListAndComposer.tsx
- src/renderer/components/message/MessageMarkdown.tsx
- src/renderer/components/message/MessageMetaData.tsx
- src/renderer/components/message/MessageWrapper.tsx
- src/renderer/delta-remote.ts
- src/renderer/stores/chat.ts
- src/shared/shared-types.d.ts
note: rebase mute notification branch after merging this pr (because of Menu.js)
> Typescriptify Frontend

- CHANGELOG.md
- CONTRIBUTORS.md
- package.json
I don't really know if this makes sense, maybe we should just merge the bugfix?
> Merge 1.3.3

- themes/_themebase.scss
- themes/dark.scss
- themes/dark_amoled.scss
- themes/darkpurple.scss
- themes/light.scss
--chatViewBgImgPath (had double, nested url in all themes except the light theme)
> fix themes chat view bg img

- docs/THEMES.md
- scss/chat/_chat-list-item.scss
- themes/_themebase.scss
- add dedicated hover color for hover and pinned
fixes #1600
> adjust hover colors

- package-lock.json
- package.json
Reverts deltachat/deltachat-desktop#1651
> Revert "Update deltachat-node to v1.32.1"

- src/main/deltachat/contacts.ts
- src/main/deltachat/controller.ts
- src/main/deltachat/login.ts
- src/main/ipc.ts
- src/renderer/ScreenController.tsx
are and handle them accordingly in the frontend
> Don't rename error events in backend, just pass them through how they

- src/main/deltachat/contacts.ts
- src/main/deltachat/controller.ts
- src/main/deltachat/login.ts
- src/main/ipc.ts
- src/renderer/ScreenController.tsx
Reverts deltachat/deltachat-desktop#1643
> Revert "Don't rename error events in backend, just pass them through how they"

- src/renderer/components/dialogs/DialogController.tsx
Additional props were not passed to dialog as expected.
For example InviteQrCode dialog had no qrcode as prop...
> Pass additional props as one object

- src/main/deltachat/controller.ts
- src/main/ipc.ts
- src/renderer/ScreenController.tsx
Partly backports https://github.com/deltachat/deltachat-desktop/pull/1643
> [1.3] Backport fix error handling

- package-lock.json
- package.json
- src/main/deltachat/controller.ts
- src/renderer/components/dialogs/ImportQrCode.tsx
- src/renderer/delta-remote.ts
Forewardports https://github.com/deltachat/deltachat-desktop/commit/8971f455f4c02329eddfce803ffc5607ea9f0695 & https://github.com/deltachat/deltachat-desktop/commit/4ab97376f8fc88e66c97307e109fcf2751e6d948
> [1.4] Forewardport Update deltachat-node v1.32.1 & Improve joinSecureJoin handling 

- src/main/deltachat/login.ts
- src/main/index.ts
Fixes https://github.com/deltachat/deltachat-desktop/issues/1663
> Fix crash on invalid address

- scss/overwrites/_bp3-overwrites.scss
- src/renderer/components/dialogs/Settings-Encryption.tsx
- src/renderer/components/dialogs/Settings.tsx
> Ui overhaul settings a bit

- src/renderer/components/dialogs/Settings-Autodelete.tsx
- src/renderer/components/dialogs/Settings.tsx
- We didn't fetch watch settings
- The autodeletion selection dialog broke
> Fix some bugs with settings

- src/main/deltachat/controller.ts
There are events that store numbers in data1
> Do not replace data1 with "" when it is 0

- scss/login/_login.scss
- src/renderer/components/Login.tsx
- src/renderer/components/dialogs/Settings-Account.tsx
- Translate automatic
- Remove some paddings
- Remove misleading "Use existing email account" hint on update account settings
- Improve styling of select component
> Fix some login ui/ux thingies

- CHANGELOG.md
- package-lock.json
- package.json
- Forwardport updating -node
- and changelog/version
> Forwardport 1.3.4

- CHANGELOG.md
- scss/_global.scss
- scss/chat/_chat-list-item.scss
- scss/contact/_contact-list.scss
- scss/main_screen/_navbar_wrapper.scss
- scss/message/_message.scss
- scss/overwrites/_react-context-menu-overwrites.scss
- src/renderer/components/MainScreen.tsx
- Default cursor for
- chatlist items 
- message text 
- contactlist item 
- context menu
- shrink clickable area of chattitle in navbar
fixes #1602
> Less cursor switching

- docs/DEVELOPMENT.md
- docs/RELEASE_WORKFLOW.md
and split it out into own file
> update release workflow

- .github/mergeable.yml
Adds a check to make sure the changelog was also changed after something in the `src` folder changed.
> add changelog check

- CHANGELOG.md
- _locales/_untranslated_en.json
- scss/message/_message-attachment.scss
- src/renderer/components/attachment/Attachment.tsx
- src/renderer/components/attachment/messageAttachment.tsx
- src/renderer/components/message/Message.tsx
(click to open)
Add "open attachment" to message context menu:
> increase clickable area of file attachments

- CHANGELOG.md
- src/main/application-constants.ts
- src/main/windows/main.ts
- src/shared/shared-types.d.ts
- src/shared/state.ts
> fix window placement on first start

- bin/build-frontend-ts.js
> fix windows building of frontend

- CHANGELOG.md
- package-lock.json
- package.json
- src/main/deltachat/chatlist.ts
- src/main/deltachat/contacts.ts
- src/main/deltachat/controller.ts
- src/main/deltachat/messagelist.ts
- src/main/deltachat/settings.ts
- src/renderer/components/dialogs/ViewProfile.tsx
- src/renderer/components/map/MapComponent.tsx
- src/shared/util.ts
Fixes https://github.com/deltachat/deltachat-desktop/issues/1739
> Update deltachat-node to 1.39.0

- CHANGELOG.md
- scss/contact/_contact-list.scss
- src/main/deltachat/settings.ts
- src/renderer/components/contact/ContactListItem.tsx
- src/renderer/components/dialogs/DialogController.tsx
- src/renderer/components/dialogs/Settings-Autodelete.tsx
- src/renderer/delta-remote.ts
Fixes https://github.com/deltachat/deltachat-desktop/issues/1724
> Implement Autodelete confirmation dialog

- src/renderer/components/helpers/OpenQrUrl.ts
Fixes https://github.com/deltachat/deltachat-desktop/issues/1744
> Dont process QrBurnerAccount while logged in

- src/main/deltachat/controller.ts
- src/main/deltachat/login.ts
some code was lost in the recent login refactoring
> fix incomplete about screen

- src/renderer/ScreenController.tsx
Fixes https://github.com/deltachat/deltachat-desktop/issues/1761
> Fix changeScreen to properly set the window.__screen variable

- scss/misc/_search-input.scss
theming:fix new group -> add member search field text color
> small theming fix for dark themes

- CHANGELOG.md
- src/main/deltachat/extras.ts
- src/main/deltachat/login.ts
- src/main/index.ts
- src/main/ipc.ts
- src/main/load-translations.ts
- src/main/menu.ts
- src/renderer/App.tsx
- src/renderer/components/helpers/PseudoListItem.tsx
- src/renderer/delta-remote.ts
> Language system fixes

- package-lock.json
- package.json
Fixes https://github.com/deltachat/deltachat-desktop/issues/1780
> Update deltachat-node to v1.40.0

- CHANGELOG.md
- src/renderer/components/composer/EmojiAndStickerPicker.tsx
on emoji click focus its searchbar, when closing refocus composer
> focus emoji seachbar on opening emoji picker

- CHANGELOG.md
- src/main/deltachat/login.ts
> add alreaddy logged in check to login function

- CHANGELOG.md
- src/renderer/components/chat/ChatList.tsx
- src/renderer/components/dialogs/MessageDetail.tsx
- src/renderer/components/message/MessageWrapper.tsx
> fix "Invalid date" in message details

- src/main/deltachat/login.ts
> prepare in app changelog

- CHANGELOG.md
- src/renderer/components/LoginScreen.tsx
> translate the term "error" in configure dialog

- CHANGELOG.md
- src/renderer/components/message/MessageList.tsx
- src/renderer/stores/chat.ts
Fixes https://github.com/deltachat/deltachat-desktop/issues/1808
Fixes https://github.com/deltachat/deltachat-desktop/issues/1808
Fixes https://github.com/deltachat/deltachat-desktop/issues/1735
> Fix messagelist bugs

- CHANGELOG.md
- src/renderer/components/dialogs/DeltaDialog.tsx
- src/renderer/components/dialogs/EnterAutocryptSetupMessage.tsx
- src/renderer/components/dialogs/MapDialog.tsx
- src/renderer/components/dialogs/Settings-Encryption.tsx
- src/renderer/components/dialogs/Settings.tsx
Fixes https://github.com/deltachat/deltachat-desktop/issues/1743
> Make all dialogs closable with escape

- src/renderer/components/dialogs/Settings-Autodelete.tsx
Fixes https://github.com/deltachat/deltachat-desktop/issues/1858
> Change autodel_title string to delete_old_messages

- src/renderer/App.tsx
- src/renderer/components/LoginScreen.tsx
> More fixes for preventing flashing login

- CHANGELOG.md
- src/renderer/components/CrashScreen.tsx
fixes that you don't see the react crash error messages in the logfile.
> log react crashes

- CHANGELOG.md
- src/renderer/components/message/Message.tsx
> use displayname for avatar initials

- CHANGELOG.md
- _locales/_untranslated_en.json
- scss/main_screen/_main_screen.scss
- src/main/deltachat/chatlist.ts
- src/renderer/components/MainScreen.tsx
- src/renderer/stores/chat.ts
- src/shared/shared-types.d.ts
> Add disappearing messages indicator

- CHANGELOG.md
- src/renderer/components/Media.tsx
> Gallery: order media after sortTimestamp, newer ones up

- CHANGELOG.md
- src/renderer/components/message/Message.tsx
> change used translation string for message details

- src/main/deltachat/chatlist.ts
- src/renderer/components/message/MessageListAndComposer.tsx
relates to https://github.com/deltachat/deltachat-node/pull/482
i can build desktop on linux locally with both the node and this PR here
> [for core 1.47] remove unused core-constants handling

- CHANGELOG.md
- src/renderer/components/dialogs/Settings.tsx
- src/renderer/global.d.ts
- src/renderer/keybindings.ts
> prevent duplicated opening of settings dialog

- CHANGELOG.md
- _locales/_untranslated_en.json
- src/renderer/components/ContextMenu.tsx
- src/renderer/components/attachment/mediaAttachment.tsx
fixes #1543
fixes #1874
additional Ideas:
We could also add delete message if we want.
I'm unsure of forward message, because you might accidentally forward some text that you didn't want to forward that way.
> Gallery context menu

- CHANGELOG.md
- build/gen-electron-builder-config.js
- docs/DEVELOPMENT.md
and document packaging process
CC @muelli 
related to https://github.com/flathub/chat.delta.desktop/pull/47
> add option to disable asar

- src/renderer/components/chat/ChatList.tsx
fixes #1892
this pr fixes the update of the unread counter in the chatlist, which was broken because the event changed.
> adapt to DC_EVENT_MSGS_NOTICED

- README.md
> add homebrew link to readme

- scss/gallery/_media.scss
- src/renderer/components/Gallery.tsx
there was sometimes a small empty space on the left so I
switched it to flexbox and haven't seen that bug since
> gallery css move to flexbox

- src/renderer/components/LoginForm.tsx
> remove hint from login error

- src/renderer/ScreenController.tsx
see #1888 for more info
fixed #1888
> remove #1888 workaround

- src/renderer/components/chat/ChatList.tsx
on contact name change
fixes #1889
> update contact names in chat list summary

- src/main/deltachat/login.ts
(pulled from android)
closes #1941
> Update translations for new core strings

- CHANGELOG.md
- src/renderer/components/dialogs/CreateChat.tsx
- src/renderer/components/dialogs/EditGroup.tsx
The problem that it is un-intuitive remains
Solve the bug part of #1939
closes #1964
> Solve the bug part of #1939

- CHANGELOG.md
- package-lock.json
- package.json
> Update deltachat-node/core to 1.50.0

- CHANGELOG.md
- src/renderer/components/message/Message.tsx
- src/renderer/components/message/MessageList.tsx
- src/renderer/components/message/MessageWrapper.tsx
> hide reply option in device chat

- CHANGELOG.md
- src/renderer/components/LoginScreen.tsx
- src/renderer/components/conversations/Timestamp.tsx
in Timestamp.tsx and LoginScreen.tsx
> Fix two state updates on unmounted components

- CHANGELOG.md
- src/renderer/components/composer/Composer.tsx
the timeout seems to be needed
fixes #1986
> select message input field on chat selection

- CHANGELOG.md
- package-lock.json
- package.json
- src/renderer/components/conversations/emoji.ts
- src/renderer/components/message/MessageBody.tsx
(turns out that the regex that contains all emojis is better than the
one that I found online - in that it only matches emojis)
fixes #1989
> reindroduce a real emoji regex

- CHANGELOG.md
- scss/composer/_composer.scss
The padding proposed by @r10s was too much for my taste, using 3px for now.
Fixes #1981
> [UI] Increase padding of draft/reply area

- CHANGELOG.md
- src/renderer/components/dialogs/QrCode.tsx
Fixes https://github.com/deltachat/deltachat-desktop/issues/2003
> Fix processing qr code again while another is still getting processed

- CHANGELOG.md
- src/renderer/components/LoginScreen.tsx
Fixes https://github.com/deltachat/deltachat-desktop/issues/2006
See https://github.com/deltachat/deltachat-core-rust/pull/2023
> Allow importing of .tar backup

- CHANGELOG.md
- src/renderer/components/chat/ChatList.tsx
> search: open profile view instead of chat on click on contact

- CHANGELOG.md
- src/renderer/components/chat/ChatListHelpers.tsx
- src/renderer/components/dialogs/DeadDrop.tsx
fixes #1972
see https://github.com/deltachat/deltachat-desktop/issues/1972#issuecomment-740763945 for what was exactly broken
> Fix contact requests ui

- CHANGELOG.md
- src/main/index.ts
Add desktop version, build time and git ref to log/-file.
```
0s [i]main/index: Deltachat Version 1.14.1 v1.14.1-19-g4a8766c2 1609776649794
```
> Add deltachat version to log

- CHANGELOG.md
- src/main/deltachat/login.ts
> store lastAccount as relative path

- CHANGELOG.md
- scss/dialogs/_settings.scss
- src/renderer/components/dialogs/Settings-Appearance.tsx
> Overhaul ui of chat background selection

- CHANGELOG.md
- src/renderer/components/dialogs/Settings-Communication.tsx
- src/renderer/components/dialogs/Settings.tsx
> [UI/UX] Make show email settings consistent with other multi value selections

- CHANGELOG.md
- src/renderer/components/dialogs/Settings.tsx
> fix hard to alter text in the middle of "Video chat instance" input field

- src/renderer/components/MainScreen.tsx
fix #2060
this bug was introduced with the minimal theme pr
and we did not have a release with it yet
so it doesn't need to be explicitly mentioned inside of the change-log
> fix "no chat selected" screen was not displayed

- scss/chat/_chat-list-item.scss
- scss/gallery/_media.scss
- scss/overwrites/_bp3-overwrites.scss
- themes/minimal.scss
> Improvements for minimal theme

- CHANGELOG.md
- src/renderer/components/dialogs/Settings-Autodelete.tsx
- src/shared/constants.ts
Fixes https://github.com/deltachat/deltachat-desktop/issues/2092
> Fix missing options autodelete server

- CHANGELOG.md
- images/videocamera.svg
- scss/_icons.scss
- scss/manifest.scss
- scss/message/_message.scss
- src/main/deltachat/messagelist.ts
- src/renderer/components/Avatar.tsx
- src/renderer/components/message/Message.tsx
Fixes https://github.com/deltachat/deltachat-desktop/issues/1992
> UI overhaul video chat invitation

- src/renderer/components/dialogs/Settings-Appearance.tsx
- static/main.html
- static/test.html
> fix alignment of colorpicker selector window

- CHANGELOG.md
- scss/dialogs/_delta-dialog.scss
- src/main/deltachat/messagelist.ts
- src/renderer/components/Menu.tsx
Fixes https://github.com/deltachat/deltachat-desktop/issues/1828
> Add ConfirmationDialog before sending videochat invitation

- bin/build-shared-version-info.js
> Include git branch into development version string

- README.md
> update homebrew install syntax

- src/renderer/components/map/MapComponent.tsx
- src/renderer/components/map/MapLayerFactory.ts
> replace contact.firstName with contact.displayName

- bin/github-actions/devbuild.js
to prevent test from failing in ci
> dev-build change package-lock version, too

- CHANGELOG.md
- src/renderer/components/dialogs/Settings.tsx
Fixes https://github.com/deltachat/deltachat-desktop/issues/2142
> Fix enabling/disabling notifications

- CHANGELOG.md
- src/renderer/components/dialogs/Settings.tsx
- src/renderer/components/message/MessageList2.tsx
- src/renderer/stores/messagelist.ts
Fixes https://github.com/deltachat/deltachat-desktop/issues/2123
> Fix crash in settings dialog when settings state is empty

- CHANGELOG.md
- src/main/deltachat/backup.ts
- src/renderer/components/dialogs/Settings-Backup.tsx
- src/renderer/contexts.ts
> pause io while exporting an backup

- CHANGELOG.md
- src/renderer/components/message/Message.tsx
Fixes https://github.com/deltachat/deltachat-desktop/issues/2066
> Change "Download attachment" to "Export attachment"

- CHANGELOG.md
- scss/dialogs/_qr-code.scss
- src/renderer/components/dialogs/CreateChat.tsx
- src/renderer/components/dialogs/EditGroup.tsx
- src/renderer/components/dialogs/QrCode.tsx
also fix theming of switcher
fixes #2163
> make qrcode scannable in darktheme

- CHANGELOG.md
- src/renderer/components/LoginScreen.tsx
- src/renderer/components/composer/Composer.tsx
- src/renderer/components/dialogs/CreateChat.tsx
- src/renderer/components/dialogs/Settings-Profile.tsx
> choose better default locations for file open dialogs

- CHANGELOG.md
- README.md
- build/gen-electron-builder-config.js
- src/main/deltachat/controller.ts
- src/shared/constants.ts
> Increase time until update notification to 120 days

- README.md
- build/gen-electron-builder-config.js
- docs/DEVELOPMENT.md
- docs/RELEASE_WORKFLOW.md
- docs/STYLES.md
- docs/THEMES.md
- src/main/deltachat/backup.ts
- src/main/deltachat/chatlist.ts
- src/main/deltachat/controller.ts
- src/main/devtools.ts
- src/main/electron-context-menu.ts
- src/main/index.ts
- src/main/state.ts
- src/main/unread-badge.ts
- src/main/windows/main.ts
- src/renderer/contexts.ts
- src/renderer/ipc.ts
- src/renderer/runtime.ts
- src/shared/logger.ts
- src/shared/shared-types.d.ts
Some spelling fixes: strings, comments and documentation.
> Spelling fixes reported mainly by codespell.

- .github/workflows/test-linux.yml
- .github/workflows/test-windows.yml
closes #2175 
This makes it slightly easier to understand for the people who didn't write these actions ;)
> Document GitHub Actions

- CHANGELOG.md
- _locales/_untranslated_en.json
- src/main/deltachat/messagelist.ts
- src/renderer/components/message/Message.tsx
- src/renderer/components/message/messageFunctions.ts
- src/renderer/delta-remote.ts
> Message html open in browser

- CHANGELOG.md
- src/main/deltachat/chat.ts
- src/main/deltachat/contacts.ts
- src/renderer/components/chat/ChatListContextMenu.tsx
- src/renderer/components/dialogs/EncryptionInfo.tsx
- src/renderer/delta-remote.ts
- src/shared/shared-types.d.ts
and hide "show encrytion info" for saved messages (resulted in error)
> add encryption info for groups

- src/renderer/components/message/Message.tsx
Core has all the logic necessary to display correct name or email address.
> fix: use contact.getDisplayName() for message author name

- CHANGELOG.md
- src/renderer/components/Menu.tsx
> Allow starting a videochat within groups

- CHANGELOG.md
- _locales/_languages.json
> add missing Czech translation

- scss/message/_message.scss
- src/renderer/components/message/Message.tsx
Fixes https://github.com/deltachat/deltachat-desktop/issues/2070
> Fix quotes not selectable and links in quotes not clickable

- CHANGELOG.md
- src/main/deltachat/chat.ts
- src/main/deltachat/contacts.ts
- src/renderer/components/chat/ChatListItem.tsx
- src/renderer/components/dialogs/DeadDrop.tsx
- src/renderer/components/message/Message.tsx
- src/renderer/delta-remote.ts
- src/shared/shared-types.d.ts
> Use new contact request api

- docs/TROUBLESHOOTING.md
this document should be linked from the website so that users can find it.
closes #1590
> Add user troubleshooting

- CHANGELOG.md
- package-lock.json
- package.json
- src/main/logins.ts
- Fix a startup crash that sometimes appeared when you had multiple accounts setup.
- update delta-chat node to 1.55.0
> fix startup crash and update deltachat node to 1.55.0

- CHANGELOG.md
- src/renderer/ScreenController.tsx
> clear userfeedback on account switch / logout

- CHANGELOG.md
- src/renderer/components/chat/ChatListContextMenu.tsx
- src/renderer/components/helpers/ChatMethods.ts
> Fix archiving/unarchiving chat deselection issues

- CHANGELOG.md
- scss/message/_message.scss
Fixes https://github.com/deltachat/deltachat-desktop/issues/2267
> Apply message styling for links to links in quotes too

- CHANGELOG.md
- src/renderer/components/dialogs/ViewProfile.tsx
Fixes https://github.com/deltachat/deltachat-desktop/issues/2271
ToDo:
> Fix links in status text

- CHANGELOG.md
- src/renderer/components/message/MessageMarkdown.tsx
> fix link parsing with brackets

- package-lock.json
- package.json
So there are no more `"resolved": false` in `package-lock.json`.
> upgrade glob-watcher to 5.0.5

- CHANGELOG.md
- src/main/ipc.ts
- src/renderer/components/composer/Composer.tsx
- src/renderer/components/composer/ComposerMessageInput.tsx
- src/renderer/runtime.ts
https://github.com/deltachat/deltachat-desktop/issues/2108
> Copy-paste images

- .github/workflows/basic-tests.yml
doesn't run on prs from forked repos (external contributors)
> try to fix that "basic code checks" workflow doesn't run on prs from forked repos

- CHANGELOG.md
- package-lock.json
- package.json
- src/main/index.ts
- src/main/themes.ts
there is now a warning about SharedArrayBuffer, which will be fixed by upgradeing react to version 17.0.2 https://github.com/facebook/react/releases/tag/v17.0.2
see https://github.com/deltachat/deltachat-desktop/pull/2302 for the pr for it.
> Upgrade to electron 13

- src/main/deltachat/extras.ts
- src/main/ipc.ts
- src/renderer/components/OfflineToast.tsx
- src/renderer/components/attachment/Attachment.tsx
- src/renderer/components/chat/ChatListItem.tsx
- src/renderer/components/composer/Composer.tsx
- src/renderer/delta-remote.ts
- src/renderer/runtime.ts
- src/shared/logger.ts
Fixes https://github.com/deltachat/deltachat-desktop/issues/2335
> Fix errors on master

- CHANGELOG.md
- docs/THEMES.md
- src/renderer/App.tsx
- src/renderer/ThemeManager.tsx
- src/renderer/components/chat/ChatList.tsx
- src/renderer/components/dialogs/ForwardMessage.tsx
- src/renderer/components/dialogs/MailtoDialog.tsx
- src/renderer/components/dialogs/ViewProfile.tsx
- themes/rocket.scss
- changeable chatlist item height 
- remove white scrollbar track of chatlist
> Update rocket theme

- CHANGELOG.md
- src/renderer/components/attachment/Attachment.tsx
- src/renderer/components/dialogs/Edit-Group-Image.tsx
- src/renderer/components/dialogs/FullscreenMedia.tsx
- src/renderer/components/dialogs/ViewProfile.tsx
and add an user visible error for when either mime type is missing or not in our list of chrome/electron supported ones.
fixes #2339
> Fix fullscreen media view for avatars

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
could solve the debian issue #2040
> upgrade electron builder to `22.12.0`

- CHANGELOG.md
- src/renderer/components/chat/ChatList.tsx
closes #2344
scroll to top if selected chat is not in current view
(archived or normal)
> fix going into archived view starts at bottom.

- CHANGELOG.md
- docs/CLI_FLAGS.md
- docs/LOGGING.md
- package.json
- src/main/index.ts
- src/main/rc.ts
- src/shared/shared-types.d.ts
> rename `--debug` flag to `--devmode`

- CHANGELOG.md
- package-lock.json
- package.json
- src/main/deltachat/login.ts
this is a test version, 1.22 will be the release version
> prepare 1.21.0

- CHANGELOG.md
- _locales/_untranslated_en.json
- scss/login/_login.scss
- src/main/deltachat/login.ts
- src/renderer/components/Login-Styles.tsx
- src/renderer/components/LoginForm.tsx
- src/renderer/components/dialogs/Settings-Account.tsx
- src/shared/shared-types.d.ts
> Implement settings for socks5

- CHANGELOG.md
- build/gen-electron-builder-config.js
- electron-builder.json5
remove user choosable installation path
enable logging installer
solves #2356
> remove user choosable instalation path

- CHANGELOG.md
- scss/map/_map.scss
- src/renderer/components/map/MapComponent.tsx
- themes/_themebase.scss
- fix unreadable poi message in darkmode (closes #2372)
- fix map crash on maps in DM chats
> map fixes 1.21.x

- CHANGELOG.md
- src/main/state.ts
we didn't discover this bug before because it only affects users that had used deltachat previously and not tested/used 1.21.0
> fix whitescreen crash on startup

- CHANGELOG.md
- scss/login/_login.scss
- src/renderer/components/Login-Styles.tsx
- src/renderer/components/dialogs/Settings-Profile.tsx
- src/renderer/components/dialogs/ViewGroup.tsx
> Convert status input to textarea

- CHANGELOG.md
- src/main/deltachat/chatlist.ts
- src/main/deltachat/contacts.ts
- src/main/deltachat/controller.ts
- src/main/deltachat/login.ts
- src/renderer/components/dialogs/ViewGroup.tsx
- src/renderer/stores/chat.ts
- src/shared/shared-types.d.ts
- src/shared/util.ts
> 🚧 async qr group join

- src/main/deltachat/settings.ts
- src/renderer/components/dialogs/ConfirmationDialog.tsx
- src/renderer/components/helpers/OpenQrUrl.tsx
- src/renderer/delta-remote.ts
- src/shared/constants.ts
closes #2297
please squash merge it
> withdraw qr

- src/renderer/components/screens/AccountSetupScreen.tsx
- test/testcafe/helpers.js
- test/testcafe/test.js
> Fix e2e tests

- scss/message/_message.scss
- src/renderer/components/message/MessageMarkdown.tsx
the new message parser code wasn't working as expected with linebreaks (last one is small, other ones are dislayed as if they were double linebreaks.)﻿
> fix linebreaks

- src/renderer/components/Menu.tsx
- src/renderer/components/chat/ChatList.tsx
- src/renderer/components/composer/Composer.tsx
- src/renderer/components/dialogs/CreateChat.tsx
- src/renderer/components/dialogs/MailtoDialog.tsx
- src/renderer/components/dialogs/QrCode.tsx
- src/renderer/components/dialogs/ViewProfile.tsx
- src/renderer/components/helpers/ChatMethods.ts
- src/renderer/components/helpers/OpenQrUrl.tsx
- src/renderer/components/map/MapComponent.tsx
- src/renderer/components/message/Message.tsx
- src/renderer/components/message/MessageList.tsx
- src/renderer/components/message/MessageMarkdown.tsx
- src/renderer/components/message/messageFunctions.ts
- src/renderer/components/screens/MainScreen.tsx
- src/renderer/stores/chat.ts
- src/renderer/stores/contacts.ts
- src/renderer/stores/locations.ts
- src/renderer/stores/store.ts
> Overhaul chat store and add typings

- CHANGELOG.md
- src/renderer/components/dialogs/About.tsx
Fix react warning in about dialog
closes #2428﻿
> Fix react warning in about dialog

- CHANGELOG.md
- src/main/deltachat/messagelist.ts
> fix the regression that qoutes without msg were not displayed and also fix #2434
